test:ubuntu16:
  image: ilrocstar/nemosys-test-img:v4-merc
  tags:
    - linux
  script:
    - mkdir build && cd build
    - CC=mpicc
    - CXX=mpicxx
    - >
      cmake ..
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_PREFIX_PATH="/Nemosys-Deps/vtk;/Nemosys-Deps/gmsh;/opt/netgen"
      -DCMAKE_INSTALL_PREFIX=../install
      -DBUILD_SHARED_LIBS=ON
      -DENABLE_MPI=ON
      -DENABLE_DTK=OFF
      -DENABLE_EXODUS=ON
      -DENABLE_EPIC=ON
      -DENABLE_PYTHON_BINDINGS=ON
      -DENABLE_TESTING=ON
      -DENABLE_BUILD_UTILS=ON
      -DENABLE_METIS=ON
      -DENABLE_NETGEN=ON
      -DENABLE_SIMMETRIX=OFF
      -DENABLE_CFMSH=ON
      -DENABLE_CGNS=ON
      -DENABLE_HDF5=ON
      -DENABLE_OPENCASCADE=OFF
      -DSIMMETRIX_LIB_DIR=/Nemosys/12.0-190512/lib/x64_rhel7_gcc48
    - make -j$(nproc)
    - make install
    - ctest --output-on-failure

test:ubuntu18:
  image: ilrocstar/nemosys-test-img-ubuntu18:v5-merc
  tags:
    - nemosys
  script:
    - mkdir build && cd build
    - CC=mpicc
    - CXX=mpicxx
    - >
      cmake ..
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_PREFIX_PATH="/Nemosys-Deps/opencascade/;/Nemosys-Deps/gmsh/;/Nemosys-Deps/netgen/;/Nemosys-Deps/vtk/;/opt/openfoam7/;"
      -DCMAKE_INSTALL_PREFIX=../install
      -DBUILD_SHARED_LIBS=ON
      -DENABLE_MPI=ON
      -DENABLE_DTK=OFF
      -DENABLE_EXODUS=ON
      -DENABLE_EPIC=ON
      -DENABLE_PYTHON_BINDINGS=ON
      -DENABLE_TESTING=ON
      -DENABLE_BUILD_UTILS=ON
      -DENABLE_METIS=ON
      -DENABLE_NETGEN=ON
      -DENABLE_SIMMETRIX=OFF
      -DENABLE_CFMSH=ON
      -DENABLE_CGNS=ON
      -DENABLE_HDF5=ON
      -DENABLE_OPENCASCADE=OFF
    - make -j$(nproc)
    - make install
    - ctest --output-on-failure

test:win10:
  image: ilrocstar/nemosys-test-img-win:v2
  tags:
    - windows
  script:
    - Set-Variable -Name "NEM_DIR" -Value "$(pwd)"
    - Copy-Item "$NEM_DIR" -Destination "$HOME\Nemosys" -Recurse
    - cd "$HOME\Nemosys"
    - md build
    - md install
    - cd build
    - >
      cmake ..
      -G "Ninja"
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_PREFIX_PATH="C:\Nemosys\boost_1_69_0;C:\Nemosys\cgns;C:\Nemosys\exodusii;C:\Nemosys\gmsh;C:\Nemosys\hdf5\cmake\hdf5;C:\Nemosys\metis;C:\Nemosys\netcdf;C:\Nemosys\netgen;C:\Nemosys\simmetrix;C:\Nemosys\vtk;C:\Nemosys\zlib"
      -DZLIB_ROOT="C:\Nemosys\zlib"
      -DCMAKE_INSTALL_PREFIX="C:\install"
      -DCMAKE_BUILD_TYPE=Release
      -DBUILD_SHARED_LIBS=ON
      -DENABLE_MPI=OFF
      -DENABLE_DTK=OFF
      -DENABLE_EXODUS=ON
      -DENABLE_EPIC=ON
      -DENABLE_PYTHON_BINDINGS=ON
      -DENABLE_TESTING=ON
      -DENABLE_BUILD_UTILS=ON
      -DENABLE_METIS=ON
      -DENABLE_NETGEN=ON
      -DENABLE_SIMMETRIX=OFF
      -DENABLE_CFMSH=OFF
      -DENABLE_OPENCASCADE=OFF
      -DENABLE_CGNS=ON
      -DENABLE_HDF5=ON
      -DSIMMETRIX_LIB_DIR="C:\Nemosys\simmetrix\12.0-190622\lib\x64_win_vc14_shared"
      -DPYTHON_EXECUTABLE="C:\Python\python.exe"
      -DSWIG_EXECUTABLE="C:\Nemosys\swigwin-3.0.12\swig.exe"
    - ninja -j ${Env:NUMBER_OF_PROCESSORS}
    - ninja install
    - ctest --output-on-failure

test:centos7:
  image: ilrocstar/nemosys-centos7:v3
  tags:
    - nemosys
  script:
    - mkdir build && cd build
    - >
      cmake3 ..
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX="../Install"
      -DBUILD_SHARED_LIBS=ON
      -DENABLE_MPI=OFF
      -DENABLE_DTK=OFF
      -DENABLE_EXODUS=ON
      -DENABLE_EPIC=ON
      -DENABLE_PYTHON_BINDINGS=ON
      -DENABLE_TESTING=ON
      -DENABLE_BUILD_UTILS=ON
      -DENABLE_METIS=ON
      -DENABLE_NETGEN=ON
      -DENABLE_SIMMETRIX=OFF
      -DENABLE_CFMSH=ON
      -DENABLE_OPENCASCADE=OFF
      -DENABLE_HDF5=ON
      -DENABLE_CGNS=ON
      -DPYTHON_EXECUTABLE=/usr/bin/python3.6
      -DBoost_INCLUDE_DIR=/usr/include/boost169/
      -DBoost_FILESYSTEM_LIBRARY_RELEASE=/usr/lib64/boost169/libboost_filesystem.so
      -DBoost_REGEX_LIBRARY_RELEASE=/usr/lib64/boost169/libboost_regex.so
    - make -j$(nproc)
    - make install
    - ctest3 --output-on-failure
