image: snatesh/nemosys-test-img:v1

before_script:
 - apt install -y python2.7-dev python-pip
 - cp -r /tmp/install .
 - mkdir build && cd build
 - CMAKE_PREFIX_PATH=../install/vtk:../install/madlib:../install/gmsh:../install/hdf5:../install/cgns:../install/netgen cmake -DENABLE_PYTHON_BINDINGS=ON -DCMAKE_INSTALL_PREFIX=../install ..
 - make -j$(nproc)
 - make install 
 - export LD_LIBRARY_PATH=../install/Nemosys/lib:$LD_LIBRARY_PATH
 - export PYTHONPATH=../install/Nemosys/python/lib/python2.7/site-packages:$PYTHONPATH 
job1:
 script:
  - make test
