image: ilrocstar/nemosys-test-img:v2

before_script:
  - apt update --fix-missing
  - mkdir build && cd build
  - CC=mpicc
  - CXX=mpicxx
  - >
    cmake ..
    -DCMAKE_PREFIX_PATH="/Nemosys-Deps/vtk;/Nemosys-Deps/gmsh;/Nemosys-Deps/opencascade;/Nemosys-Deps/netgen"
    -DCMAKE_INSTALL_PREFIX=../install
    -DENABLE_PYTHON_BINDINGS=OFF
    -DENABLE_BUILD_UTILS=ON
    -DENABLE_MPI=ON
    -DENABLE_TESTING=ON
    -DBUILD_SHARED_LIBS=ON
    -DENABLE_EXODUS=ON
    -DENABLE_CFMSH=OFF
  - make -j$(nproc)
  - make install

job1:
 script:
  - make test
