stages:
  - test
  - deploy

test:ubuntu18:
  image: ilrocstar/nemosys-test-img-ubuntu18:v8
  tags:
    - nemosys
  script:
    - mkdir build && cd build
    - CC=mpicc
    - CXX=mpicxx
    - >
      cmake ..
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_PREFIX_PATH="/Nemosys-Deps/opencascade/;/Nemosys-Deps/gmsh/;/Nemosys-Deps/netgen/;/Nemosys-Deps/vtk/;/opt/openfoam7/;"
      -DCMAKE_INSTALL_PREFIX=../install
      -DBUILD_SHARED_LIBS=ON
      -DENABLE_MPI=OFF
      -DENABLE_EPIC=ON
      -DENABLE_PYTHON_BINDINGS=ON
      -DENABLE_TESTING=ON
      -DENABLE_BUILD_UTILS=ON
      -DENABLE_METIS=ON
      -DENABLE_NETGEN=ON
      -DENABLE_CFMSH=ON
      -DENABLE_CGNS=OFF
      -DENABLE_HDF5=OFF
      -DENABLE_OPENCASCADE=ON
    - make -j$(nproc)
    - make install
    - ctest --output-on-failure
    - cpack -G DEB
  artifacts:
    when: always
    reports:
      junit: "/builds/Nemosys/Nemosys/build/testing/junit/*.xml"
    paths:
      - "/builds/Nemosys/Nemosys/build/*.deb"

deploy:all:
  stage: deploy
  only:
    - master@Nemosys/Nemosys
  script: 
    - apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - scp -r /builds/Nemosys/Nemosys/build/*.deb nemosys@192.168.1.122:/home/nemosys/repo
    - scp -r /builds/Nemosys/Nemosys/build/*.rpm nemosys@192.168.1.122:/home/nemosys/rpmrepo
  dependencies:
    - test:ubuntu18
    - test:centos7

deploy:public:
  stage: deploy
  only:
    - public_repo_auto_deploy@Nemosys/Nemosys
  script:
    - apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - scp -r /builds/Nemosys/Nemosys/build/*.deb repoman@50.244.52.204:/home/repoman/ubuntu18-repo
    - scp -r /builds/Nemosys/Nemosys/build/*.rpm repoman@50.244.52.204:/home/repoman/centos7-repo
  dependencies:
    - test:ubuntu18
    - test:centos7

test:win10:
  image: ilrocstar/nemosys-test-img-win:v3
  tags:
    - windows
  script:
    - Set-Variable -Name "NEM_DIR" -Value "$(pwd)"
    - Copy-Item "$NEM_DIR" -Destination "$HOME\Nemosys" -Recurse
    - cd "$HOME\Nemosys"
    - md build
    - md install
    - cd build
    - >
      cmake ..
      -G "Ninja"
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_PREFIX_PATH="C:\Nemosys\boost_1_69_0;C:\Nemosys\cgns;C:\Nemosys\exodusii;C:\Nemosys\gmsh;C:\Nemosys\hdf5\cmake\hdf5;C:\Nemosys\metis;C:\Nemosys\netcdf;C:\Nemosys\netgen;C:\Nemosys\vtk;C:\Nemosys\zlib"
      -DZLIB_ROOT="C:\Nemosys\zlib"
      -DCMAKE_INSTALL_PREFIX="C:\install"
      -DCMAKE_BUILD_TYPE=Release
      -DBUILD_SHARED_LIBS=ON
      -DENABLE_MPI=OFF
      -DENABLE_EPIC=ON
      -DENABLE_PYTHON_BINDINGS=ON
      -DENABLE_TESTING=ON
      -DENABLE_BUILD_UTILS=ON
      -DENABLE_METIS=ON
      -DENABLE_NETGEN=ON
      -DENABLE_CFMSH=OFF
      -DENABLE_OPENCASCADE=OFF
      -DENABLE_CGNS=ON
      -DENABLE_HDF5=ON
      -DPYTHON_EXECUTABLE="C:\Python\python.exe"
      -DSWIG_EXECUTABLE="C:\Nemosys\swigwin-3.0.12\swig.exe"
    - ninja -j ${Env:NUMBER_OF_PROCESSORS}
    - ninja install
    - ctest --output-on-failure
    - cpack -G WIX
    - Copy-Item "*.msi" -Destination "$NEM_DIR"
    - Copy-Item "testing\junit\*.xml" -Destination "$NEM_DIR"
  artifacts:
    when: always
    reports:
      junit: "*.xml"
    paths:
      - "*.msi"

test:centos7:
  image: ilrocstar/nemosys-centos7:v7
  tags:
    - nemosys
  script:
    - mkdir build && cd build
    - >
      cmake3 ..
      -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_INSTALL_PREFIX="../Install"
      -DBUILD_SHARED_LIBS=ON
      -DENABLE_MPI=OFF
      -DENABLE_EPIC=ON
      -DENABLE_PYTHON_BINDINGS=ON
      -DENABLE_TESTING=ON
      -DENABLE_BUILD_UTILS=ON
      -DENABLE_METIS=ON
      -DENABLE_NETGEN=ON
      -DENABLE_CFMSH=ON
      -DENABLE_OPENCASCADE=ON
      -DENABLE_HDF5=OFF
      -DENABLE_CGNS=OFF
      -DPYTHON_EXECUTABLE=/usr/bin/python3.6
      -DBoost_INCLUDE_DIR=/usr/include/boost169/
      -DBoost_FILESYSTEM_LIBRARY_RELEASE=/usr/lib64/boost169/libboost_filesystem.so
      -DBoost_REGEX_LIBRARY_RELEASE=/usr/lib64/boost169/libboost_regex.so
    - make -j$(nproc)
    - make install
    - ctest3 --output-on-failure
    - cpack3 -G RPM
    - ls /builds/Nemosys/Nemosys/build/
  artifacts:
    when: always
    reports:
      junit: "/builds/Nemosys/Nemosys/build/testing/junit/*.xml"
    paths:
      - "/builds/Nemosys/Nemosys/build/*.rpm"
