NEMoSys: cgnsAnalyzer.C File Reference
cgnsAnalyzer.C File Reference
Functions
CGNS_ENUMT (MassUnits_t)
CGNS_ENUMT (LengthUnits_t)
CGNS_ENUMT (TimeUnits_t)
CGNS_ENUMT (TemperatureUnits_t)
CGNS_ENUMT (AngleUnits_t)
CGNS_ENUMT (ZoneType_t)
CGNS_ENUMT (ElementType_t)
Function Documentation
CGNS_ENUMT() [1/7]
CGNS_ENUMT (MassUnits_t)
Definition at line 457 of file cgnsAnalyzer.C.
Referenced by CGNS_ENUMT(), cgnsAnalyzer::closeCG(), cgnsAnalyzer::getSectionConn(), cgnsAnalyzer::getSectionMesh(), cgnsAnalyzer::getSectionNames(), cgnsAnalyzer::getSolutionData(), cgnsAnalyzer::overwriteSolData(), cgnsAnalyzer::populateSolutionDataNames(), and cgnsWriter::~cgnsWriter().
 { return massU; }
CGNS_ENUMT() [2/7]
CGNS_ENUMT (LengthUnits_t)
Definition at line 459 of file cgnsAnalyzer.C.
 { return lengthU; }
CGNS_ENUMT() [3/7]
CGNS_ENUMT (TimeUnits_t)
Definition at line 461 of file cgnsAnalyzer.C.
 { return timeU; }
CGNS_ENUMT() [4/7]
CGNS_ENUMT (TemperatureUnits_t)
Definition at line 463 of file cgnsAnalyzer.C.
{
   return tempU;
 }
CGNS_ENUMT() [5/7]
CGNS_ENUMT (AngleUnits_t)
Definition at line 467 of file cgnsAnalyzer.C.
 { return angleU; }
CGNS_ENUMT() [6/7]
CGNS_ENUMT (ZoneType_t)
Definition at line 469 of file cgnsAnalyzer.C.
 { return zoneType; }
CGNS_ENUMT() [7/7]
CGNS_ENUMT (ElementType_t)
Definition at line 574 of file cgnsAnalyzer.C.
References CGNS_ENUMT().
{
   std::vector<std::string> secNames;
   getSectionNames(secNames);
   auto it = std::find(secNames.begin(), secNames.end(), secName);
   if (it == secNames.end()) {
     std::cerr << "No section found named " << secName << "\n";
     throw;
   }
   int iSec = it - secNames.begin();
   // reading section info
   int nBdry, parentFlag;
   cgsize_t eBeg, eEnd;
   CGNS_ENUMT(ElementType_t) secTyp;
   char sectionname[33];
   if (cg_section_read(indexFile, indexBase, indexZone, iSec, sectionname,
                       &secTyp, &eBeg, &eEnd, &nBdry, &parentFlag) != CG_OK)
     std::cerr << "Error in load, " << cg_get_error() << std::endl;
   return secTyp;
 }