NEMoSys: MeshQuality Class Reference
MeshQuality Class Reference
Detailed Description
Definition at line 46 of file MeshQuality.H.
Public Member Functions
MeshQuality ()=default
MeshQuality (const meshBase *_mesh)
MeshQuality (const cfmeshQualityParams *params)
~MeshQuality ()
MeshQuality (const MeshQuality &that)=delete
MeshQuality & operator= (const MeshQuality &that)=delete
void checkMesh (std::ostream &outputStream)
void checkMesh ()
void checkMesh (const std::string &fname)
vtkSmartPointer< vtkDoubleArray > getStats (int n)
void cfmOptimize ()
Private Attributes
const meshBase * mesh
vtkSmartPointer< vtkMeshQuality > qualityFilter
const cfmeshQualityParams * _cfmQPrms
Constructor & Destructor Documentation
MeshQuality() [1/4]
MeshQuality::MeshQuality () default
MeshQuality() [2/4]
MeshQuality::MeshQuality (const meshBase * _mesh) explicit
Definition at line 46 of file MeshQuality.C.
References meshBase::getDataSet(), mesh, NEM::MSH::New(), and qualityFilter.
                                               : mesh(_mesh) {
   qualityFilter = vtkSmartPointer<vtkMeshQuality>::New();
   qualityFilter->SetInputData(mesh->getDataSet());
   qualityFilter->SetTriangleQualityMeasureToShape();
   qualityFilter->SetTetQualityMeasureToShape();
   qualityFilter->SetQuadQualityMeasureToShape();
   qualityFilter->SetHexQualityMeasureToShape();
   qualityFilter->Update();
 }
MeshQuality() [3/4]
MeshQuality::MeshQuality (const cfmeshQualityParams * params) inline explicit
Definition at line 51 of file MeshQuality.H.
 { _cfmQPrms = params; }
~MeshQuality()
MeshQuality::~MeshQuality ()
Definition at line 56 of file MeshQuality.C.
{
   //  mesh->unsetCellDataArray("Quality");
   //  mesh->unsetFieldDataArray("Mesh Triangle Quality");
   //  mesh->unsetFieldDataArray("Mesh Quadrilateral Quality");
   //  mesh->unsetFieldDataArray("Mesh Tetrahedron Quality");
   //  mesh->unsetFieldDataArray("Mesh Hexahedron Quality");
 }
MeshQuality() [4/4]
MeshQuality::MeshQuality (const MeshQuality & that) delete
Member Function Documentation
cfmOptimize()
void MeshQuality::cfmOptimize ()
Definition at line 179 of file MeshQuality.C.
References _cfmQPrms, cfmeshQualityParams::consCellSet, cfmeshQualityParams::nIterations, cfmeshQualityParams::nLoops, cfmeshQualityParams::nSrfItr, and cfmeshQualityParams::qualThrsh.
Referenced by NEM::DRV::OptimizeMeshQualDriver::execute().
{
 #ifdef HAVE_CFMSH
   // initialize openfoam
   //#include "setRootCase.H"
   int argc = 1;
   char **argv = new char *[2];
   argv[0] = new char[100];
   strcpy(argv[0], "NONE");
   Foam::argList args(argc, argv);
   //#include "createTime.H"
   Foam::Info << "Create time\n" << Foam::endl;
   Foam::Time runTime(Foam::Time::controlDictName, args);
   //- 2d cartesian mesher cannot be run in parallel
   Foam::argList::noParallel();
   //- load the mesh from disk
   Foam::Module::polyMeshGen pmg(runTime);
   pmg.read();
   //- construct the smoother
   Foam::Module::meshOptimizer mOpt(pmg);
   if (_cfmQPrms->consCellSet.has_value()) {
     const std::string &constrainedCellSet = _cfmQPrms->consCellSet.value();
     //- lock cells in constrainedCellSet
     mOpt.lockCellsInSubset(constrainedCellSet);
     //- find boundary faces which shall be locked
     Foam::Module::labelLongList lockedBndFaces, selectedCells;
     const Foam::label sId = pmg.cellSubsetIndex(constrainedCellSet);
     pmg.cellsInSubset(sId, selectedCells);
     Foam::boolList activeCell(pmg.cells().size(), false);
     forAll (selectedCells, i)
       activeCell[selectedCells[i]] = true;
   }
   //- clear geometry information before volume smoothing
   pmg.clearAddressingData();
   //- perform optimisation using the laplace smoother and
   mOpt.optimizeMeshFV(_cfmQPrms->nLoops, _cfmQPrms->nLoops,
                       _cfmQPrms->nIterations, _cfmQPrms->nSrfItr);
   //- perform optimisation of worst quality faces
   mOpt.optimizeMeshFVBestQuality(_cfmQPrms->nLoops, _cfmQPrms->qualThrsh);
   //- check the mesh again and untangl bad regions if any of them exist
   mOpt.untangleMeshFV(_cfmQPrms->nLoops, _cfmQPrms->nIterations,
                       _cfmQPrms->nSrfItr);
   Foam::Info << "Writing mesh" << Foam::endl;
   pmg.write();
   delete[] argv;
   Foam::Info << "Finished mesh quality enhancement task." << Foam::endl;
 #else
   std::cerr << "Compile with CFMSH option enabled to use this feature."
             << std::endl;
 #endif
 }
checkMesh() [1/3]
void MeshQuality::checkMesh (std::ostream & outputStream)
Definition at line 64 of file MeshQuality.C.
References cellType, meshBase::getDataSet(), meshBase::getFileName(), meshBase::getNumberOfCells(), getStats(), mesh, qualityFilter, nemAux::trim_fname(), and meshBase::write().
Referenced by meshBase::checkMesh().
{
   outputStream << "------------- Shape Quality Statistics -------------\n\n";
   outputStream << "Cell Type" << std::setw(16) << "Num Cells" << std::setw(16)
                << "Minimum" << std::setw(16) << "Maximum" << std::setw(16)
                << "Average" << std::setw(16) << "Variance" << std::endl;
   for (int i = 0; i < 4; ++i) {
     if (i == 0)
       outputStream << "Tri" << std::setw(16);
     else if (i == 1)
       outputStream << "Quad" << std::setw(15);
     else if (i == 2)
       outputStream << "Tet" << std::setw(16);
     else
       outputStream << "Hex" << std::setw(16);
     vtkSmartPointer<vtkDoubleArray> qualityField = getStats(i);
     double *val = qualityField->GetTuple(0);
     outputStream << std::right << val[4] << std::setw(16) << std::right
                  << val[0] << std::setw(16) << std::right << val[2]
                  << std::setw(16) << std::right << val[1] << std::setw(16)
                  << std::right << val[3] << std::endl;
   }
   outputStream << "\n------------- Detailed Statistics ------------------\n"
                << std::endl;
   vtkSmartPointer<vtkDoubleArray> qualityArray = vtkDoubleArray::SafeDownCast(
       qualityFilter->GetOutput()->GetCellData()->GetArray("Quality"));
   mesh->getDataSet()->GetCellData()->AddArray(qualityArray);
   std::string qfn = nemAux::trim_fname(mesh->getFileName(), "") + "-qal.vtu";
   mesh->write(qfn);
   // writing to file
   outputStream << "Type" << std::setw(10) << "Quality\n" << std::endl;
   for (int i = 0; i < mesh->getNumberOfCells(); ++i) {
     int cellType = mesh->getDataSet()->GetCell(i)->GetCellType();
     double val = qualityArray->GetValue(i);
     switch (cellType) {
       case VTK_TRIANGLE: {
         outputStream << "TRI\t" << std::right << setw(10) << val << "\n";
         break;
       }
       case VTK_TETRA: {
         outputStream << "TET\t" << std::right << setw(10) << val << "\n";
         break;
       }
       case VTK_QUAD: {
         outputStream << "QUAD\t" << std::right << setw(10) << val << "\n";
         break;
       }
       case VTK_HEXAHEDRON: {
         outputStream << "HEX\t" << std::right << setw(10) << val << "\n";
         break;
       }
       default: {
         std::cerr
             << "Invalid cell type. Only tri, quad, tet, and hex supported."
             << std::endl;
         exit(1);
       }
     }
   }
 }
checkMesh() [2/3]
void MeshQuality::checkMesh ()
Definition at line 131 of file MeshQuality.C.
Referenced by checkMesh().
 { checkMesh(std::cout); }
checkMesh() [3/3]
void MeshQuality::checkMesh (const std::string & fname)
Definition at line 133 of file MeshQuality.C.
References checkMesh().
{
   std::ofstream outputStream(fname);
   if (!outputStream.good()) {
     std::cerr << "Error opening file " << fname << std::endl;
     exit(1);
   }
   checkMesh(outputStream);
 }
getStats()
vtkSmartPointer< vtkDoubleArray > MeshQuality::getStats (int n)
Definition at line 142 of file MeshQuality.C.
References NEM::MSH::New(), and qualityFilter.
Referenced by checkMesh().
{
   vtkSmartPointer<vtkDoubleArray> qualityField =
       vtkSmartPointer<vtkDoubleArray>::New();
   switch (n) {
     case 0: {
       qualityField = vtkDoubleArray::SafeDownCast(
           qualityFilter->GetOutput()->GetFieldData()->GetArray(
               "Mesh Triangle Quality"));
       break;
     }
     case 1: {
       qualityField = vtkDoubleArray::SafeDownCast(
           qualityFilter->GetOutput()->GetFieldData()->GetArray(
               "Mesh Quadrilateral Quality"));
       break;
     }
     case 2: {
       qualityField = vtkDoubleArray::SafeDownCast(
           qualityFilter->GetOutput()->GetFieldData()->GetArray(
               "Mesh Tetrahedron Quality"));
       break;
     }
     case 3: {
       qualityField = vtkDoubleArray::SafeDownCast(
           qualityFilter->GetOutput()->GetFieldData()->GetArray(
               "Mesh Hexahedron Quality"));
       break;
     }
     default: {
       std::cerr << "Invalid cell type. Only tri, quad, tet, and hex supported."
                 << std::endl;
       exit(1);
     }
   }
   return qualityField;
 }
operator=()
MeshQuality& MeshQuality::operator= (const MeshQuality & that) delete
Member Data Documentation
_cfmQPrms
const cfmeshQualityParams* MeshQuality::_cfmQPrms private
Definition at line 72 of file MeshQuality.H.
Referenced by cfmOptimize().
mesh
const meshBase* MeshQuality::mesh private
Definition at line 69 of file MeshQuality.H.
Referenced by checkMesh(), and MeshQuality().
qualityFilter
vtkSmartPointer<vtkMeshQuality> MeshQuality::qualityFilter private
Definition at line 70 of file MeshQuality.H.
Referenced by checkMesh(), getStats(), and MeshQuality().
The documentation for this class was generated from the following files:
MeshQuality.H
MeshQuality.C