NEMoSys: NEM::NUCMESH::RectangularArray Class Reference
NEM::NUCMESH::RectangularArray Class Reference
Detailed Description
Definition at line 40 of file RectangularArray.H.
Public Member Functions
RectangularArray (const std::array< std::size_t, 2 > &gridDims, const std::array< double, 2 > &deltaGrid, const std::array< double, 3 > &center={0, 0, 0})
const std::size_t & getPattern (std::size_t x, std::size_t y) const
void setPattern (std::size_t x, std::size_t y, std::size_t patternKey)
The shape at [x, y] will be translated by [(x - (getGridDims()[0] - 1) / 2) * getGridDistance()[0], (y - (getGridDims()[1].
const std::array< std::size_t, 2 > & getGridDims () const
const std::array< double, 2 > & getGridDistance () const
void setGridDistance (const std::array< double, 2 > &gridDistance)
std::size_t getNumPatternShapes () const
const ShapeBase * getPatternShape (std::size_t idx) const
void setPatternShape (std::size_t idx, const std::shared_ptr< ShapeBase > &shape)
template<typename Shape >
void insertPatternShape (std::size_t idx, Shape &&shape)
template<typename Shape , typename... Args>
void makePatternShape (std::size_t idx, Args &&...args)
void fillPattern (std::size_t idx)
const std::array< double, 3 > & getCenter () const
void setCenter (const std::array< double, 3 > &center)
Static Public Member Functions
static std::array< double, 3 > getRotatedPoint (const std::array< double, 3 > &center, const std::array< double, 2 > &rotation)
Protected Member Functions
NEM::GEO::GeoManager createGeo () const override
Construct a NEM::GEO::GeoManager.
std::size_t getPatternSize () const
const std::size_t & getPattern (std::size_t idx) const
void setPattern (std::size_t idx, std::size_t patternKey)
template<typename Modifier >
NEM::GEO::GeoManager createGeoImpl (Modifier &&modifier) const
Static Protected Member Functions
static NEM::GEO::GeoManager basicTransformation (const gp_Trsf &transformation, NEM::GEO::GeoManager &&geoMetadata)
static void mergeGeo (NEM::GEO::GeoManager &keepGeo, NEM::GEO::GeoManager &&removeGeo)
Merge two 2d NEM::GEO::GeoManager objects by cutting shapes in removeGeo from shapes in keepGeo and sewing the resulting faces.
Private Attributes
std::array< std::size_t, 2 > dims_
std::array< double, 2 > delta_
Inherits NEM::NUCMESH::ShapesArray.
Constructor & Destructor Documentation
RectangularArray()
NEM::NUCMESH::RectangularArray::RectangularArray (const std::array< std::size_t, 2 > & gridDims, const std::array< double, 2 > & deltaGrid, const std::array< double, 3 > & center = {0, 0, 0})
Definition at line 37 of file RectangularArray.C.
     : ShapesArray(center, gridDims[0] * gridDims[1]),
       dims_(gridDims),
       delta_(deltaGrid) {}
Member Function Documentation
basicTransformation()
NEM::GEO::GeoManager NEM::NUCMESH::ShapesArray::basicTransformation (const gp_Trsf & transformation, NEM::GEO::GeoManager && geoMetadata) static protected inherited
Definition at line 81 of file ShapesArray.C.
References NEM::GEO::GeoManager::buildCompound(), NEM::GEO::GeoManager::insert(), and NEM::DRV::JSON::shapeType.
Referenced by NEM::NUCMESH::HexagonalArray::createGeo(), createGeo(), and NEM::NUCMESH::PolarArray::createGeo().
{
   auto compound = geoMetadata.buildCompound();
   BRepBuilderAPI_Transform transformer{transformation};
   transformer.Perform(compound);
   NEM::GEO::GeoManager output(geoMetadata.getDim());
   static constexpr std::array<TopAbs_ShapeEnum, 4> shapeTypes{
       TopAbs_SOLID, TopAbs_FACE, TopAbs_EDGE, TopAbs_VERTEX};
   for (auto &shapeType : shapeTypes) {
     for (TopExp_Explorer explorer{compound, shapeType}; explorer.More();
          explorer.Next()) {
       auto &oldSubshape = explorer.Current();
       if (auto old_metadata = geoMetadata.get(oldSubshape)) {
         output.insert(transformer.ModifiedShape(oldSubshape),
                       std::move(*old_metadata));
       }
     }
   }
   return output;
 }
createGeo()
NEM::GEO::GeoManager NEM::NUCMESH::RectangularArray::createGeo () const override protected virtual
Returns
A NEM::GEO::GeoManager object representing the shape described by this object
Implements NEM::NUCMESH::ShapeBase.
Definition at line 54 of file RectangularArray.C.
References NEM::NUCMESH::ShapesArray::basicTransformation(), NEM::NUCMESH::ShapesArray::createGeoImpl(), delta_, dims_, and NEM::NUCMESH::ShapeBase::getCenter().
{
   const auto maxY = static_cast<int>(this->dims_[1] - 1);
   std::array<int, 2> coord{-static_cast<int>(this->dims_[0] - 1), -maxY};
   return this->createGeoImpl([this, maxY,
                               &coord](NEM::GEO::GeoManager *const inp) {
     if (inp) {
       auto &center = this->getCenter();
       gp_Trsf transformation{};
       transformation.SetTranslation(
           gp_Vec{center[0] + coord[0] * this->delta_[0] / 2.,
                  center[1] + coord[1] * this->delta_[1] / 2., center[2]});
       *inp = ShapesArray::basicTransformation(transformation, std::move(*inp));
     }
     coord[1] += 2;
     if (coord[1] > maxY) {
       coord[1] = -maxY;
       coord[0] += 2;
     }
   });
 }
createGeoImpl()
template<typename Modifier > NEM::GEO::GeoManager NEM::NUCMESH::ShapesArray::createGeoImpl (Modifier && modifier) const inline protected inherited
Definition at line 87 of file ShapesArray.H.
References NEM::NUCMESH::ShapeBase::mergeGeo().
Referenced by NEM::NUCMESH::HexagonalArray::createGeo(), createGeo(), and NEM::NUCMESH::PolarArray::createGeo().
{
     NEM::GEO::GeoManager output(0);
     for (auto &patternId : pattern_) {
       auto shape = patternId < patternShapes_.size()
                        ? patternShapes_.at(patternId).get()
                        : nullptr;
       if (shape) {
         auto subShapeOut = shape->createGeo();
         modifier(&subShapeOut);
         ShapeBase::mergeGeo(output, std::move(subShapeOut));
       } else {
         modifier(nullptr);
       }
     }
     return output;
   }
fillPattern()
void NEM::NUCMESH::ShapesArray::fillPattern (std::size_t idx) inherited
Definition at line 65 of file ShapesArray.C.
References NEM::NUCMESH::ShapesArray::pattern_.
{
   for (auto &pattern : pattern_) {
     pattern = idx;
   }
 }
getCenter()
const std::array< double, 3 > & NEM::NUCMESH::ShapeBase::getCenter () const inherited
Definition at line 50 of file ShapeBase.C.
References NEM::NUCMESH::ShapeBase::center_.
Referenced by NEM::NUCMESH::HexagonalArray::createGeo(), createGeo(), NEM::NUCMESH::CirclesAndPolys::createGeo(), NEM::NUCMESH::PolarArray::createGeo(), and NEM::NUCMESH::Circles::createGeo().
 { return center_; }
getGridDims()
const std::array<std::size_t, 2>& NEM::NUCMESH::RectangularArray::getGridDims () const inline
Definition at line 54 of file RectangularArray.H.
Referenced by NEM::DRV::JSON::modify_helper().
 { return dims_; }
getGridDistance()
const std::array<double, 2>& NEM::NUCMESH::RectangularArray::getGridDistance () const inline
Definition at line 55 of file RectangularArray.H.
 { return delta_; }
getNumPatternShapes()
std::size_t NEM::NUCMESH::ShapesArray::getNumPatternShapes () const inherited
Definition at line 45 of file ShapesArray.C.
References NEM::NUCMESH::ShapesArray::patternShapes_.
Referenced by NEM::DRV::JSON::modify_helper().
{
   return patternShapes_.size();
 }
getPattern() [1/2]
const std::size_t & NEM::NUCMESH::RectangularArray::getPattern (std::size_t x, std::size_t y) const
Definition at line 44 of file RectangularArray.C.
References dims_, and NEM::NUCMESH::ShapesArray::getPattern().
{
   return this->ShapesArray::getPattern(x * dims_[1] + y);
 }
getPattern() [2/2]
const std::size_t & NEM::NUCMESH::ShapesArray::getPattern (std::size_t idx) const protected inherited
Definition at line 73 of file ShapesArray.C.
References NEM::NUCMESH::ShapesArray::pattern_.
Referenced by getPattern(), and NEM::NUCMESH::HexagonalArray::getPatternCoordCenter().
{
   return pattern_.at(idx);
 }
getPatternShape()
const ShapeBase * NEM::NUCMESH::ShapesArray::getPatternShape (std::size_t idx) const inherited
Definition at line 49 of file ShapesArray.C.
References NEM::NUCMESH::ShapesArray::patternShapes_.
{
   if (idx < patternShapes_.size()) {
     return patternShapes_.at(idx).get();
   } else {
     return nullptr;
   }
 }
getPatternSize()
std::size_t NEM::NUCMESH::ShapesArray::getPatternSize () const protected inherited
Definition at line 71 of file ShapesArray.C.
References NEM::NUCMESH::ShapesArray::pattern_.
 { return pattern_.size(); }
getRotatedPoint()
std::array< double, 3 > NEM::NUCMESH::ShapeBase::getRotatedPoint (const std::array< double, 3 > & center, const std::array< double, 2 > & rotation) static inherited
Parameters
center Center of circle
rotation {Radius, angle in degrees}
Returns
Point on circle with center center and normal [0, 0, 1], radius rotation[0] and angle (in degrees) rotation[1]
Definition at line 58 of file ShapeBase.C.
Referenced by NEM::NUCMESH::PolarArray::createGeo(), and NEM::DRV::JSON::modify_helper().
{
   auto angle = rotation[1] * M_PI / 180.;
   return {center[0] + rotation[0] * std::cos(angle),
           center[1] + rotation[0] * std::sin(angle), center[2]};
 }
insertPatternShape()
template<typename Shape > void NEM::NUCMESH::ShapesArray::insertPatternShape (std::size_t idx, Shape && shape) inline inherited
Definition at line 62 of file ShapesArray.H.
{
     this->setPatternShape(idx,
                           std::make_shared<typename std::decay<Shape>::type>(
                               std::forward<Shape>(shape)));
   }
makePatternShape()
template<typename Shape , typename... Args> void NEM::NUCMESH::ShapesArray::makePatternShape (std::size_t idx, Args &&... args) inline inherited
Definition at line 69 of file ShapesArray.H.
{
     this->setPatternShape(idx,
                           std::make_shared<Shape>(std::forward<Args>(args)...));
   }
mergeGeo()
void NEM::NUCMESH::ShapeBase::mergeGeo (NEM::GEO::GeoManager & keepGeo, NEM::GEO::GeoManager && removeGeo) static protected inherited
Parameters
[in,out] keepGeo Merge geometry from removeGeo into this object
[in] removeGeo Move geometry and data from this object into keepGeo
Definition at line 66 of file ShapeBase.C.
References NEM::GEO::GeoManager::buildCompound(), NEM::GEO::GeoManager::deleteShapes(), NEM::GEO::GeoManager::getDim(), NEM::GEO::GeoManager::insert(), NEM::GEO::GeoManager::modify(), NEM::GEO::GeoManager::setDim(), and NEM::DRV::JSON::shapeType.
Referenced by NEM::NUCMESH::ShapesArray::createGeoImpl(), and NEM::SRV::NucMeshSrv::FillOutputPortInformation().
{
   auto origCompound = keepGeo.buildCompound();
   if (origCompound.IsNull()) {
     keepGeo = std::move(removeGeo);
     return;
   } else {
     auto newCompound = removeGeo.buildCompound();
     TopoDS_ListOfShape newShapes;
     static constexpr std::array<TopAbs_ShapeEnum, 4> shapeTypes{
         TopAbs_SOLID, TopAbs_FACE, TopAbs_EDGE, TopAbs_VERTEX};
     for (auto &shapeType : shapeTypes) {
       for (TopExp_Explorer explorer{newCompound, shapeType}; explorer.More();
            explorer.Next()) {
         auto &oldSubshape = explorer.Current();
         if (auto old_metadata = removeGeo.get(oldSubshape)) {
           keepGeo.insert(oldSubshape, std::move(*old_metadata));
         }
       }
     }
     if (!newCompound.IsNull()) {
       keepGeo.setDim(std::max(keepGeo.getDim(), removeGeo.getDim()));
       BRepAlgoAPI_Cut cutter{origCompound, newCompound};
       if (cutter.HasDeleted() || cutter.HasModified() ||
           cutter.HasGenerated()) {
         auto deletedShapes = keepGeo.modify(cutter, {TopAbs_EDGE, TopAbs_FACE});
         keepGeo.deleteShapes(deletedShapes[0]);
       }
       BRepBuilderAPI_Sewing sewer{};
       std::vector<TopoDS_Shape> sewedShapes;
       auto compound = keepGeo.buildCompound();
       for (TopExp_Explorer explorer{compound, TopAbs_FACE}; explorer.More();
            explorer.Next()) {
         sewer.Add(explorer.Current());
         sewedShapes.emplace_back(explorer.Current());
       }
       sewer.Perform();
       auto deletedShapes =
           keepGeo.modify(sewer, sewedShapes, {TopAbs_EDGE, TopAbs_FACE});
       keepGeo.deleteShapes(deletedShapes);
     }
   }
 }
setCenter()
void NEM::NUCMESH::ShapeBase::setCenter (const std::array< double, 3 > & center) inherited
Definition at line 52 of file ShapeBase.C.
References NEM::NUCMESH::ShapeBase::center_.
Referenced by NEM::DRV::JSON::modify_helper().
{
   center_ = center;
 }
setGridDistance()
void NEM::NUCMESH::RectangularArray::setGridDistance (const std::array< double, 2 > & gridDistance) inline
Definition at line 56 of file RectangularArray.H.
Referenced by NEM::DRV::JSON::modify_helper().
{
     delta_ = gridDistance;
   }
setPattern() [1/2]
void NEM::NUCMESH::RectangularArray::setPattern (std::size_t x, std::size_t y, std::size_t patternKey)
1) / 2) * getGridDistance()[1], 0] + getCenter() .
Definition at line 49 of file RectangularArray.C.
References dims_, and NEM::NUCMESH::ShapesArray::setPattern().
Referenced by NEM::DRV::JSON::modify_helper().
{
   this->ShapesArray::setPattern(x * dims_[1] + y, patternKey);
 }
setPattern() [2/2]
void NEM::NUCMESH::ShapesArray::setPattern (std::size_t idx, std::size_t patternKey) protected inherited
Definition at line 77 of file ShapesArray.C.
References NEM::NUCMESH::ShapesArray::pattern_.
Referenced by NEM::DRV::JSON::modify_helper(), setPattern(), and NEM::NUCMESH::HexagonalArray::setPatternCoordCenter().
{
   pattern_.at(idx) = patternKey;
 }
setPatternShape()
void NEM::NUCMESH::ShapesArray::setPatternShape (std::size_t idx, const std::shared_ptr< ShapeBase > & shape) inherited
Definition at line 57 of file ShapesArray.C.
References NEM::NUCMESH::ShapesArray::patternShapes_.
Referenced by NEM::DRV::JSON::modify_helper().
{
   if (idx >= patternShapes_.size()) {
     patternShapes_.resize(idx + 1);
   }
   patternShapes_.at(idx) = shape;
 }
Member Data Documentation
delta_
std::array<double, 2> NEM::NUCMESH::RectangularArray::delta_ private
Definition at line 65 of file RectangularArray.H.
Referenced by createGeo().
dims_
std::array<std::size_t, 2> NEM::NUCMESH::RectangularArray::dims_ private
Definition at line 64 of file RectangularArray.H.
Referenced by createGeo(), getPattern(), and setPattern().
The documentation for this class was generated from the following files:
RectangularArray.H
RectangularArray.C