NEMoSys: NEM::NUCMESH::ShapeBase Class Reference
NEM::NUCMESH::ShapeBase Class Reference abstract
Abstract base class for types that create NEM::GEO::GeoManager.
Detailed Description
Also see NEM::DRV::NucMeshDriver
Definition at line 52 of file ShapeBase.H.
Public Member Functions
virtual ~ShapeBase ()=default
const std::array< double, 3 > & getCenter () const
void setCenter (const std::array< double, 3 > &center)
Static Public Member Functions
static std::array< double, 3 > getRotatedPoint (const std::array< double, 3 > &center, const std::array< double, 2 > &rotation)
Protected Member Functions
ShapeBase (const std::array< double, 3 > &center={0, 0, 0})
ShapeBase (const ShapeBase &)=default
ShapeBase & operator= (const ShapeBase &)=default
ShapeBase (ShapeBase &&)=default
ShapeBase & operator= (ShapeBase &&)=default
virtual NEM::GEO::GeoManager createGeo () const =0
Construct a NEM::GEO::GeoManager.
Static Protected Member Functions
static void mergeGeo (NEM::GEO::GeoManager &keepGeo, NEM::GEO::GeoManager &&removeGeo)
Merge two 2d NEM::GEO::GeoManager objects by cutting shapes in removeGeo from shapes in keepGeo and sewing the resulting faces.
Private Attributes
std::array< double, 3 > center_
Friends
class NEM::SRV::NucMeshSrv
class ShapesArray
Inherited by NEM::NUCMESH::Circles, NEM::NUCMESH::CirclesAndPolys, and NEM::NUCMESH::ShapesArray.
Constructor & Destructor Documentation
~ShapeBase()
virtual NEM::NUCMESH::ShapeBase::~ShapeBase () virtual default
ShapeBase() [1/3]
NEM::NUCMESH::ShapeBase::ShapeBase (const std::array< double, 3 > & center = {0, 0, 0}) explicit protected
Definition at line 56 of file ShapeBase.C.
 : center_(center) {}
ShapeBase() [2/3]
NEM::NUCMESH::ShapeBase::ShapeBase (const ShapeBase &) protected default
ShapeBase() [3/3]
NEM::NUCMESH::ShapeBase::ShapeBase (ShapeBase &&) protected default
Member Function Documentation
createGeo()
virtual NEM::GEO::GeoManager NEM::NUCMESH::ShapeBase::createGeo () const protected pure virtual
Returns
A NEM::GEO::GeoManager object representing the shape described by this object
Implemented in NEM::NUCMESH::Circles, NEM::NUCMESH::PolarArray, NEM::NUCMESH::CirclesAndPolys, NEM::NUCMESH::HexagonalArray, and NEM::NUCMESH::RectangularArray.
getCenter()
const std::array< double, 3 > & NEM::NUCMESH::ShapeBase::getCenter () const
Definition at line 50 of file ShapeBase.C.
References center_.
Referenced by NEM::NUCMESH::HexagonalArray::createGeo(), NEM::NUCMESH::RectangularArray::createGeo(), NEM::NUCMESH::CirclesAndPolys::createGeo(), NEM::NUCMESH::PolarArray::createGeo(), and NEM::NUCMESH::Circles::createGeo().
 { return center_; }
getRotatedPoint()
std::array< double, 3 > NEM::NUCMESH::ShapeBase::getRotatedPoint (const std::array< double, 3 > & center, const std::array< double, 2 > & rotation) static
Parameters
center Center of circle
rotation {Radius, angle in degrees}
Returns
Point on circle with center center and normal [0, 0, 1], radius rotation[0] and angle (in degrees) rotation[1]
Definition at line 58 of file ShapeBase.C.
Referenced by NEM::NUCMESH::PolarArray::createGeo(), and NEM::DRV::JSON::modify_helper().
{
   auto angle = rotation[1] * M_PI / 180.;
   return {center[0] + rotation[0] * std::cos(angle),
           center[1] + rotation[0] * std::sin(angle), center[2]};
 }
mergeGeo()
void NEM::NUCMESH::ShapeBase::mergeGeo (NEM::GEO::GeoManager & keepGeo, NEM::GEO::GeoManager && removeGeo) static protected
Parameters
[in,out] keepGeo Merge geometry from removeGeo into this object
[in] removeGeo Move geometry and data from this object into keepGeo
Definition at line 66 of file ShapeBase.C.
References NEM::GEO::GeoManager::buildCompound(), NEM::GEO::GeoManager::deleteShapes(), NEM::GEO::GeoManager::getDim(), NEM::GEO::GeoManager::insert(), NEM::GEO::GeoManager::modify(), NEM::GEO::GeoManager::setDim(), and NEM::DRV::JSON::shapeType.
Referenced by NEM::NUCMESH::ShapesArray::createGeoImpl(), and NEM::SRV::NucMeshSrv::FillOutputPortInformation().
{
   auto origCompound = keepGeo.buildCompound();
   if (origCompound.IsNull()) {
     keepGeo = std::move(removeGeo);
     return;
   } else {
     auto newCompound = removeGeo.buildCompound();
     TopoDS_ListOfShape newShapes;
     static constexpr std::array<TopAbs_ShapeEnum, 4> shapeTypes{
         TopAbs_SOLID, TopAbs_FACE, TopAbs_EDGE, TopAbs_VERTEX};
     for (auto &shapeType : shapeTypes) {
       for (TopExp_Explorer explorer{newCompound, shapeType}; explorer.More();
            explorer.Next()) {
         auto &oldSubshape = explorer.Current();
         if (auto old_metadata = removeGeo.get(oldSubshape)) {
           keepGeo.insert(oldSubshape, std::move(*old_metadata));
         }
       }
     }
     if (!newCompound.IsNull()) {
       keepGeo.setDim(std::max(keepGeo.getDim(), removeGeo.getDim()));
       BRepAlgoAPI_Cut cutter{origCompound, newCompound};
       if (cutter.HasDeleted() || cutter.HasModified() ||
           cutter.HasGenerated()) {
         auto deletedShapes = keepGeo.modify(cutter, {TopAbs_EDGE, TopAbs_FACE});
         keepGeo.deleteShapes(deletedShapes[0]);
       }
       BRepBuilderAPI_Sewing sewer{};
       std::vector<TopoDS_Shape> sewedShapes;
       auto compound = keepGeo.buildCompound();
       for (TopExp_Explorer explorer{compound, TopAbs_FACE}; explorer.More();
            explorer.Next()) {
         sewer.Add(explorer.Current());
         sewedShapes.emplace_back(explorer.Current());
       }
       sewer.Perform();
       auto deletedShapes =
           keepGeo.modify(sewer, sewedShapes, {TopAbs_EDGE, TopAbs_FACE});
       keepGeo.deleteShapes(deletedShapes);
     }
   }
 }
operator=() [1/2]
ShapeBase& NEM::NUCMESH::ShapeBase::operator= (const ShapeBase &) protected default
operator=() [2/2]
ShapeBase& NEM::NUCMESH::ShapeBase::operator= (ShapeBase &&) protected default
setCenter()
void NEM::NUCMESH::ShapeBase::setCenter (const std::array< double, 3 > & center)
Definition at line 52 of file ShapeBase.C.
References center_.
Referenced by NEM::DRV::JSON::modify_helper().
{
   center_ = center;
 }
Friends And Related Function Documentation
NEM::SRV::NucMeshSrv
friend class NEM::SRV::NucMeshSrv friend
Definition at line 56 of file ShapeBase.H.
ShapesArray
friend class ShapesArray friend
Definition at line 57 of file ShapeBase.H.
Member Data Documentation
center_
std::array<double, 3> NEM::NUCMESH::ShapeBase::center_ private
Definition at line 97 of file ShapeBase.H.
Referenced by getCenter(), and setCenter().
The documentation for this class was generated from the following files:
ShapeBase.H
ShapeBase.C