NEMoSys: NEM::DRV::OptimizeMeshQualDriver Class Reference
NEM::DRV::OptimizeMeshQualDriver Class Reference
Detailed Description
Definition at line 86 of file MeshQualityDriver.H.
Classes
struct Opts
Public Member Functions
OptimizeMeshQualDriver (std::vector< cfmeshQualityParams > params)
const std::vector< cfmeshQualityParams > & getParams () const
void setParams (std::vector< cfmeshQualityParams > params)
void addParams (cfmeshQualityParams params)
void execute () const override
Run the workflow represented by the driver.
Static Public Member Functions
static std::unique_ptr< NemDriver > readJSON (const jsoncons::json &inputjson)
Factory method for all drivers.
Private Member Functions
OptimizeMeshQualDriver ()
const Opts & getOpts () const
void setOpts (Opts opts)
Private Attributes
Opts opts_
Inherits NEM::DRV::MeshQualityDriver.
Constructor & Destructor Documentation
OptimizeMeshQualDriver() [1/2]
NEM::DRV::OptimizeMeshQualDriver::OptimizeMeshQualDriver (std::vector< cfmeshQualityParams > params) explicit
Definition at line 69 of file MeshQualityDriver.C.
     : opts_(std::move(params)) {}
OptimizeMeshQualDriver() [2/2]
NEM::DRV::OptimizeMeshQualDriver::OptimizeMeshQualDriver () private
Definition at line 73 of file MeshQualityDriver.C.
     : OptimizeMeshQualDriver(std::vector<cfmeshQualityParams>{}) {}
Member Function Documentation
addParams()
void NEM::DRV::OptimizeMeshQualDriver::addParams (cfmeshQualityParams params)
Definition at line 85 of file MeshQualityDriver.C.
References opts_, and NEM::DRV::OptimizeMeshQualDriver::Opts::params.
{
   this->opts_.params.emplace_back(std::move(params));
 }
execute()
void NEM::DRV::OptimizeMeshQualDriver::execute () const override virtual
Implements NEM::DRV::NemDriver.
Definition at line 97 of file MeshQualityDriver.C.
References MeshQuality::cfmOptimize(), opts_, and NEM::DRV::OptimizeMeshQualDriver::Opts::params.
{
   for (const auto &param : this->opts_.params) {
     MeshQuality mq{&param};
     mq.cfmOptimize();
   }
 }
getOpts()
const OptimizeMeshQualDriver::Opts & NEM::DRV::OptimizeMeshQualDriver::getOpts () const private
Definition at line 89 of file MeshQualityDriver.C.
References opts_.
Referenced by getParams().
{
   return opts_;
 }
getParams()
const std::vector< cfmeshQualityParams > & NEM::DRV::OptimizeMeshQualDriver::getParams () const
Definition at line 76 of file MeshQualityDriver.C.
References getOpts(), and NEM::DRV::OptimizeMeshQualDriver::Opts::params.
           {
   return getOpts().params;
 }
readJSON()
std::unique_ptr< NemDriver > NEM::DRV::NemDriver::readJSON (const jsoncons::json & inputjson) static inherited
Parameters
inputjson json input with "Program Type" key
Returns
pointer to base NemDriver class
Definition at line 37 of file NemDriver.C.
Referenced by NEM::DRV::MeshGenDriver::MeshGenDriver().
{
   return inputjson.as<std::unique_ptr<NemDriver>>();
 }
setOpts()
void NEM::DRV::OptimizeMeshQualDriver::setOpts (Opts opts) private
Definition at line 93 of file MeshQualityDriver.C.
References opts_.
Referenced by setParams().
{
   this->opts_ = std::move(opts);
 }
setParams()
void NEM::DRV::OptimizeMeshQualDriver::setParams (std::vector< cfmeshQualityParams > params)
Definition at line 81 of file MeshQualityDriver.C.
References setOpts().
{
   setOpts(Opts{std::move(params)});
 }
Member Data Documentation
opts_
Opts NEM::DRV::OptimizeMeshQualDriver::opts_ private
Definition at line 114 of file MeshQualityDriver.H.
Referenced by addParams(), execute(), getOpts(), and setOpts().
The documentation for this class was generated from the following files:
MeshQualityDriver.H
MeshQualityDriver.C