NEMoSys: NEM::DRV::NetgenMeshGenDriver Class Reference
NEM::DRV::NetgenMeshGenDriver Class Reference
Detailed Description
Definition at line 40 of file NetgenMeshGenDriver.H.
Classes
struct Opts
Public Types
using Files = MeshGenFiles
Public Member Functions
NetgenMeshGenDriver (Files files, netgenParams params)
const Files & getFiles () const
void setFiles (Files files)
const netgenParams & getParams () const
void setParams (netgenParams params)
void execute () const override
Run the workflow represented by the driver.
Static Public Member Functions
static std::unique_ptr< NemDriver > readJSON (const jsoncons::json &inputjson)
Factory method for all drivers.
Private Member Functions
NetgenMeshGenDriver ()
const Opts & getOpts () const
void setOpts (Opts opts)
Private Attributes
Files files_
Opts opts_
Inherits NEM::DRV::MeshGenDriver.
Member Typedef Documentation
Files
using NEM::DRV::NetgenMeshGenDriver::Files = MeshGenFiles
Definition at line 42 of file NetgenMeshGenDriver.H.
Constructor & Destructor Documentation
NetgenMeshGenDriver() [1/2]
NEM::DRV::NetgenMeshGenDriver::NetgenMeshGenDriver (Files files, netgenParams params)
Definition at line 41 of file NetgenMeshGenDriver.C.
     : files_(std::move(files)), opts_(std::move(params)) {}
NetgenMeshGenDriver() [2/2]
NEM::DRV::NetgenMeshGenDriver::NetgenMeshGenDriver () private
Definition at line 44 of file NetgenMeshGenDriver.C.
     : NetgenMeshGenDriver({{}, {}}, {}) {}
Member Function Documentation
execute()
void NEM::DRV::NetgenMeshGenDriver::execute () const override virtual
Implements NEM::DRV::NemDriver.
Definition at line 69 of file NetgenMeshGenDriver.C.
References meshBase::CreateShared(), meshBase::exportVolToVtk(), files_, NEM::DRV::MeshGenDriver::MeshGenFiles::inputGeoFile, mesh, opts_, NEM::DRV::MeshGenDriver::MeshGenFiles::outputMeshFile, NEM::DRV::NetgenMeshGenDriver::Opts::params, and nemAux::trim_fname().
{
   netgenGen generator{&this->opts_.params};
   int status = generator.createMeshFromSTL(this->files_.inputGeoFile.c_str());
   if (status) {
     std::cerr << "Mesh Generation encountered error." << std::endl;
     exit(1);
   }
   std::string newname = nemAux::trim_fname(this->files_.inputGeoFile, ".vol");
   auto mesh = meshBase::CreateShared(meshBase::exportVolToVtk(newname));
   mesh->setFileName(this->files_.outputMeshFile);
   mesh->report();
   mesh->write();
 }
getFiles()
const NetgenMeshGenDriver::Files & NEM::DRV::NetgenMeshGenDriver::getFiles () const
Definition at line 47 of file NetgenMeshGenDriver.C.
References files_.
{
   return files_;
 }
getOpts()
const NetgenMeshGenDriver::Opts & NEM::DRV::NetgenMeshGenDriver::getOpts () const private
Definition at line 63 of file NetgenMeshGenDriver.C.
References opts_.
Referenced by getParams().
{
   return opts_;
 }
getParams()
const netgenParams & NEM::DRV::NetgenMeshGenDriver::getParams () const
Definition at line 55 of file NetgenMeshGenDriver.C.
References getOpts(), and NEM::DRV::NetgenMeshGenDriver::Opts::params.
{
   return getOpts().params;
 }
readJSON()
std::unique_ptr< NemDriver > NEM::DRV::NemDriver::readJSON (const jsoncons::json & inputjson) static inherited
Parameters
inputjson json input with "Program Type" key
Returns
pointer to base NemDriver class
Definition at line 37 of file NemDriver.C.
Referenced by NEM::DRV::MeshGenDriver::MeshGenDriver().
{
   return inputjson.as<std::unique_ptr<NemDriver>>();
 }
setFiles()
void NEM::DRV::NetgenMeshGenDriver::setFiles (Files files)
Definition at line 51 of file NetgenMeshGenDriver.C.
References files_.
{
   this->files_ = std::move(files);
 }
setOpts()
void NEM::DRV::NetgenMeshGenDriver::setOpts (Opts opts) private
Definition at line 67 of file NetgenMeshGenDriver.C.
References opts_.
Referenced by setParams().
 { this->opts_ = std::move(opts); }
setParams()
void NEM::DRV::NetgenMeshGenDriver::setParams (netgenParams params)
Definition at line 59 of file NetgenMeshGenDriver.C.
References setOpts().
{
   setOpts(Opts{std::move(params)});
 }
Member Data Documentation
files_
Files NEM::DRV::NetgenMeshGenDriver::files_ private
Definition at line 67 of file NetgenMeshGenDriver.H.
Referenced by execute(), getFiles(), and setFiles().
opts_
Opts NEM::DRV::NetgenMeshGenDriver::opts_ private
Definition at line 68 of file NetgenMeshGenDriver.H.
Referenced by execute(), getOpts(), and setOpts().
The documentation for this class was generated from the following files:
NetgenMeshGenDriver.H
NetgenMeshGenDriver.C