NEMoSys: NEM::MSH::gmshGeoMesh Class Reference
NEM::MSH::gmshGeoMesh Class Reference
A concrete implementation of geoMeshBase representing a Gmsh mesh.
Detailed Description
Definition at line 41 of file gmshGeoMesh.H.
Public Member Functions
gmshGeoMesh ()
Construct a gmshGeoMesh with an empty mesh.
gmshGeoMesh (const std::string &gmshMesh)
Construct a gmshGeoMesh from an existing gmsh model.
~gmshGeoMesh () override
void write (const std::string &fileName) override
Write mesh to file.
void report (std::ostream &out) const override
Print a report about the mesh.
virtual void takeGeoMesh (geoMeshBase *otherGeoMesh)
Take the GeoMesh of another geoMeshBase.
virtual void reconstructGeo ()
Construct the geometry from the mesh alone.
virtual void mergeGeoMesh (geoMeshBase *otherGeoMesh)
Merge mesh data from a new geoMesh to an existing geoMesh.
const std::string & getGeoEntArrayName () const
Get the name of the geometric entities array.
void setGeoEntArrayName (const std::string &geoEntArrayName)
Set the name of the geometric entities array.
double getAngleThreshold () const
Get the angle threshold used for surface classification.
void setAngleThreshold (double angleThreshold)
Set the angle threshold used for surface classification.
nemId_t getNumberOfPoints () const
Get the number of points in mesh.
nemId_t getNumberOfCells () const
Get the number of cells in mesh.
void getPoint (nemId_t id, std::array< double, 3 > *x) const
Get the coordinate of a point.
std::array< double, 3 > getPoint (nemId_t id) const
Get the coordinate of a point.
void getCell (nemId_t cellId, vtkGenericCell *cell) const
Get cell.
vtkCell * getCell (nemId_t cellId) const
Get cell.
void getCellBounds (nemId_t cellId, std::array< double, 6 > *bounds) const
Get cell bounds.
std::array< double, 6 > getCellBounds (nemId_t cellId) const
Get cell bounds.
VTKCellType getCellType (nemId_t cellId) const
Get VTK cell type.
void getCellPoints (nemId_t cellId, vtkIdList *ptIds) const
Get list of point ids defining specified cell.
void getPointCells (nemId_t ptId, vtkIdList *cellIds) const
Get list of cell ids using specified point.
void getCellNeighbors (nemId_t cellId, vtkIdList *ptIds, vtkIdList *cellIds) const
Get list of cells sharing points ptIds excluding cellId.
int getNumberOfPointDataArrays () const
Get number of arrays in the point data.
void getPointDataArrayCopy (const std::string &arrayName, vtkAbstractArray *array, int *arrayIdx=nullptr) const
Get copy of point data array by name.
vtkSmartPointer< vtkAbstractArray > getPointDataArrayCopy (const std::string &arrayName, int *arrayIdx=nullptr) const
Create and return a copy of point data array by name.
void getPointDataArrayCopy (int arrayIdx, vtkAbstractArray *array) const
Get copy of point data array by index.
vtkSmartPointer< vtkAbstractArray > getPointDataArrayCopy (int arrayIdx) const
Create and return a copy of point data array by index.
int getNumberOfCellDataArrays () const
Get number of arrays in the cell data.
void getCellDataArrayCopy (const std::string &arrayName, vtkAbstractArray *array, int *arrayIdx=nullptr) const
Get copy of cell data array by name.
vtkSmartPointer< vtkAbstractArray > getCellDataArrayCopy (const std::string &arrayName, int *arrayIdx=nullptr) const
Create and return a copy of cell data array by name.
void getCellDataArrayCopy (int arrayIdx, vtkAbstractArray *array) const
Get copy of cell data array by index.
vtkSmartPointer< vtkAbstractArray > getCellDataArrayCopy (int arrayIdx) const
Create and return a copy of cell data array by index.
int getNumberOfFieldDataArrays () const
Get number of arrays in the field data.
void getFieldDataArrayCopy (const std::string &arrayName, vtkAbstractArray *array, int *arrayIdx=nullptr) const
Get copy of field data array by name.
vtkSmartPointer< vtkAbstractArray > getFieldDataArrayCopy (const std::string &arrayName, int *arrayIdx=nullptr) const
Create and return a copy of field data array by name.
void getFieldDataArrayCopy (int arrayIdx, vtkAbstractArray *array) const
Get copy of field data array by index.
vtkSmartPointer< vtkAbstractArray > getFieldDataArrayCopy (int arrayIdx) const
Create and return a copy of field data array by index.
Static Public Member Functions
static gmshGeoMesh * New ()
static vtkTypeMacro(gmshGeoMesh, geoMeshBase) public VTKCellType getVTKTypeFromGmshType (const std::string &gmshType)
Create a gmshGeoMesh from a file.
Protected Member Functions
int setPointDataArray (vtkAbstractArray *array)
Set point data.
int setCellDataArray (vtkAbstractArray *array)
Set cell data.
int setFieldDataArray (vtkAbstractArray *array)
Set field data.
void unsetPointDataArray (int arrayIdx)
Remove point data array by index.
void unsetPointDataArray (const std::string &arrayName)
Remove point data array by name.
void unsetCellDataArray (int arrayIdx)
Remove cell data array by index.
void unsetCellDataArray (const std::string &arrayName)
Remove cell data array by name.
void unsetFieldDataArray (int arrayIdx)
Remove field data array by index.
void unsetFieldDataArray (const std::string &arrayName)
Remove field data array by name.
const GeoMesh & getGeoMesh () const
Get the underlying geometry object.
void setGeoMesh (const geoMeshBase::GeoMesh &geoMesh)
Set the underlying geometry object.
Static Protected Attributes
static constexpr auto GEO_ENT_DEFAULT_NAME = "GeoEnt"
Private Member Functions
void resetNative () override
Static Private Member Functions
static GeoMesh gmsh2GM (const std::string &gmshMesh)
Convert gmshMesh (name of a gmsh model) to GeoMesh.
static std::string GM2gmsh (const GeoMesh &geoMesh)
Add the mesh from geoMesh to the gmsh model in geoMesh.
Private Attributes
std::string _gmshMesh
Inherits NEM::MSH::geoMeshBase.
Constructor & Destructor Documentation
gmshGeoMesh() [1/2]
NEM::MSH::gmshGeoMesh::gmshGeoMesh ()
Definition at line 111 of file gmshGeoMesh.C.
Referenced by NEM::MSH::vtkStandardNewMacro().
 : gmshGeoMesh(std::string()) {}
gmshGeoMesh() [2/2]
NEM::MSH::gmshGeoMesh::gmshGeoMesh (const std::string & gmshMesh) explicit
Parameters
gmshMesh name of gmsh model created from gmsh::open or gmsh::add
Definition at line 113 of file gmshGeoMesh.C.
     : geoMeshBase(gmsh2GM(gmshMesh)), _gmshMesh(gmshMesh) {
   std::cout << "gmshGeoMesh constructed" << std::endl;
 }
~gmshGeoMesh()
NEM::MSH::gmshGeoMesh::~gmshGeoMesh () override
Definition at line 118 of file gmshGeoMesh.C.
References NEM::MSH::GmshInterface::Finalize().
{
   GmshInterface::Finalize();
   std::cout << "gmshGeoMesh destructed" << std::endl;
 }
Member Function Documentation
getAngleThreshold()
double NEM::MSH::geoMeshBase::getAngleThreshold () const inline inherited
Returns
angle threshold (in radians)
Definition at line 171 of file geoMeshBase.H.
 { return _angleThreshold; }
getCell() [1/2]
void NEM::MSH::geoMeshBase::getCell (nemId_t cellId, vtkGenericCell * cell) const inline inherited
Parameters
cellId cell id
cell cell
Definition at line 214 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     _geoMesh.mesh->GetCell(cellId, cell);
   }
getCell() [2/2]
vtkCell* NEM::MSH::geoMeshBase::getCell (nemId_t cellId) const inline inherited
Parameters
cellId cell id
Returns
cell
Definition at line 222 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetCell(cellId);
   }
getCellBounds() [1/2]
void NEM::MSH::geoMeshBase::getCellBounds (nemId_t cellId, std::array< double, 6 > * bounds) const inline inherited
Parameters
cellId cell id
bounds array of bounds as (x_min,x_max, y_min,y_max, z_min,z_max)
Definition at line 230 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellBounds(cellId, bounds->data());
   }
getCellBounds() [2/2]
std::array<double, 6> NEM::MSH::geoMeshBase::getCellBounds (nemId_t cellId) const inline inherited
Parameters
cellId cell id
Returns
array of bounds as (x_min,x_max, y_min,y_max, z_min,z_max)
Definition at line 238 of file geoMeshBase.H.
{
     std::array<double, 6> bounds{};
     getCellBounds(cellId, &bounds);
     return bounds;
   }
getCellDataArrayCopy() [1/4]
void NEM::MSH::geoMeshBase::getCellDataArrayCopy (const std::string & arrayName, vtkAbstractArray * array, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
array cell data array
arrayIdx array index
Definition at line 180 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
Referenced by NEM::MSH::diffMesh().
{
   getArrCopy(_geoMesh.mesh->GetCellData(), arrayName, arrayIdx, array);
 }
getCellDataArrayCopy() [2/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getCellDataArrayCopy (const std::string & arrayName, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
arrayIdx array index
Returns
pointer to copy of array
Definition at line 186 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetCellData(), arrayName, arrayIdx);
 }
getCellDataArrayCopy() [3/4]
void NEM::MSH::geoMeshBase::getCellDataArrayCopy (int arrayIdx, vtkAbstractArray * array) const inherited
Parameters
arrayIdx array index
array cell data array
Definition at line 191 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   getArrCopy(_geoMesh.mesh->GetCellData(), arrayIdx, array);
 }
getCellDataArrayCopy() [4/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getCellDataArrayCopy (int arrayIdx) const inherited
Parameters
arrayIdx array index
Returns
pointer to copy of array
Definition at line 196 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetCellData(), arrayIdx);
 }
getCellNeighbors()
void NEM::MSH::geoMeshBase::getCellNeighbors (nemId_t cellId, vtkIdList * ptIds, vtkIdList * cellIds) const inline inherited
Parameters
cellId id of cell to exclude
ptIds point id
cellIds list of cell ids
Definition at line 273 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellNeighbors(cellId, ptIds, cellIds);
   }
getCellPoints()
void NEM::MSH::geoMeshBase::getCellPoints (nemId_t cellId, vtkIdList * ptIds) const inline inherited
Parameters
cellId cell id
ptIds list of point ids
Definition at line 256 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellPoints(cellId, ptIds);
   }
getCellType()
VTKCellType NEM::MSH::geoMeshBase::getCellType (nemId_t cellId) const inline inherited
Parameters
cellId cell id
Returns
VTK cell type (see vtk documentation for specifics)
Definition at line 248 of file geoMeshBase.H.
{
     return static_cast<VTKCellType>(_geoMesh.mesh->GetCellType(cellId));
   }
getFieldDataArrayCopy() [1/4]
void NEM::MSH::geoMeshBase::getFieldDataArrayCopy (const std::string & arrayName, vtkAbstractArray * array, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
array field data array
arrayIdx array index
Definition at line 201 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   getArrCopy(_geoMesh.mesh->GetFieldData(), arrayName, arrayIdx, array);
 }
getFieldDataArrayCopy() [2/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getFieldDataArrayCopy (const std::string & arrayName, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
arrayIdx array index
Returns
pointer to copy of array
Definition at line 207 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetFieldData(), arrayName, arrayIdx);
 }
getFieldDataArrayCopy() [3/4]
void NEM::MSH::geoMeshBase::getFieldDataArrayCopy (int arrayIdx, vtkAbstractArray * array) const inherited
Parameters
arrayIdx array index
array field data array
Definition at line 212 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   getArrCopy(_geoMesh.mesh->GetFieldData(), arrayIdx, array);
 }
getFieldDataArrayCopy() [4/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getFieldDataArrayCopy (int arrayIdx) const inherited
Parameters
arrayIdx array index
Returns
pointer to copy of array
Definition at line 217 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetFieldData(), arrayIdx);
 }
getGeoEntArrayName()
const std::string& NEM::MSH::geoMeshBase::getGeoEntArrayName () const inline inherited
Returns
name of geometric entities array
Definition at line 157 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
 { return _geoMesh.link; }
getGeoMesh()
const GeoMesh& NEM::MSH::geoMeshBase::getGeoMesh () const inline protected inherited
Note
This is not a copy; Gmsh does not support cloning a model.
Definition at line 533 of file geoMeshBase.H.
Referenced by NEM::MSH::exoGeoMesh::addCellsToBlock(), NEM::MSH::exoGeoMesh::addElemBlock(), NEM::MSH::exoGeoMesh::addElemBlockProperty(), NEM::MSH::exoGeoMesh::addNodeSet(), NEM::MSH::exoGeoMesh::addSideSet(), NEM::MSH::exoGeoMesh::exoGeoMesh(), NEM::MSH::exoGeoMesh::getElemBlock(), NEM::MSH::exoGeoMesh::getElemBlockId(), NEM::MSH::exoGeoMesh::getSideSet(), NEM::MSH::vtkGeoMesh::getVtkMesh(), NEM::MSH::inpGeoMesh::inpGeoMesh(), NEM::MSH::exoGeoMesh::reassignCells(), NEM::MSH::oshGeoMesh::reconstructGeo(), NEM::MSH::exoGeoMesh::reconstructGeo(), NEM::MSH::geoMeshBase::report(), NEM::MSH::exoGeoMesh::resetElemBlocks(), NEM::MSH::smeshGeoMesh::resetNative(), resetNative(), NEM::MSH::inpGeoMesh::resetNative(), NEM::MSH::foamGeoMesh::resetNative(), NEM::MSH::oshGeoMesh::resetNative(), NEM::MSH::exoGeoMesh::resetNative(), NEM::MSH::exoGeoMesh::scaleNodes(), NEM::MSH::oshGeoMesh::setOshMesh(), NEM::MSH::exoGeoMesh::setPhysGrpPropertyName(), NEM::MSH::exoGeoMesh::setSideSetObjId(), NEM::MSH::exoGeoMesh::stitch(), write(), NEM::MSH::vtkGeoMesh::write(), and NEM::MSH::exoGeoMesh::write().
 { return _geoMesh; }
getNumberOfCellDataArrays()
int NEM::MSH::geoMeshBase::getNumberOfCellDataArrays () const inline inherited
Returns
number of arrays in the cell data
Definition at line 318 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     return _geoMesh.mesh->GetCellData()->GetNumberOfArrays();
   }
getNumberOfCells()
nemId_t NEM::MSH::geoMeshBase::getNumberOfCells () const inline inherited
Returns
number of cells in mesh
Definition at line 190 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
 { return _geoMesh.mesh->GetNumberOfCells(); }
getNumberOfFieldDataArrays()
int NEM::MSH::geoMeshBase::getNumberOfFieldDataArrays () const inline inherited
Returns
number of arrays in the field data
Definition at line 355 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetFieldData()->GetNumberOfArrays();
   }
getNumberOfPointDataArrays()
int NEM::MSH::geoMeshBase::getNumberOfPointDataArrays () const inline inherited
Returns
number of arrays in the point data
Definition at line 281 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     return _geoMesh.mesh->GetPointData()->GetNumberOfArrays();
   }
getNumberOfPoints()
nemId_t NEM::MSH::geoMeshBase::getNumberOfPoints () const inline inherited
Returns
number of points in mesh
Definition at line 183 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     return _geoMesh.mesh->GetNumberOfPoints();
   }
getPoint() [1/2]
void NEM::MSH::geoMeshBase::getPoint (nemId_t id, std::array< double, 3 > * x) const inline inherited
Parameters
id point id
x array of coordinates as (x,y,z)
Definition at line 196 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     _geoMesh.mesh->GetPoint(id, x->data());
   }
getPoint() [2/2]
std::array<double, 3> NEM::MSH::geoMeshBase::getPoint (nemId_t id) const inline inherited
Parameters
id point id
Returns
array of coordinates as (x,y,z)
Definition at line 204 of file geoMeshBase.H.
{
     std::array<double, 3> x{};
     getPoint(id, &x);
     return x;
   }
getPointCells()
void NEM::MSH::geoMeshBase::getPointCells (nemId_t ptId, vtkIdList * cellIds) const inline inherited
Parameters
ptId point id
cellIds list of cell ids
Definition at line 264 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetPointCells(ptId, cellIds);
   }
getPointDataArrayCopy() [1/4]
void NEM::MSH::geoMeshBase::getPointDataArrayCopy (const std::string & arrayName, vtkAbstractArray * array, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
array point data array
arrayIdx array index
Definition at line 159 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
Referenced by NEM::MSH::diffMesh().
{
   getArrCopy(_geoMesh.mesh->GetPointData(), arrayName, arrayIdx, array);
 }
getPointDataArrayCopy() [2/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getPointDataArrayCopy (const std::string & arrayName, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
arrayIdx array index
Returns
pointer to copy of array
Definition at line 165 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetPointData(), arrayName, arrayIdx);
 }
getPointDataArrayCopy() [3/4]
void NEM::MSH::geoMeshBase::getPointDataArrayCopy (int arrayIdx, vtkAbstractArray * array) const inherited
Parameters
arrayIdx array index
array point data array
Definition at line 170 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   getArrCopy(_geoMesh.mesh->GetPointData(), arrayIdx, array);
 }
getPointDataArrayCopy() [4/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getPointDataArrayCopy (int arrayIdx) const inherited
Parameters
arrayIdx array index
Returns
pointer to copy of array
Definition at line 175 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetPointData(), arrayIdx);
 }
getVTKTypeFromGmshType()
VTKCellType NEM::MSH::gmshGeoMesh::getVTKTypeFromGmshType (const std::string & gmshType) static
Parameters
fileName file name that gmsh can read
Returns
new gmshGeoMesh object Convert gmsh cell type to VTK cell type
Parameters
gmshType gmsh cell type
Returns
VTK cell type
Definition at line 131 of file gmshGeoMesh.C.
References nemAux::findFromStr(), and nemAux::findToStr().
{
   std::string name = nemAux::findToStr(gmshType, " ");
   int numV;
   if (name == "Point") {
     numV = 1;
   } else {
     numV = std::stoi(nemAux::findFromStr(gmshType, " "));
   }
   if (name == "Point") {
     return VTK_VERTEX;
   } else if (name == "Line") {
     switch (numV) {
       case 3: return VTK_QUADRATIC_EDGE;
       default: return VTK_LINE;
     }
   } else if (name == "Triangle") {
     switch (numV) {
       case 6: return VTK_QUADRATIC_TRIANGLE;
       default: return VTK_TRIANGLE;
     }
   } else if (name == "Quadrilateral") {
     switch (numV) {
       case 8: return VTK_QUADRATIC_QUAD;
       case 9: return VTK_BIQUADRATIC_QUAD;
       default: return VTK_QUAD;
     }
   } else if (name == "Polygon") {
     return VTK_POLYGON;
   } else if (name == "Tetrahedron") {
     switch (numV) {
       case 10: return VTK_QUADRATIC_TETRA;
       default: return VTK_TETRA;
     }
   } else if (name == "Hexahedron") {
     switch (numV) {
       case 20: return VTK_QUADRATIC_HEXAHEDRON;
       case 27: return VTK_TRIQUADRATIC_HEXAHEDRON;
       default: return VTK_HEXAHEDRON;
     }
   } else if (name == "Prism") {
     return VTK_WEDGE;
   } else if (name == "Pyramid") {
     return VTK_PYRAMID;
   } else if (name == "Trihedron" ||  // Flat Quad + 2 Tris.
              name == "Polyhedron")   // Occurs in MElementCuts
   {
     std::cerr << "ERROR in Gmsh to VTK element conversion: Gmsh element \""
               << name << "\" is not supported by VTK." << std::endl;
   } else {
     std::cerr << "ERROR in Gmsh to VTK element conversion: Gmsh element \""
               << name << "\" is not recognized." << std::endl;
   }
   throw;
 }
GM2gmsh()
std::string NEM::MSH::gmshGeoMesh::GM2gmsh (const GeoMesh & geoMesh) static private
Definition at line 271 of file gmshGeoMesh.C.
References NEM::MSH::geoMeshBase::GeoMesh::geo, NEM::MSH::geoMeshBase::SideSet::getGeoEntArr(), NEM::MSH::geoMeshBase::GeoMesh::link, NEM::MSH::geoMeshBase::GeoMesh::mesh, NEM::MSH::geoMeshBase::SideSet::sides, and NEM::MSH::geoMeshBase::GeoMesh::sideSet.
Referenced by write().
{
   gmsh::model::setCurrent(geoMesh.geo);
   if (geoMesh.mesh->GetNumberOfPoints() > 0) {  // Add points
     std::vector<std::size_t> nodeTags;
     std::vector<double> coord;
     vtkSmartPointer<vtkPoints> dataSetPoints = geoMesh.mesh->GetPoints();
     coord.resize(3 * dataSetPoints->GetNumberOfPoints());
     nodeTags.resize(dataSetPoints->GetNumberOfPoints());
     for (vtkIdType ptId = 0; ptId < dataSetPoints->GetNumberOfPoints();
          ++ptId) {
       nodeTags[ptId] = ptId + 1;
       dataSetPoints->GetPoint(ptId, &coord[3 * ptId]);
     }
     gmsh::vectorpair dimTags;
     gmsh::model::getEntities(dimTags);
     gmsh::model::mesh::addNodes(dimTags[0].first, dimTags[0].second, nodeTags,
                                 coord);
   }
   if (geoMesh.mesh->GetNumberOfCells() > 0) {  // Add elements
     // Sort all cells by entity and element type
     auto it =
         vtkSmartPointer<vtkCellIterator>::Take(geoMesh.mesh->NewCellIterator());
     vtkSmartPointer<vtkIntArray> geoEntArray = vtkIntArray::FastDownCast(
         geoMesh.mesh->GetCellData()->GetArray(geoMesh.link.c_str()));
     for (it->InitTraversal(); !it->IsDoneWithTraversal(); it->GoToNextCell()) {
       int geoEnt = geoEntArray->GetTypedComponent(it->GetCellId(), 0);
       vtkSmartPointer<vtkIdList> ptIds = it->GetPointIds();
       std::vector<std::size_t> nodeTag;
       for (vtkIdType pt = 0; pt < it->GetNumberOfPoints(); ++pt) {
         nodeTag.emplace_back(ptIds->GetId(pt) + 1);
       }
       gmsh::model::mesh::addElementsByType(
           geoEnt, getGmshTypeFromVTKType(it->GetCellType()),
           {static_cast<std::size_t>(it->GetCellId() + 1)}, nodeTag);
     }
   }
   if (geoMesh.sideSet.sides && geoMesh.sideSet.sides->GetNumberOfCells() > 0) {
     auto it = vtkSmartPointer<vtkCellIterator>::Take(
         geoMesh.sideSet.sides->NewCellIterator());
     auto geoEntArray = geoMesh.sideSet.getGeoEntArr();
     for (it->InitTraversal(); !it->IsDoneWithTraversal(); it->GoToNextCell()) {
       int geoEnt = geoEntArray->GetTypedComponent(it->GetCellId(), 0);
       vtkSmartPointer<vtkIdList> ptIds = it->GetPointIds();
       std::vector<std::size_t> nodeTag;
       for (vtkIdType pt = 0; pt < it->GetNumberOfPoints(); ++pt) {
         nodeTag.emplace_back(ptIds->GetId(pt) + 1);
       }
       gmsh::model::mesh::addElementsByType(
           geoEnt, getGmshTypeFromVTKType(it->GetCellType()),
           {static_cast<std::size_t>(it->GetCellId() + 1)}, nodeTag);
     }
   }
   gmsh::model::mesh::reclassifyNodes();
   return geoMesh.geo;
 }
gmsh2GM()
geoMeshBase::GeoMesh NEM::MSH::gmshGeoMesh::gmsh2GM (const std::string & gmshMesh) static private
Definition at line 187 of file gmshGeoMesh.C.
References NEM::MSH::geoMeshBase::GEO_ENT_DEFAULT_NAME, NEM::MSH::New(), and points.
{
   auto vtkMesh = vtkSmartPointer<vtkUnstructuredGrid>::New();
   if (gmshMesh.empty()) return {vtkMesh, gmshMesh, "", {}};
   std::string geoEntArrayName = GEO_ENT_DEFAULT_NAME;
   gmsh::model::setCurrent(gmshMesh);
   // Track GMSH node ids and VTK point ids.
   std::map<std::size_t, vtkIdType> gmshNodeNum2vtkId;
   {  // Add points
     vtkSmartPointer<vtkPoints> points =
         vtkSmartPointer<vtkPoints>::Take(vtkPoints::New(VTK_DOUBLE));
     // Get GMSH nodes
     std::vector<std::size_t> nodeTags;
     std::vector<double> coord;
     std::vector<double> parametricCoord;
     gmsh::model::mesh::getNodes(nodeTags, coord, parametricCoord);
     // Allocate
     points->Allocate(nodeTags.size());
     // Convert GMSH nodes to VTK points
     for (std::size_t i = 0; i < nodeTags.size(); ++i) {
       gmshNodeNum2vtkId[nodeTags[i]] = points->GetNumberOfPoints();
       points->InsertNextPoint(coord[i * 3 + 0], coord[i * 3 + 1],
                               coord[i * 3 + 2]);
     }
     vtkMesh->SetPoints(points);
   }
   {  // Add elements and geometric entities
     // Note: Cannot pre-allocate cells since GMSH does not provide an API to get
     // total number of elements
     gmsh::vectorpair dimTags;
     gmsh::model::getEntities(dimTags, gmsh::model::getDimension());
     // geoEnt: Track entities to place as cell data
     vtkSmartPointer<vtkIntArray> vtkEntities =
         vtkSmartPointer<vtkIntArray>::New();
     vtkEntities->Initialize();  // Cannot allocate
     vtkEntities->SetName(geoEntArrayName.c_str());
     addGmshEntitiesToDataSet(dimTags, gmshNodeNum2vtkId, vtkMesh, vtkEntities);
     // geoEnt: Add geometric entity data to VTK
     vtkMesh->GetCellData()->AddArray(vtkEntities);
     // Since could not allocate elements/cells, we have to squeeze
     vtkMesh->Squeeze();
   }
   SideSet sideSet{};
   {  // sideSet
     gmsh::vectorpair dimTags;
     gmsh::model::getEntities(dimTags, gmsh::model::getDimension() - 1);
     if (!dimTags.empty()) {
       auto sideSetPD = vtkSmartPointer<vtkPolyData>::New();
       sideSetPD->SetPoints(vtkMesh->GetPoints());
       sideSetPD->Allocate();
       vtkNew<vtkIntArray> vtkEntities{};
       addGmshEntitiesToDataSet(dimTags, gmshNodeNum2vtkId, sideSetPD,
                                vtkEntities);
       if (sideSetPD->GetNumberOfCells() > 0) {
         sideSetPD->Squeeze();
         sideSet = SideSet(sideSetPD, vtkEntities);
       }
     }
   }
   // TODO: Add point, cell data
   // Only keep the geometry in the gmshMesh
   gmsh::model::mesh::clear();
   return {vtkMesh, gmshMesh, geoEntArrayName, sideSet};
 }
mergeGeoMesh()
void NEM::MSH::geoMeshBase::mergeGeoMesh (geoMeshBase * otherGeoMesh) virtual inherited
Deletes the data from the new geoMesh pointer
Parameters
otherGeoMesh A new geoMesh data to merge
Definition at line 113 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, NEM::MSH::geoMeshBase::GeoMesh::mesh, NEM::MSH::New(), and NEM::MSH::geoMeshBase::resetNative().
{
   vtkSmartPointer<vtkAppendFilter> appendFilter =
       vtkSmartPointer<vtkAppendFilter>::New();
   appendFilter->AddInputData(_geoMesh.mesh);
   appendFilter->AddInputData(otherGeoMesh->_geoMesh.mesh);
   appendFilter->MergePointsOn();
   appendFilter->Update();
   _geoMesh.mesh = appendFilter->GetOutput();
   otherGeoMesh->_geoMesh = {
       vtkSmartPointer<vtkUnstructuredGrid>::New(), {}, {}, {}};
   otherGeoMesh->resetNative();
 }
New()
static gmshGeoMesh* NEM::MSH::gmshGeoMesh::New () static
Referenced by NEM::MSH::New(), and NEM::SRV::srvBase::RequestDataObject().
reconstructGeo()
void NEM::MSH::geoMeshBase::reconstructGeo () virtual inherited
Sets geometry, link, and side set. Does not alter the mesh.
Reimplemented in NEM::MSH::exoGeoMesh, NEM::MSH::oshGeoMesh, and NEM::MSH::inpGeoMesh.
Definition at line 466 of file geoMeshBaseReconstructGeo.C.
References NEM::MSH::geoMeshBase::_angleThreshold, NEM::MSH::geoMeshBase::_geoMesh, NEM::MSH::geoMeshBase::GeoMesh::geo, NEM::MSH::geoMeshBase::GEO_ENT_DEFAULT_NAME, nemAux::getRandomString(), NEM::MSH::geoMeshBase::GeoMesh::link, NEM::MSH::geoMeshBase::GeoMesh::mesh, NEM::MSH::geoMeshBase::SideSet::sides, and NEM::MSH::geoMeshBase::GeoMesh::sideSet.
Referenced by NEM::MSH::inpGeoMesh::reconstructGeo(), NEM::MSH::oshGeoMesh::reconstructGeo(), and NEM::MSH::exoGeoMesh::reconstructGeo().
{
 #ifdef HAVE_GMSH
   if (_geoMesh.geo.empty()) {
     _geoMesh.geo = "geoMesh_" + nemAux::getRandomString(6);
   } else {
     gmsh::model::setCurrent(_geoMesh.geo);
     gmsh::model::remove();
   }
   gmsh::model::add(_geoMesh.geo);
   gmsh::model::setCurrent(_geoMesh.geo);
 #endif
   if (_geoMesh.link.empty()) {
     _geoMesh.link = GEO_ENT_DEFAULT_NAME;
   }
   _geoMesh.sideSet = SideSet{
       computeDiscreteGeoFromMsh(_geoMesh.mesh, _geoMesh.link, _angleThreshold)};
   assert(_geoMesh.mesh->GetPoints() == _geoMesh.sideSet.sides->GetPoints());
 }
report()
void NEM::MSH::gmshGeoMesh::report (std::ostream & out) const override virtual
Parameters
out stream
Implements NEM::MSH::geoMeshBase.
Definition at line 129 of file gmshGeoMesh.C.
References NEM::MSH::geoMeshBase::report().
 { geoMeshBase::report(out); }
resetNative()
void NEM::MSH::gmshGeoMesh::resetNative () override private virtual
Implements NEM::MSH::geoMeshBase.
Definition at line 338 of file gmshGeoMesh.C.
References _gmshMesh, NEM::MSH::geoMeshBase::GEO_ENT_DEFAULT_NAME, NEM::MSH::geoMeshBase::getGeoMesh(), nemAux::getRandomString(), mesh, NEM::MSH::geoMeshBase::GeoMesh::mesh, NEM::MSH::New(), and NEM::MSH::geoMeshBase::setGeoMesh().
{
   auto gm = getGeoMesh();
   if (gm.geo.empty()) {
     gm.geo = "geoMesh_" + nemAux::getRandomString(6);
     gmsh::model::add(gm.geo);
   }
   if (gm.link.empty()) {
     gm.link = GEO_ENT_DEFAULT_NAME;
     auto linkArr = vtkSmartPointer<vtkIntArray>::New();
     linkArr->SetName(gm.link.c_str());
     linkArr->SetNumberOfTuples(getGeoMesh().mesh->GetNumberOfCells());
     linkArr->FillComponent(0, 1);
     getGeoMesh().mesh->GetCellData()->AddArray(linkArr);
   }
   setGeoMesh(gm);
   _gmshMesh = gm.geo;
 }
setAngleThreshold()
void NEM::MSH::geoMeshBase::setAngleThreshold (double angleThreshold) inline inherited
Parameters
angleThreshold (in radians)
Definition at line 176 of file geoMeshBase.H.
{
     _angleThreshold = angleThreshold;
   }
setCellDataArray()
int NEM::MSH::geoMeshBase::setCellDataArray (vtkAbstractArray * array) inline protected inherited
Parameters
array array pointer
Returns
array index
Definition at line 473 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetCellData()->AddArray(array);
   }
setFieldDataArray()
int NEM::MSH::geoMeshBase::setFieldDataArray (vtkAbstractArray * array) inline protected inherited
Parameters
array array pointer
Returns
array index
Definition at line 481 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetFieldData()->AddArray(array);
   }
setGeoEntArrayName()
void NEM::MSH::geoMeshBase::setGeoEntArrayName (const std::string & geoEntArrayName) inline inherited
Parameters
geoEntArrayName name of geometric entities array
Definition at line 162 of file geoMeshBase.H.
{
     auto a = _geoMesh.mesh->GetCellData()->GetArray(_geoMesh.link.c_str());
     if (a) a->SetName(geoEntArrayName.c_str());
     _geoMesh.link = geoEntArrayName;
   }
setGeoMesh()
void NEM::MSH::geoMeshBase::setGeoMesh (const geoMeshBase::GeoMesh & geoMesh) inline protected inherited
Parameters
geoMesh a mesh and geometry
Definition at line 538 of file geoMeshBase.H.
References NEM::MSH::geoMeshBase::GeoMesh::mesh, NEM::MSH::geoMeshBase::SideSet::sides, and NEM::MSH::geoMeshBase::GeoMesh::sideSet.
Referenced by NEM::MSH::exoGeoMesh::addCellsToBlock(), NEM::MSH::exoGeoMesh::addElemBlock(), NEM::MSH::exoGeoMesh::addSideSet(), NEM::MSH::exoGeoMesh::reassignCells(), NEM::MSH::exoGeoMesh::reconstructGeo(), resetNative(), NEM::MSH::exoGeoMesh::resetNative(), NEM::MSH::exoGeoMesh::scaleNodes(), NEM::MSH::foamGeoMesh::setFoamMesh(), NEM::MSH::oshGeoMesh::setOshMesh(), NEM::MSH::smeshGeoMesh::setSMeshMesh(), NEM::MSH::vtkGeoMesh::setVtkMesh(), NEM::MSH::exoGeoMesh::stitch(), NEM::MSH::oshGeoMesh::takeGeoMesh(), and NEM::MSH::exoGeoMesh::takeGeoMesh().
{
     assert(geoMesh.mesh->GetNumberOfCells() == 0 ||
            geoMesh.mesh->GetNumberOfPoints() == 0 ||
            geoMesh.sideSet.sides == nullptr ||
            geoMesh.sideSet.sides->GetPoints() == geoMesh.mesh->GetPoints());
     _geoMesh = geoMesh;
   }
setPointDataArray()
int NEM::MSH::geoMeshBase::setPointDataArray (vtkAbstractArray * array) inline protected inherited
Parameters
array array pointer
Returns
array index
Definition at line 465 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetPointData()->AddArray(array);
   }
takeGeoMesh()
void NEM::MSH::geoMeshBase::takeGeoMesh (geoMeshBase * otherGeoMesh) virtual inherited
Note that otherGeoMesh will be left with an empty mesh.
Parameters
otherGeoMesh other geoMeshBase object; mesh will be left empty
Reimplemented in NEM::MSH::exoGeoMesh, and NEM::MSH::oshGeoMesh.
Definition at line 104 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, NEM::MSH::New(), and NEM::MSH::geoMeshBase::resetNative().
Referenced by NEM::MSH::oshGeoMesh::takeGeoMesh(), and NEM::MSH::exoGeoMesh::takeGeoMesh().
{
   _geoMesh = std::move(otherGeoMesh->_geoMesh);
   otherGeoMesh->_geoMesh = {
       vtkSmartPointer<vtkUnstructuredGrid>::New(), {}, {}, {}};
   otherGeoMesh->resetNative();
   resetNative();
 }
unsetCellDataArray() [1/2]
void NEM::MSH::geoMeshBase::unsetCellDataArray (int arrayIdx) inline protected inherited
Parameters
arrayIdx array index
Definition at line 503 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellData()->RemoveArray(arrayIdx);
   }
unsetCellDataArray() [2/2]
void NEM::MSH::geoMeshBase::unsetCellDataArray (const std::string & arrayName) inline protected inherited
Parameters
arrayName array name
Definition at line 510 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellData()->RemoveArray(arrayName.c_str());
   }
unsetFieldDataArray() [1/2]
void NEM::MSH::geoMeshBase::unsetFieldDataArray (int arrayIdx) inline protected inherited
Parameters
arrayIdx array index
Definition at line 517 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetFieldData()->RemoveArray(arrayIdx);
   }
unsetFieldDataArray() [2/2]
void NEM::MSH::geoMeshBase::unsetFieldDataArray (const std::string & arrayName) inline protected inherited
Parameters
arrayName array name
Definition at line 524 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetFieldData()->RemoveArray(arrayName.c_str());
   }
unsetPointDataArray() [1/2]
void NEM::MSH::geoMeshBase::unsetPointDataArray (int arrayIdx) inline protected inherited
Parameters
arrayIdx array index
Definition at line 489 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetPointData()->RemoveArray(arrayIdx);
   }
unsetPointDataArray() [2/2]
void NEM::MSH::geoMeshBase::unsetPointDataArray (const std::string & arrayName) inline protected inherited
Parameters
arrayName array name
Definition at line 496 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetPointData()->RemoveArray(arrayName.c_str());
   }
write()
void NEM::MSH::gmshGeoMesh::write (const std::string & fileName) override virtual
Parameters
fileName file name
Implements NEM::MSH::geoMeshBase.
Definition at line 123 of file gmshGeoMesh.C.
References _gmshMesh, NEM::MSH::geoMeshBase::getGeoMesh(), and GM2gmsh().
{
   _gmshMesh = GM2gmsh(this->getGeoMesh());
   gmsh::write(fileName);
   gmsh::model::mesh::clear();
 }
Member Data Documentation
_gmshMesh
std::string NEM::MSH::gmshGeoMesh::_gmshMesh private
Definition at line 92 of file gmshGeoMesh.H.
Referenced by resetNative(), and write().
GEO_ENT_DEFAULT_NAME
constexpr auto NEM::MSH::geoMeshBase::GEO_ENT_DEFAULT_NAME = "GeoEnt" static protected inherited
Definition at line 446 of file geoMeshBase.H.
Referenced by gmsh2GM(), NEM::MSH::inpGeoMesh::inp2GM(), NEM::MSH::oshGeoMesh::osh2GM(), NEM::MSH::exoGeoMesh::reconstructGeo(), NEM::MSH::geoMeshBase::reconstructGeo(), and resetNative().
The documentation for this class was generated from the following files:
gmshGeoMesh.H
gmshGeoMesh.C