NEMoSys: NEM::DRV::BlockMeshMeshGenDriver Class Reference
NEM::DRV::BlockMeshMeshGenDriver Class Reference
Detailed Description
Definition at line 39 of file BlockMeshMeshGenDriver.H.
Classes
struct Opts
Public Types
using Files = DriverOutFile
Public Member Functions
BlockMeshMeshGenDriver (Files file, blockMeshParams params)
const Files & getFiles () const
void setFiles (Files file)
const blockMeshParams & getParams () const
void setParams (blockMeshParams params)
void execute () const override
Run the workflow represented by the driver.
Static Public Member Functions
static std::unique_ptr< NemDriver > readJSON (const jsoncons::json &inputjson)
Factory method for all drivers.
Private Member Functions
BlockMeshMeshGenDriver ()
const Opts & getOpts () const
void setOpts (Opts opts)
Private Attributes
Files file_
Opts opts_
Inherits NEM::DRV::MeshGenDriver.
Member Typedef Documentation
Files
using NEM::DRV::BlockMeshMeshGenDriver::Files = DriverOutFile
Definition at line 41 of file BlockMeshMeshGenDriver.H.
Constructor & Destructor Documentation
BlockMeshMeshGenDriver() [1/2]
NEM::DRV::BlockMeshMeshGenDriver::BlockMeshMeshGenDriver (Files file, blockMeshParams params)
Definition at line 41 of file BlockMeshMeshGenDriver.C.
     : file_(std::move(file)), opts_(std::move(params)) {}
BlockMeshMeshGenDriver() [2/2]
NEM::DRV::BlockMeshMeshGenDriver::BlockMeshMeshGenDriver () private
Definition at line 45 of file BlockMeshMeshGenDriver.C.
     : BlockMeshMeshGenDriver(Files{{}}, {}) {}
Member Function Documentation
execute()
void NEM::DRV::BlockMeshMeshGenDriver::execute () const override virtual
Implements NEM::DRV::NemDriver.
Definition at line 72 of file BlockMeshMeshGenDriver.C.
References meshBase::Create(), blockMeshGen::createMeshFromSTL(), meshBase::CreateShared(), file_, mesh, opts_, NEM::DRV::DriverOutFile::outputFile, and NEM::DRV::BlockMeshMeshGenDriver::Opts::params.
{
   auto paramsCopy = this->opts_.params;
   blockMeshGen generator{&paramsCopy};
   // TODO: Make sure blockMeshGen::createMeshFromSTL sets return value and check
   //  it here
   // Parameter not used
   generator.createMeshFromSTL(nullptr);
   auto mesh = meshBase::CreateShared(
       meshBase::Create(generator.getDataSet(), this->file_.outputFile));
   mesh->report();
   mesh->write();
 }
getFiles()
const BlockMeshMeshGenDriver::Files & NEM::DRV::BlockMeshMeshGenDriver::getFiles () const
Definition at line 48 of file BlockMeshMeshGenDriver.C.
References file_.
{
   return file_;
 }
getOpts()
const BlockMeshMeshGenDriver::Opts & NEM::DRV::BlockMeshMeshGenDriver::getOpts () const private
Definition at line 64 of file BlockMeshMeshGenDriver.C.
References opts_.
Referenced by getParams().
{
   return opts_;
 }
getParams()
const blockMeshParams & NEM::DRV::BlockMeshMeshGenDriver::getParams () const
Definition at line 56 of file BlockMeshMeshGenDriver.C.
References getOpts(), and NEM::DRV::BlockMeshMeshGenDriver::Opts::params.
{
   return getOpts().params;
 }
readJSON()
std::unique_ptr< NemDriver > NEM::DRV::NemDriver::readJSON (const jsoncons::json & inputjson) static inherited
Parameters
inputjson json input with "Program Type" key
Returns
pointer to base NemDriver class
Definition at line 37 of file NemDriver.C.
Referenced by NEM::DRV::MeshGenDriver::MeshGenDriver().
{
   return inputjson.as<std::unique_ptr<NemDriver>>();
 }
setFiles()
void NEM::DRV::BlockMeshMeshGenDriver::setFiles (Files file)
Definition at line 52 of file BlockMeshMeshGenDriver.C.
References file_.
{
   this->file_ = std::move(file);
 }
setOpts()
void NEM::DRV::BlockMeshMeshGenDriver::setOpts (Opts opts) private
Definition at line 68 of file BlockMeshMeshGenDriver.C.
References opts_.
Referenced by setParams().
{
   this->opts_ = std::move(opts);
 }
setParams()
void NEM::DRV::BlockMeshMeshGenDriver::setParams (blockMeshParams params)
Definition at line 60 of file BlockMeshMeshGenDriver.C.
References setOpts().
{
   setOpts(Opts{std::move(params)});
 }
Member Data Documentation
file_
Files NEM::DRV::BlockMeshMeshGenDriver::file_ private
Definition at line 66 of file BlockMeshMeshGenDriver.H.
Referenced by execute(), getFiles(), and setFiles().
opts_
Opts NEM::DRV::BlockMeshMeshGenDriver::opts_ private
Definition at line 67 of file BlockMeshMeshGenDriver.H.
Referenced by execute(), getOpts(), and setOpts().
The documentation for this class was generated from the following files:
BlockMeshMeshGenDriver.H
BlockMeshMeshGenDriver.C