NEMoSys: solutionData Class Reference
solutionData Class Reference
Detailed Description
Definition at line 65 of file cgnsAnalyzer.H.
Public Member Functions
solutionData (std::string sName, solution_type_t inDataType)
~solutionData ()=default
void appendData (const vecSlnType &data, int inNData, int inNDim)
void getData (vecSlnType &inBuff, int &outNData, int &outNDim) const
void getData (vecSlnType &inBuff, int &outNData, int &outNDim, const std::vector< bool > &mask) const
void rmvDataIdx (const std::vector< int > &rmvIdx)
std::string getDataName () const
int getNDim () const
int getNData () const
solution_type_t getDataType () const
void clearBuff ()
Private Types
using vecSlnType = std::vector< double >
Private Attributes
vecSlnType slnData
std::string dataName
int nDim
int nData
solution_type_t dataType
Member Typedef Documentation
vecSlnType
using solutionData::vecSlnType = std::vector<double> private
Definition at line 67 of file cgnsAnalyzer.H.
Constructor & Destructor Documentation
solutionData()
solutionData::solutionData (std::string sName, solution_type_t inDataType) inline
Definition at line 70 of file cgnsAnalyzer.H.
References data.
Referenced by cgnsAnalyzer::appendSolutionData(), and cgnsAnalyzer::getSolutionDataObj().
       : dataName(std::move(sName)), nDim(0), nData(0), dataType(inDataType) {}
~solutionData()
solutionData::~solutionData () default
Member Function Documentation
appendData()
void solutionData::appendData (const vecSlnType & data, int inNData, int inNDim)
Definition at line 39 of file cgnsAnalyzer.C.
References nData, nDim, and slnData.
Referenced by cgnsAnalyzer::appendSolutionData(), and cgnsAnalyzer::getSolutionDataObj().
{
   // sanity check
   if (!slnData.empty()) {
     if (nDim != inNDim || inNDim == 0) {
       std::cerr << "Incompatible data size can not be appended."
                 << "Current nDim = " << nDim << " Requested nDim = " << inNDim
                 << std::endl;
       return;
     }
   } else {
     nDim = inNDim;
   }
   // deep copy data
   slnData.insert(slnData.end(), inBuff.begin(), inBuff.end());
   nData += inNData;
 }
clearBuff()
void solutionData::clearBuff () inline
Definition at line 89 of file cgnsAnalyzer.H.
References UNKNOWN.
                    {
     dataName = "";
     dataType = solution_type_t::UNKNOWN;
     nDim = 0;
     nData = 0;
     slnData.clear();
   };
getData() [1/2]
void solutionData::getData (vecSlnType & inBuff, int & outNData, int & outNDim) const
Definition at line 58 of file cgnsAnalyzer.C.
References nData, nDim, and slnData.
Referenced by cgnsAnalyzer::stitchFields().
{
   // deep copy data
   outBuff.insert(outBuff.begin(), slnData.begin(), slnData.end());
   outNData = nData;
   outNDim = nDim;
 }
getData() [2/2]
void solutionData::getData (vecSlnType & inBuff, int & outNData, int & outNDim, const std::vector< bool > & mask) const
Definition at line 67 of file cgnsAnalyzer.C.
References nDim, and slnData.
{
   // deep copy data
   int cntr1 = 0;
   int cntr2 = 0;
   for (const auto &id : mask) {
     if (id) {
       outBuff.insert(outBuff.end(), slnData[cntr1]);
       cntr2++;
     }
     cntr1++;
   }
   outNData = cntr2;
   outNDim = nDim;
 }
getDataName()
std::string solutionData::getDataName () const inline
Definition at line 81 of file cgnsAnalyzer.H.
Referenced by cgnsAnalyzer::stitchFields().
 { return dataName; };
getDataType()
solution_type_t solutionData::getDataType () const inline
Definition at line 87 of file cgnsAnalyzer.H.
Referenced by cgnsAnalyzer::stitchFields().
 { return dataType; };
getNData()
int solutionData::getNData () const inline
Definition at line 85 of file cgnsAnalyzer.H.
Referenced by cgnsAnalyzer::loadSolutionDataContainer().
 { return nData; };
getNDim()
int solutionData::getNDim () const inline
Definition at line 83 of file cgnsAnalyzer.H.
Referenced by cgnsAnalyzer::loadSolutionDataContainer().
 { return nDim; };
rmvDataIdx()
void solutionData::rmvDataIdx (const std::vector< int > & rmvIdx)
Definition at line 83 of file cgnsAnalyzer.C.
References id, nData, nDim, and slnData.
{
   vecSlnType nsdv;
   int nnd = 0;
   for (int id = 0; id < nData; id++) {
     auto it = std::find(rmvIdx.begin(), rmvIdx.end(), id);
     if (it != rmvIdx.end())
       continue;
     else {
       nnd++;
       for (int iDim = 0; iDim < nDim; iDim++)
         nsdv.push_back(slnData[id * nDim + iDim]);
     }
   }
   slnData = nsdv;
   nData = nnd;
 }
Member Data Documentation
dataName
std::string solutionData::dataName private
Definition at line 99 of file cgnsAnalyzer.H.
dataType
solution_type_t solutionData::dataType private
Definition at line 102 of file cgnsAnalyzer.H.
Referenced by cgnsAnalyzer::getSolutionData(), and cgnsAnalyzer::getSolutionDataObj().
nData
int solutionData::nData private
Definition at line 101 of file cgnsAnalyzer.H.
Referenced by appendData(), getData(), rmvDataIdx(), and cgnsAnalyzer::stitchFields().
nDim
int solutionData::nDim private
Definition at line 100 of file cgnsAnalyzer.H.
Referenced by appendData(), getData(), and rmvDataIdx().
slnData
vecSlnType solutionData::slnData private
Definition at line 95 of file cgnsAnalyzer.H.
Referenced by appendData(), getData(), cgnsAnalyzer::getSolutionDataObj(), and rmvDataIdx().
The documentation for this class was generated from the following files:
cgnsAnalyzer.H
cgnsAnalyzer.C