NEMoSys: meshPartitioner Class Reference
meshPartitioner Class Reference
Detailed Description
Definition at line 96 of file meshPartitioner.H.
Public Member Functions
meshPartitioner (int nNde, int nElm, const std::vector< int > &elemConn, MeshType_t meshType)
meshPartitioner (const meshBase *inMB)
~meshPartitioner ()
void setNPartition (int nPartition)
int getNPartition () const
int partition (int nPartition)
int partition ()
std::vector< double > getPartedNde () const
std::vector< double > getPartedElm () const
void setPartedElm (const std::vector< double > &prtElm)
std::vector< double > getCrds (int iPart, const std::vector< double > &crds) const
std::vector< int > getConns (int iPart) const
int getNNdePart (int iPart) const
int getNElmPart (int iPart) const
std::map< int, int > getPartToGlobNodeMap (int iPart) const
std::map< int, int > getPartToGlobElmMap (int iPart) const
std::vector< double > getNdeSlnScalar (int iPart, const std::vector< double > &slns) const
std::vector< double > getElmSlnScalar (int iPart, const std::vector< double > &slns) const
std::vector< double > getElmSlnVec (int iPart, const std::vector< double > &slns, int nComp) const
Private Member Functions
void buildPartitions ()
Private Attributes
int nNde
int nElm
int nPart
std::vector< int > elmConnVec
std::vector< int > elmConn
MeshType_t meshType
std::vector< int > epart
std::vector< int > npart
std::vector< meshPartition * > meshParts
Constructor & Destructor Documentation
meshPartitioner() [1/2]
meshPartitioner::meshPartitioner (int nNde, int nElm, const std::vector< int > & elemConn, MeshType_t meshType) inline
Definition at line 101 of file meshPartitioner.H.
Referenced by meshPartitioner().
                                          :
         nNde(nNde), nElm(nElm), nPart(0), meshType(meshType)
     {
       elmConn.insert(elmConn.begin(), elemConn.begin(), elemConn.end());
     }
meshPartitioner() [2/2]
meshPartitioner::meshPartitioner (const meshBase * inMB) explicit
Definition at line 169 of file meshPartitioner.C.
References meshBase::getConnectivities(), meshBase::getDataSet(), meshBase::getNumberOfCells(), meshBase::getNumberOfPoints(), MESH_TETRA_4, MESH_TRI_3, meshPartitioner(), meshPartition::nElm, NEM::MSH::New(), and meshPartition::nNde.
 {
   vtkSmartPointer<vtkCellTypes> celltypes = vtkSmartPointer<vtkCellTypes>::New();
   inMB->getDataSet()->GetCellTypes(celltypes);
   for (int i = 0; i < celltypes->GetNumberOfTypes(); ++i)
   {
     if (!(celltypes->IsType(VTK_TETRA)) && !(celltypes->IsType(VTK_TRIANGLE))) {
       std::cerr
           << "Partitioner works for 4-node tet and 3-node tri elements only."
           << std::endl;
       exit(-1);
     }
   }
   nNde = inMB->getNumberOfPoints();
   // FIXME: METIS uses int for vertex indices. NEMoSys uses nemId_t (= size_t).
   //        This is a narrowing conversion!
   std::vector<nemId_t> elmConnVec_nemId_t = inMB->getConnectivities();
   elmConnVec = std::vector<int>(elmConnVec_nemId_t.begin(),
                                 elmConnVec_nemId_t.end());
   elmConn = elmConnVec;
   // 1 based index for elmConnVec, 0 based for elmConn
   for (int &i : elmConnVec)
   {
     i = i + 1;
   }
   nElm = inMB->getNumberOfCells();
   if (celltypes->IsType(VTK_TETRA))
     meshType = MeshType_t::MESH_TETRA_4;
   else if (celltypes->IsType(VTK_TRIANGLE))
     meshType = MeshType_t::MESH_TRI_3;
   else {
     std::cerr << "Mesh with unsupported element types." << std::endl;
     exit(-1);
   }
   nPart = 0;
   std::cout << " ------------------- Partitioner Stats ---------------------\n";
   std::cout << "Mesh type : "
             << (meshType == MeshType_t::MESH_TRI_3 ? "Triangular"
                                                    : "Tetrahedral")
             << "\n";
   std::cout << "Number of nodes = " << nNde << "\n"
             << "Number of elements = " << nElm << "\n";
   std::cout << "Size of elmConn = " << elmConnVec.size() << "\n";
   std::cout << "Min connectivity passed to partitioner = "
             << *std::min_element(elmConnVec.begin(), elmConnVec.end()) << "\n";
   std::cout << "Max connectivity passed to partitioner = "
             << *std::max_element(elmConnVec.begin(), elmConnVec.end()) << "\n";
   std::cout << " ----------------------------------------------------------"
             << std::endl;
 }
~meshPartitioner()
meshPartitioner::~meshPartitioner () inline
Definition at line 121 of file meshPartitioner.H.
     {
       if (!meshParts.empty())
         for (int iPart = 0; iPart < nPart; iPart++)
           delete meshParts[iPart];
     };
Member Function Documentation
buildPartitions()
void meshPartitioner::buildPartitions () private
Definition at line 424 of file meshPartitioner.C.
References meshPartition::meshPartition().
 {
   for (int iPart = 0; iPart < nPart; iPart++)
   {
     auto *newPart = new meshPartition(iPart, epart, elmConnVec, meshType);
     meshParts.push_back(newPart);
   }
 }
getConns()
std::vector<int> meshPartitioner::getConns (int iPart) const inline
Definition at line 142 of file meshPartitioner.H.
     { return meshParts[iPart]->getConns(); }
getCrds()
std::vector<double> meshPartitioner::getCrds (int iPart, const std::vector< double > & crds) const inline
Definition at line 139 of file meshPartitioner.H.
     { return meshParts[iPart]->getCrds(crds); }
getElmSlnScalar()
std::vector<double> meshPartitioner::getElmSlnScalar (int iPart, const std::vector< double > & slns) const inline
Definition at line 158 of file meshPartitioner.H.
     { return meshParts[iPart]->getElmSlns(slns); }
getElmSlnVec()
std::vector<double> meshPartitioner::getElmSlnVec (int iPart, const std::vector< double > & slns, int nComp) const inline
Definition at line 161 of file meshPartitioner.H.
     { return meshParts[iPart]->getElmSlnsVec(slns, nComp); }
getNdeSlnScalar()
std::vector<double> meshPartitioner::getNdeSlnScalar (int iPart, const std::vector< double > & slns) const inline
Definition at line 154 of file meshPartitioner.H.
     { return getCrds(iPart, slns); }
getNElmPart()
int meshPartitioner::getNElmPart (int iPart) const inline
Definition at line 145 of file meshPartitioner.H.
 { return meshParts[iPart]->nElm; }
getNNdePart()
int meshPartitioner::getNNdePart (int iPart) const inline
Definition at line 144 of file meshPartitioner.H.
 { return meshParts[iPart]->nNde; }
getNPartition()
int meshPartitioner::getNPartition () const inline
Definition at line 130 of file meshPartitioner.H.
 { return nPart; }
getPartedElm()
std::vector< double > meshPartitioner::getPartedElm () const
Definition at line 406 of file meshPartitioner.C.
 {
   std::vector<double> elmParted(epart.begin(), epart.end());
   return elmParted;
 }
getPartedNde()
std::vector< double > meshPartitioner::getPartedNde () const
Definition at line 400 of file meshPartitioner.C.
 {
   std::vector<double> ndeParted(npart.begin(), npart.end());
   return ndeParted;
 }
getPartToGlobElmMap()
std::map< int, int > meshPartitioner::getPartToGlobElmMap (int iPart) const
Definition at line 445 of file meshPartitioner.C.
 {
   if (iPart > meshParts.size())
   {
     std::cerr << "requested partition number exceeds available partitions"
               << std::endl;
     exit(1);
   }
   return meshParts[iPart]->getPartToGlobElmMap();
 }
getPartToGlobNodeMap()
std::map< int, int > meshPartitioner::getPartToGlobNodeMap (int iPart) const
Definition at line 434 of file meshPartitioner.C.
 {
   if (iPart > meshParts.size())
   {
     std::cerr << "requested partition number exceeds available partitions"
               << std::endl;
     exit(1);
   }
   return meshParts[iPart]->getPartToGlobNodeMap();
 }
partition() [1/2]
int meshPartitioner::partition (int nPartition)
Definition at line 270 of file meshPartitioner.C.
 {
   setNPartition(nPartition);
   return partition();
 }
partition() [2/2]
int meshPartitioner::partition ()
Definition at line 276 of file meshPartitioner.C.
References MESH_TETRA_4, MESH_TRI_3, meshPartition::nElm, and meshPartition::nNde.
 {
   // check
   if (nPart == 0)
   {
     std::cerr << "Number of partitions must be set." << std::endl;
     exit(-1);
   }
   std::cout << "Partitioning the mesh." << std::endl;
 #ifdef HAVE_METIS
   // prepare metis datastructs
   std::vector<idx_t> eptr(nElm + 1);
   idx_t objval = 0;
   epart.resize(nElm, 0);
   npart.resize(nNde, 0);
   int ncommon = 1;
   switch (meshType)
   {
     case MeshType_t::MESH_TETRA_4:
       eptr[0] = 0;
       for (int iElm = 1; iElm <= nElm; iElm++)
         eptr[iElm] = iElm * 4;
       ncommon = 3;
       break;
     case MeshType_t::MESH_TRI_3:
       eptr[0] = 0;
       for (int iElm = 1; iElm <= nElm; iElm++)
         eptr[iElm] = iElm * 3;
       ncommon = 2;
       break;
     default:
       std::cerr << "Unknown or unimplemented element type." << std::endl;
   }
   // setting options (some default values, should be tailored)
   int res;
   METIS_SetDefaultOptions(options);
   options[METIS_OPTION_NUMBERING] = 0; // 0-based index
   options[METIS_OPTION_CONTIG] = 1; // try for contiguous partitions
   options[METIS_OPTION_PTYPE] = METIS_PTYPE_KWAY; // multilevel k-way partitioning
   //options[METIS_OPTION_PTYPE] = METIS_PTYPE_RB; // multilevel recursive bisectioning
   options[METIS_OPTION_OBJTYPE] = METIS_OBJTYPE_VOL; // minimize edge cut METIS_OBJTYPE_VOL(comm vol)
   //options[METIS_OPTION_OBJTYPE] = METIS_OBJTYPE_CUT;
   options[METIS_OPTION_UFACTOR] = 1; // load imbalance of 1.001
   //options[METIS_OPTION_CTYPE] = METIS_CTYPE_SHEM; // sorted heavy-edge matching
   // To try to match METIS in Rocstar partitioner, the options can be changed to:
   // - Add SHEM method:      options[METIS_OPTION_CTYPE] = METIS_CTYPE_SHEM;
   // - Replace KWAY with RB: options[METIS_OPTION_PTYPE] = METIS_PTYPE_RB
   // - Replace VOL with CUT: options[METIS_OPTION_OBJTYPE] = METIS_OBJTYPE_CUT
   //options[METIS_OPTION_DBGLVL] = METIS_DBG_INFO | METIS_DBG_TIME |
   //                               METIS_DBG_CONNINFO | METIS_DBG_CONTIGINFO;
   res = METIS_OK;
   /*
   // DEBUG: checking equivalent graph of the mesh
   std::cout << "METIS: Calculating mesh dual graph...." << std::endl;
   idx_t *xadj, *adjncy;
   idx_t numflag = 0;
   res = METIS_MeshToDual(&nElm, &nNde, &eptr[0], &elmConn[0], &ncommon,
                          &numflag, &xadj, &adjncy);
   std::ofstream graphFile;
   graphFile.open("dualGraph.txt");
   for (int iElm = 0; iElm < nElm; iElm++)
   {
     graphFile << " Elm Idx " << iElm + 1 << " -> ";
     for (int iAdj = xadj[iElm]; iAdj < xadj[iElm + 1]; iAdj++)
       graphFile << adjncy[iAdj] << " ";
     graphFile << " ***  " << std::endl;
   }
   graphFile.close();
   std::cout << "Dual graph for the mesh is written to -> dualGraph.txt "
             << std::endl;
   */
   // calling metis partioner
   if (nPart > 1)
   {
     /*
     // DEBUG Information
     std::cout << "Sending data to METIS..." << std::endl;
     std::cout << "nElm = " << nElm << std::endl;
     std::cout << "nNde = " << nNde << std::endl;
     std::cout << "eptr[0] = " << eptr[0] << std::endl;
     std::cout << "eptr[end] = " << eptr[nElm] << std::endl;
     std::cout << "eind = " << elmConn[0] << std::endl;
     */
 //    res = METIS_PartMeshNodal(&nElm, &nNde, &eptr[0], &elmConn[0], nullptr,
 //                              nullptr, &nPart, nullptr, options, &objval,
 //                              &epart[0], &npart[0]);
     res = METIS_PartMeshDual(&nElm, &nNde, &eptr[0], &elmConn[0], nullptr,
                              nullptr, &ncommon, &nPart, nullptr, options,
                              &objval, &epart[0], &npart[0]);
     std::cout << "Received data from METIS" << std::endl;
   }
   // output partitioning results
   // check success
   if (res == METIS_OK)
   {
     std::cout << "Successfully partitioned the mesh." << std::endl;
     // removing the first member of the npart as default
     // index starts from 1
     npart.erase(npart.begin());
     buildPartitions();
     return 0;
   }
   else
   {
     std::cerr << "Failed to partition with error code " << res << std::endl;
     return 1;
   }
 #else
   std::cerr
       << "METIS is not enabled during build. Build NEMoSys with ENABLE_METIS to use this method."
       << std::endl;
   exit(1);
 #endif
 }
setNPartition()
void meshPartitioner::setNPartition (int nPartition) inline
Definition at line 129 of file meshPartitioner.H.
 { nPart = nPartition; }
setPartedElm()
void meshPartitioner::setPartedElm (const std::vector< double > & prtElm)
Definition at line 413 of file meshPartitioner.C.
 {
   int minp, maxp;
   minp = (int)*std::min_element(prtElm.begin(), prtElm.end());
   maxp = (int)*std::max_element(prtElm.begin(), prtElm.end());
   setNPartition(maxp - minp + 1);
   epart.insert(epart.begin(), prtElm.begin(), prtElm.end());
   buildPartitions();
 }
Member Data Documentation
elmConn
std::vector<int> meshPartitioner::elmConn private
Definition at line 174 of file meshPartitioner.H.
elmConnVec
std::vector<int> meshPartitioner::elmConnVec private
Definition at line 173 of file meshPartitioner.H.
epart
std::vector<int> meshPartitioner::epart private
Definition at line 180 of file meshPartitioner.H.
meshParts
std::vector<meshPartition *> meshPartitioner::meshParts private
Definition at line 183 of file meshPartitioner.H.
meshType
MeshType_t meshPartitioner::meshType private
Definition at line 175 of file meshPartitioner.H.
nElm
int meshPartitioner::nElm private
Definition at line 171 of file meshPartitioner.H.
nNde
int meshPartitioner::nNde private
Definition at line 170 of file meshPartitioner.H.
nPart
int meshPartitioner::nPart private
Definition at line 172 of file meshPartitioner.H.
npart
std::vector<int> meshPartitioner::npart private
Definition at line 181 of file meshPartitioner.H.
The documentation for this class was generated from the following files:
meshPartitioner.H
meshPartitioner.C