NEMoSys: orthoPoly3D Class Reference
orthoPoly3D Class Reference
Detailed Description
Definition at line 77 of file orthoPoly3D.H.
Public Member Functions
orthoPoly3D ()
orthoPoly3D (int _order, const Eigen::VectorXd &_sigma, const std::vector< double > &_x, const std::vector< double > &_y, const std::vector< double > &_z)
orthoPoly3D (int _order, const std::vector< std::vector< double >> &coords)
orthoPoly3D (orthoPoly3D &&op)
orthoPoly3D & operator= (orthoPoly3D &&op)
orthoPoly3D (const orthoPoly3D &)=delete
orthoPoly3D & operator= (const orthoPoly3D &)=delete
~orthoPoly3D ()=default
void computeA (const Eigen::VectorXd &sigma)
double operator() (const std::vector< double > &coord)
double eval (const std::vector< double > &coord)
bool status () const
void resetA ()
void Reset ()
Eigen::VectorXd getCoeffs () const
Static Public Member Functions
static orthoPoly3D * Create (int _order, const std::vector< std::vector< double >> &coords)
static std::unique_ptr< orthoPoly3D > CreateUnique (int _order, const std::vector< std::vector< double >> &coords)
Private Member Functions
void initCheck ()
Private Attributes
int order
std::unique_ptr< orthoPoly1D > opx
std::unique_ptr< orthoPoly1D > opy
std::unique_ptr< orthoPoly1D > opz
Eigen::VectorXd a
std::vector< unsigned int > toRemove
bool finished
Constructor & Destructor Documentation
orthoPoly3D() [1/5]
orthoPoly3D::orthoPoly3D ()
Definition at line 110 of file orthoPoly3D.C.
References a.
Referenced by Create(), and initCheck().
                          : opx(new orthoPoly1D()),
                              opy(new orthoPoly1D()),
                              opz(new orthoPoly1D()),
                              finished(false)
 {
   a.resize(0);
 }
orthoPoly3D() [2/5]
orthoPoly3D::orthoPoly3D (int _order, const Eigen::VectorXd & _sigma, const std::vector< double > & _x, const std::vector< double > & _y, const std::vector< double > & _z)
orthoPoly3D() [3/5]
orthoPoly3D::orthoPoly3D (int _order, const std::vector< std::vector< double >> & coords)
Definition at line 153 of file orthoPoly3D.C.
References initCheck(), opx, opy, opz, order, and nemAux::printVec().
     : order(_order), finished(false)
 {
   //int root(round(cbrt(coords.size())));
   //if (coords.size() != root * root * root &&
   //    coords.size() != (root + 1) * (root + 1) * (root + 1))
   //{
   //  std::cerr << "coords are definitely not in a cartesian product set"
   //            << std::endl;
   //  exit(1);
   //}
   initCheck();
   std::vector<double> x(coords.size());
   std::vector<double> y(coords.size());
   std::vector<double> z(coords.size());
   for (int i = 0; i < coords.size(); ++i)
   {
     x[i] = coords[i][0];
     y[i] = coords[i][1];
     z[i] = coords[i][2];
   }
   std::cout << "non-unique coords" << std::endl;
 #ifdef NEMOSYS_DEBUG
   nemAux::printVec(x); //nemAux::printVec(y); nemAux::printVec(z);
 #endif
   //std::vector<double> x_unique;
   //for (int i = 0; i < x.size(); ++i)
   //{
   //  x_unique.push_back(x[i]);
   //  for (int j = i + 1; j < x.size(); ++j)
   //  {
   //    if (x_unique[i] != x[j])
   //  }
   //}
   //std::sort(x.begin(), x.end());
   //x.erase(std::unique(x.begin(), x.end(), Pred), x.end());
   //std::cout << "unique coords" << std::endl;
   //nemAux::printVec(x); //nemAux::printVec(y); nemAux::printVec(z);
   opx = std::unique_ptr<orthoPoly1D>(new orthoPoly1D(order, x));
   opy = std::unique_ptr<orthoPoly1D>(new orthoPoly1D(order, y));
   opz = std::unique_ptr<orthoPoly1D>(new orthoPoly1D(order, z));
 }
orthoPoly3D() [4/5]
orthoPoly3D::orthoPoly3D (orthoPoly3D && op)
Definition at line 203 of file orthoPoly3D.C.
     : order(op.order),
       opx(std::move(op.opx)),
       opy(std::move(op.opy)),
       opz(std::move(op.opz)),
       a(op.a),
       toRemove(op.toRemove),
       finished(op.finished)
 {
   op.Reset();
 }
orthoPoly3D() [5/5]
orthoPoly3D::orthoPoly3D (const orthoPoly3D &) delete
~orthoPoly3D()
orthoPoly3D::~orthoPoly3D () default
Member Function Documentation
computeA()
void orthoPoly3D::computeA (const Eigen::VectorXd & sigma)
Definition at line 254 of file orthoPoly3D.C.
References a, nemAux::Timer::elapsed(), finished, opx, opy, opz, nemAux::printVec(), removeRowT(), nemAux::Timer::start(), nemAux::Timer::stop(), and toRemove.
Referenced by initCheck(), and PatchRecovery::recoverNodalSolution().
 {
   if (!finished)
   {
 #ifdef NEMOSYS_DEBUG
     nemAux::Timer T;
 #endif
     MatrixXd tmp1 = opx->phi * opx->phiTphiInv;
     MatrixXd tmp2 = opy->phi * opy->phiTphiInv;
     MatrixXd tmp3 = opz->phi * opz->phiTphiInv;
 #ifdef NEMOSYS_DEBUG
     nemAux::Timer T1;
     T1.start();
 #endif
     MatrixXd kronProd_full = kroneckerProduct(tmp1, tmp2);
     kronProd_full = kroneckerProduct(kronProd_full, tmp3).eval();
 #ifdef NEMOSYS_DEBUG
     T1.stop();
     std::cout << "Time for building kronprod in constructor: " << T1.elapsed()
               << "\n";
     std::cout << "kronProd_full: " << kronProd_full.rows() << " "
               << kronProd_full.cols() << "\n";
     std::cout << "Removing rows: ";
     nemAux::printVec(toRemove);
 #endif
     MatrixXdRM kronProd_red(kronProd_full.cols() - toRemove.size(),
                             kronProd_full.rows());
 #ifdef NEMOSYS_DEBUG
     T.start();
 #endif
     removeRowT(kronProd_full, kronProd_red, toRemove);
     std::cout << "kronProd_red: " << kronProd_red.rows() << " "
               << kronProd_red.cols() << "\n";
     std::cout << "sigma size: " << sigma.size() << "\n";
     a = kronProd_red * sigma;
 #ifdef NEMOSYS_DEBUG
     T.stop();
     std::cout << "Time: " << T.elapsed() << std::endl;
     std::cout << "shape of a: " << a.rows() << " " << a.cols() << std::endl;
 #endif
     finished = true;
   }
 }
Create()
orthoPoly3D * orthoPoly3D::Create (int _order, const std::vector< std::vector< double >> & coords) static
Definition at line 239 of file orthoPoly3D.C.
References orthoPoly3D().
Referenced by CreateUnique().
 {
   return new orthoPoly3D(_order, coords);
 }
CreateUnique()
std::unique_ptr< orthoPoly3D > orthoPoly3D::CreateUnique (int _order, const std::vector< std::vector< double >> & coords) static
Definition at line 245 of file orthoPoly3D.C.
References Create().
Referenced by PatchRecovery::recoverNodalSolution().
 {
   return std::unique_ptr<orthoPoly3D>(
       orthoPoly3D::Create(_order, coords));
 }
eval()
double orthoPoly3D::eval (const std::vector< double > & coord)
Definition at line 309 of file orthoPoly3D.C.
References a, finished, opx, opy, opz, order, removeColumn(), and toRemove.
Referenced by operator()(), and PatchRecovery::recoverNodalSolution().
 {
   if (!finished)
   {
     std::cerr << "Coefficients to basis have not been generated" << std::endl;
     exit(1);
   }
   MatrixXd phix(1, order + 1);
   MatrixXd phiy(1, order + 1);
   MatrixXd phiz(1, order + 1);
   for (int i = 0; i < order + 1; ++i)
   {
     phix(0, i) = opx->EvaluateOrthogonal(i, coord[0]);
     phiy(0, i) = opy->EvaluateOrthogonal(i, coord[1]);
     phiz(0, i) = opz->EvaluateOrthogonal(i, coord[2]);
   }
   MatrixXd Phi = kroneckerProduct(phix, phiy);
   Phi = kroneckerProduct(Phi, phiz).eval();
 #ifdef NEMOSYS_DEBUG
   std::cout << Phi.rows() << " " << Phi.cols() << std::endl;
 #endif
   MatrixXd Phi_red(Phi.rows(), Phi.cols() - toRemove.size());
   removeColumn(Phi, Phi_red, toRemove);
 #ifdef NEMOSYS_DEBUG
   std::cout << Phi_red.rows() << " " << Phi_red.cols() << std::endl;
   std::cout << a.rows() << " " << a.cols() << std::endl;
 #endif
   return (Phi_red * a)(0, 0);
 }
getCoeffs()
Eigen::VectorXd orthoPoly3D::getCoeffs () const inline
Definition at line 134 of file orthoPoly3D.H.
 { return a; }
initCheck()
void orthoPoly3D::initCheck () private
Definition at line 118 of file orthoPoly3D.C.
References computeA(), finished, opx, opy, opz, order, orthoPoly3D(), and toRemove.
Referenced by orthoPoly3D().
 {
   if (order == 1)
     toRemove = {3, 5, 6, 7};
   else if (order == 2)
     toRemove = {5, 7, 8, 11, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 25,
                 26};
   else if (order == 3)
     toRemove = {7, 10, 11, 13, 14, 15, 19, 22, 23, 25, 26,
                 27, 28, 29, 30, 31, 34, 35, 37, 38, 39, 40,
                 41, 42, 43, 44, 45, 46, 47, 49, 50, 51, 52,
                 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63};
   else
   {
     std::cerr << "Polynomial order greater than 3 is not supported"
               << std::endl;
     exit(1);
   }
 }
operator()()
double orthoPoly3D::operator() (const std::vector< double > & coord)
Definition at line 344 of file orthoPoly3D.C.
References a, nemAux::Timer::elapsed(), eval(), opx, opy, opz, removeColumn(), nemAux::Timer::start(), nemAux::Timer::stop(), and toRemove.
 {
   return eval(coord);
 }
operator=() [1/2]
orthoPoly3D & orthoPoly3D::operator= (orthoPoly3D && op)
Definition at line 217 of file orthoPoly3D.C.
References a, finished, opx, opy, opz, order, Reset(), and toRemove.
 {
   // check against self assignment
   if (this != &op)
   {
     // release held resources
     this->Reset();
     // move resources from op to this (i.e. pilfer)
     opx = std::move(op.opx);
     opy = std::move(op.opy);
     opz = std::move(op.opz);
     a = op.a;
     toRemove = op.toRemove;
     finished = op.finished;
     order = op.order;
     // set op to default state
     op.Reset();
   }
   return *this;
 }
operator=() [2/2]
orthoPoly3D& orthoPoly3D::operator= (const orthoPoly3D &) delete
Reset()
void orthoPoly3D::Reset ()
Definition at line 376 of file orthoPoly3D.C.
References a, finished, opx, opy, opz, and toRemove.
Referenced by operator=().
 {
   if (opx) opx.reset();
   if (opy) opy.reset();
   if (opz) opz.reset();
   a.resize(0);
   finished = false;
   toRemove.resize(0);
 }
resetA()
void orthoPoly3D::resetA ()
Definition at line 299 of file orthoPoly3D.C.
References a, and finished.
Referenced by PatchRecovery::recoverNodalSolution().
 {
   if (finished)
   {
     a.resize(0);
     finished = false;
   }
 }
status()
bool orthoPoly3D::status () const inline
Definition at line 127 of file orthoPoly3D.H.
 { return finished; }
Member Data Documentation
a
Eigen::VectorXd orthoPoly3D::a private
Definition at line 146 of file orthoPoly3D.H.
Referenced by computeA(), eval(), operator()(), operator=(), orthoPoly3D(), Reset(), and resetA().
finished
bool orthoPoly3D::finished private
Definition at line 150 of file orthoPoly3D.H.
Referenced by computeA(), eval(), initCheck(), operator=(), Reset(), and resetA().
opx
std::unique_ptr<orthoPoly1D> orthoPoly3D::opx private
Definition at line 140 of file orthoPoly3D.H.
Referenced by computeA(), eval(), initCheck(), operator()(), operator=(), orthoPoly3D(), and Reset().
opy
std::unique_ptr<orthoPoly1D> orthoPoly3D::opy private
Definition at line 142 of file orthoPoly3D.H.
Referenced by computeA(), eval(), initCheck(), operator()(), operator=(), orthoPoly3D(), and Reset().
opz
std::unique_ptr<orthoPoly1D> orthoPoly3D::opz private
Definition at line 144 of file orthoPoly3D.H.
Referenced by computeA(), eval(), initCheck(), operator()(), operator=(), orthoPoly3D(), and Reset().
order
int orthoPoly3D::order private
Definition at line 138 of file orthoPoly3D.H.
Referenced by eval(), initCheck(), operator=(), and orthoPoly3D().
toRemove
std::vector<unsigned int> orthoPoly3D::toRemove private
Definition at line 148 of file orthoPoly3D.H.
Referenced by computeA(), eval(), initCheck(), operator()(), operator=(), and Reset().
The documentation for this class was generated from the following files:
orthoPoly3D.H
orthoPoly3D.C