NEMoSys: NEM::DRV::CFMeshMeshGenDriver Class Reference
NEM::DRV::CFMeshMeshGenDriver Class Reference
Detailed Description
Definition at line 39 of file CFMeshMeshGenDriver.H.
Classes
struct Opts
Public Types
using Files = MeshGenFiles
Public Member Functions
CFMeshMeshGenDriver (Files files, cfmeshParams params)
const Files & getFiles () const
void setFiles (Files files)
const cfmeshParams & getParams () const
void setParams (cfmeshParams params)
void execute () const override
Run the workflow represented by the driver.
Static Public Member Functions
static std::unique_ptr< NemDriver > readJSON (const jsoncons::json &inputjson)
Factory method for all drivers.
Private Member Functions
CFMeshMeshGenDriver ()
const Opts & getOpts () const
void setOpts (Opts opts)
Private Attributes
Files files_
Opts opts_
Inherits NEM::DRV::MeshGenDriver.
Member Typedef Documentation
Files
using NEM::DRV::CFMeshMeshGenDriver::Files = MeshGenFiles
Definition at line 41 of file CFMeshMeshGenDriver.H.
Constructor & Destructor Documentation
CFMeshMeshGenDriver() [1/2]
NEM::DRV::CFMeshMeshGenDriver::CFMeshMeshGenDriver (Files files, cfmeshParams params)
Definition at line 40 of file CFMeshMeshGenDriver.C.
     : files_(std::move(files)), opts_(std::move(params)) {}
CFMeshMeshGenDriver() [2/2]
NEM::DRV::CFMeshMeshGenDriver::CFMeshMeshGenDriver () private
Definition at line 43 of file CFMeshMeshGenDriver.C.
     : CFMeshMeshGenDriver({{}, {}}, {}) {}
Member Function Documentation
execute()
void NEM::DRV::CFMeshMeshGenDriver::execute () const override virtual
Implements NEM::DRV::NemDriver.
Definition at line 77 of file CFMeshMeshGenDriver.C.
References cfmeshGen::createMeshFromSTL(), files_, NEM::DRV::MeshGenDriver::MeshGenFiles::inputGeoFile, mesh, NEM::MSH::New(), opts_, NEM::DRV::MeshGenDriver::MeshGenFiles::outputMeshFile, NEM::DRV::CFMeshMeshGenDriver::Opts::params, and nemAux::trim_fname().
{
   auto paramsCopy = this->opts_.params;
   cfmeshGen generator{&paramsCopy};
   // TODO: Make sure blockMeshGen::createMeshFromSTL sets return value and check
   //  it here
   // Parameter not used
   generator.createMeshFromSTL(nullptr);
   std::string newname = nemAux::trim_fname(this->files_.inputGeoFile, ".vtu");
   //  auto mesh =
   //      meshBase::CreateShared(meshBase::Create(generator.getDataSet(),
   //      newname));
   //  mesh->setFileName(this->files_.outputMeshFile);
   //  mesh->report();
   //  mesh->write();
   auto mesh = NEM::MSH::New(this->files_.outputMeshFile);
   mesh->takeGeoMesh(generator.gmData.get());
   mesh->write(this->files_.outputMeshFile);
   mesh->Delete();
 }
getFiles()
const CFMeshMeshGenDriver::Files & NEM::DRV::CFMeshMeshGenDriver::getFiles () const
Definition at line 46 of file CFMeshMeshGenDriver.C.
References files_.
{
   return files_;
 }
getOpts()
const CFMeshMeshGenDriver::Opts & NEM::DRV::CFMeshMeshGenDriver::getOpts () const private
Definition at line 63 of file CFMeshMeshGenDriver.C.
References opts_.
Referenced by getParams().
{
   return opts_;
 }
getParams()
const cfmeshParams & NEM::DRV::CFMeshMeshGenDriver::getParams () const
Definition at line 55 of file CFMeshMeshGenDriver.C.
References getOpts(), and NEM::DRV::CFMeshMeshGenDriver::Opts::params.
{
   return getOpts().params;
 }
readJSON()
std::unique_ptr< NemDriver > NEM::DRV::NemDriver::readJSON (const jsoncons::json & inputjson) static inherited
Parameters
inputjson json input with "Program Type" key
Returns
pointer to base NemDriver class
Definition at line 37 of file NemDriver.C.
Referenced by NEM::DRV::MeshGenDriver::MeshGenDriver().
{
   return inputjson.as<std::unique_ptr<NemDriver>>();
 }
setFiles()
void NEM::DRV::CFMeshMeshGenDriver::setFiles (Files files)
Definition at line 50 of file CFMeshMeshGenDriver.C.
References files_, cfmeshParams::geomFilePath, NEM::DRV::MeshGenDriver::MeshGenFiles::inputGeoFile, opts_, and NEM::DRV::CFMeshMeshGenDriver::Opts::params.
{
   this->opts_.params.geomFilePath = files.inputGeoFile;
   this->files_ = std::move(files);
 }
setOpts()
void NEM::DRV::CFMeshMeshGenDriver::setOpts (Opts opts) private
Definition at line 67 of file CFMeshMeshGenDriver.C.
References files_, cfmeshParams::geomFilePath, NEM::DRV::MeshGenDriver::MeshGenFiles::inputGeoFile, opts_, and NEM::DRV::CFMeshMeshGenDriver::Opts::params.
Referenced by setParams().
{
   if (!opts.params.geomFilePath.empty()) {
     this->files_.inputGeoFile = opts.params.geomFilePath;
     this->opts_ = std::move(opts);
   } else {
     this->opts_ = std::move(opts);
     this->opts_.params.geomFilePath = this->files_.inputGeoFile;
   }
 }
setParams()
void NEM::DRV::CFMeshMeshGenDriver::setParams (cfmeshParams params)
Definition at line 59 of file CFMeshMeshGenDriver.C.
References setOpts().
{
   setOpts(Opts{std::move(params)});
 }
Member Data Documentation
files_
Files NEM::DRV::CFMeshMeshGenDriver::files_ private
Definition at line 66 of file CFMeshMeshGenDriver.H.
Referenced by execute(), getFiles(), setFiles(), and setOpts().
opts_
Opts NEM::DRV::CFMeshMeshGenDriver::opts_ private
Definition at line 67 of file CFMeshMeshGenDriver.H.
Referenced by execute(), getOpts(), setFiles(), and setOpts().
The documentation for this class was generated from the following files:
CFMeshMeshGenDriver.H
CFMeshMeshGenDriver.C