NEMoSys: NEM::DRV::FoamRefineDriver Class Reference
NEM::DRV::FoamRefineDriver Class Reference
Detailed Description
Definition at line 58 of file FoamRefineDriver.H.
Classes
struct Opts
Public Types
using Files = DriverInOutFiles
Public Member Functions
FoamRefineDriver (Files files, Opts opts)
const Opts & getOpts () const
void setOpts (Opts opts)
void execute () const override
Run the workflow represented by the driver.
virtual const Files & getFiles () const
virtual void setFiles (Files files)
Static Public Member Functions
static std::unique_ptr< NemDriver > readJSON (const jsoncons::json &inputjson)
Factory method for all drivers.
Protected Attributes
Files files_
Private Member Functions
FoamRefineDriver ()
Private Attributes
Opts opts_
Inherits NEM::DRV::RefineDriver.
Member Typedef Documentation
Files
using NEM::DRV::RefineDriver::Files = DriverInOutFiles inherited
Definition at line 42 of file RefineDriver.H.
Constructor & Destructor Documentation
FoamRefineDriver() [1/2]
NEM::DRV::FoamRefineDriver::FoamRefineDriver (Files files, Opts opts)
Definition at line 99 of file FoamRefineDriver.C.
     : RefineDriver(std::move(files)), opts_(std::move(opts)) {}
FoamRefineDriver() [2/2]
NEM::DRV::FoamRefineDriver::FoamRefineDriver () private
Definition at line 102 of file FoamRefineDriver.C.
 : FoamRefineDriver({{}, {}}, {{}, {}}) {}
Member Function Documentation
execute()
void NEM::DRV::FoamRefineDriver::execute () const override virtual
Implements NEM::DRV::NemDriver.
Definition at line 110 of file FoamRefineDriver.C.
References Foam::AMRFoam::assignToVolScalarField(), meshBase::CreateShared(), NEM::DRV::FoamRefineOptsBase::endTime, NEM::DRV::RefineDriver::files_, NEM::DRV::FoamRefineDriver::Opts::inputFieldFile, NEM::DRV::DriverInOutFiles::inputMeshFile, mesh, opts_, NEM::DRV::DriverInOutFiles::outputMeshFile, NEM::DRV::FoamRefineDriver::Opts::refCriteria, NEM::DRV::RefineDriver::RefineDriver(), NEM::DRV::FoamRefineOptsBase::refineInterval, NEM::DRV::FoamRefineOptsBase::startTime, NEM::DRV::FoamRefineOptsBase::timeStep, Foam::AMRFoam::updateAMRML(), and NEM::DRV::FoamRefineDriver::Opts::VALUE.
{
   // Initializes AMR workflow
   std::unique_ptr<getDicts> initFoam;
   initFoam = std::unique_ptr<getDicts>(new getDicts());
   initFoam->writeBasicDicts("system/", this->opts_.startTime,
                             this->opts_.timeStep, this->opts_.endTime);
   initFoam->createDynamicMeshDict(true);
   auto controlDict_ = initFoam->createControlDict(true);
   Foam::Time runTime(controlDict_.get(), ".", ".");
   auto amr = initializeRefine(this->files_, this->opts_, runTime);
   int nSteps = static_cast<int>(std::round(opts_.endTime / opts_.timeStep));
   // Creates scalar field from incoming text/CSV files
   Foam::volScalarField meshFieldXY =
       amr->readIncomingCellField(this->opts_.inputFieldFile, "meshFieldXY");
   if (opts_.refCriteria == Opts::Criteria::VALUE) {
     for (int i = 0; i < nSteps; i++) {
       amr->updateAMR(this->opts_.refineInterval, this->opts_.maxRefinement,
                      meshFieldXY, this->opts_.lowerRefineLevel,
                      this->opts_.upperRefineLevel, this->opts_.unrefineAbove,
                      this->opts_.unrefineBelow, this->opts_.nBufferLayers,
                      this->opts_.maxCells);
       runTime++;
     }
     meshFieldXY.write();
   } else {  // opts_.refCriteria == Opts::Criteria::GRADIENT
     Foam::volScalarField magGrad = amr->getGradient(meshFieldXY);
     for (int i = 0; i < nSteps; i++) {
       amr->updateAMR(this->opts_.refineInterval, this->opts_.maxRefinement,
                      magGrad, this->opts_.lowerRefineLevel,
                      this->opts_.upperRefineLevel, this->opts_.unrefineAbove,
                      this->opts_.unrefineBelow, this->opts_.nBufferLayers,
                      this->opts_.maxCells);
       runTime++;
     }
     magGrad.write();
   }
   finishRefine(amr.get(), this->files_.outputMeshFile, runTime);
   std::cout << "End!" << std::endl;
 }
getFiles()
const RefineDriver::Files & NEM::DRV::RefineDriver::getFiles () const virtual inherited
Definition at line 40 of file RefineDriver.C.
References NEM::DRV::RefineDriver::files_.
{
   return files_;
 }
getOpts()
const FoamRefineDriver::Opts & NEM::DRV::FoamRefineDriver::getOpts () const
Definition at line 104 of file FoamRefineDriver.C.
References opts_.
{
   return opts_;
 }
readJSON()
std::unique_ptr< NemDriver > NEM::DRV::NemDriver::readJSON (const jsoncons::json & inputjson) static inherited
Parameters
inputjson json input with "Program Type" key
Returns
pointer to base NemDriver class
Definition at line 37 of file NemDriver.C.
Referenced by NEM::DRV::MeshGenDriver::MeshGenDriver().
{
   return inputjson.as<std::unique_ptr<NemDriver>>();
 }
setFiles()
void NEM::DRV::RefineDriver::setFiles (Files files) virtual inherited
Definition at line 44 of file RefineDriver.C.
References NEM::DRV::RefineDriver::files_.
{
   this->files_ = std::move(files);
 }
setOpts()
void NEM::DRV::FoamRefineDriver::setOpts (Opts opts)
Definition at line 108 of file FoamRefineDriver.C.
References opts_.
 { this->opts_ = std::move(opts); }
Member Data Documentation
files_
Files NEM::DRV::RefineDriver::files_ protected inherited
Definition at line 51 of file RefineDriver.H.
Referenced by NEM::DRV::UniformRefineDriver::execute(), NEM::DRV::Z2RefineDriver::execute(), NEM::DRV::SizeFieldRefineDriver::execute(), execute(), NEM::DRV::OmegahRefineDriver::execute(), NEM::DRV::RefineDriver::getFiles(), and NEM::DRV::RefineDriver::setFiles().
opts_
Opts NEM::DRV::FoamRefineDriver::opts_ private
Definition at line 86 of file FoamRefineDriver.H.
Referenced by execute(), getOpts(), and setOpts().
The documentation for this class was generated from the following files:
FoamRefineDriver.H
FoamRefineDriver.C