NEMoSys: NEM::MSH::GmshInterface Class Reference
NEM::MSH::GmshInterface Class Reference
management class for Gmsh interface
Detailed Description
Gmsh uses global (and static members) variables that are initialized and finalized by Gmsh API commands. This class manages geoMeshBase usage of Gmsh to guarantee finalization only when no geoMeshBase instances are left.
Definition at line 66 of file geoMeshBase.H.
Public Member Functions
~GmshInterface ()
GmshInterface (const GmshInterface &)=delete
GmshInterface & operator= (const GmshInterface &)=delete
GmshInterface (GmshInterface &&)=delete
GmshInterface & operator= (GmshInterface &&)=delete
Static Public Member Functions
static void Initialize ()
Initialize Gmsh.
static void Finalize ()
Finalize Gmsh.
Private Member Functions
GmshInterface ()
Static Private Attributes
static std::shared_ptr< GmshInterface > instance = nullptr
static int count = 0
Constructor & Destructor Documentation
~GmshInterface()
NEM::MSH::GmshInterface::~GmshInterface ()
Definition at line 57 of file geoMeshBase.C.
References count, and instance.
{
 #ifdef HAVE_GMSH
   gmsh::finalize();
   std::cout << "Gmsh finalized" << std::endl;
 #endif
 }
GmshInterface() [1/3]
NEM::MSH::GmshInterface::GmshInterface (const GmshInterface &) delete
GmshInterface() [2/3]
NEM::MSH::GmshInterface::GmshInterface (GmshInterface &&) delete
GmshInterface() [3/3]
NEM::MSH::GmshInterface::GmshInterface () private
Definition at line 48 of file geoMeshBase.C.
Referenced by Initialize().
{
 #ifdef HAVE_GMSH
   gmsh::initialize();
   gmsh::option::setNumber("General.Terminal", 1.0);  // Gmsh errors to stderr
   gmsh::option::setNumber("Mesh.SaveAll", 1);
   std::cout << "Gmsh initialized" << std::endl;
 #endif
 }
Member Function Documentation
Finalize()
void NEM::MSH::GmshInterface::Finalize () static
Will only call gmsh::finalize() if count is zero.
Definition at line 72 of file geoMeshBase.C.
References count, and instance.
Referenced by NEM::MSH::geoMeshBase::~geoMeshBase(), and NEM::MSH::gmshGeoMesh::~gmshGeoMesh().
{
   --count;
   if (count == 0) instance.reset();
 }
Initialize()
void NEM::MSH::GmshInterface::Initialize () static
Will only call gmsh::initialize() on first call to method.
Definition at line 67 of file geoMeshBase.C.
References count, GmshInterface(), and instance.
Referenced by NEM::MSH::foamGeoMesh::foam2GM(), NEM::MSH::geoMeshBase::geoMeshBase(), NEM::MSH::inpGeoMesh::inp2GM(), NEM::MSH::vtkGeoMesh::vtk2GM(), and NEM::MSH::vtkStandardNewMacro().
{
   ++count;
   if (!instance) instance = std::shared_ptr<GmshInterface>(new GmshInterface());
 }
operator=() [1/2]
GmshInterface& NEM::MSH::GmshInterface::operator= (const GmshInterface &) delete
operator=() [2/2]
GmshInterface& NEM::MSH::GmshInterface::operator= (GmshInterface &&) delete
Member Data Documentation
count
int NEM::MSH::GmshInterface::count = 0 static private
Definition at line 92 of file geoMeshBase.H.
Referenced by Finalize(), Initialize(), and ~GmshInterface().
instance
std::shared_ptr< GmshInterface > NEM::MSH::GmshInterface::instance = nullptr static private
Definition at line 91 of file geoMeshBase.H.
Referenced by Finalize(), Initialize(), and ~GmshInterface().
The documentation for this class was generated from the following files:
geoMeshBase.H
geoMeshBase.C