NEMoSys: NEM::SRV::srvBase Class Reference
NEM::SRV::srvBase Class Reference abstract
abstract class for services acting on geoMeshBase
Detailed Description
srvBase is an abstract class specifying the interface for all services acting on a geoMeshBase mesh and geometry object. It derives from the vtkAlgorithm, exposing the vtk robust algorithm pipeline for NEMoSys services.
Definition at line 53 of file srvBase.H.
Public Member Functions
vtkAbstractTypeMacro(srvBase, vtkAlgorithm) public NEM::MSH::geoMeshBase * GetOutput ()
Get the output GeoMeshBase for a port on this algorithm.
NEM::MSH::geoMeshBase * GetOutput (int)
Protected Member Functions
srvBase ()
~srvBase () override
virtual int RequestInformation (vtkInformation *request, vtkInformationVector **inputVector, vtkInformationVector *outputVector)
virtual int RequestDataObject (vtkInformation *request, vtkInformationVector **inputVector, vtkInformationVector *outputVector)
This is called by the superclass.
virtual int RequestData (vtkInformation *request, vtkInformationVector **inputVector, vtkInformationVector *outputVector)=0
This is called by the superclass.
virtual int RequestUpdateExtent (vtkInformation *request, vtkInformationVector **inputVector, vtkInformationVector *outputVector)
This is called by the superclass.
Inherits vtkAlgorithm.
Inherited by NEM::SRV::NucMeshSrv, and NEM::SRV::omegahRefineSrv.
Constructor & Destructor Documentation
srvBase()
NEM::SRV::srvBase::srvBase () protected
Definition at line 64 of file srvBase.C.
                  {
   std::cout << "srvBase constructed" << std::endl;
 }
~srvBase()
NEM::SRV::srvBase::~srvBase () override protected
Definition at line 68 of file srvBase.C.
References RequestData(), RequestDataObject(), RequestInformation(), and RequestUpdateExtent().
                   {
   std::cout << "srvBase destructed" << std::endl;
 }
Member Function Documentation
GetOutput() [1/2]
NEM::MSH::geoMeshBase * NEM::SRV::srvBase::GetOutput ()
Definition at line 104 of file srvBase.C.
 { return this->GetOutput(0); }
GetOutput() [2/2]
NEM::MSH::geoMeshBase * NEM::SRV::srvBase::GetOutput (int port)
Definition at line 106 of file srvBase.C.
{
   return NEM::MSH::geoMeshBase::SafeDownCast(this->GetOutputDataObject(port));
 }
RequestData()
virtual int NEM::SRV::srvBase::RequestData (vtkInformation * request, vtkInformationVector ** inputVector, vtkInformationVector * outputVector) protected pure virtual
This is the method you should override.
Implemented in NEM::SRV::omegahRefineSrv.
Referenced by NEM::SRV::NucMeshSrv::FillOutputPortInformation(), and ~srvBase().
RequestDataObject()
int NEM::SRV::srvBase::RequestDataObject (vtkInformation * request, vtkInformationVector ** inputVector, vtkInformationVector * outputVector) protected virtual
Definition at line 110 of file srvBase.C.
References NEM::MSH::gmshGeoMesh::New(), NEM::MSH::vtkGeoMesh::New(), NEM::MSH::smeshGeoMesh::New(), NEM::MSH::foamGeoMesh::New(), NEM::MSH::exoGeoMesh::New(), NEM::MSH::inpGeoMesh::New(), and NEM::MSH::oshGeoMesh::New().
Referenced by ~srvBase().
{
   for (int i = 0; i < outputVector->GetNumberOfInformationObjects(); ++i) {
     auto outInfo = outputVector->GetInformationObject(i);
     auto outAlgInfo = this->GetOutputPortInformation(i);
     if (!outAlgInfo->Has(vtkDataObject::DATA_TYPE_NAME())) {
       return 0;
     }
     std::string typeName = outAlgInfo->Get(vtkDataObject::DATA_TYPE_NAME());
     MSH::geoMeshBase *output = nullptr;
     if (typeName == "vtkGeoMesh") {
       output = MSH::vtkGeoMesh::New();
     } else if (typeName == "gmshGeoMesh") {
 #ifdef HAVE_GMSH
       output = MSH::gmshGeoMesh::New();
 #endif
     } else if (typeName == "oshGeoMesh") {
       output = MSH::oshGeoMesh::New();
     } else if (typeName == "exoGeoMesh") {
       output = MSH::exoGeoMesh::New();
     } else if (typeName == "inpGeoMesh") {
       output = MSH::inpGeoMesh::New();
     } else if (typeName == "foamGeoMesh") {
 #ifdef HAVE_CFMSH
       output = MSH::foamGeoMesh::New();
 #endif
     } else if (typeName == "smeshGeoMesh") {
 #ifdef HAVE_OCC
       output = MSH::smeshGeoMesh::New();
 #endif
     } else if (typeName == "geoMeshBase") {
       if (i < this->GetNumberOfInputPorts() &&
           inputVector[i]->GetNumberOfInformationObjects() > 0) {
         auto inObj = inputVector[i]
                 ->GetInformationObject(0)
                 ->Get(vtkDataObject::DATA_OBJECT());
         if (inObj) {
           output = MSH::geoMeshBase::SafeDownCast(inObj->NewInstance());
         }
       }
     }
     if (!output) {
       return 0;
     }
     outInfo->Set(vtkDataObject::DATA_OBJECT(), output);
     output->FastDelete();
     this->GetOutputPortInformation(i)->Set(
         vtkDataObject::DATA_EXTENT_TYPE(), output->GetExtentType());
   }
   return 1;
 }
RequestInformation()
int NEM::SRV::srvBase::RequestInformation (vtkInformation * request, vtkInformationVector ** inputVector, vtkInformationVector * outputVector) protected virtual
Definition at line 97 of file srvBase.C.
Referenced by ~srvBase().
{
   // do nothing let subclasses handle it
   return 1;
 }
RequestUpdateExtent()
int NEM::SRV::srvBase::RequestUpdateExtent (vtkInformation * request, vtkInformationVector ** inputVector, vtkInformationVector * outputVector) protected virtual
Definition at line 163 of file srvBase.C.
Referenced by ~srvBase().
{
   int numInputPorts = this->GetNumberOfInputPorts();
   for (int i = 0; i < numInputPorts; i++) {
     int numInputConnections = this->GetNumberOfInputConnections(i);
     for (int j = 0; j < numInputConnections; j++) {
       vtkInformation *inputInfo = inputVector[i]->GetInformationObject(j);
       inputInfo->Set(vtkStreamingDemandDrivenPipeline::EXACT_EXTENT(), 1);
     }
   }
   return 1;
 }
The documentation for this class was generated from the following files:
srvBase.H
srvBase.C