NEMoSys: NEM::MSH::smeshGeoMesh Class Reference
NEM::MSH::smeshGeoMesh Class Reference abstract
Detailed Description
Definition at line 43 of file smeshGeoMesh.H.
Public Member Functions
smeshGeoMesh ()
~smeshGeoMesh () override
void setSMeshMesh (std::unique_ptr< SMESH_Mesh > &&mesh, std::shared_ptr< SMESH_Gen > gen)
const SMESH_Mesh & getSMESHMesh () const
virtual void write (const std::string &fileName)=0
Write mesh to file.
virtual void report (std::ostream &out) const =0
Print a report about the mesh.
virtual void takeGeoMesh (geoMeshBase *otherGeoMesh)
Take the GeoMesh of another geoMeshBase.
virtual void reconstructGeo ()
Construct the geometry from the mesh alone.
virtual void mergeGeoMesh (geoMeshBase *otherGeoMesh)
Merge mesh data from a new geoMesh to an existing geoMesh.
const std::string & getGeoEntArrayName () const
Get the name of the geometric entities array.
void setGeoEntArrayName (const std::string &geoEntArrayName)
Set the name of the geometric entities array.
double getAngleThreshold () const
Get the angle threshold used for surface classification.
void setAngleThreshold (double angleThreshold)
Set the angle threshold used for surface classification.
nemId_t getNumberOfPoints () const
Get the number of points in mesh.
nemId_t getNumberOfCells () const
Get the number of cells in mesh.
void getPoint (nemId_t id, std::array< double, 3 > *x) const
Get the coordinate of a point.
std::array< double, 3 > getPoint (nemId_t id) const
Get the coordinate of a point.
void getCell (nemId_t cellId, vtkGenericCell *cell) const
Get cell.
vtkCell * getCell (nemId_t cellId) const
Get cell.
void getCellBounds (nemId_t cellId, std::array< double, 6 > *bounds) const
Get cell bounds.
std::array< double, 6 > getCellBounds (nemId_t cellId) const
Get cell bounds.
VTKCellType getCellType (nemId_t cellId) const
Get VTK cell type.
void getCellPoints (nemId_t cellId, vtkIdList *ptIds) const
Get list of point ids defining specified cell.
void getPointCells (nemId_t ptId, vtkIdList *cellIds) const
Get list of cell ids using specified point.
void getCellNeighbors (nemId_t cellId, vtkIdList *ptIds, vtkIdList *cellIds) const
Get list of cells sharing points ptIds excluding cellId.
int getNumberOfPointDataArrays () const
Get number of arrays in the point data.
void getPointDataArrayCopy (const std::string &arrayName, vtkAbstractArray *array, int *arrayIdx=nullptr) const
Get copy of point data array by name.
vtkSmartPointer< vtkAbstractArray > getPointDataArrayCopy (const std::string &arrayName, int *arrayIdx=nullptr) const
Create and return a copy of point data array by name.
void getPointDataArrayCopy (int arrayIdx, vtkAbstractArray *array) const
Get copy of point data array by index.
vtkSmartPointer< vtkAbstractArray > getPointDataArrayCopy (int arrayIdx) const
Create and return a copy of point data array by index.
int getNumberOfCellDataArrays () const
Get number of arrays in the cell data.
void getCellDataArrayCopy (const std::string &arrayName, vtkAbstractArray *array, int *arrayIdx=nullptr) const
Get copy of cell data array by name.
vtkSmartPointer< vtkAbstractArray > getCellDataArrayCopy (const std::string &arrayName, int *arrayIdx=nullptr) const
Create and return a copy of cell data array by name.
void getCellDataArrayCopy (int arrayIdx, vtkAbstractArray *array) const
Get copy of cell data array by index.
vtkSmartPointer< vtkAbstractArray > getCellDataArrayCopy (int arrayIdx) const
Create and return a copy of cell data array by index.
int getNumberOfFieldDataArrays () const
Get number of arrays in the field data.
void getFieldDataArrayCopy (const std::string &arrayName, vtkAbstractArray *array, int *arrayIdx=nullptr) const
Get copy of field data array by name.
vtkSmartPointer< vtkAbstractArray > getFieldDataArrayCopy (const std::string &arrayName, int *arrayIdx=nullptr) const
Create and return a copy of field data array by name.
void getFieldDataArrayCopy (int arrayIdx, vtkAbstractArray *array) const
Get copy of field data array by index.
vtkSmartPointer< vtkAbstractArray > getFieldDataArrayCopy (int arrayIdx) const
Create and return a copy of field data array by index.
Static Public Member Functions
static smeshGeoMesh * New ()
Protected Member Functions
int setPointDataArray (vtkAbstractArray *array)
Set point data.
int setCellDataArray (vtkAbstractArray *array)
Set cell data.
int setFieldDataArray (vtkAbstractArray *array)
Set field data.
void unsetPointDataArray (int arrayIdx)
Remove point data array by index.
void unsetPointDataArray (const std::string &arrayName)
Remove point data array by name.
void unsetCellDataArray (int arrayIdx)
Remove cell data array by index.
void unsetCellDataArray (const std::string &arrayName)
Remove cell data array by name.
void unsetFieldDataArray (int arrayIdx)
Remove field data array by index.
void unsetFieldDataArray (const std::string &arrayName)
Remove field data array by name.
const GeoMesh & getGeoMesh () const
Get the underlying geometry object.
void setGeoMesh (const geoMeshBase::GeoMesh &geoMesh)
Set the underlying geometry object.
Static Protected Attributes
static constexpr auto GEO_ENT_DEFAULT_NAME = "GeoEnt"
Private Member Functions
void resetNative () override
Static Private Member Functions
static GeoMesh SmeshToGM (SMESH_Mesh &mesh)
static void GMToSMESH (const GeoMesh &geoMesh, SMESH_Mesh &outMesh)
Private Attributes
std::shared_ptr< SMESH_Gen > gen_
std::unique_ptr< SMESH_Mesh > mesh_
Inherits NEM::MSH::geoMeshBase.
Constructor & Destructor Documentation
smeshGeoMesh()
NEM::MSH::smeshGeoMesh::smeshGeoMesh ()
~smeshGeoMesh()
NEM::MSH::smeshGeoMesh::~smeshGeoMesh () override default
Referenced by NEM::MSH::mesh_().
Member Function Documentation
getAngleThreshold()
double NEM::MSH::geoMeshBase::getAngleThreshold () const inline inherited
Returns
angle threshold (in radians)
Definition at line 171 of file geoMeshBase.H.
 { return _angleThreshold; }
getCell() [1/2]
void NEM::MSH::geoMeshBase::getCell (nemId_t cellId, vtkGenericCell * cell) const inline inherited
Parameters
cellId cell id
cell cell
Definition at line 214 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     _geoMesh.mesh->GetCell(cellId, cell);
   }
getCell() [2/2]
vtkCell* NEM::MSH::geoMeshBase::getCell (nemId_t cellId) const inline inherited
Parameters
cellId cell id
Returns
cell
Definition at line 222 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetCell(cellId);
   }
getCellBounds() [1/2]
void NEM::MSH::geoMeshBase::getCellBounds (nemId_t cellId, std::array< double, 6 > * bounds) const inline inherited
Parameters
cellId cell id
bounds array of bounds as (x_min,x_max, y_min,y_max, z_min,z_max)
Definition at line 230 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellBounds(cellId, bounds->data());
   }
getCellBounds() [2/2]
std::array<double, 6> NEM::MSH::geoMeshBase::getCellBounds (nemId_t cellId) const inline inherited
Parameters
cellId cell id
Returns
array of bounds as (x_min,x_max, y_min,y_max, z_min,z_max)
Definition at line 238 of file geoMeshBase.H.
{
     std::array<double, 6> bounds{};
     getCellBounds(cellId, &bounds);
     return bounds;
   }
getCellDataArrayCopy() [1/4]
void NEM::MSH::geoMeshBase::getCellDataArrayCopy (const std::string & arrayName, vtkAbstractArray * array, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
array cell data array
arrayIdx array index
Definition at line 180 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
Referenced by NEM::MSH::diffMesh().
{
   getArrCopy(_geoMesh.mesh->GetCellData(), arrayName, arrayIdx, array);
 }
getCellDataArrayCopy() [2/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getCellDataArrayCopy (const std::string & arrayName, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
arrayIdx array index
Returns
pointer to copy of array
Definition at line 186 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetCellData(), arrayName, arrayIdx);
 }
getCellDataArrayCopy() [3/4]
void NEM::MSH::geoMeshBase::getCellDataArrayCopy (int arrayIdx, vtkAbstractArray * array) const inherited
Parameters
arrayIdx array index
array cell data array
Definition at line 191 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   getArrCopy(_geoMesh.mesh->GetCellData(), arrayIdx, array);
 }
getCellDataArrayCopy() [4/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getCellDataArrayCopy (int arrayIdx) const inherited
Parameters
arrayIdx array index
Returns
pointer to copy of array
Definition at line 196 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetCellData(), arrayIdx);
 }
getCellNeighbors()
void NEM::MSH::geoMeshBase::getCellNeighbors (nemId_t cellId, vtkIdList * ptIds, vtkIdList * cellIds) const inline inherited
Parameters
cellId id of cell to exclude
ptIds point id
cellIds list of cell ids
Definition at line 273 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellNeighbors(cellId, ptIds, cellIds);
   }
getCellPoints()
void NEM::MSH::geoMeshBase::getCellPoints (nemId_t cellId, vtkIdList * ptIds) const inline inherited
Parameters
cellId cell id
ptIds list of point ids
Definition at line 256 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellPoints(cellId, ptIds);
   }
getCellType()
VTKCellType NEM::MSH::geoMeshBase::getCellType (nemId_t cellId) const inline inherited
Parameters
cellId cell id
Returns
VTK cell type (see vtk documentation for specifics)
Definition at line 248 of file geoMeshBase.H.
{
     return static_cast<VTKCellType>(_geoMesh.mesh->GetCellType(cellId));
   }
getFieldDataArrayCopy() [1/4]
void NEM::MSH::geoMeshBase::getFieldDataArrayCopy (const std::string & arrayName, vtkAbstractArray * array, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
array field data array
arrayIdx array index
Definition at line 201 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   getArrCopy(_geoMesh.mesh->GetFieldData(), arrayName, arrayIdx, array);
 }
getFieldDataArrayCopy() [2/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getFieldDataArrayCopy (const std::string & arrayName, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
arrayIdx array index
Returns
pointer to copy of array
Definition at line 207 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetFieldData(), arrayName, arrayIdx);
 }
getFieldDataArrayCopy() [3/4]
void NEM::MSH::geoMeshBase::getFieldDataArrayCopy (int arrayIdx, vtkAbstractArray * array) const inherited
Parameters
arrayIdx array index
array field data array
Definition at line 212 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   getArrCopy(_geoMesh.mesh->GetFieldData(), arrayIdx, array);
 }
getFieldDataArrayCopy() [4/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getFieldDataArrayCopy (int arrayIdx) const inherited
Parameters
arrayIdx array index
Returns
pointer to copy of array
Definition at line 217 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetFieldData(), arrayIdx);
 }
getGeoEntArrayName()
const std::string& NEM::MSH::geoMeshBase::getGeoEntArrayName () const inline inherited
Returns
name of geometric entities array
Definition at line 157 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
 { return _geoMesh.link; }
getGeoMesh()
const GeoMesh& NEM::MSH::geoMeshBase::getGeoMesh () const inline protected inherited
Note
This is not a copy; Gmsh does not support cloning a model.
Definition at line 533 of file geoMeshBase.H.
Referenced by NEM::MSH::exoGeoMesh::addCellsToBlock(), NEM::MSH::exoGeoMesh::addElemBlock(), NEM::MSH::exoGeoMesh::addElemBlockProperty(), NEM::MSH::exoGeoMesh::addNodeSet(), NEM::MSH::exoGeoMesh::addSideSet(), NEM::MSH::exoGeoMesh::exoGeoMesh(), NEM::MSH::exoGeoMesh::getElemBlock(), NEM::MSH::exoGeoMesh::getElemBlockId(), NEM::MSH::exoGeoMesh::getSideSet(), NEM::MSH::vtkGeoMesh::getVtkMesh(), NEM::MSH::inpGeoMesh::inpGeoMesh(), NEM::MSH::exoGeoMesh::reassignCells(), NEM::MSH::oshGeoMesh::reconstructGeo(), NEM::MSH::exoGeoMesh::reconstructGeo(), NEM::MSH::geoMeshBase::report(), NEM::MSH::exoGeoMesh::resetElemBlocks(), resetNative(), NEM::MSH::gmshGeoMesh::resetNative(), NEM::MSH::inpGeoMesh::resetNative(), NEM::MSH::foamGeoMesh::resetNative(), NEM::MSH::oshGeoMesh::resetNative(), NEM::MSH::exoGeoMesh::resetNative(), NEM::MSH::exoGeoMesh::scaleNodes(), NEM::MSH::oshGeoMesh::setOshMesh(), NEM::MSH::exoGeoMesh::setPhysGrpPropertyName(), NEM::MSH::exoGeoMesh::setSideSetObjId(), NEM::MSH::exoGeoMesh::stitch(), NEM::MSH::vtkGeoMesh::write(), NEM::MSH::gmshGeoMesh::write(), and NEM::MSH::exoGeoMesh::write().
 { return _geoMesh; }
getNumberOfCellDataArrays()
int NEM::MSH::geoMeshBase::getNumberOfCellDataArrays () const inline inherited
Returns
number of arrays in the cell data
Definition at line 318 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     return _geoMesh.mesh->GetCellData()->GetNumberOfArrays();
   }
getNumberOfCells()
nemId_t NEM::MSH::geoMeshBase::getNumberOfCells () const inline inherited
Returns
number of cells in mesh
Definition at line 190 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
 { return _geoMesh.mesh->GetNumberOfCells(); }
getNumberOfFieldDataArrays()
int NEM::MSH::geoMeshBase::getNumberOfFieldDataArrays () const inline inherited
Returns
number of arrays in the field data
Definition at line 355 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetFieldData()->GetNumberOfArrays();
   }
getNumberOfPointDataArrays()
int NEM::MSH::geoMeshBase::getNumberOfPointDataArrays () const inline inherited
Returns
number of arrays in the point data
Definition at line 281 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     return _geoMesh.mesh->GetPointData()->GetNumberOfArrays();
   }
getNumberOfPoints()
nemId_t NEM::MSH::geoMeshBase::getNumberOfPoints () const inline inherited
Returns
number of points in mesh
Definition at line 183 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     return _geoMesh.mesh->GetNumberOfPoints();
   }
getPoint() [1/2]
void NEM::MSH::geoMeshBase::getPoint (nemId_t id, std::array< double, 3 > * x) const inline inherited
Parameters
id point id
x array of coordinates as (x,y,z)
Definition at line 196 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     _geoMesh.mesh->GetPoint(id, x->data());
   }
getPoint() [2/2]
std::array<double, 3> NEM::MSH::geoMeshBase::getPoint (nemId_t id) const inline inherited
Parameters
id point id
Returns
array of coordinates as (x,y,z)
Definition at line 204 of file geoMeshBase.H.
{
     std::array<double, 3> x{};
     getPoint(id, &x);
     return x;
   }
getPointCells()
void NEM::MSH::geoMeshBase::getPointCells (nemId_t ptId, vtkIdList * cellIds) const inline inherited
Parameters
ptId point id
cellIds list of cell ids
Definition at line 264 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetPointCells(ptId, cellIds);
   }
getPointDataArrayCopy() [1/4]
void NEM::MSH::geoMeshBase::getPointDataArrayCopy (const std::string & arrayName, vtkAbstractArray * array, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
array point data array
arrayIdx array index
Definition at line 159 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
Referenced by NEM::MSH::diffMesh().
{
   getArrCopy(_geoMesh.mesh->GetPointData(), arrayName, arrayIdx, array);
 }
getPointDataArrayCopy() [2/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getPointDataArrayCopy (const std::string & arrayName, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
arrayIdx array index
Returns
pointer to copy of array
Definition at line 165 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetPointData(), arrayName, arrayIdx);
 }
getPointDataArrayCopy() [3/4]
void NEM::MSH::geoMeshBase::getPointDataArrayCopy (int arrayIdx, vtkAbstractArray * array) const inherited
Parameters
arrayIdx array index
array point data array
Definition at line 170 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   getArrCopy(_geoMesh.mesh->GetPointData(), arrayIdx, array);
 }
getPointDataArrayCopy() [4/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getPointDataArrayCopy (int arrayIdx) const inherited
Parameters
arrayIdx array index
Returns
pointer to copy of array
Definition at line 175 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetPointData(), arrayIdx);
 }
getSMESHMesh()
const SMESH_Mesh & NEM::MSH::smeshGeoMesh::getSMESHMesh () const
Definition at line 149 of file smeshGeoMesh.C.
References mesh_.
 { return *mesh_; }
GMToSMESH()
void NEM::MSH::smeshGeoMesh::GMToSMESH (const GeoMesh & geoMesh, SMESH_Mesh & outMesh) static private
Definition at line 151 of file smeshGeoMesh.C.
References NEM::MSH::geoMeshBase::SideSet::getGeoEntArr(), NEM::MSH::geoMeshBase::SideSet::getSideSetNames(), NEM::MSH::geoMeshBase::GeoMesh::link, NEM::MSH::geoMeshBase::GeoMesh::mesh, points, NEM::MSH::geoMeshBase::SideSet::sides, and NEM::MSH::geoMeshBase::GeoMesh::sideSet.
Referenced by resetNative().
{
   auto grid = geoMesh.mesh;
   if (grid->GetNumberOfCells() == 0) { return; }
   auto linkArr = grid->GetCellData()->GetArray(geoMesh.link.c_str());
   auto points = grid->GetPoints();
   auto meshDS = outMesh.GetMeshDS();
   std::vector<SMDS_MeshNode *> smdsNodes;  // indexed by geoMesh id
   smdsNodes.reserve(points->GetNumberOfPoints());
   {
     std::array<double, 3> pointBuffer{};
     for (vtkIdType i = 0; i < points->GetNumberOfPoints(); ++i) {
       grid->GetPoint(i, pointBuffer.data());
       smdsNodes.emplace_back(
           meshDS->AddNode(pointBuffer[0], pointBuffer[1], pointBuffer[2]));
     }
   }
   insertWithGroup(smdsNodes, meshDS, outMesh, grid, linkArr,
                   vtkStringArray::SafeDownCast(
                       grid->GetFieldData()->GetArray("Group Names")));
   insertWithGroup(smdsNodes, meshDS, outMesh, geoMesh.sideSet.sides,
                   geoMesh.sideSet.getGeoEntArr(),
                   geoMesh.sideSet.getSideSetNames());
 }
mergeGeoMesh()
void NEM::MSH::geoMeshBase::mergeGeoMesh (geoMeshBase * otherGeoMesh) virtual inherited
Deletes the data from the new geoMesh pointer
Parameters
otherGeoMesh A new geoMesh data to merge
Definition at line 113 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, NEM::MSH::geoMeshBase::GeoMesh::mesh, NEM::MSH::New(), and NEM::MSH::geoMeshBase::resetNative().
{
   vtkSmartPointer<vtkAppendFilter> appendFilter =
       vtkSmartPointer<vtkAppendFilter>::New();
   appendFilter->AddInputData(_geoMesh.mesh);
   appendFilter->AddInputData(otherGeoMesh->_geoMesh.mesh);
   appendFilter->MergePointsOn();
   appendFilter->Update();
   _geoMesh.mesh = appendFilter->GetOutput();
   otherGeoMesh->_geoMesh = {
       vtkSmartPointer<vtkUnstructuredGrid>::New(), {}, {}, {}};
   otherGeoMesh->resetNative();
 }
New()
static smeshGeoMesh* NEM::MSH::smeshGeoMesh::New () static
Referenced by NEM::MSH::New(), and NEM::SRV::srvBase::RequestDataObject().
reconstructGeo()
void NEM::MSH::geoMeshBase::reconstructGeo () virtual inherited
Sets geometry, link, and side set. Does not alter the mesh.
Reimplemented in NEM::MSH::exoGeoMesh, NEM::MSH::oshGeoMesh, and NEM::MSH::inpGeoMesh.
Definition at line 466 of file geoMeshBaseReconstructGeo.C.
References NEM::MSH::geoMeshBase::_angleThreshold, NEM::MSH::geoMeshBase::_geoMesh, NEM::MSH::geoMeshBase::GeoMesh::geo, NEM::MSH::geoMeshBase::GEO_ENT_DEFAULT_NAME, nemAux::getRandomString(), NEM::MSH::geoMeshBase::GeoMesh::link, NEM::MSH::geoMeshBase::GeoMesh::mesh, NEM::MSH::geoMeshBase::SideSet::sides, and NEM::MSH::geoMeshBase::GeoMesh::sideSet.
Referenced by NEM::MSH::inpGeoMesh::reconstructGeo(), NEM::MSH::oshGeoMesh::reconstructGeo(), and NEM::MSH::exoGeoMesh::reconstructGeo().
{
 #ifdef HAVE_GMSH
   if (_geoMesh.geo.empty()) {
     _geoMesh.geo = "geoMesh_" + nemAux::getRandomString(6);
   } else {
     gmsh::model::setCurrent(_geoMesh.geo);
     gmsh::model::remove();
   }
   gmsh::model::add(_geoMesh.geo);
   gmsh::model::setCurrent(_geoMesh.geo);
 #endif
   if (_geoMesh.link.empty()) {
     _geoMesh.link = GEO_ENT_DEFAULT_NAME;
   }
   _geoMesh.sideSet = SideSet{
       computeDiscreteGeoFromMsh(_geoMesh.mesh, _geoMesh.link, _angleThreshold)};
   assert(_geoMesh.mesh->GetPoints() == _geoMesh.sideSet.sides->GetPoints());
 }
report()
void NEM::MSH::geoMeshBase::report (std::ostream & out) const pure virtual inherited
Parameters
out stream
Implemented in NEM::MSH::oshGeoMesh, NEM::MSH::exoGeoMesh, NEM::MSH::foamGeoMesh, NEM::MSH::gmshGeoMesh, and NEM::MSH::vtkGeoMesh.
Definition at line 97 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::getGeoMesh(), mesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
Referenced by NEM::MSH::inpGeoMesh::inpGeoMesh(), NEM::MSH::mesh_(), NEM::MSH::gmshGeoMesh::report(), NEM::MSH::vtkGeoMesh::report(), NEM::MSH::foamGeoMesh::report(), NEM::MSH::exoGeoMesh::report(), and NEM::MSH::oshGeoMesh::report().
{
   out << this->GetClassName() << ":\n";
   auto mesh = getGeoMesh().mesh;
   out << "Nodes:\t" << mesh->GetNumberOfPoints() << '\n';
   out << "Elements:\t" << mesh->GetNumberOfCells() << '\n';
 }
resetNative()
void NEM::MSH::smeshGeoMesh::resetNative () override private virtual
Implements NEM::MSH::geoMeshBase.
Definition at line 134 of file smeshGeoMesh.C.
References gen_, NEM::MSH::geoMeshBase::getGeoMesh(), GMToSMESH(), and mesh_.
{
   // Careful! Delete mesh before deleting gen!
   mesh_.reset();
   gen_.reset(new SMESH_Gen{});
   mesh_.reset(gen_->CreateMesh(false));
   smeshGeoMesh::GMToSMESH(getGeoMesh(), *mesh_);
 }
setAngleThreshold()
void NEM::MSH::geoMeshBase::setAngleThreshold (double angleThreshold) inline inherited
Parameters
angleThreshold (in radians)
Definition at line 176 of file geoMeshBase.H.
{
     _angleThreshold = angleThreshold;
   }
setCellDataArray()
int NEM::MSH::geoMeshBase::setCellDataArray (vtkAbstractArray * array) inline protected inherited
Parameters
array array pointer
Returns
array index
Definition at line 473 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetCellData()->AddArray(array);
   }
setFieldDataArray()
int NEM::MSH::geoMeshBase::setFieldDataArray (vtkAbstractArray * array) inline protected inherited
Parameters
array array pointer
Returns
array index
Definition at line 481 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetFieldData()->AddArray(array);
   }
setGeoEntArrayName()
void NEM::MSH::geoMeshBase::setGeoEntArrayName (const std::string & geoEntArrayName) inline inherited
Parameters
geoEntArrayName name of geometric entities array
Definition at line 162 of file geoMeshBase.H.
{
     auto a = _geoMesh.mesh->GetCellData()->GetArray(_geoMesh.link.c_str());
     if (a) a->SetName(geoEntArrayName.c_str());
     _geoMesh.link = geoEntArrayName;
   }
setGeoMesh()
void NEM::MSH::geoMeshBase::setGeoMesh (const geoMeshBase::GeoMesh & geoMesh) inline protected inherited
Parameters
geoMesh a mesh and geometry
Definition at line 538 of file geoMeshBase.H.
References NEM::MSH::geoMeshBase::GeoMesh::mesh, NEM::MSH::geoMeshBase::SideSet::sides, and NEM::MSH::geoMeshBase::GeoMesh::sideSet.
Referenced by NEM::MSH::exoGeoMesh::addCellsToBlock(), NEM::MSH::exoGeoMesh::addElemBlock(), NEM::MSH::exoGeoMesh::addSideSet(), NEM::MSH::exoGeoMesh::reassignCells(), NEM::MSH::exoGeoMesh::reconstructGeo(), NEM::MSH::gmshGeoMesh::resetNative(), NEM::MSH::exoGeoMesh::resetNative(), NEM::MSH::exoGeoMesh::scaleNodes(), NEM::MSH::foamGeoMesh::setFoamMesh(), NEM::MSH::oshGeoMesh::setOshMesh(), setSMeshMesh(), NEM::MSH::vtkGeoMesh::setVtkMesh(), NEM::MSH::exoGeoMesh::stitch(), NEM::MSH::oshGeoMesh::takeGeoMesh(), and NEM::MSH::exoGeoMesh::takeGeoMesh().
{
     assert(geoMesh.mesh->GetNumberOfCells() == 0 ||
            geoMesh.mesh->GetNumberOfPoints() == 0 ||
            geoMesh.sideSet.sides == nullptr ||
            geoMesh.sideSet.sides->GetPoints() == geoMesh.mesh->GetPoints());
     _geoMesh = geoMesh;
   }
setPointDataArray()
int NEM::MSH::geoMeshBase::setPointDataArray (vtkAbstractArray * array) inline protected inherited
Parameters
array array pointer
Returns
array index
Definition at line 465 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetPointData()->AddArray(array);
   }
setSMeshMesh()
void NEM::MSH::smeshGeoMesh::setSMeshMesh (std::unique_ptr< SMESH_Mesh > && mesh, std::shared_ptr< SMESH_Gen > gen)
Definition at line 142 of file smeshGeoMesh.C.
References gen_, mesh, mesh_, NEM::MSH::geoMeshBase::setGeoMesh(), and SmeshToGM().
Referenced by NEM::SRV::NucMeshSrv::FillOutputPortInformation().
{
   mesh_ = std::move(mesh);
   gen_ = std::move(gen);
   setGeoMesh(SmeshToGM(*mesh_));
 }
SmeshToGM()
geoMeshBase::GeoMesh NEM::MSH::smeshGeoMesh::SmeshToGM (SMESH_Mesh & mesh) static private
Definition at line 176 of file smeshGeoMesh.C.
References NEM::MSH::containerWrapper(), and maxDim.
Referenced by setSMeshMesh().
{
   vtkNew<vtkUnstructuredGrid> gmGrid;
   vtkNew<vtkPolyData> sideSetSides;
   int numGMCells;
   int maxDim;
   if ((numGMCells = mesh.NbVolumes()) > 0) {
     maxDim = 3;
   } else if ((numGMCells = mesh.NbFaces()) > 0) {
     maxDim = 2;
   } else if ((numGMCells = mesh.NbEdges()) > 0) {
     maxDim = 1;
   } else {
     return {gmGrid, {}, {}, {}};
   }
   auto smeshGrid = mesh.GetMeshDS()->GetGrid();
   gmGrid->Allocate(numGMCells);
   gmGrid->SetPoints(smeshGrid->GetPoints());
   sideSetSides->Allocate();
   sideSetSides->SetPoints(smeshGrid->GetPoints());
   vtkNew<vtkStringArray> groupNamesGrid;
   groupNamesGrid->SetName("Group Names");
   vtkNew<vtkStringArray> groupNamesSides;
   // indexed by vtkID on mesh.GetMeshDS()->GetGrid()
   std::vector<int> groups(smeshGrid->GetNumberOfCells(), -1);
   for (auto group : NEM::MSH::containerWrapper(mesh.GetGroups())) {
     auto groupId = group->GetID();
     if (groupId >= 0) {
       for (auto elem :
            NEM::MSH::containerWrapper(group->GetGroupDS()->GetElements())) {
         auto vtkId = elem->GetVtkID();
         if (vtkId >= 0) {
           auto &cellGroup = groups[vtkId];
           if (cellGroup >= 0) {
             // For now, the behavior is to choose the "latest" group.
             std::cerr << "Warning! SMESH Element found on multiple groups. "
                          "Behavior is undefined.\n";
           }
           cellGroup = groupId;
         }
       }
       auto elemType = group->GetGroupDS()->GetType();
       auto groupDim =
           elemType == SMDSAbs_Volume                                    ? 3
           : elemType == SMDSAbs_Face                                    ? 2
           : (elemType == SMDSAbs_Node || elemType == SMDSAbs_0DElement) ? 1
                                                                         : -1;
       if (groupDim == maxDim || groupDim == -1) {
         groupNamesGrid->InsertValue(groupId, group->GetName());
       }
       if (groupDim == maxDim - 1 || groupDim == -1) {
         groupNamesSides->InsertValue(groupId, group->GetName());
       }
     }
   }
   vtkNew<vtkIntArray> groupsArr;
   groupsArr->SetName("GeoEnt");
   groupsArr->SetNumberOfComponents(1);
   groupsArr->SetNumberOfTuples(numGMCells);
   groupsArr->FillComponent(0, -1);
   vtkNew<vtkIntArray> sideSetEntArr;
   bool geoMeshHasLink;
   for (auto cellIter =
            vtkSmartPointer<vtkCellIterator>::Take(smeshGrid->NewCellIterator());
        !cellIter->IsDoneWithTraversal(); cellIter->GoToNextCell()) {
     auto cellDim = cellIter->GetCellDimension();
     if (cellDim == maxDim) {
       auto gmId = gmGrid->InsertNextCell(cellIter->GetCellType(),
                                          cellIter->GetPointIds());
       auto group = groups[cellIter->GetCellId()];
       if (group >= 0) {
         geoMeshHasLink = true;
         groupsArr->SetComponent(gmId, 0, group);
       }
     } else if (cellDim == maxDim - 1) {
       auto group = groups[cellIter->GetCellId()];
       if (group >= 0) {
         sideSetSides->InsertNextCell(cellIter->GetCellType(),
                                      cellIter->GetPointIds());
         sideSetEntArr->InsertNextValue(group);
       }
     }
   }
   std::string link;
   if (geoMeshHasLink) {
     gmGrid->GetCellData()->AddArray(groupsArr);
     gmGrid->GetFieldData()->AddArray(groupNamesGrid);
     link = groupsArr->GetName();
   }
   return {gmGrid,
           {},
           std::move(link),
           sideSetSides->GetNumberOfCells() > 0
               ? SideSet(sideSetSides, sideSetEntArr, nullptr, nullptr,
                         groupNamesSides)
               : SideSet{}};
 }
takeGeoMesh()
void NEM::MSH::geoMeshBase::takeGeoMesh (geoMeshBase * otherGeoMesh) virtual inherited
Note that otherGeoMesh will be left with an empty mesh.
Parameters
otherGeoMesh other geoMeshBase object; mesh will be left empty
Reimplemented in NEM::MSH::exoGeoMesh, and NEM::MSH::oshGeoMesh.
Definition at line 104 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, NEM::MSH::New(), and NEM::MSH::geoMeshBase::resetNative().
Referenced by NEM::MSH::oshGeoMesh::takeGeoMesh(), and NEM::MSH::exoGeoMesh::takeGeoMesh().
{
   _geoMesh = std::move(otherGeoMesh->_geoMesh);
   otherGeoMesh->_geoMesh = {
       vtkSmartPointer<vtkUnstructuredGrid>::New(), {}, {}, {}};
   otherGeoMesh->resetNative();
   resetNative();
 }
unsetCellDataArray() [1/2]
void NEM::MSH::geoMeshBase::unsetCellDataArray (int arrayIdx) inline protected inherited
Parameters
arrayIdx array index
Definition at line 503 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellData()->RemoveArray(arrayIdx);
   }
unsetCellDataArray() [2/2]
void NEM::MSH::geoMeshBase::unsetCellDataArray (const std::string & arrayName) inline protected inherited
Parameters
arrayName array name
Definition at line 510 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellData()->RemoveArray(arrayName.c_str());
   }
unsetFieldDataArray() [1/2]
void NEM::MSH::geoMeshBase::unsetFieldDataArray (int arrayIdx) inline protected inherited
Parameters
arrayIdx array index
Definition at line 517 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetFieldData()->RemoveArray(arrayIdx);
   }
unsetFieldDataArray() [2/2]
void NEM::MSH::geoMeshBase::unsetFieldDataArray (const std::string & arrayName) inline protected inherited
Parameters
arrayName array name
Definition at line 524 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetFieldData()->RemoveArray(arrayName.c_str());
   }
unsetPointDataArray() [1/2]
void NEM::MSH::geoMeshBase::unsetPointDataArray (int arrayIdx) inline protected inherited
Parameters
arrayIdx array index
Definition at line 489 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetPointData()->RemoveArray(arrayIdx);
   }
unsetPointDataArray() [2/2]
void NEM::MSH::geoMeshBase::unsetPointDataArray (const std::string & arrayName) inline protected inherited
Parameters
arrayName array name
Definition at line 496 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetPointData()->RemoveArray(arrayName.c_str());
   }
write()
virtual void NEM::MSH::geoMeshBase::write (const std::string & fileName) pure virtual inherited
Parameters
fileName file name
Implemented in NEM::MSH::oshGeoMesh, NEM::MSH::exoGeoMesh, NEM::MSH::foamGeoMesh, NEM::MSH::gmshGeoMesh, and NEM::MSH::vtkGeoMesh.
Referenced by NEM::MSH::inpGeoMesh::inpGeoMesh(), and NEM::MSH::mesh_().
Member Data Documentation
gen_
std::shared_ptr<SMESH_Gen> NEM::MSH::smeshGeoMesh::gen_ private
Definition at line 63 of file smeshGeoMesh.H.
Referenced by resetNative(), and setSMeshMesh().
GEO_ENT_DEFAULT_NAME
constexpr auto NEM::MSH::geoMeshBase::GEO_ENT_DEFAULT_NAME = "GeoEnt" static protected inherited
Definition at line 446 of file geoMeshBase.H.
Referenced by NEM::MSH::gmshGeoMesh::gmsh2GM(), NEM::MSH::inpGeoMesh::inp2GM(), NEM::MSH::oshGeoMesh::osh2GM(), NEM::MSH::exoGeoMesh::reconstructGeo(), NEM::MSH::geoMeshBase::reconstructGeo(), and NEM::MSH::gmshGeoMesh::resetNative().
mesh_
std::unique_ptr<SMESH_Mesh> NEM::MSH::smeshGeoMesh::mesh_ private
Definition at line 64 of file smeshGeoMesh.H.
Referenced by getSMESHMesh(), resetNative(), and setSMeshMesh().
The documentation for this class was generated from the following files:
smeshGeoMesh.H
smeshGeoMesh.C