NEMoSys: NEM::DRV::InputGenDriver Class Reference
NEM::DRV::InputGenDriver Class Reference
Detailed Description
Definition at line 41 of file InputGenDriver.H.
Public Member Functions
InputGenDriver (std::string service, jsoncons::json opts)
const std::string & getService () const
void setService (std::string service)
const jsoncons::json & getOpts () const
void setOpts (jsoncons::json opts)
void execute () const override
Run the workflow represented by the driver.
Static Public Member Functions
static std::unique_ptr< NemDriver > readJSON (const jsoncons::json &inputjson)
Factory method for all drivers.
Private Member Functions
InputGenDriver ()=default
jsoncons::string_view getProgramType () const override
Private Attributes
std::string service_ {}
jsoncons::json opts_ {}
Static Private Attributes
static constexpr const char * programType = "Input Generation"
Inherits NEM::DRV::NemDriver.
Constructor & Destructor Documentation
InputGenDriver() [1/2]
NEM::DRV::InputGenDriver::InputGenDriver (std::string service, jsoncons::json opts)
Definition at line 39 of file InputGenDriver.C.
     : service_(std::move(service)), opts_(std::move(opts)) {}
InputGenDriver() [2/2]
NEM::DRV::InputGenDriver::InputGenDriver () private default
Member Function Documentation
execute()
void NEM::DRV::InputGenDriver::execute () const override virtual
Implements NEM::DRV::NemDriver.
Definition at line 58 of file InputGenDriver.C.
References opts_, service_, nemAux::Timer::start(), nemAux::Timer::stop(), and nemAux::toLower().
{
   std::string srvName = this->service_;
   nemAux::toLower(srvName);
   nemAux::Timer T;
   T.start();
   if (srvName == "epic_2016") {
 #ifdef HAVE_EPIC
     ep16Prep::readJSON(this->opts_);
 #else
     std::cerr << "Compile the code with EPIC module enabled." << std::endl;
     exit(0);
 #endif
   } else if (srvName == "epic_2016_post") {
 #ifdef HAVE_EPIC
     int ret;
     NEM::EPC::ep16Post::readJSON(this->opts_, ret);
 #else
     std::cerr << "Compile the code with EPIC module enabled." << std::endl;
     exit(0);
 #endif
   } else {
     std::cerr << "The input generation service " << srvName << "is unsupported."
               << std::endl;
   }
   T.stop();
 }
getOpts()
const jsoncons::json & NEM::DRV::InputGenDriver::getOpts () const
Definition at line 48 of file InputGenDriver.C.
References opts_.
 { return opts_; }
getProgramType()
jsoncons::string_view NEM::DRV::InputGenDriver::getProgramType () const override private virtual
Implements NEM::DRV::NemDriver.
Definition at line 54 of file InputGenDriver.C.
References programType.
{
   return programType;
 }
getService()
const std::string & NEM::DRV::InputGenDriver::getService () const
Definition at line 42 of file InputGenDriver.C.
References service_.
 { return service_; }
readJSON()
std::unique_ptr< NemDriver > NEM::DRV::NemDriver::readJSON (const jsoncons::json & inputjson) static inherited
Parameters
inputjson json input with "Program Type" key
Returns
pointer to base NemDriver class
Definition at line 37 of file NemDriver.C.
Referenced by NEM::DRV::MeshGenDriver::MeshGenDriver().
{
   return inputjson.as<std::unique_ptr<NemDriver>>();
 }
setOpts()
void NEM::DRV::InputGenDriver::setOpts (jsoncons::json opts)
Definition at line 50 of file InputGenDriver.C.
References opts_.
{
   this->opts_ = std::move(opts);
 }
setService()
void NEM::DRV::InputGenDriver::setService (std::string service)
Definition at line 44 of file InputGenDriver.C.
References service_.
{
   this->service_ = std::move(service);
 }
Member Data Documentation
opts_
jsoncons::json NEM::DRV::InputGenDriver::opts_ {} private
Definition at line 59 of file InputGenDriver.H.
Referenced by execute(), getOpts(), and setOpts().
programType
constexpr const char* NEM::DRV::InputGenDriver::programType = "Input Generation" static private
Definition at line 56 of file InputGenDriver.H.
Referenced by getProgramType().
service_
std::string NEM::DRV::InputGenDriver::service_ {} private
Definition at line 58 of file InputGenDriver.H.
Referenced by execute(), getService(), and setService().
The documentation for this class was generated from the following files:
InputGenDriver.H
InputGenDriver.C