NEMoSys: nemosysGModel Class Reference
nemosysGModel Class Reference
Detailed Description
Definition at line 46 of file gmshMesh.C.
Public Member Functions
void storeElementsInEntities (std::map< int, std::vector< MElement *>> &map)
void associateEntityWithMeshVertices (bool force=false)
void storeVerticesInEntities (std::vector< MVertex *> &vertices)
void storePhysicalTagsInEntities (int dim, std::map< int, std::map< int, std::string >> &map)
Inherits GModel.
Member Function Documentation
associateEntityWithMeshVertices()
void nemosysGModel::associateEntityWithMeshVertices (bool force = false) inline
Definition at line 52 of file gmshMesh.C.
Referenced by gmshMesh::write().
{
     GModel::_associateEntityWithMeshVertices(force);
   }
storeElementsInEntities()
void nemosysGModel::storeElementsInEntities (std::map< int, std::vector< MElement *>> & map) inline
Definition at line 48 of file gmshMesh.C.
Referenced by gmshMesh::write().
{
     GModel::_storeElementsInEntities(map);
   }
storePhysicalTagsInEntities()
void nemosysGModel::storePhysicalTagsInEntities (int dim, std::map< int, std::map< int, std::string >> & map) inline
Definition at line 60 of file gmshMesh.C.
{
     GModel::_storePhysicalTagsInEntities(dim, map);
   }
storeVerticesInEntities()
void nemosysGModel::storeVerticesInEntities (std::vector< MVertex *> & vertices) inline
Definition at line 56 of file gmshMesh.C.
Referenced by gmshMesh::write().
{
     GModel::_storeVerticesInEntities(vertices);
   }
The documentation for this class was generated from the following file:
gmshMesh.C