NEMoSys: NEM::NUCMESH::CirclesAndPolys Class Reference
NEM::NUCMESH::CirclesAndPolys Class Reference
A set of concentric circles and polygons and the faces they enclose.
Detailed Description
Definition at line 48 of file CirclesAndPolys.H.
Public Member Functions
CirclesAndPolys (int numSides, std::vector< PolyRing > rings, const std::array< double, 3 > &center={0, 0, 0})
Container to describe a set of concentric circles/polygons.
int getNumSides () const
void setNumSides (int numSides)
const std::vector< PolyRing > & getRings () const
void setRings (std::vector< PolyRing > rings)
void addRing (const PolyRing &ring)
const std::array< double, 3 > & getCenter () const
void setCenter (const std::array< double, 3 > &center)
Static Public Member Functions
static std::array< double, 3 > getRotatedPoint (const std::array< double, 3 > &center, const std::array< double, 2 > &rotation)
Protected Member Functions
NEM::GEO::GeoManager createGeo () const override
Construct a NEM::GEO::GeoManager.
Static Protected Member Functions
static void mergeGeo (NEM::GEO::GeoManager &keepGeo, NEM::GEO::GeoManager &&removeGeo)
Merge two 2d NEM::GEO::GeoManager objects by cutting shapes in removeGeo from shapes in keepGeo and sewing the resulting faces.
Private Attributes
int numSides_
std::vector< PolyRing > rings_
Inherits NEM::NUCMESH::ShapeBase.
Constructor & Destructor Documentation
CirclesAndPolys()
NEM::NUCMESH::CirclesAndPolys::CirclesAndPolys (int numSides, std::vector< PolyRing > rings, const std::array< double, 3 > & center = {0, 0, 0})
Parameters
numSides Number of sides for polygons (note circles are treated as numSides arcs)
rings Radius and meshing description of each ring
center Center of shapes
Definition at line 151 of file CirclesAndPolys.C.
     : ShapeBase(center), numSides_(numSides), rings_(std::move(rings)) {}
Member Function Documentation
addRing()
void NEM::NUCMESH::CirclesAndPolys::addRing (const PolyRing & ring)
Definition at line 167 of file CirclesAndPolys.C.
References rings_.
{
   this->rings_.emplace_back(ring);
 }
createGeo()
NEM::GEO::GeoManager NEM::NUCMESH::CirclesAndPolys::createGeo () const override protected virtual
Returns
A NEM::GEO::GeoManager object representing the shape described by this object
Implements NEM::NUCMESH::ShapeBase.
Definition at line 298 of file CirclesAndPolys.C.
References NEM::NUCMESH::drawNested(), NEM::NUCMESH::ShapeBase::getCenter(), numSides_, NEM::NUCMESH::Ring::radius, rings_, NEM::NUCMESH::PolyRing::rotation, and NEM::NUCMESH::PolyRing::shapeType.
{
   return drawNested(
       numSides_, rings_, this->getCenter(), [this](const PolyRing &ring) {
         return getRingVerticesAndCircEdges(this->getCenter(), this->numSides_,
                                            ring.radius, ring.rotation,
                                            ring.shapeType);
       });
 }
getCenter()
const std::array< double, 3 > & NEM::NUCMESH::ShapeBase::getCenter () const inherited
Definition at line 50 of file ShapeBase.C.
References NEM::NUCMESH::ShapeBase::center_.
Referenced by NEM::NUCMESH::HexagonalArray::createGeo(), NEM::NUCMESH::RectangularArray::createGeo(), createGeo(), NEM::NUCMESH::PolarArray::createGeo(), and NEM::NUCMESH::Circles::createGeo().
 { return center_; }
getNumSides()
int NEM::NUCMESH::CirclesAndPolys::getNumSides () const
Definition at line 155 of file CirclesAndPolys.C.
References numSides_.
 { return numSides_; }
getRings()
const std::vector< PolyRing > & NEM::NUCMESH::CirclesAndPolys::getRings () const
Definition at line 159 of file CirclesAndPolys.C.
References rings_.
{
   return rings_;
 }
getRotatedPoint()
std::array< double, 3 > NEM::NUCMESH::ShapeBase::getRotatedPoint (const std::array< double, 3 > & center, const std::array< double, 2 > & rotation) static inherited
Parameters
center Center of circle
rotation {Radius, angle in degrees}
Returns
Point on circle with center center and normal [0, 0, 1], radius rotation[0] and angle (in degrees) rotation[1]
Definition at line 58 of file ShapeBase.C.
Referenced by NEM::NUCMESH::PolarArray::createGeo(), and NEM::DRV::JSON::modify_helper().
{
   auto angle = rotation[1] * M_PI / 180.;
   return {center[0] + rotation[0] * std::cos(angle),
           center[1] + rotation[0] * std::sin(angle), center[2]};
 }
mergeGeo()
void NEM::NUCMESH::ShapeBase::mergeGeo (NEM::GEO::GeoManager & keepGeo, NEM::GEO::GeoManager && removeGeo) static protected inherited
Parameters
[in,out] keepGeo Merge geometry from removeGeo into this object
[in] removeGeo Move geometry and data from this object into keepGeo
Definition at line 66 of file ShapeBase.C.
References NEM::GEO::GeoManager::buildCompound(), NEM::GEO::GeoManager::deleteShapes(), NEM::GEO::GeoManager::getDim(), NEM::GEO::GeoManager::insert(), NEM::GEO::GeoManager::modify(), NEM::GEO::GeoManager::setDim(), and NEM::DRV::JSON::shapeType.
Referenced by NEM::NUCMESH::ShapesArray::createGeoImpl(), and NEM::SRV::NucMeshSrv::FillOutputPortInformation().
{
   auto origCompound = keepGeo.buildCompound();
   if (origCompound.IsNull()) {
     keepGeo = std::move(removeGeo);
     return;
   } else {
     auto newCompound = removeGeo.buildCompound();
     TopoDS_ListOfShape newShapes;
     static constexpr std::array<TopAbs_ShapeEnum, 4> shapeTypes{
         TopAbs_SOLID, TopAbs_FACE, TopAbs_EDGE, TopAbs_VERTEX};
     for (auto &shapeType : shapeTypes) {
       for (TopExp_Explorer explorer{newCompound, shapeType}; explorer.More();
            explorer.Next()) {
         auto &oldSubshape = explorer.Current();
         if (auto old_metadata = removeGeo.get(oldSubshape)) {
           keepGeo.insert(oldSubshape, std::move(*old_metadata));
         }
       }
     }
     if (!newCompound.IsNull()) {
       keepGeo.setDim(std::max(keepGeo.getDim(), removeGeo.getDim()));
       BRepAlgoAPI_Cut cutter{origCompound, newCompound};
       if (cutter.HasDeleted() || cutter.HasModified() ||
           cutter.HasGenerated()) {
         auto deletedShapes = keepGeo.modify(cutter, {TopAbs_EDGE, TopAbs_FACE});
         keepGeo.deleteShapes(deletedShapes[0]);
       }
       BRepBuilderAPI_Sewing sewer{};
       std::vector<TopoDS_Shape> sewedShapes;
       auto compound = keepGeo.buildCompound();
       for (TopExp_Explorer explorer{compound, TopAbs_FACE}; explorer.More();
            explorer.Next()) {
         sewer.Add(explorer.Current());
         sewedShapes.emplace_back(explorer.Current());
       }
       sewer.Perform();
       auto deletedShapes =
           keepGeo.modify(sewer, sewedShapes, {TopAbs_EDGE, TopAbs_FACE});
       keepGeo.deleteShapes(deletedShapes);
     }
   }
 }
setCenter()
void NEM::NUCMESH::ShapeBase::setCenter (const std::array< double, 3 > & center) inherited
Definition at line 52 of file ShapeBase.C.
References NEM::NUCMESH::ShapeBase::center_.
Referenced by NEM::DRV::JSON::modify_helper().
{
   center_ = center;
 }
setNumSides()
void NEM::NUCMESH::CirclesAndPolys::setNumSides (int numSides)
Definition at line 157 of file CirclesAndPolys.C.
References numSides_.
Referenced by NEM::DRV::JSON::modify_helper().
 { this->numSides_ = numSides; }
setRings()
void NEM::NUCMESH::CirclesAndPolys::setRings (std::vector< PolyRing > rings)
Definition at line 163 of file CirclesAndPolys.C.
References rings_.
Referenced by NEM::DRV::JSON::modify_helper().
{
   this->rings_ = std::move(rings);
 }
Member Data Documentation
numSides_
int NEM::NUCMESH::CirclesAndPolys::numSides_ private
Definition at line 70 of file CirclesAndPolys.H.
Referenced by createGeo(), getNumSides(), and setNumSides().
rings_
std::vector<PolyRing> NEM::NUCMESH::CirclesAndPolys::rings_ private
Definition at line 71 of file CirclesAndPolys.H.
Referenced by addRing(), createGeo(), getRings(), and setRings().
The documentation for this class was generated from the following files:
CirclesAndPolys.H
CirclesAndPolys.C