NEMoSys: NEM::DRV::SnappyMeshMeshGenDriver Class Reference
NEM::DRV::SnappyMeshMeshGenDriver Class Reference
Detailed Description
Definition at line 39 of file SnappyMeshMeshGenDriver.H.
Classes
struct Opts
Public Types
using Files = MeshGenFiles
Public Member Functions
SnappyMeshMeshGenDriver (Files files, snappymeshParams params)
const Files & getFiles () const
void setFiles (Files files)
const snappymeshParams & getParams () const
void setParams (snappymeshParams params)
void execute () const override
Run the workflow represented by the driver.
Static Public Member Functions
static std::unique_ptr< NemDriver > readJSON (const jsoncons::json &inputjson)
Factory method for all drivers.
Private Member Functions
SnappyMeshMeshGenDriver ()
const Opts & getOpts () const
void setOpts (Opts opts)
Private Attributes
Files files_
Opts opts_
Inherits NEM::DRV::MeshGenDriver.
Member Typedef Documentation
Files
using NEM::DRV::SnappyMeshMeshGenDriver::Files = MeshGenFiles
Definition at line 41 of file SnappyMeshMeshGenDriver.H.
Constructor & Destructor Documentation
SnappyMeshMeshGenDriver() [1/2]
NEM::DRV::SnappyMeshMeshGenDriver::SnappyMeshMeshGenDriver (Files files, snappymeshParams params)
Definition at line 41 of file SnappyMeshMeshGenDriver.C.
     : files_(std::move(files)), opts_(std::move(params)) {}
SnappyMeshMeshGenDriver() [2/2]
NEM::DRV::SnappyMeshMeshGenDriver::SnappyMeshMeshGenDriver () private
Definition at line 45 of file SnappyMeshMeshGenDriver.C.
     : SnappyMeshMeshGenDriver({{}, {}}, {}) {}
Member Function Documentation
execute()
void NEM::DRV::SnappyMeshMeshGenDriver::execute () const override virtual
Implements NEM::DRV::NemDriver.
Definition at line 80 of file SnappyMeshMeshGenDriver.C.
References meshBase::Create(), snappymeshGen::createMeshFromSTL(), meshBase::CreateShared(), files_, NEM::DRV::MeshGenDriver::MeshGenFiles::inputGeoFile, mesh, opts_, NEM::DRV::MeshGenDriver::MeshGenFiles::outputMeshFile, NEM::DRV::SnappyMeshMeshGenDriver::Opts::params, and nemAux::trim_fname().
{
   auto paramsCopy = this->opts_.params;
   snappymeshGen generator{&paramsCopy};
   // TODO: Make sure blockMeshGen::createMeshFromSTL sets return value and check
   //  it here
   // Parameter not used
   generator.createMeshFromSTL(nullptr);
   std::string newname = nemAux::trim_fname(this->files_.inputGeoFile, ".vtu");
   auto mesh =
       meshBase::CreateShared(meshBase::Create(generator.getDataSet(), newname));
   mesh->setFileName(this->files_.outputMeshFile);
   mesh->report();
   mesh->write();
 }
getFiles()
const SnappyMeshMeshGenDriver::Files & NEM::DRV::SnappyMeshMeshGenDriver::getFiles () const
Definition at line 48 of file SnappyMeshMeshGenDriver.C.
References files_.
           {
   return files_;
 }
getOpts()
const SnappyMeshMeshGenDriver::Opts & NEM::DRV::SnappyMeshMeshGenDriver::getOpts () const private
Definition at line 66 of file SnappyMeshMeshGenDriver.C.
References opts_.
Referenced by getParams().
{
   return opts_;
 }
getParams()
const snappymeshParams & NEM::DRV::SnappyMeshMeshGenDriver::getParams () const
Definition at line 58 of file SnappyMeshMeshGenDriver.C.
References getOpts(), and NEM::DRV::SnappyMeshMeshGenDriver::Opts::params.
{
   return getOpts().params;
 }
readJSON()
std::unique_ptr< NemDriver > NEM::DRV::NemDriver::readJSON (const jsoncons::json & inputjson) static inherited
Parameters
inputjson json input with "Program Type" key
Returns
pointer to base NemDriver class
Definition at line 37 of file NemDriver.C.
Referenced by NEM::DRV::MeshGenDriver::MeshGenDriver().
{
   return inputjson.as<std::unique_ptr<NemDriver>>();
 }
setFiles()
void NEM::DRV::SnappyMeshMeshGenDriver::setFiles (Files files)
Definition at line 53 of file SnappyMeshMeshGenDriver.C.
References files_, snappymeshParams::geomFileName, NEM::DRV::MeshGenDriver::MeshGenFiles::inputGeoFile, opts_, and NEM::DRV::SnappyMeshMeshGenDriver::Opts::params.
{
   this->opts_.params.geomFileName = files.inputGeoFile;
   this->files_ = std::move(files);
 }
setOpts()
void NEM::DRV::SnappyMeshMeshGenDriver::setOpts (Opts opts) private
Definition at line 70 of file SnappyMeshMeshGenDriver.C.
References files_, snappymeshParams::geomFileName, NEM::DRV::MeshGenDriver::MeshGenFiles::inputGeoFile, opts_, and NEM::DRV::SnappyMeshMeshGenDriver::Opts::params.
Referenced by setParams().
{
   if (!opts.params.geomFileName.empty()) {
     this->files_.inputGeoFile = opts.params.geomFileName;
     this->opts_ = std::move(opts);
   } else {
     this->opts_ = std::move(opts);
     this->opts_.params.geomFileName = this->files_.inputGeoFile;
   }
 }
setParams()
void NEM::DRV::SnappyMeshMeshGenDriver::setParams (snappymeshParams params)
Definition at line 62 of file SnappyMeshMeshGenDriver.C.
References setOpts().
{
   setOpts(Opts{std::move(params)});
 }
Member Data Documentation
files_
Files NEM::DRV::SnappyMeshMeshGenDriver::files_ private
Definition at line 66 of file SnappyMeshMeshGenDriver.H.
Referenced by execute(), getFiles(), setFiles(), and setOpts().
opts_
Opts NEM::DRV::SnappyMeshMeshGenDriver::opts_ private
Definition at line 67 of file SnappyMeshMeshGenDriver.H.
Referenced by execute(), getOpts(), setFiles(), and setOpts().
The documentation for this class was generated from the following files:
SnappyMeshMeshGenDriver.H
SnappyMeshMeshGenDriver.C