NEMoSys: NEM::NUCMESH::NucMeshGeo Class Reference
NEM::NUCMESH::NucMeshGeo Class Reference
Detailed Description
Definition at line 44 of file NucMeshGeo.H.
Public Types
using MapType = std::unordered_map< TopoDS_Shape, std::shared_ptr< ShapeData >, ShapeMapHasher_Hash, ShapeMapHasher_KeyEqual >
Public Member Functions
std::unique_ptr< SMESH_Mesh > computeMesh (SMESH_Gen &generator)
Construct a mesh using the shapes in the map and their ShapeData.
int getDim () const
Get dimension of geometry.
void setDim (int dim)
Set the dimension.
std::vector< TopoDS_Shape > modify (BRepBuilderAPI_MakeShape &op, const std::vector< TopoDS_Shape > &shapes, const std::vector< TopAbs_ShapeEnum > &typesToTraverse={ TopAbs_VERTEX, TopAbs_EDGE, TopAbs_FACE, TopAbs_SOLID})
Modify this geoMetadata after a BRepBuilderAPI_MakeShape operation.
std::vector< TopoDS_Shape > modify (BRepBuilderAPI_MakeShape &op, const TopTools_ListOfShape &shapes, const std::vector< TopAbs_ShapeEnum > &typesToTraverse={ TopAbs_VERTEX, TopAbs_EDGE, TopAbs_FACE, TopAbs_SOLID})
std::array< std::vector< TopoDS_Shape >, 2 > modify (BRepAlgoAPI_BooleanOperation &op, const std::vector< TopAbs_ShapeEnum > &typesToTraverse={ TopAbs_VERTEX, TopAbs_EDGE, TopAbs_FACE, TopAbs_SOLID})
std::vector< TopoDS_Shape > modify (BRepBuilderAPI_Sewing &op, const std::vector< TopoDS_Shape > &shapes, const std::vector< TopAbs_ShapeEnum > &typesToTraverse={ TopAbs_VERTEX, TopAbs_EDGE, TopAbs_FACE, TopAbs_SOLID})
void deleteShapes (const TopoDS_Shape &shape)
Remove a shape from the map.
void deleteShapes (const std::vector< TopoDS_Shape > &shapes)
Delete a set of shapes.
TopoDS_Compound buildCompound () const
Create a compound from shapes present in the map that have same dimension as the instance.
std::shared_ptr< ShapeData > * get (const TopoDS_Shape &shape)
Get the data from the map.
const std::shared_ptr< ShapeData > * get (const TopoDS_Shape &shape) const
Get the data from the map.
std::pair< MapType::iterator, bool > insert (const TopoDS_Shape &shape, std::shared_ptr< ShapeData > shapeData)
template<typename T >
std::pair< MapType::iterator, bool > insertForward (const TopoDS_Shape &shape, T &&shapeData)
Helper to insert a shape and data into the map.
template<typename T , typename... Args>
std::pair< MapType::iterator, bool > insertConstruct (const TopoDS_Shape &shape, Args &&...args)
Helper to insert a shape and construct data.
MapType & getMap ()
const MapType & getMap () const
Get the shapes and data.
Protected Member Functions
bool isChild (const TopoDS_Shape &shape) const
void modifyImpl (BRepBuilderAPI_MakeShape &op, const TopoDS_Shape &shape, std::vector< TopoDS_Shape > &shapesToRemove)
Protected Attributes
MapType map_
int dim_
Inherits NEM::GEO::GeoManager.
Member Typedef Documentation
MapType
using NEM::GEO::GeoManager::MapType = std::unordered_map<TopoDS_Shape, std::shared_ptr<ShapeData>, ShapeMapHasher_Hash, ShapeMapHasher_KeyEqual> inherited
Definition at line 85 of file GeoManager.H.
Member Function Documentation
buildCompound()
TopoDS_Compound NEM::GEO::GeoManager::buildCompound () const inherited
Returns
compound of shapes
Definition at line 145 of file GeoManager.C.
References NEM::GEO::GeoManager::isChild(), and NEM::GEO::GeoManager::map_.
Referenced by NEM::NUCMESH::ShapesArray::basicTransformation(), computeMesh(), and NEM::NUCMESH::ShapeBase::mergeGeo().
{
   BRep_Builder builder;
   TopoDS_Compound compound;
   // If no top-dimension shapes, then return a null compound
   bool addedShapes = false;
   for (auto &shape : map_) {
     if (!isChild(shape.first)) {
       if (!addedShapes) {
         builder.MakeCompound(compound);
         addedShapes = true;
       }
       builder.Add(compound, shape.first);
     }
   }
   return compound;
 }
computeMesh()
std::unique_ptr< SMESH_Mesh > NEM::NUCMESH::NucMeshGeo::computeMesh (SMESH_Gen & generator)
Note there is a default edge hypothesis (StdMeshers_AutomaticLength), edge algorithm (StdMeshers_Regular_1D), and face algorithm (StdMeshers_MEFISTO_2D). Geometry and mesh regenerated on each call.
Returns
Generated mesh
Definition at line 48 of file NucMeshGeo.C.
References NEM::GEO::GeoManager::buildCompound(), NEM::GEO::GeoManager::isChild(), NEM::GEO::GeoManager::map_, mesh, and NEM::DRV::JSON::shapeType.
Referenced by NEM::SRV::NucMeshSrv::FillOutputPortInformation().
{
   std::unique_ptr<SMESH_Mesh> mesh{generator.CreateMesh(false)};
   std::vector<std::unique_ptr<SMESH_Hypothesis>> hypotheses;
   auto compound = this->buildCompound();
   mesh->ShapeToMesh(compound);
   {
     auto edgeAlgId = generator.GetANewId();
     hypotheses.emplace_back(new StdMeshers_Regular_1D{edgeAlgId, &generator});
     mesh->AddHypothesis(compound, edgeAlgId);
     auto edgeHypId = generator.GetANewId();
     hypotheses.emplace_back(
         new StdMeshers_Adaptive1D{edgeHypId, &generator});
     mesh->AddHypothesis(compound, edgeHypId);
   }
   {
     auto faceAlgId = generator.GetANewId();
     hypotheses.emplace_back(new StdMeshers_MEFISTO_2D{faceAlgId, &generator});
     mesh->AddHypothesis(compound, faceAlgId);
   }
   std::unordered_set<TopoDS_Shape, ShapeMapHasher_Hash, ShapeMapHasher_KeyEqual>
       generated_shapes;
   for (auto &shape : map_) {
     if (!isChild(shape.first)) {
       static constexpr std::array<TopAbs_ShapeEnum, 4> shapeTypes{
           TopAbs_VERTEX, TopAbs_EDGE, TopAbs_FACE, TopAbs_SOLID};
       for (auto &shapeType : shapeTypes) {
         for (TopExp_Explorer explorer{shape.first, shapeType}; explorer.More();
              explorer.Next()) {
           auto &subShape = explorer.Current();
           auto findIter = map_.find(subShape);
           if (findIter != map_.end() &&
               generated_shapes.find(subShape) == generated_shapes.end()) {
             if (auto nmData =
                     dynamic_cast<NucMeshShapeData *>(findIter->second.get())) {
               nmData->setupAlgos(explorer.Current(), generator, *mesh,
                                  hypotheses);
             }
             generated_shapes.emplace(subShape);
           }
         }
       }
     }
   }
   generator.Compute(*mesh, compound);
   return mesh;
 }
deleteShapes() [1/2]
void NEM::GEO::GeoManager::deleteShapes (const TopoDS_Shape & shape) inherited
Note there is no effect if shape's dimension is less than the instance dimension (to avoid removing shapes that are still referenced by other shapes).
Parameters
shape Shape to remove, if present
Definition at line 127 of file GeoManager.C.
References NEM::GEO::GeoManager::isChild(), and NEM::GEO::GeoManager::map_.
Referenced by NEM::GEO::GeoManager::deleteShapes(), and NEM::NUCMESH::ShapeBase::mergeGeo().
{
   if (!isChild(shape)) {
     auto findIter = map_.find(shape);
     if (findIter != map_.end()) {
       if (findIter->second) {
         findIter->second->updateDeleted(shape, *this);
       }
       map_.erase(findIter);
     }
   }
 }
deleteShapes() [2/2]
void NEM::GEO::GeoManager::deleteShapes (const std::vector< TopoDS_Shape > & shapes) inherited
Parameters
shapes Shapes to remove, if present
Definition at line 139 of file GeoManager.C.
References NEM::GEO::GeoManager::deleteShapes().
{
   for (auto &shape : shapes) {
     this->deleteShapes(shape);
   }
 }
get() [1/2]
std::shared_ptr< ShapeData > * NEM::GEO::GeoManager::get (const TopoDS_Shape & shape) inherited
Definition at line 162 of file GeoManager.C.
References NEM::GEO::GeoManager::map_.
{
   auto findIter = map_.find(shape);
   if (findIter != map_.end()) {
     return &findIter->second;
   } else {
     return nullptr;
   }
 }
get() [2/2]
const std::shared_ptr< ShapeData > * NEM::GEO::GeoManager::get (const TopoDS_Shape & shape) const inherited
Parameters
shape Shape to query
Returns
Pointer to data in the map, or nullptr if shape not in map. If a pointer to a nullptr, then shape is in map, but data in map is null.
Definition at line 171 of file GeoManager.C.
References NEM::GEO::GeoManager::map_.
{
   auto findIter = map_.find(shape);
   if (findIter != map_.end()) {
     return &findIter->second;
   } else {
     return nullptr;
   }
 }
getDim()
int NEM::GEO::GeoManager::getDim () const inherited
Returns
dimension
Definition at line 50 of file GeoManager.C.
References NEM::GEO::GeoManager::dim_.
Referenced by NEM::NUCMESH::ShapeBase::mergeGeo().
 { return dim_; }
getMap() [1/2]
GeoManager::MapType & NEM::GEO::GeoManager::getMap () inherited
Definition at line 186 of file GeoManager.C.
References NEM::GEO::GeoManager::map_.
Referenced by NEM::NUCMESH::CopyOverrideShapeData< QuadMeshSurface, GroupData >::updateModified().
 { return map_; }
getMap() [2/2]
const GeoManager::MapType & NEM::GEO::GeoManager::getMap () const inherited
Returns
Map from shapes to data
Definition at line 188 of file GeoManager.C.
References NEM::GEO::GeoManager::map_.
 { return map_; }
insert()
std::pair< GeoManager::MapType::iterator, bool > NEM::GEO::GeoManager::insert (const TopoDS_Shape & shape, std::shared_ptr< ShapeData > shapeData) inherited
Definition at line 181 of file GeoManager.C.
References NEM::GEO::GeoManager::map_.
Referenced by NEM::NUCMESH::ShapesArray::basicTransformation(), and NEM::NUCMESH::ShapeBase::mergeGeo().
{
   return map_.emplace(shape, std::move(shapeData));
 }
insertConstruct()
template<typename T , typename... Args> std::pair<MapType::iterator, bool> NEM::GEO::GeoManager::insertConstruct (const TopoDS_Shape & shape, Args &&... args) inline inherited
Template Parameters
T ShapeData type
Args Types of T constructor
Parameters
shape Shape to insert
args Arguments of T constructor for data to associate with shape
Returns
iterator to inserted or already existing element, and whether or not there was an insertion
Definition at line 218 of file GeoManager.H.
{
     auto emplaceIter = getMap().emplace(shape, std::shared_ptr<ShapeData>{});
     if (emplaceIter.second) {
       emplaceIter.first->second.reset(new T(std::forward<Args>(args)...));
     }
     return emplaceIter;
   }
insertForward()
template<typename T > std::pair<MapType::iterator, bool> NEM::GEO::GeoManager::insertForward (const TopoDS_Shape & shape, T && shapeData) inline inherited
Template Parameters
T ShapeData type
Parameters
shape Shape to insert
shapeData Data to associate to with
Returns
iterator to inserted or already existing element, and whether or not there was an insertion
Definition at line 197 of file GeoManager.H.
{
     auto emplaceIter = getMap().emplace(shape, std::shared_ptr<ShapeData>{});
     if (emplaceIter.second) {
       emplaceIter.first->second.reset(
           new typename std::decay<T>::type(std::forward<T>(shapeData)));
     }
     return emplaceIter;
   }
isChild()
bool NEM::GEO::GeoManager::isChild (const TopoDS_Shape & shape) const protected inherited
Definition at line 190 of file GeoManager.C.
References NEM::GEO::GeoManager::dim_.
Referenced by NEM::GEO::GeoManager::buildCompound(), computeMesh(), and NEM::GEO::GeoManager::deleteShapes().
{
   int shapeDim;
   switch (shape.ShapeType()) {
     case TopAbs_COMPSOLID:
     case TopAbs_SOLID: shapeDim = 3; break;
     case TopAbs_SHELL:
     case TopAbs_FACE: shapeDim = 2; break;
     case TopAbs_WIRE:
     case TopAbs_EDGE: shapeDim = 1; break;
     case TopAbs_VERTEX: shapeDim = 0; break;
     case TopAbs_COMPOUND:
     case TopAbs_SHAPE:
     default: return false;
   }
   return shapeDim < dim_;
 }
modify() [1/4]
std::vector< TopoDS_Shape > NEM::GEO::GeoManager::modify (BRepBuilderAPI_MakeShape & op, const std::vector< TopoDS_Shape > & shapes, const std::vector< TopAbs_ShapeEnum > & typesToTraverse = { TopAbs_VERTEX, TopAbs_EDGE, TopAbs_FACE, TopAbs_SOLID}) inherited
Parameters
op Modification of geometry
shapes Geometry objects assumed to be inputs of op. The corresponding values in the map dictate the behavior of the resulting metadata.
typesToTraverse Traverse the subshapes of shapes with these types. An empty list means only shapes will be examined.
Returns
Shapes that are no longer present in the output of op
Definition at line 74 of file GeoManager.C.
References NEM::GEO::GeoManager::modifyImpl(), and NEM::GEO::modifyTempl().
Referenced by NEM::NUCMESH::ShapeBase::mergeGeo(), and NEM::GEO::GeoManager::modify().
{
   return modifyTempl(op, shapes, typesToTraverse,
                      [this, &op](const TopoDS_Shape &shape,
                                  std::vector<TopoDS_Shape> &shapesToRemove) {
                        this->modifyImpl(op, shape, shapesToRemove);
                      });
 }
modify() [2/4]
std::vector< TopoDS_Shape > NEM::GEO::GeoManager::modify (BRepBuilderAPI_MakeShape & op, const TopTools_ListOfShape & shapes, const std::vector< TopAbs_ShapeEnum > & typesToTraverse = { TopAbs_VERTEX, TopAbs_EDGE, TopAbs_FACE, TopAbs_SOLID}) inherited
Definition at line 84 of file GeoManager.C.
References NEM::GEO::GeoManager::modifyImpl(), and NEM::GEO::modifyTempl().
{
   return modifyTempl(op, shapes, typesToTraverse,
                      [this, &op](const TopoDS_Shape &shape,
                                  std::vector<TopoDS_Shape> &shapesToRemove) {
                        this->modifyImpl(op, shape, shapesToRemove);
                      });
 }
modify() [3/4]
std::array< std::vector< TopoDS_Shape >, 2 > NEM::GEO::GeoManager::modify (BRepAlgoAPI_BooleanOperation & op, const std::vector< TopAbs_ShapeEnum > & typesToTraverse = { TopAbs_VERTEX, TopAbs_EDGE, TopAbs_FACE, TopAbs_SOLID}) inherited
shapes are inferred from
Definition at line 94 of file GeoManager.C.
References NEM::GEO::GeoManager::modify().
{
   return {this->modify(op, op.Arguments(), typesToTraverse),
           this->modify(op, op.Tools(), typesToTraverse)};
 }
modify() [4/4]
std::vector< TopoDS_Shape > NEM::GEO::GeoManager::modify (BRepBuilderAPI_Sewing & op, const std::vector< TopoDS_Shape > & shapes, const std::vector< TopAbs_ShapeEnum > & typesToTraverse = { TopAbs_VERTEX, TopAbs_EDGE, TopAbs_FACE, TopAbs_SOLID}) inherited
Definition at line 101 of file GeoManager.C.
References NEM::GEO::GeoManager::map_, NEM::GEO::modifyTempl(), and NEM::DRV::JSON::shapeType.
{
   return modifyTempl(
       op, shapes, typesToTraverse,
       [this, &op](const TopoDS_Shape &shape,
                   std::vector<TopoDS_Shape> &shapesToRemove) {
         auto findIter = map_.find(shape);
         if (findIter != map_.end()) {
           auto shapeType = shape.ShapeType();
           auto modified =
               (shapeType == TopAbs_FACE || shapeType == TopAbs_SHELL)
                   ? op.Modified(shape)
                   : op.ModifiedSubShape(shape);
           if (!modified.IsSame(shape)) {
             TopTools_ListOfShape modShapes;
             modShapes.Append(modified);
             if (findIter->second) {
               findIter->second->updateModified(shape, modShapes, *this);
             }
             shapesToRemove.emplace_back(shape);
           }
         }
       });
 }
modifyImpl()
void NEM::GEO::GeoManager::modifyImpl (BRepBuilderAPI_MakeShape & op, const TopoDS_Shape & shape, std::vector< TopoDS_Shape > & shapesToRemove) protected inherited
Definition at line 207 of file GeoManager.C.
References NEM::GEO::GeoManager::map_.
Referenced by NEM::GEO::GeoManager::modify().
{
   if (op.IsDeleted(shape)) {
     shapesToRemove.emplace_back(shape);
   } else {
     auto findIter = map_.find(shape);
     if (findIter != map_.end()) {
       auto &generated = op.Generated(shape);
       if (!generated.IsEmpty()) {
         if (findIter->second) {
           findIter->second->updateGenerated(shape, generated, *this);
         }
       }
       auto &modified = op.Modified(shape);
       if (!modified.IsEmpty()) {
         if (findIter->second) {
           findIter->second->updateModified(shape, modified, *this);
         }
         shapesToRemove.emplace_back(shape);
       }
     }
   }
 }
setDim()
void NEM::GEO::GeoManager::setDim (int dim) inherited
Parameters
dim dimension (between 1 and 3)
Definition at line 52 of file GeoManager.C.
References NEM::GEO::GeoManager::dim_.
Referenced by NEM::NUCMESH::ShapeBase::mergeGeo().
 { dim_ = dim; }
Member Data Documentation
dim_
int NEM::GEO::GeoManager::dim_ protected inherited
Definition at line 240 of file GeoManager.H.
Referenced by NEM::GEO::GeoManager::getDim(), NEM::GEO::GeoManager::isChild(), and NEM::GEO::GeoManager::setDim().
map_
MapType NEM::GEO::GeoManager::map_ protected inherited
Definition at line 239 of file GeoManager.H.
Referenced by NEM::GEO::GeoManager::buildCompound(), computeMesh(), NEM::GEO::GeoManager::deleteShapes(), NEM::GEO::GeoManager::get(), NEM::GEO::GeoManager::getMap(), NEM::GEO::GeoManager::insert(), NEM::GEO::GeoManager::modify(), and NEM::GEO::GeoManager::modifyImpl().
The documentation for this class was generated from the following files:
NucMeshGeo.H
NucMeshGeo.C