NEMoSys: orthoPoly1D Class Reference
orthoPoly1D Class Reference
Detailed Description
Definition at line 39 of file orthoPoly1D.H.
Public Member Functions
orthoPoly1D (int _order, const std::vector< double > &x)
orthoPoly1D ()=default
orthoPoly1D (const orthoPoly1D &op)
orthoPoly1D & operator= (const orthoPoly1D &op)
~orthoPoly1D ()=default
double EvaluateOrthogonal (int power, double xk) const
void ComputeAB (const std::vector< double > &x)
void EvaluateOrthogonals (const std::vector< double > &x)
void ComputePhiTPhiInv (const std::vector< double > &x)
Public Attributes
int order
std::vector< double > a
std::vector< double > b
Eigen::MatrixXd phi
Eigen::MatrixXd phiTphiInv
Constructor & Destructor Documentation
orthoPoly1D() [1/3]
orthoPoly1D::orthoPoly1D (int _order, const std::vector< double > & x)
Definition at line 37 of file orthoPoly1D.C.
References a, b, ComputePhiTPhiInv(), phi, and phiTphiInv.
     : order(_order)
 {
   a.resize(_order + 1);
   b.resize(_order);
   phi.resize(x.size(), _order + 1);
   phiTphiInv.resize(_order + 1, _order + 1);
   ComputePhiTPhiInv(x);
 }
orthoPoly1D() [2/3]
orthoPoly1D::orthoPoly1D () default
orthoPoly1D() [3/3]
orthoPoly1D::orthoPoly1D (const orthoPoly1D & op)
Definition at line 47 of file orthoPoly1D.C.
References a, b, order, phi, and phiTphiInv.
 {
   order = op.order;
   a = op.a;
   b = op.b;
   phi = op.phi;
   phiTphiInv = op.phiTphiInv;
 }
~orthoPoly1D()
orthoPoly1D::~orthoPoly1D () default
Member Function Documentation
ComputeAB()
void orthoPoly1D::ComputeAB (const std::vector< double > & x)
Definition at line 91 of file orthoPoly1D.C.
References a, b, EvaluateOrthogonal(), and order.
Referenced by EvaluateOrthogonals().
 {
   a[0] = 0.;
   int n = x.size();
   for (int i = 0; i < n; ++i)
   {
     a[0] += x[i];
   }
   a[0] /= n;
   for (int i = 1; i < order; ++i)
   {
     double sum0, sum1, sum2;
     sum0 = sum1 = sum2 = 0.0;
     for (int j = 0; j < n; ++j)
     {
       double tmp0 = EvaluateOrthogonal(i - 1, x[j]);
       double tmp1 = EvaluateOrthogonal(i, x[j]);
       sum0 += tmp0 * tmp0;
       sum1 += tmp1 * tmp1;
       sum2 += x[j] * tmp1 * tmp1;
     }
     a[i] = sum2 / sum1;
     b[i - 1] = sum1 / sum0;
   }
 }
ComputePhiTPhiInv()
void orthoPoly1D::ComputePhiTPhiInv (const std::vector< double > & x)
Definition at line 131 of file orthoPoly1D.C.
References EvaluateOrthogonals(), phi, and phiTphiInv.
Referenced by orthoPoly1D().
 {
   EvaluateOrthogonals(x);
   VectorXd tmp = (phi.transpose() * phi).diagonal();
   for (int i = 0; i < tmp.rows(); ++i)
     tmp(i) = 1. / tmp(i);
   phiTphiInv = tmp.asDiagonal();
 }
EvaluateOrthogonal()
double orthoPoly1D::EvaluateOrthogonal (int power, double xk) const
Definition at line 69 of file orthoPoly1D.C.
References a, and b.
Referenced by ComputeAB(), and EvaluateOrthogonals().
 {
   double p0 = 1.;
   if (power == 0)
     return p0;
   double p1 = xk - a[0];
   if (power == 1)
     return p1;
   double p2 = std::numeric_limits<double>::quiet_NaN();
   for (int i = 1; i < power; ++i)
   {
     p2 = (xk - a[i]) * p1 - b[i - 1] * p0;
     p0 = p1;
     p1 = p2;
   }
   return p2;
 }
EvaluateOrthogonals()
void orthoPoly1D::EvaluateOrthogonals (const std::vector< double > & x)
Definition at line 120 of file orthoPoly1D.C.
References ComputeAB(), EvaluateOrthogonal(), order, and phi.
Referenced by ComputePhiTPhiInv().
 {
   ComputeAB(x);
   for (int i = 0; i < order + 1; ++i)
   {
     for (int j = 0; j < x.size(); ++j)
       phi(j, i) = EvaluateOrthogonal(i, x[j]);
   }
 }
operator=()
orthoPoly1D & orthoPoly1D::operator= (const orthoPoly1D & op)
Definition at line 56 of file orthoPoly1D.C.
References a, b, order, phi, and phiTphiInv.
 {
   if (this != &op)
   {
     order = op.order;
     a = op.a;
     b = op.b;
     phi = op.phi;
     phiTphiInv = op.phiTphiInv;
   }
   return *this;
 }
Member Data Documentation
a
std::vector<double> orthoPoly1D::a
Definition at line 77 of file orthoPoly1D.H.
Referenced by ComputeAB(), EvaluateOrthogonal(), operator=(), and orthoPoly1D().
b
std::vector<double> orthoPoly1D::b
Definition at line 79 of file orthoPoly1D.H.
Referenced by ComputeAB(), EvaluateOrthogonal(), operator=(), and orthoPoly1D().
order
int orthoPoly1D::order
Definition at line 73 of file orthoPoly1D.H.
Referenced by ComputeAB(), EvaluateOrthogonals(), operator=(), and orthoPoly1D().
phi
Eigen::MatrixXd orthoPoly1D::phi
Definition at line 81 of file orthoPoly1D.H.
Referenced by ComputePhiTPhiInv(), EvaluateOrthogonals(), operator=(), and orthoPoly1D().
phiTphiInv
Eigen::MatrixXd orthoPoly1D::phiTphiInv
Definition at line 83 of file orthoPoly1D.H.
Referenced by ComputePhiTPhiInv(), operator=(), and orthoPoly1D().
The documentation for this class was generated from the following files:
orthoPoly1D.H
orthoPoly1D.C