NEMoSys: NEM::DRV::TemplateMeshDriver Class Reference
NEM::DRV::TemplateMeshDriver Class Reference
Driver class to generate meshes according to a template.
Detailed Description
Definition at line 44 of file TemplateMeshDriver.H.
Classes
struct Opts
Public Types
using Files = DriverOutFile
Public Member Functions
TemplateMeshDriver (Files file, Opts opts)
const Files & getFiles () const
void setFiles (Files file)
const Opts & getOpts () const
void setOpts (Opts opts)
void execute () const override
Run the workflow represented by the driver.
~TemplateMeshDriver () override
Static Public Member Functions
static std::unique_ptr< NemDriver > readJSON (const jsoncons::json &inputjson)
Factory method for all drivers.
Private Member Functions
TemplateMeshDriver ()
jsoncons::string_view getProgramType () const override
Static Private Member Functions
static void executeTemplate (std::string tplName, std::string outName, std::string params)
Executes the template file.
static std::string spiralTapePipe (jsoncons::json inputjson)
Reads the parameters for Spiral Tape geometry/mesh from the input JSON file and generates the appropriate parameters file.
static void insertParams (std::string file, std::string params_name)
Inserts the parameters file name into the template file at the appropriate line.
static void encrypt (std::string inFile, std::string outFile)
Encrypts the template file.
static std::string decrypt (std::string filename)
Decrypts the template file.
Private Attributes
Files file_
Opts opts_
Static Private Attributes
static constexpr const char * programType = "Template Mesh Generation"
Inherits NEM::DRV::NemDriver.
Member Typedef Documentation
Files
using NEM::DRV::TemplateMeshDriver::Files = DriverOutFile
Definition at line 46 of file TemplateMeshDriver.H.
Constructor & Destructor Documentation
TemplateMeshDriver() [1/2]
NEM::DRV::TemplateMeshDriver::TemplateMeshDriver (Files file, Opts opts) explicit
Definition at line 50 of file TemplateMeshDriver.C.
     : file_(std::move(file)), opts_(std::move(opts)) {
   std::cout << "TemplateMeshDriver created" << std::endl;
 }
~TemplateMeshDriver()
NEM::DRV::TemplateMeshDriver::~TemplateMeshDriver () override
Definition at line 58 of file TemplateMeshDriver.C.
{
   std::cout << "TemplateMeshDriver destroyed" << std::endl;
 }
TemplateMeshDriver() [2/2]
NEM::DRV::TemplateMeshDriver::TemplateMeshDriver () private
Definition at line 55 of file TemplateMeshDriver.C.
     : TemplateMeshDriver(Files{{}}, Opts{{}}) {}
Member Function Documentation
decrypt()
std::string NEM::DRV::TemplateMeshDriver::decrypt (std::string filename) static private
Parameters
filename Input file name
Returns
Returns the decrypted file name
Definition at line 232 of file TemplateMeshDriver.C.
Referenced by executeTemplate().
{
   std::ifstream in(filename, std::ios_base::binary);
   if (!in.is_open()) {
     std::cerr << "Error: Template file " << filename << " is not open!"
               << std::endl;
     exit(-1);
   } else {
     unsigned vsize;
     in.read(reinterpret_cast<char *>(&vsize), sizeof(unsigned));
     std::vector<double> stuff(vsize);
     in.read(reinterpret_cast<char *>(&stuff[0]), vsize * sizeof(double));
     std::string result;
     for (double &d : stuff) {
       int inv_d = (int)std::sqrt(d);
       result += inv_d;
     }
     size_t lastindex = filename.find_last_of(".");
     std::string rawname = filename.substr(0, lastindex);
     std::string name = rawname + ".geo";
     std::ofstream ascii(name);
     ascii << result << std::endl;
     ascii.close();
     return name;
   }
 }
encrypt()
void NEM::DRV::TemplateMeshDriver::encrypt (std::string inFile, std::string outFile) static private
Parameters
inFile Input file name
outFile Output file name
Definition at line 262 of file TemplateMeshDriver.C.
{
   std::ifstream file(inFile);
   std::string str;
   file.seekg(0, std::ios::end);
   str.reserve(file.tellg());
   file.seekg(0, std::ios::beg);
   str.assign((std::istreambuf_iterator<char>(file)),
              std::istreambuf_iterator<char>());
   int a;
   double b;
   std::vector<double> line;
   for (char const &c : str) {
     a = (int)c;
     b = std::pow(a, 2);
     line.push_back(b);
   }
   unsigned linesize = line.size();
   std::ofstream o(outFile, std::ios_base::binary);
   o.write(reinterpret_cast<char *>(&linesize), sizeof(unsigned));
   o.write(reinterpret_cast<char *>(&line[0]), line.size() * sizeof(double));
   o.close();
   line.clear();
 }
execute()
void NEM::DRV::TemplateMeshDriver::execute () const override virtual
Implements NEM::DRV::NemDriver.
Definition at line 78 of file TemplateMeshDriver.C.
References nemAux::Timer::elapsed(), executeTemplate(), file_, opts_, NEM::DRV::DriverOutFile::outputFile, spiralTapePipe(), nemAux::Timer::start(), nemAux::Timer::stop(), NEM::DRV::TemplateMeshDriver::Opts::templateName, and NEM::DRV::TemplateMeshDriver::Opts::templateParams.
{
   static const std::map<std::string, std::string> tpl_map = {
       {"Spiral Tape Pipe", "spiral_tape_pipe.tpl"}};
   std::string params_name{};
   // Generate parameters file for template
   if (this->opts_.templateName == "Spiral Tape Pipe") {
     params_name = spiralTapePipe(this->opts_.templateParams);
   } else {
     std::cerr << "Error: Template name not found" << std::endl;
     exit(-1);
   }
   gmsh::initialize();
   gmsh::option::setNumber("General.Terminal", 1);
   std::cout << "Generating mesh from template" << std::endl;
   nemAux::Timer T;
   T.start();
   // Execute the template script
   executeTemplate(tpl_map.at(this->opts_.templateName), this->file_.outputFile,
                   params_name);
   T.stop();
   std::cout << "Meshing time = " << (T.elapsed() / 1000.0) << " seconds\n";
 }
executeTemplate()
void NEM::DRV::TemplateMeshDriver::executeTemplate (std::string tplName, std::string outName, std::string params) static private
Parameters
tplName Template file to be executed
outName Output mesh file name
params Parameters file name
Definition at line 104 of file TemplateMeshDriver.C.
References decrypt(), and insertParams().
Referenced by execute().
{
   // Decrypt the tpl and return the file name
   std::string name = decrypt(tplName);
   // Insert the name of the parameters file into the decrypted tpl
   insertParams(name, params);
   // Open and mesh the tpl
   gmsh::open(name);
   std::remove(name.c_str());
   // gmsh::fltk::run();
   gmsh::model::mesh::generate(2);
   gmsh::model::mesh::generate(3);
   gmsh::model::mesh::removeDuplicateNodes();
   gmsh::write(outName + ".msh");
   gmsh::finalize();
 }
getFiles()
const TemplateMeshDriver::Files & NEM::DRV::TemplateMeshDriver::getFiles () const
Definition at line 62 of file TemplateMeshDriver.C.
References file_.
{
   return file_;
 }
getOpts()
const TemplateMeshDriver::Opts & NEM::DRV::TemplateMeshDriver::getOpts () const
Definition at line 68 of file TemplateMeshDriver.C.
References opts_.
{
   return opts_;
 }
getProgramType()
jsoncons::string_view NEM::DRV::TemplateMeshDriver::getProgramType () const override private virtual
Implements NEM::DRV::NemDriver.
Definition at line 74 of file TemplateMeshDriver.C.
References programType.
{
   return programType;
 }
insertParams()
void NEM::DRV::TemplateMeshDriver::insertParams (std::string file, std::string params_name) static private
Parameters
file Template file to be executed
params_name Parameters file name
Definition at line 207 of file TemplateMeshDriver.C.
Referenced by executeTemplate().
{
   std::ifstream in(file);
   std::string str;
   std::vector<std::string> text;
   while (!in.eof()) {
     std::getline(in, str, '\n');
     text.push_back(str);
     std::string a = "SetFactory(\"built-in\");";
     std::string b = "SetFactory(\"OpenCASCADE\");";
     if (a.compare(str) == 0 || b.compare(str) == 0) {
       text.push_back("Include \"" + params_name + "\";");
     }
   }
   in.close();
   std::ofstream out(file);
   for (int i = 0; i < text.size(); ++i) {
     out << text[i] << std::endl;
   }
   out.close();
 }
readJSON()
std::unique_ptr< NemDriver > NEM::DRV::NemDriver::readJSON (const jsoncons::json & inputjson) static inherited
Parameters
inputjson json input with "Program Type" key
Returns
pointer to base NemDriver class
Definition at line 37 of file NemDriver.C.
Referenced by NEM::DRV::MeshGenDriver::MeshGenDriver().
{
   return inputjson.as<std::unique_ptr<NemDriver>>();
 }
setFiles()
void NEM::DRV::TemplateMeshDriver::setFiles (Files file)
Definition at line 66 of file TemplateMeshDriver.C.
References file_.
 { this->file_ = std::move(file); }
setOpts()
void NEM::DRV::TemplateMeshDriver::setOpts (Opts opts)
Definition at line 72 of file TemplateMeshDriver.C.
References opts_.
 { this->opts_ = std::move(opts); }
spiralTapePipe()
std::string NEM::DRV::TemplateMeshDriver::spiralTapePipe (jsoncons::json inputjson) static private
Parameters
inputjson Input JSON object
Returns
The date and time stamped parameters file name
Definition at line 123 of file TemplateMeshDriver.C.
Referenced by execute().
{
   std::cout << "Reading Template Parameters" << std::endl;
   double rx = 1;                // Ellipse radius x-dir
   double ry = 1;                // Ellipse radius y-dir
   double thickness = 0.05;      // Thickness of spiral tape in y-dir
   double extrude_len = 3;       // Extrusion length
   double n_turns = 0.5;         // Number of spiral turns
   double width_percent = 0.85;  // Percentage of x-dir diameter for tape width
   double mSize_min = 0.048;     // Minimum mesh size, size a walls
   double mSize_max = 0.1;       // Maximum mesh size, size in bulk
   double dist_min = 0.05;       // Distance from walls with mSize_min
   double dist_max = 0.2;        // Distance from walls with mSize_max
   double bl_wall_n = 0.0038;    // Boundary layer mesh size normal to wall
   double bl_far = 0.08;         // Mesh size away from wall
   double bl_thickness = 0.02;   // Boundary layer mesh thickness
   double ratio = 1.3;           // Mesh size ratio normal to wall
   double extrude_layers = 20;   // Number of extruded elements during extrusion
   int element_order = 1;  // Finite element order
   int fan_points = 3;     // Number of fan points in boundary layer at corners
   if (inputjson.contains("rx")) rx = inputjson["rx"].as_double();
   if (inputjson.contains("ry")) ry = inputjson["ry"].as_double();
   if (inputjson.contains("thickness"))
     thickness = inputjson["thickness"].as_double();
   if (inputjson.contains("extrude_len"))
     extrude_len = inputjson["extrude_len"].as_double();
   if (inputjson.contains("n_turns")) n_turns = inputjson["n_turns"].as_double();
   if (inputjson.contains("width_percent"))
     width_percent = inputjson["width_percent"].as_double();
   if (inputjson.contains("dist_min"))
     dist_min = inputjson["dist_min"].as_double();
   if (inputjson.contains("dist_max"))
     dist_max = inputjson["dist_max"].as_double();
   if (inputjson.contains("mSize_min"))
     mSize_min = inputjson["mSize_min"].as_double();
   if (inputjson.contains("mSize_max"))
     mSize_max = inputjson["mSize_max"].as_double();
   if (inputjson.contains("bl_wall_n"))
     bl_wall_n = inputjson["bl_wall_n"].as_double();
   if (inputjson.contains("bl_far")) bl_far = inputjson["bl_far"].as_double();
   if (inputjson.contains("bl_thickness"))
     bl_thickness = inputjson["bl_thickness"].as_double();
   if (inputjson.contains("ratio")) ratio = inputjson["ratio"].as_double();
   if (inputjson.contains("fan_points"))
     fan_points = inputjson["fan_points"].as<int>();
   if (inputjson.contains("extrude_layers"))
     extrude_layers = inputjson["extrude_layers"].as_double();
   if (inputjson.contains("element_order"))
     element_order = inputjson["element_order"].as<int>();
   std::ofstream out;
   time_t t = time(0);
   struct tm *now = localtime(&t);
   char paramsName[80];
   strftime(paramsName, 80, "params_%Y-%m-%d-%H:%M:%S.txt", now);
   out.open(paramsName);
   out << "rx = " << rx << ";" << std::endl;
   out << "ry = " << ry << ";" << std::endl;
   out << "thickness = " << thickness << ";" << std::endl;
   out << "extrude_len = " << extrude_len << ";" << std::endl;
   out << "n_turns = " << n_turns << ";" << std::endl;
   out << "width_percent = " << width_percent << ";" << std::endl;
   out << "dist_min = " << dist_min << ";" << std::endl;
   out << "dist_max = " << dist_max << ";" << std::endl;
   out << "mSize_min = " << mSize_min << ";" << std::endl;
   out << "mSize_max = " << mSize_max << ";" << std::endl;
   out << "bl_wall_n = " << bl_wall_n << ";" << std::endl;
   out << "bl_far = " << bl_far << ";" << std::endl;
   out << "bl_thickness = " << bl_thickness << ";" << std::endl;
   out << "ratio = " << ratio << ";" << std::endl;
   out << "fan_points = " << fan_points << ";" << std::endl;
   out << "extrude_layers = " << extrude_layers << ";" << std::endl;
   out << "element_order = " << element_order << ";" << std::endl;
   out.close();
   return paramsName;
 }
Member Data Documentation
file_
Files NEM::DRV::TemplateMeshDriver::file_ private
Definition at line 72 of file TemplateMeshDriver.H.
Referenced by execute(), getFiles(), and setFiles().
opts_
Opts NEM::DRV::TemplateMeshDriver::opts_ private
Definition at line 73 of file TemplateMeshDriver.H.
Referenced by execute(), getOpts(), and setOpts().
programType
constexpr const char* NEM::DRV::TemplateMeshDriver::programType = "Template Mesh Generation" static private
Definition at line 75 of file TemplateMeshDriver.H.
Referenced by getProgramType().
The documentation for this class was generated from the following files:
TemplateMeshDriver.H
TemplateMeshDriver.C