NEMoSys: NEM::DRV::TransferDriver Class Reference
NEM::DRV::TransferDriver Class Reference
Detailed Description
Definition at line 40 of file TransferDriver.H.
Classes
struct Files
struct Opts
Public Member Functions
TransferDriver (Files files, Opts opts)
const Files & getFiles () const
void setFiles (Files files)
const Opts & getOpts () const
void setOpts (Opts opts)
void execute () const override
Run the workflow represented by the driver.
~TransferDriver () override
Static Public Member Functions
static std::shared_ptr< TransferBase > CreateTransferObject (meshBase *srcmsh, meshBase *trgmsh, const std::string &method)
static std::unique_ptr< NemDriver > readJSON (const jsoncons::json &inputjson)
Factory method for all drivers.
Private Member Functions
TransferDriver ()
jsoncons::string_view getProgramType () const override
Private Attributes
Files files_
Opts opts_
Static Private Attributes
static constexpr const char * programType = "Transfer"
Inherits NEM::DRV::NemDriver.
Constructor & Destructor Documentation
TransferDriver() [1/2]
NEM::DRV::TransferDriver::TransferDriver (Files files, Opts opts)
Definition at line 56 of file TransferDriver.C.
     : files_(std::move(files)), opts_(std::move(opts)) {
   std::cout << "TransferDriver created" << std::endl;
 }
~TransferDriver()
NEM::DRV::TransferDriver::~TransferDriver () override
Definition at line 99 of file TransferDriver.C.
{
   std::cout << "TransferDriver destroyed" << std::endl;
 }
TransferDriver() [2/2]
NEM::DRV::TransferDriver::TransferDriver () private
Definition at line 61 of file TransferDriver.C.
 : TransferDriver({{}, {}, {}}, {{}, {}}) {}
Member Function Documentation
CreateTransferObject()
std::shared_ptr< TransferBase > NEM::DRV::TransferDriver::CreateTransferObject (meshBase * srcmsh, meshBase * trgmsh, const std::string & method) static
Definition at line 107 of file TransferDriver.C.
References FETransfer::CreateShared(), ConservativeSurfaceTransfer::CreateShared(), and ConservativeVolumeTransfer::CreateShared().
Referenced by OrderOfAccuracy::computeMeshWithResolution(), OrderOfAccuracy::computeRichardsonExtrapolation(), execute(), OrderOfAccuracy::OrderOfAccuracy(), proteusHdf5::proteusHdf5(), NEM::ADP::Refine::run(), and vtkMesh::vtkMesh().
{
   if (method == "Consistent Interpolation") {
     return FETransfer::CreateShared(srcmsh, trgmsh);
   }
 #ifdef HAVE_IMPACT
   else if (method == "Conservative Surface Transfer") {
     return ConservativeSurfaceTransfer::CreateShared(srcmsh, trgmsh);
   }
 #endif
 #ifdef HAVE_SUPERMESH
   else if (method == "Conservative Volume Transfer") {
     return ConservativeVolumeTransfer::CreateShared(srcmsh, trgmsh);
   }
 #endif
   else {
     std::cerr << "Method " << method << " is not supported." << std::endl;
     std::cerr << "Supported methods are : " << std::endl;
     std::cerr << "1) Consistent Interpolation" << std::endl;
 #ifdef HAVE_IMPACT
     std::cerr << "2) Conservative Surface Transfer" << std::endl;
 #endif
 #ifdef HAVE_SUPERMESH
     std::cerr << "3) Conservative Volume Transfer" << std::endl;
 #endif
     exit(1);
   }
 }
execute()
void NEM::DRV::TransferDriver::execute () const override virtual
Implements NEM::DRV::NemDriver.
Definition at line 63 of file TransferDriver.C.
References NEM::DRV::TransferDriver::Opts::arrayNames, NEM::DRV::TransferDriver::Opts::checkQuality, meshBase::Create(), CreateTransferObject(), nemAux::Timer::elapsed(), files_, NEM::DRV::TransferDriver::Opts::method, opts_, NEM::DRV::TransferDriver::Files::outputMeshFile, NEM::DRV::TransferDriver::Files::sourceMeshFile, nemAux::Timer::start(), nemAux::Timer::stop(), and NEM::DRV::TransferDriver::Files::targetMeshFile.
{
   std::shared_ptr<meshBase> source{
       meshBase::Create(this->files_.sourceMeshFile)};
   std::shared_ptr<meshBase> target{
       meshBase::Create(this->files_.targetMeshFile)};
   std::cout << "TransferDriver created" << std::endl;
   nemAux::Timer T;
   T.start();
   source->setCheckQuality(this->opts_.checkQuality);
   // source->transfer(target, method, arrayNames);
   auto transfer = TransferDriver::CreateTransferObject(
       source.get(), target.get(), this->opts_.method);
   if (this->opts_.arrayNames) {
     transfer->transferPointData(
         source->getArrayIDs(this->opts_.arrayNames.value()),
         source->getNewArrayNames());
   } else {
     transfer->run(source->getNewArrayNames());
   }
   source->write("new.vtu");
   T.stop();
   std::cout << "Time spent transferring data (ms) " << T.elapsed() << std::endl;
   target->write(this->files_.outputMeshFile);
 }
getFiles()
const TransferDriver::Files & NEM::DRV::TransferDriver::getFiles () const
Definition at line 91 of file TransferDriver.C.
References files_.
 { return files_; }
getOpts()
const TransferDriver::Opts & NEM::DRV::TransferDriver::getOpts () const
Definition at line 95 of file TransferDriver.C.
References opts_.
 { return opts_; }
getProgramType()
jsoncons::string_view NEM::DRV::TransferDriver::getProgramType () const override private virtual
Implements NEM::DRV::NemDriver.
Definition at line 103 of file TransferDriver.C.
References programType.
{
   return programType;
 }
readJSON()
std::unique_ptr< NemDriver > NEM::DRV::NemDriver::readJSON (const jsoncons::json & inputjson) static inherited
Parameters
inputjson json input with "Program Type" key
Returns
pointer to base NemDriver class
Definition at line 37 of file NemDriver.C.
Referenced by NEM::DRV::MeshGenDriver::MeshGenDriver().
{
   return inputjson.as<std::unique_ptr<NemDriver>>();
 }
setFiles()
void NEM::DRV::TransferDriver::setFiles (Files files)
Definition at line 93 of file TransferDriver.C.
References files_.
 { this->files_ = std::move(files); }
setOpts()
void NEM::DRV::TransferDriver::setOpts (Opts opts)
Definition at line 97 of file TransferDriver.C.
References opts_.
 { this->opts_ = std::move(opts); }
Member Data Documentation
files_
Files NEM::DRV::TransferDriver::files_ private
Definition at line 85 of file TransferDriver.H.
Referenced by execute(), getFiles(), and setFiles().
opts_
Opts NEM::DRV::TransferDriver::opts_ private
Definition at line 86 of file TransferDriver.H.
Referenced by execute(), getOpts(), and setOpts().
programType
constexpr const char* NEM::DRV::TransferDriver::programType = "Transfer" static private
Definition at line 82 of file TransferDriver.H.
Referenced by getProgramType().
The documentation for this class was generated from the following files:
TransferDriver.H
TransferDriver.C