NEMoSys: NEM::DRV::GmshMeshGenDriver Class Reference
NEM::DRV::GmshMeshGenDriver Class Reference
Detailed Description
Definition at line 39 of file GmshMeshGenDriver.H.
Classes
struct Opts
Public Types
using Files = MeshGenFiles
Public Member Functions
GmshMeshGenDriver (Files files, NEM::GEN::gmshParams params)
const Files & getFiles () const
void setFiles (Files files)
const NEM::GEN::gmshParams & getParams () const
void setParams (NEM::GEN::gmshParams params)
void execute () const override
Run the workflow represented by the driver.
Static Public Member Functions
static std::unique_ptr< NemDriver > readJSON (const jsoncons::json &inputjson)
Factory method for all drivers.
Private Member Functions
GmshMeshGenDriver ()
const Opts & getOpts () const
void setOpts (Opts opts)
Private Attributes
Files files_
Opts opts_
Inherits NEM::DRV::MeshGenDriver.
Member Typedef Documentation
Files
using NEM::DRV::GmshMeshGenDriver::Files = MeshGenFiles
Definition at line 41 of file GmshMeshGenDriver.H.
Constructor & Destructor Documentation
GmshMeshGenDriver() [1/2]
NEM::DRV::GmshMeshGenDriver::GmshMeshGenDriver (Files files, NEM::GEN::gmshParams params)
Definition at line 41 of file GmshMeshGenDriver.C.
     : files_(std::move(files)), opts_(std::move(params)) {}
GmshMeshGenDriver() [2/2]
NEM::DRV::GmshMeshGenDriver::GmshMeshGenDriver () private
Definition at line 44 of file GmshMeshGenDriver.C.
 : GmshMeshGenDriver({{}, {}}, {}) {}
Member Function Documentation
execute()
void NEM::DRV::GmshMeshGenDriver::execute () const override virtual
Implements NEM::DRV::NemDriver.
Definition at line 77 of file GmshMeshGenDriver.C.
References NEM::GEN::gmshGen::createMeshFromSTL(), meshBase::CreateShared(), meshBase::exportGmshToVtk(), files_, nemAux::find_ext(), mesh, opts_, NEM::DRV::GmshMeshGenDriver::Opts::params, and nemAux::trim_fname().
{
   auto paramsCopy = this->opts_.params;
   NEM::GEN::gmshGen generator{&paramsCopy};
   int status = generator.createMeshFromSTL(this->files_.inputGeoFile.c_str());
   if (status) {
     std::cerr << "Mesh Generation encountered error." << std::endl;
     exit(1);
   }
   std::string outputType = nemAux::find_ext(this->files_.outputMeshFile);
   if (outputType == ".msh") {
     return;
   }
   std::string newname = nemAux::trim_fname(this->files_.inputGeoFile, ".msh");
   auto mesh = meshBase::CreateShared(meshBase::exportGmshToVtk(newname));
   mesh->setFileName(this->files_.outputMeshFile);
   mesh->report();
   mesh->write();
 }
getFiles()
const GmshMeshGenDriver::Files & NEM::DRV::GmshMeshGenDriver::getFiles () const
Definition at line 46 of file GmshMeshGenDriver.C.
References files_.
{
   return files_;
 }
getOpts()
const GmshMeshGenDriver::Opts & NEM::DRV::GmshMeshGenDriver::getOpts () const private
Definition at line 63 of file GmshMeshGenDriver.C.
References opts_.
Referenced by getParams().
{
   return opts_;
 }
getParams()
const NEM::GEN::gmshParams & NEM::DRV::GmshMeshGenDriver::getParams () const
Definition at line 55 of file GmshMeshGenDriver.C.
References getOpts(), and NEM::DRV::GmshMeshGenDriver::Opts::params.
{
   return getOpts().params;
 }
readJSON()
std::unique_ptr< NemDriver > NEM::DRV::NemDriver::readJSON (const jsoncons::json & inputjson) static inherited
Parameters
inputjson json input with "Program Type" key
Returns
pointer to base NemDriver class
Definition at line 37 of file NemDriver.C.
Referenced by NEM::DRV::MeshGenDriver::MeshGenDriver().
{
   return inputjson.as<std::unique_ptr<NemDriver>>();
 }
setFiles()
void NEM::DRV::GmshMeshGenDriver::setFiles (Files files)
Definition at line 50 of file GmshMeshGenDriver.C.
References files_, NEM::GEN::gmshParams::ofname, opts_, and NEM::DRV::GmshMeshGenDriver::Opts::params.
{
   this->opts_.params.ofname = files.outputMeshFile;
   this->files_ = std::move(files);
 }
setOpts()
void NEM::DRV::GmshMeshGenDriver::setOpts (Opts opts) private
Definition at line 67 of file GmshMeshGenDriver.C.
References files_, NEM::GEN::gmshParams::ofname, opts_, and NEM::DRV::GmshMeshGenDriver::Opts::params.
Referenced by setParams().
{
   if (!opts.params.ofname.empty()) {
     this->files_.outputMeshFile = opts.params.ofname;
     this->opts_ = std::move(opts);
   } else {
     this->opts_ = std::move(opts);
     this->opts_.params.ofname = this->files_.outputMeshFile;
   }
 }
setParams()
void NEM::DRV::GmshMeshGenDriver::setParams (NEM::GEN::gmshParams params)
Definition at line 59 of file GmshMeshGenDriver.C.
References setOpts().
{
   setOpts(Opts{std::move(params)});
 }
Member Data Documentation
files_
Files NEM::DRV::GmshMeshGenDriver::files_ private
Definition at line 66 of file GmshMeshGenDriver.H.
Referenced by execute(), getFiles(), setFiles(), and setOpts().
opts_
Opts NEM::DRV::GmshMeshGenDriver::opts_ private
Definition at line 67 of file GmshMeshGenDriver.H.
Referenced by execute(), getOpts(), setFiles(), and setOpts().
The documentation for this class was generated from the following files:
GmshMeshGenDriver.H
GmshMeshGenDriver.C