NEMoSys: TransferBase Class Reference
TransferBase Class Reference abstract
Detailed Description
Definition at line 38 of file TransferBase.H.
Public Member Functions
TransferBase ()
virtual ~TransferBase ()
virtual int transferPointData (const std::vector< int > &arrayIDs, const std::vector< std::string > &newnames=std::vector< std::string >())=0
Transfer point data with given ids from source to target.
virtual int transferCellData (const std::vector< int > &arrayIDs, const std::vector< std::string > &newnames=std::vector< std::string >())=0
Transfer cell data with given ids from source to target.
int transferPointData (const std::vector< std::string > &arrayNames, const std::vector< std::string > &newnames=std::vector< std::string >())
Transfer point data with given field names from source to target.
int transferCellData (const std::vector< std::string > &arrayNames, const std::vector< std::string > &newnames=std::vector< std::string >())
Transfer cell data with given field names from source to target.
virtual int run (const std::vector< std::string > &newnames=std::vector< std::string >())=0
Transfer all fields.
void setCheckQual (bool x)
void setContBool (bool x)
Protected Attributes
meshBase * source
meshBase * target
vtkSmartPointer< vtkStaticCellLocator > srcCellLocator = nullptr
vtkSmartPointer< vtkStaticCellLocator > trgCellLocator = nullptr
vtkSmartPointer< vtkStaticPointLocator > srcPointLocator = nullptr
vtkSmartPointer< vtkStaticPointLocator > trgPointLocator = nullptr
bool checkQual
bool continuous
double c2cTrnsDistTol
Private Member Functions
std::vector< int > getArrayIDs (const std::vector< std::string > &arrayNames, vtkFieldData *fieldData)
given array names and field data, return vector of corresponding array ids in the field data
int getDataArrayIndex (const std::string &arrayName, vtkFieldData *data)
given array name and field data, returns index of array with given name (-1 if not found)
Inherited by ConservativeSurfaceTransfer, ConservativeVolumeTransfer, and FETransfer.
Constructor & Destructor Documentation
TransferBase()
TransferBase::TransferBase () inline
Definition at line 40 of file TransferBase.H.
       : source(nullptr),
         target(nullptr),
         checkQual(false),
         continuous(false),
         c2cTrnsDistTol(1.e-6) {
     std::cout << "TransferBase constructed" << std::endl;
   }
~TransferBase()
virtual TransferBase::~TransferBase () inline virtual
Definition at line 49 of file TransferBase.H.
{
     std::cout << "TransferBase destroyed" << std::endl;
   }
Member Function Documentation
getArrayIDs()
std::vector< int > TransferBase::getArrayIDs (const std::vector< std::string > & arrayNames, vtkFieldData * fieldData) private
Definition at line 56 of file TransferBase.C.
References getDataArrayIndex().
Referenced by transferCellData(), and transferPointData().
 {
   std::vector<int> arrayIDs;
   for(auto arrayName : arrayNames)
   {
     int arrayIndex = getDataArrayIndex(arrayName, fieldData);
     if(arrayIndex == -1)
     {
       std::cerr << "Array " << arrayName << " not found." << std::endl;
       exit(1);
     }
     arrayIDs.push_back(arrayIndex);
   }
   return arrayIDs;
 }
getDataArrayIndex()
int TransferBase::getDataArrayIndex (const std::string & arrayName, vtkFieldData * data) private
Parameters
arrayName name of array
data mesh field data that includes the sought after arrays
Returns
array id
Definition at line 72 of file TransferBase.C.
Referenced by getArrayIDs().
 {
   for(int arrayIndex = 0; arrayIndex < data->GetNumberOfArrays(); ++arrayIndex)
   {
     if(arrayName == data->GetArrayName(arrayIndex)) return arrayIndex;
   }
   return -1;
 }
run()
virtual int TransferBase::run (const std::vector< std::string > & newnames = std::vector< std::string >()) pure virtual
Parameters
newnames optional array of names to be applied to transferred fields
Returns
0 upon completion
Implemented in FETransfer, ConservativeVolumeTransfer, and ConservativeSurfaceTransfer.
Referenced by FETransfer::CreateShared(), and ConservativeVolumeTransfer::transferCellData().
setCheckQual()
void TransferBase::setCheckQual (bool x) inline
Definition at line 100 of file TransferBase.H.
 { checkQual = x; }
setContBool()
void TransferBase::setContBool (bool x) inline
Definition at line 102 of file TransferBase.H.
 { continuous = x; }
transferCellData() [1/2]
virtual int TransferBase::transferCellData (const std::vector< int > & arrayIDs, const std::vector< std::string > & newnames = std::vector< std::string >()) pure virtual
Parameters
arrayIDs array of array ids to specify which fields to transfer
newnames optional array of names to be applied to transferred fields
Returns
0 upon completion
Implemented in FETransfer, ConservativeVolumeTransfer, and ConservativeSurfaceTransfer.
Referenced by FETransfer::CreateShared(), and transferCellData().
transferCellData() [2/2]
int TransferBase::transferCellData (const std::vector< std::string > & arrayNames, const std::vector< std::string > & newnames = std::vector<std::string>())
Parameters
arrayIDs array of array names to specify which fields to transfer
newnames optional array of names to be applied to transferred fields
Returns
0 upon completion
Definition at line 47 of file TransferBase.C.
References getArrayIDs(), meshBase::getDataSet(), source, and transferCellData().
 {
   vtkCellData* cellData = source->getDataSet()->GetCellData();
   std::vector<int> arrayIDs = getArrayIDs(arrayNames, cellData);
   return transferCellData(arrayIDs, newnames);
 }
transferPointData() [1/2]
virtual int TransferBase::transferPointData (const std::vector< int > & arrayIDs, const std::vector< std::string > & newnames = std::vector< std::string >()) pure virtual
Parameters
arrayIDs array of array ids to specify which fields to transfer
newnames optional array of names to be applied to transferred fields
Returns
0 upon completion
Implemented in FETransfer, ConservativeVolumeTransfer, and ConservativeSurfaceTransfer.
Referenced by FETransfer::CreateShared(), ConservativeSurfaceTransfer::CreateShared(), ConservativeVolumeTransfer::CreateShared(), and transferPointData().
transferPointData() [2/2]
int TransferBase::transferPointData (const std::vector< std::string > & arrayNames, const std::vector< std::string > & newnames = std::vector<std::string>())
Parameters
arrayIDs array of array names to specify which fields to transfer
newnames optional array of names to be applied to transferred fields
Returns
0 upon completion
Definition at line 36 of file TransferBase.C.
References getArrayIDs(), meshBase::getDataSet(), source, and transferPointData().
 {
   vtkPointData* pointData = source->getDataSet()->GetPointData();
   std::vector<int> arrayIDs = getArrayIDs(arrayNames, pointData);
   return transferPointData(arrayIDs, newnames);
 }
Member Data Documentation
c2cTrnsDistTol
double TransferBase::c2cTrnsDistTol protected
Definition at line 116 of file TransferBase.H.
Referenced by FETransfer::transferCellData().
checkQual
bool TransferBase::checkQual protected
Definition at line 114 of file TransferBase.H.
Referenced by FETransfer::transferPointData().
continuous
bool TransferBase::continuous protected
Definition at line 115 of file TransferBase.H.
Referenced by FETransfer::transferCellData().
source
meshBase* TransferBase::source protected
Definition at line 105 of file TransferBase.H.
Referenced by ConservativeVolumeTransfer::ConservativeVolumeTransfer(), ConservativeVolumeTransfer::constructSupermesh(), FETransfer::FETransfer(), FETransfer::getClosestSourceCell(), FETransfer::run(), transferCellData(), FETransfer::transferCellData(), ConservativeSurfaceTransfer::transferPointData(), FETransfer::transferPointData(), transferPointData(), and ConservativeSurfaceTransfer::writeOverlay().
srcCellLocator
vtkSmartPointer<vtkStaticCellLocator> TransferBase::srcCellLocator = nullptr protected
Definition at line 108 of file TransferBase.H.
Referenced by FETransfer::FETransfer(), and FETransfer::getClosestSourceCell().
srcPointLocator
vtkSmartPointer<vtkStaticPointLocator> TransferBase::srcPointLocator = nullptr protected
Definition at line 111 of file TransferBase.H.
Referenced by FETransfer::FETransfer().
target
meshBase* TransferBase::target protected
Definition at line 106 of file TransferBase.H.
Referenced by ConservativeVolumeTransfer::ConservativeVolumeTransfer(), ConservativeVolumeTransfer::constructSupermesh(), FETransfer::FETransfer(), FETransfer::getClosestSourceCell(), FETransfer::run(), FETransfer::transferCellData(), ConservativeSurfaceTransfer::transferPointData(), FETransfer::transferPointData(), and ConservativeSurfaceTransfer::writeOverlay().
trgCellLocator
vtkSmartPointer<vtkStaticCellLocator> TransferBase::trgCellLocator = nullptr protected
Definition at line 109 of file TransferBase.H.
Referenced by FETransfer::FETransfer(), and FETransfer::getClosestSourceCell().
trgPointLocator
vtkSmartPointer<vtkStaticPointLocator> TransferBase::trgPointLocator = nullptr protected
Definition at line 112 of file TransferBase.H.
Referenced by FETransfer::FETransfer().
The documentation for this class was generated from the following files:
TransferBase.H
TransferBase.C