NEMoSys: polyApprox Class Reference
polyApprox Class Reference
Detailed Description
Definition at line 39 of file polyApprox.H.
Public Member Functions
polyApprox (int _order, const std::vector< std::vector< double >> &coords)
~polyApprox ()=default
polyApprox (const polyApprox &)=delete
polyApprox & operator= (const polyApprox &)=delete
void computeCoeff (const Eigen::VectorXd &data)
void resetCoeff ()
double eval (const std::vector< double > &coord) const
Static Public Member Functions
static std::unique_ptr< polyApprox > CreateUnique (int order, const std::vector< std::vector< double >> &coords)
Private Member Functions
Eigen::VectorXd computeBasis (const std::vector< double > &coord) const
Private Attributes
int order
std::vector< Eigen::VectorXd > basis
Eigen::MatrixXd A
Eigen::VectorXd b
Eigen::VectorXd a
Constructor & Destructor Documentation
polyApprox() [1/2]
polyApprox::polyApprox (int _order, const std::vector< std::vector< double >> & coords)
Definition at line 41 of file polyApprox.C.
References A, a, b, basis, computeBasis(), and order.
Referenced by CreateUnique().
     : order(_order)//, coords(_coords)
 {
   switch (order)
   {
     case 1:
     {
       A = MatrixXd::Zero(4, 4);
       b = VectorXd::Zero(4);
       a.resize(4);
       break;
     }
     case 2:
     {
       A = MatrixXd::Zero(10, 10);//.resize(10, 10);
       b = VectorXd::Zero(10);//resize(10);
       a.resize(10);
       break;
     }
     default:
     {
       std::cerr << "Error: order: " << order << " is not supported"
                 << std::endl;
       exit(1);
     }
   }
   basis.resize(coords.size());
   for (int i = 0; i < coords.size(); ++i)
   {
     basis[i] = computeBasis(coords[i]);
     A = A + basis[i] * (basis[i].transpose()); // * basis[i];
   }
 }
~polyApprox()
polyApprox::~polyApprox () default
polyApprox() [2/2]
polyApprox::polyApprox (const polyApprox &) delete
Member Function Documentation
computeBasis()
VectorXd polyApprox::computeBasis (const std::vector< double > & coord) const private
Definition at line 109 of file polyApprox.C.
References order.
Referenced by eval(), and polyApprox().
 {
   switch (order)
   {
     case 1:
     {
       Vector4d basisVec;
       basisVec(0) = 1;
       basisVec(1) = coord[0];
       basisVec(2) = coord[1];
       basisVec(3) = coord[2];
       return basisVec;
     }
     case 2:
     {
       Vector10d basisVec;
       basisVec(0) = 1;
       basisVec(1) = coord[0];
       basisVec(2) = coord[1];
       basisVec(3) = coord[2];
       basisVec(4) = coord[0] * coord[0];
       basisVec(5) = coord[0] * coord[1];
       basisVec(6) = coord[0] * coord[2];
       basisVec(7) = coord[1] * coord[1];
       basisVec(8) = coord[1] * coord[2];
       basisVec(9) = coord[2] * coord[2];
       return basisVec;
     }
     default:
     {
       std::cerr << "Error: order " << order << " is not supported."
                 << std::endl;
       exit(1);
     }
   }
 }
computeCoeff()
void polyApprox::computeCoeff (const Eigen::VectorXd & data)
Definition at line 85 of file polyApprox.C.
References A, a, b, basis, and data.
Referenced by PatchRecovery::computeNodalError(), and PatchRecovery::recoverNodalSolution().
 {
   for (int i = 0; i < basis.size(); ++i)
   {
     b = b + basis[i] * data(i); // basis[i].transpose() * data(i);
   }
   a = A.partialPivLu().solve(b);
 }
CreateUnique()
std::unique_ptr< polyApprox > polyApprox::CreateUnique (int order, const std::vector< std::vector< double >> & coords) static
Definition at line 78 of file polyApprox.C.
References polyApprox().
Referenced by PatchRecovery::computeNodalError(), and PatchRecovery::recoverNodalSolution().
 {
   return std::unique_ptr<polyApprox>(new polyApprox(order, coords));
 }
eval()
double polyApprox::eval (const std::vector< double > & coord) const
Definition at line 102 of file polyApprox.C.
References a, and computeBasis().
Referenced by PatchRecovery::computeNodalError(), and PatchRecovery::recoverNodalSolution().
 {
   VectorXd P = computeBasis(coord);
   return (P.transpose() * a)(0, 0);
 }
operator=()
polyApprox& polyApprox::operator= (const polyApprox &) delete
resetCoeff()
void polyApprox::resetCoeff ()
Definition at line 95 of file polyApprox.C.
References a, and b.
Referenced by PatchRecovery::computeNodalError(), and PatchRecovery::recoverNodalSolution().
 {
   a.setZero();
   b.setZero();
 }
Member Data Documentation
A
Eigen::MatrixXd polyApprox::A private
Definition at line 66 of file polyApprox.H.
Referenced by computeCoeff(), and polyApprox().
a
Eigen::VectorXd polyApprox::a private
Definition at line 70 of file polyApprox.H.
Referenced by computeCoeff(), eval(), polyApprox(), and resetCoeff().
b
Eigen::VectorXd polyApprox::b private
Definition at line 68 of file polyApprox.H.
Referenced by computeCoeff(), polyApprox(), and resetCoeff().
basis
std::vector<Eigen::VectorXd> polyApprox::basis private
Definition at line 64 of file polyApprox.H.
Referenced by computeCoeff(), and polyApprox().
order
int polyApprox::order private
Definition at line 62 of file polyApprox.H.
Referenced by computeBasis(), and polyApprox().
The documentation for this class was generated from the following files:
polyApprox.H
polyApprox.C