NEMoSys: NEM::NUCMESH::GroupData Class Reference
NEM::NUCMESH::GroupData Class Reference abstract
Class to hold the material/physical group of a geometry.
Detailed Description
Definition at line 92 of file NucMeshShapeData.H.
Public Member Functions
GroupData (std::string groupName, SMDSAbs_ElementType type)
void setupAlgos (const TopoDS_Shape &shape, SMESH_Gen &generator, SMESH_Mesh &mesh, std::vector< std::unique_ptr< SMESH_Hypothesis >> &generatedHyps) const override
Method that is called when a GeoManager instance tries to mesh shape.
virtual void updateGenerated (const TopoDS_Shape &shape, const TopTools_ListOfShape &generatedShapes, GeoManager &geoMetadata) const
Method that is called when a geometry operation generates new shapes.
virtual void updateModified (const TopoDS_Shape &shape, const TopTools_ListOfShape &modifiedShapes, GeoManager &geoMetadata) const =0
Method that is called when a geometry operation modifies shape.
virtual void updateDeleted (const TopoDS_Shape &shape, GeoManager &geoMetadata)
Method that is called when geoMetadata removes shape.
Public Attributes
std::string groupName
SMDSAbs_ElementType type
Inherits NEM::NUCMESH::NucMeshShapeData.
Inherited by NEM::NUCMESH::CopyOverrideShapeData< QuadMeshSurface, GroupData >, NEM::NUCMESH::CopyOverrideShapeData< SideSetEdge, GroupData >, and NEM::NUCMESH::CopyOverrideShapeData< TriMeshSurface, GroupData >.
Constructor & Destructor Documentation
GroupData()
NEM::NUCMESH::GroupData::GroupData (std::string groupName, SMDSAbs_ElementType type) inline
Definition at line 94 of file NucMeshShapeData.H.
References mesh.
       : groupName(std::move(groupName)), type(type) {}
Member Function Documentation
setupAlgos()
void NEM::NUCMESH::GroupData::setupAlgos (const TopoDS_Shape & shape, SMESH_Gen & generator, SMESH_Mesh & mesh, std::vector< std::unique_ptr< SMESH_Hypothesis >> & generatedHyps) const override virtual
Default implementation does nothing
Parameters
[in] shape Shape to mesh
[in,out] generator Generator that will mesh
[in,out] mesh Mesh that will mesh
[out] generatedHyps Output list of created hypotheses/algorithms (for memory management; will be deleted when the GeoManager instance is deleted)
Reimplemented from NEM::NUCMESH::NucMeshShapeData.
Reimplemented in NEM::NUCMESH::QuadMeshSurface, NEM::NUCMESH::TriMeshSurface, NEM::NUCMESH::EdgeSegments, and NEM::NUCMESH::SideSetEdge.
Definition at line 56 of file NucMeshShapeData.C.
References NEM::MSH::containerWrapper(), groupName, and type.
Referenced by NEM::NUCMESH::SideSetEdge::setupAlgos(), NEM::NUCMESH::TriMeshSurface::setupAlgos(), and NEM::NUCMESH::QuadMeshSurface::setupAlgos().
{
   if (!groupName.empty()) {
     bool addedToGroup = false;
     int oldGroup = -1;
     bool removeOldGroup = false;
     for (auto group : NEM::MSH::containerWrapper(mesh.GetGroups())) {
       auto groupDS = group->GetGroupDS();
       if (groupName == group->GetName() && groupDS &&
           type == group->GetGroupDS()->GetType()) {
         if (auto otherGeomGroup =
                 dynamic_cast<SMESHDS_GroupOnGeom *>(groupDS)) {
           auto otherPred = boost::make_shared<SMESH::Controls::BelongToGeom>();
           otherPred->SetGeom(otherGeomGroup->GetShape());
           otherPred->SetType(type);
           auto thisPred = boost::make_shared<SMESH::Controls::BelongToGeom>();
           thisPred->SetGeom(shape);
           thisPred->SetType(type);
           auto disjunction = boost::make_shared<SMESH::Controls::LogicalOR>();
           disjunction->SetPredicate1(otherPred);
           disjunction->SetPredicate2(thisPred);
           mesh.AddGroup(type, groupName.c_str(), -1, TopoDS_Shape{},
                         disjunction);
           addedToGroup = true;
           oldGroup = group->GetID();
           removeOldGroup = true;
           break;
         } else if (auto otherFilterGroup =
                        dynamic_cast<SMESHDS_GroupOnFilter *>(groupDS)) {
           auto otherPred = otherFilterGroup->GetPredicate();
           auto thisPred = boost::make_shared<SMESH::Controls::BelongToGeom>();
           thisPred->SetGeom(shape);
           thisPred->SetType(type);
           auto disjunction = boost::make_shared<SMESH::Controls::LogicalOR>();
           disjunction->SetPredicate1(otherPred);
           disjunction->SetPredicate2(thisPred);
           otherFilterGroup->SetPredicate(disjunction);
           addedToGroup = true;
           break;
         }
       }
     }
     if (!addedToGroup) { mesh.AddGroup(type, groupName.c_str(), -1, shape); }
     if (removeOldGroup && oldGroup >= 0) { mesh.RemoveGroup(oldGroup); }
   }
 }
updateDeleted()
virtual void NEM::GEO::ShapeData::updateDeleted (const TopoDS_Shape & shape, GeoManager & geoMetadata) inline virtual inherited
Default implementation does nothing
Parameters
[in] shape Shape to be removed
[in,out] geoMetadata Geometry-to-data map to alter
Definition at line 83 of file ShapeData.H.
                                                       {};
updateGenerated()
virtual void NEM::GEO::ShapeData::updateGenerated (const TopoDS_Shape & shape, const TopTools_ListOfShape & generatedShapes, GeoManager & geoMetadata) const inline virtual inherited
Default implementation does nothing
Parameters
[in] shape Argument to operation; shape existing in geoMetadata
[in] generatedShapes Shapes provided by a call to op.Generated(shape) for some geometry operation
[in,out] geoMetadata Geometry-to-data map to alter
Definition at line 62 of file ShapeData.H.
                                                               {};
updateModified()
virtual void NEM::GEO::ShapeData::updateModified (const TopoDS_Shape & shape, const TopTools_ListOfShape & modifiedShapes, GeoManager & geoMetadata) const pure virtual inherited
Parameters
[in] shape Argument to operation; shape existing in geoMetadata
[in] modifiedShapes Shapes provided by a call to op.Modified(shape) for some geometry operation
[in,out] geoMetadata Geometry-to-data map to alter
Implemented in NEM::NUCMESH::CopyOverrideShapeData< SideSetEdge, GroupData >, NEM::NUCMESH::CopyOverrideShapeData< TriMeshSurface, GroupData >, NEM::NUCMESH::CopyOverrideShapeData< EdgeSegments, SideSetEdge >, and NEM::NUCMESH::CopyOverrideShapeData< QuadMeshSurface, GroupData >.
Member Data Documentation
groupName
std::string NEM::NUCMESH::GroupData::groupName
Definition at line 102 of file NucMeshShapeData.H.
Referenced by setupAlgos().
type
SMDSAbs_ElementType NEM::NUCMESH::GroupData::type
Definition at line 103 of file NucMeshShapeData.H.
Referenced by setupAlgos().
The documentation for this class was generated from the following files:
NucMeshShapeData.H
NucMeshShapeData.C