NEMoSys: NEM::NUCMESH::ShapesArray Class Reference
NEM::NUCMESH::ShapesArray Class Reference abstract
Abstract base class representing a set of other ShapeBase objects, with a transformation applied to each.
Detailed Description
Definition at line 52 of file ShapesArray.H.
Public Member Functions
std::size_t getNumPatternShapes () const
const ShapeBase * getPatternShape (std::size_t idx) const
void setPatternShape (std::size_t idx, const std::shared_ptr< ShapeBase > &shape)
template<typename Shape >
void insertPatternShape (std::size_t idx, Shape &&shape)
template<typename Shape , typename... Args>
void makePatternShape (std::size_t idx, Args &&...args)
void fillPattern (std::size_t idx)
const std::array< double, 3 > & getCenter () const
void setCenter (const std::array< double, 3 > &center)
Static Public Member Functions
static std::array< double, 3 > getRotatedPoint (const std::array< double, 3 > &center, const std::array< double, 2 > &rotation)
Protected Member Functions
ShapesArray (const std::array< double, 3 > &center, std::size_t numPatternShapes)
std::size_t getPatternSize () const
const std::size_t & getPattern (std::size_t idx) const
void setPattern (std::size_t idx, std::size_t patternKey)
template<typename Modifier >
NEM::GEO::GeoManager createGeoImpl (Modifier &&modifier) const
virtual NEM::GEO::GeoManager createGeo () const =0
Construct a NEM::GEO::GeoManager.
Static Protected Member Functions
static NEM::GEO::GeoManager basicTransformation (const gp_Trsf &transformation, NEM::GEO::GeoManager &&geoMetadata)
static void mergeGeo (NEM::GEO::GeoManager &keepGeo, NEM::GEO::GeoManager &&removeGeo)
Merge two 2d NEM::GEO::GeoManager objects by cutting shapes in removeGeo from shapes in keepGeo and sewing the resulting faces.
Private Attributes
std::vector< std::shared_ptr< ShapeBase > > patternShapes_
A set of other ShapeBase objects, referenced by pattern_.
std::vector< decltype(patternShapes_)::size_type > pattern_
Each entry of pattern_ is an index into patternShapes_; subclasses interpret how to transform each entry.
Inherits NEM::NUCMESH::ShapeBase.
Inherited by NEM::NUCMESH::HexagonalArray, NEM::NUCMESH::PolarArray, and NEM::NUCMESH::RectangularArray.
Constructor & Destructor Documentation
ShapesArray()
NEM::NUCMESH::ShapesArray::ShapesArray (const std::array< double, 3 > & center, std::size_t numPatternShapes) protected
Definition at line 41 of file ShapesArray.C.
     : ShapeBase(center), patternShapes_(), pattern_(numPatternShapes) {}
Member Function Documentation
basicTransformation()
NEM::GEO::GeoManager NEM::NUCMESH::ShapesArray::basicTransformation (const gp_Trsf & transformation, NEM::GEO::GeoManager && geoMetadata) static protected
Definition at line 81 of file ShapesArray.C.
References NEM::GEO::GeoManager::buildCompound(), NEM::GEO::GeoManager::insert(), and NEM::DRV::JSON::shapeType.
Referenced by NEM::NUCMESH::HexagonalArray::createGeo(), NEM::NUCMESH::RectangularArray::createGeo(), and NEM::NUCMESH::PolarArray::createGeo().
{
   auto compound = geoMetadata.buildCompound();
   BRepBuilderAPI_Transform transformer{transformation};
   transformer.Perform(compound);
   NEM::GEO::GeoManager output(geoMetadata.getDim());
   static constexpr std::array<TopAbs_ShapeEnum, 4> shapeTypes{
       TopAbs_SOLID, TopAbs_FACE, TopAbs_EDGE, TopAbs_VERTEX};
   for (auto &shapeType : shapeTypes) {
     for (TopExp_Explorer explorer{compound, shapeType}; explorer.More();
          explorer.Next()) {
       auto &oldSubshape = explorer.Current();
       if (auto old_metadata = geoMetadata.get(oldSubshape)) {
         output.insert(transformer.ModifiedShape(oldSubshape),
                       std::move(*old_metadata));
       }
     }
   }
   return output;
 }
createGeo()
virtual NEM::GEO::GeoManager NEM::NUCMESH::ShapeBase::createGeo () const protected pure virtual inherited
Returns
A NEM::GEO::GeoManager object representing the shape described by this object
Implemented in NEM::NUCMESH::Circles, NEM::NUCMESH::PolarArray, NEM::NUCMESH::CirclesAndPolys, NEM::NUCMESH::HexagonalArray, and NEM::NUCMESH::RectangularArray.
createGeoImpl()
template<typename Modifier > NEM::GEO::GeoManager NEM::NUCMESH::ShapesArray::createGeoImpl (Modifier && modifier) const inline protected
Definition at line 87 of file ShapesArray.H.
References NEM::NUCMESH::ShapeBase::mergeGeo().
Referenced by NEM::NUCMESH::HexagonalArray::createGeo(), NEM::NUCMESH::RectangularArray::createGeo(), and NEM::NUCMESH::PolarArray::createGeo().
{
     NEM::GEO::GeoManager output(0);
     for (auto &patternId : pattern_) {
       auto shape = patternId < patternShapes_.size()
                        ? patternShapes_.at(patternId).get()
                        : nullptr;
       if (shape) {
         auto subShapeOut = shape->createGeo();
         modifier(&subShapeOut);
         ShapeBase::mergeGeo(output, std::move(subShapeOut));
       } else {
         modifier(nullptr);
       }
     }
     return output;
   }
fillPattern()
void NEM::NUCMESH::ShapesArray::fillPattern (std::size_t idx)
Definition at line 65 of file ShapesArray.C.
References pattern_.
{
   for (auto &pattern : pattern_) {
     pattern = idx;
   }
 }
getCenter()
const std::array< double, 3 > & NEM::NUCMESH::ShapeBase::getCenter () const inherited
Definition at line 50 of file ShapeBase.C.
References NEM::NUCMESH::ShapeBase::center_.
Referenced by NEM::NUCMESH::HexagonalArray::createGeo(), NEM::NUCMESH::RectangularArray::createGeo(), NEM::NUCMESH::CirclesAndPolys::createGeo(), NEM::NUCMESH::PolarArray::createGeo(), and NEM::NUCMESH::Circles::createGeo().
 { return center_; }
getNumPatternShapes()
std::size_t NEM::NUCMESH::ShapesArray::getNumPatternShapes () const
Definition at line 45 of file ShapesArray.C.
References patternShapes_.
Referenced by NEM::DRV::JSON::modify_helper().
{
   return patternShapes_.size();
 }
getPattern()
const std::size_t & NEM::NUCMESH::ShapesArray::getPattern (std::size_t idx) const protected
Definition at line 73 of file ShapesArray.C.
References pattern_.
Referenced by NEM::NUCMESH::RectangularArray::getPattern(), and NEM::NUCMESH::HexagonalArray::getPatternCoordCenter().
{
   return pattern_.at(idx);
 }
getPatternShape()
const ShapeBase * NEM::NUCMESH::ShapesArray::getPatternShape (std::size_t idx) const
Definition at line 49 of file ShapesArray.C.
References patternShapes_.
{
   if (idx < patternShapes_.size()) {
     return patternShapes_.at(idx).get();
   } else {
     return nullptr;
   }
 }
getPatternSize()
std::size_t NEM::NUCMESH::ShapesArray::getPatternSize () const protected
Definition at line 71 of file ShapesArray.C.
References pattern_.
 { return pattern_.size(); }
getRotatedPoint()
std::array< double, 3 > NEM::NUCMESH::ShapeBase::getRotatedPoint (const std::array< double, 3 > & center, const std::array< double, 2 > & rotation) static inherited
Parameters
center Center of circle
rotation {Radius, angle in degrees}
Returns
Point on circle with center center and normal [0, 0, 1], radius rotation[0] and angle (in degrees) rotation[1]
Definition at line 58 of file ShapeBase.C.
Referenced by NEM::NUCMESH::PolarArray::createGeo(), and NEM::DRV::JSON::modify_helper().
{
   auto angle = rotation[1] * M_PI / 180.;
   return {center[0] + rotation[0] * std::cos(angle),
           center[1] + rotation[0] * std::sin(angle), center[2]};
 }
insertPatternShape()
template<typename Shape > void NEM::NUCMESH::ShapesArray::insertPatternShape (std::size_t idx, Shape && shape) inline
Definition at line 62 of file ShapesArray.H.
{
     this->setPatternShape(idx,
                           std::make_shared<typename std::decay<Shape>::type>(
                               std::forward<Shape>(shape)));
   }
makePatternShape()
template<typename Shape , typename... Args> void NEM::NUCMESH::ShapesArray::makePatternShape (std::size_t idx, Args &&... args) inline
Definition at line 69 of file ShapesArray.H.
{
     this->setPatternShape(idx,
                           std::make_shared<Shape>(std::forward<Args>(args)...));
   }
mergeGeo()
void NEM::NUCMESH::ShapeBase::mergeGeo (NEM::GEO::GeoManager & keepGeo, NEM::GEO::GeoManager && removeGeo) static protected inherited
Parameters
[in,out] keepGeo Merge geometry from removeGeo into this object
[in] removeGeo Move geometry and data from this object into keepGeo
Definition at line 66 of file ShapeBase.C.
References NEM::GEO::GeoManager::buildCompound(), NEM::GEO::GeoManager::deleteShapes(), NEM::GEO::GeoManager::getDim(), NEM::GEO::GeoManager::insert(), NEM::GEO::GeoManager::modify(), NEM::GEO::GeoManager::setDim(), and NEM::DRV::JSON::shapeType.
Referenced by createGeoImpl(), and NEM::SRV::NucMeshSrv::FillOutputPortInformation().
{
   auto origCompound = keepGeo.buildCompound();
   if (origCompound.IsNull()) {
     keepGeo = std::move(removeGeo);
     return;
   } else {
     auto newCompound = removeGeo.buildCompound();
     TopoDS_ListOfShape newShapes;
     static constexpr std::array<TopAbs_ShapeEnum, 4> shapeTypes{
         TopAbs_SOLID, TopAbs_FACE, TopAbs_EDGE, TopAbs_VERTEX};
     for (auto &shapeType : shapeTypes) {
       for (TopExp_Explorer explorer{newCompound, shapeType}; explorer.More();
            explorer.Next()) {
         auto &oldSubshape = explorer.Current();
         if (auto old_metadata = removeGeo.get(oldSubshape)) {
           keepGeo.insert(oldSubshape, std::move(*old_metadata));
         }
       }
     }
     if (!newCompound.IsNull()) {
       keepGeo.setDim(std::max(keepGeo.getDim(), removeGeo.getDim()));
       BRepAlgoAPI_Cut cutter{origCompound, newCompound};
       if (cutter.HasDeleted() || cutter.HasModified() ||
           cutter.HasGenerated()) {
         auto deletedShapes = keepGeo.modify(cutter, {TopAbs_EDGE, TopAbs_FACE});
         keepGeo.deleteShapes(deletedShapes[0]);
       }
       BRepBuilderAPI_Sewing sewer{};
       std::vector<TopoDS_Shape> sewedShapes;
       auto compound = keepGeo.buildCompound();
       for (TopExp_Explorer explorer{compound, TopAbs_FACE}; explorer.More();
            explorer.Next()) {
         sewer.Add(explorer.Current());
         sewedShapes.emplace_back(explorer.Current());
       }
       sewer.Perform();
       auto deletedShapes =
           keepGeo.modify(sewer, sewedShapes, {TopAbs_EDGE, TopAbs_FACE});
       keepGeo.deleteShapes(deletedShapes);
     }
   }
 }
setCenter()
void NEM::NUCMESH::ShapeBase::setCenter (const std::array< double, 3 > & center) inherited
Definition at line 52 of file ShapeBase.C.
References NEM::NUCMESH::ShapeBase::center_.
Referenced by NEM::DRV::JSON::modify_helper().
{
   center_ = center;
 }
setPattern()
void NEM::NUCMESH::ShapesArray::setPattern (std::size_t idx, std::size_t patternKey) protected
Definition at line 77 of file ShapesArray.C.
References pattern_.
Referenced by NEM::DRV::JSON::modify_helper(), NEM::NUCMESH::RectangularArray::setPattern(), and NEM::NUCMESH::HexagonalArray::setPatternCoordCenter().
{
   pattern_.at(idx) = patternKey;
 }
setPatternShape()
void NEM::NUCMESH::ShapesArray::setPatternShape (std::size_t idx, const std::shared_ptr< ShapeBase > & shape)
Definition at line 57 of file ShapesArray.C.
References patternShapes_.
Referenced by NEM::DRV::JSON::modify_helper().
{
   if (idx >= patternShapes_.size()) {
     patternShapes_.resize(idx + 1);
   }
   patternShapes_.at(idx) = shape;
 }
Member Data Documentation
pattern_
std::vector<decltype(patternShapes_)::size_type> NEM::NUCMESH::ShapesArray::pattern_ private
Definition at line 116 of file ShapesArray.H.
Referenced by fillPattern(), getPattern(), getPatternSize(), and setPattern().
patternShapes_
std::vector<std::shared_ptr<ShapeBase> > NEM::NUCMESH::ShapesArray::patternShapes_ private
Definition at line 111 of file ShapesArray.H.
Referenced by getNumPatternShapes(), getPatternShape(), and setPatternShape().
The documentation for this class was generated from the following files:
ShapesArray.H
ShapesArray.C