NEMoSys: NEM::MSH::inpGeoMesh Class Reference
NEM::MSH::inpGeoMesh Class Reference abstract
Class representing meshes in CalculiX input deck (similar to ABAQUS)
Detailed Description
Currently supports the keywords ELEMENT ("C3D4", "C3D8", and "C3D6" types, ELSET parameter), ELSET, NSET, and SURFACE (TYPE=ELEMENT only). By default, physical groups with dimension equal to mesh dimension are turned into ELSETs, and NSETs and physical groups with dimension one less than mesh dimension are turned into SURFACEs and NSETs.
Definition at line 49 of file inpGeoMesh.H.
Classes
struct InpSets
Public Member Functions
decltype(InpSets::nodeSets) & getNSets ()
decltype(InpSets::elSets) & getElSets ()
decltype(InpSets::surfaces) & getSurfaces ()
virtual void write (const std::string &fileName)=0
Write mesh to file.
virtual void report (std::ostream &out) const =0
Print a report about the mesh.
virtual void takeGeoMesh (geoMeshBase *otherGeoMesh)
Take the GeoMesh of another geoMeshBase.
virtual void mergeGeoMesh (geoMeshBase *otherGeoMesh)
Merge mesh data from a new geoMesh to an existing geoMesh.
const std::string & getGeoEntArrayName () const
Get the name of the geometric entities array.
void setGeoEntArrayName (const std::string &geoEntArrayName)
Set the name of the geometric entities array.
double getAngleThreshold () const
Get the angle threshold used for surface classification.
void setAngleThreshold (double angleThreshold)
Set the angle threshold used for surface classification.
nemId_t getNumberOfPoints () const
Get the number of points in mesh.
nemId_t getNumberOfCells () const
Get the number of cells in mesh.
void getPoint (nemId_t id, std::array< double, 3 > *x) const
Get the coordinate of a point.
std::array< double, 3 > getPoint (nemId_t id) const
Get the coordinate of a point.
void getCell (nemId_t cellId, vtkGenericCell *cell) const
Get cell.
vtkCell * getCell (nemId_t cellId) const
Get cell.
void getCellBounds (nemId_t cellId, std::array< double, 6 > *bounds) const
Get cell bounds.
std::array< double, 6 > getCellBounds (nemId_t cellId) const
Get cell bounds.
VTKCellType getCellType (nemId_t cellId) const
Get VTK cell type.
void getCellPoints (nemId_t cellId, vtkIdList *ptIds) const
Get list of point ids defining specified cell.
void getPointCells (nemId_t ptId, vtkIdList *cellIds) const
Get list of cell ids using specified point.
void getCellNeighbors (nemId_t cellId, vtkIdList *ptIds, vtkIdList *cellIds) const
Get list of cells sharing points ptIds excluding cellId.
int getNumberOfPointDataArrays () const
Get number of arrays in the point data.
void getPointDataArrayCopy (const std::string &arrayName, vtkAbstractArray *array, int *arrayIdx=nullptr) const
Get copy of point data array by name.
vtkSmartPointer< vtkAbstractArray > getPointDataArrayCopy (const std::string &arrayName, int *arrayIdx=nullptr) const
Create and return a copy of point data array by name.
void getPointDataArrayCopy (int arrayIdx, vtkAbstractArray *array) const
Get copy of point data array by index.
vtkSmartPointer< vtkAbstractArray > getPointDataArrayCopy (int arrayIdx) const
Create and return a copy of point data array by index.
int getNumberOfCellDataArrays () const
Get number of arrays in the cell data.
void getCellDataArrayCopy (const std::string &arrayName, vtkAbstractArray *array, int *arrayIdx=nullptr) const
Get copy of cell data array by name.
vtkSmartPointer< vtkAbstractArray > getCellDataArrayCopy (const std::string &arrayName, int *arrayIdx=nullptr) const
Create and return a copy of cell data array by name.
void getCellDataArrayCopy (int arrayIdx, vtkAbstractArray *array) const
Get copy of cell data array by index.
vtkSmartPointer< vtkAbstractArray > getCellDataArrayCopy (int arrayIdx) const
Create and return a copy of cell data array by index.
int getNumberOfFieldDataArrays () const
Get number of arrays in the field data.
void getFieldDataArrayCopy (const std::string &arrayName, vtkAbstractArray *array, int *arrayIdx=nullptr) const
Get copy of field data array by name.
vtkSmartPointer< vtkAbstractArray > getFieldDataArrayCopy (const std::string &arrayName, int *arrayIdx=nullptr) const
Create and return a copy of field data array by name.
void getFieldDataArrayCopy (int arrayIdx, vtkAbstractArray *array) const
Get copy of field data array by index.
vtkSmartPointer< vtkAbstractArray > getFieldDataArrayCopy (int arrayIdx) const
Create and return a copy of field data array by index.
Static Public Member Functions
static inpGeoMesh * New ()
static inpGeoMesh * Read (const std::string &fileName)
Protected Member Functions
inpGeoMesh ()
inpGeoMesh (const std::string &fileName)
void reconstructGeo () override
Construct the geometry from the mesh alone.
int setPointDataArray (vtkAbstractArray *array)
Set point data.
int setCellDataArray (vtkAbstractArray *array)
Set cell data.
int setFieldDataArray (vtkAbstractArray *array)
Set field data.
void unsetPointDataArray (int arrayIdx)
Remove point data array by index.
void unsetPointDataArray (const std::string &arrayName)
Remove point data array by name.
void unsetCellDataArray (int arrayIdx)
Remove cell data array by index.
void unsetCellDataArray (const std::string &arrayName)
Remove cell data array by name.
void unsetFieldDataArray (int arrayIdx)
Remove field data array by index.
void unsetFieldDataArray (const std::string &arrayName)
Remove field data array by name.
const GeoMesh & getGeoMesh () const
Get the underlying geometry object.
void setGeoMesh (const geoMeshBase::GeoMesh &geoMesh)
Set the underlying geometry object.
Static Protected Attributes
static constexpr auto GEO_ENT_DEFAULT_NAME = "GeoEnt"
Private Member Functions
inpGeoMesh (std::pair< GeoMesh, InpSets > mesh)
Ctor meant for ease of delegating to geoMeshBase ctor.
void resetNative () override
Static Private Member Functions
static std::pair< GeoMesh, InpSets > inp2GM (const std::string &fileName)
Private Attributes
InpSets inpSets_
Holds data specific to inp format.
Inherits NEM::MSH::geoMeshBase.
Constructor & Destructor Documentation
inpGeoMesh() [1/3]
NEM::MSH::inpGeoMesh::inpGeoMesh () protected
Definition at line 605 of file inpGeoMesh.C.
References NEM::MSH::inpGeoMesh::InpSets::elSets, NEM::MSH::geoMeshBase::getGeoMesh(), inpSets_, mesh, NEM::MSH::inpGeoMesh::InpSets::nodeSets, points, NEM::MSH::geoMeshBase::report(), NEM::MSH::inpGeoMesh::InpSets::surfaces, and NEM::MSH::geoMeshBase::write().
 : inpGeoMesh(std::string{}) {}
inpGeoMesh() [2/3]
NEM::MSH::inpGeoMesh::inpGeoMesh (const std::string & fileName) explicit protected
Definition at line 599 of file inpGeoMesh.C.
     : inpGeoMesh(inp2GM(fileName)) {}
inpGeoMesh() [3/3]
NEM::MSH::inpGeoMesh::inpGeoMesh (std::pair< GeoMesh, InpSets > mesh) explicit private
Parameters
mesh from parsing a .inp mesh file
Definition at line 602 of file inpGeoMesh.C.
     : geoMeshBase(std::move(mesh.first)), inpSets_(std::move(mesh.second)) {}
Member Function Documentation
getAngleThreshold()
double NEM::MSH::geoMeshBase::getAngleThreshold () const inline inherited
Returns
angle threshold (in radians)
Definition at line 171 of file geoMeshBase.H.
 { return _angleThreshold; }
getCell() [1/2]
void NEM::MSH::geoMeshBase::getCell (nemId_t cellId, vtkGenericCell * cell) const inline inherited
Parameters
cellId cell id
cell cell
Definition at line 214 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     _geoMesh.mesh->GetCell(cellId, cell);
   }
getCell() [2/2]
vtkCell* NEM::MSH::geoMeshBase::getCell (nemId_t cellId) const inline inherited
Parameters
cellId cell id
Returns
cell
Definition at line 222 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetCell(cellId);
   }
getCellBounds() [1/2]
void NEM::MSH::geoMeshBase::getCellBounds (nemId_t cellId, std::array< double, 6 > * bounds) const inline inherited
Parameters
cellId cell id
bounds array of bounds as (x_min,x_max, y_min,y_max, z_min,z_max)
Definition at line 230 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellBounds(cellId, bounds->data());
   }
getCellBounds() [2/2]
std::array<double, 6> NEM::MSH::geoMeshBase::getCellBounds (nemId_t cellId) const inline inherited
Parameters
cellId cell id
Returns
array of bounds as (x_min,x_max, y_min,y_max, z_min,z_max)
Definition at line 238 of file geoMeshBase.H.
{
     std::array<double, 6> bounds{};
     getCellBounds(cellId, &bounds);
     return bounds;
   }
getCellDataArrayCopy() [1/4]
void NEM::MSH::geoMeshBase::getCellDataArrayCopy (const std::string & arrayName, vtkAbstractArray * array, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
array cell data array
arrayIdx array index
Definition at line 180 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
Referenced by NEM::MSH::diffMesh().
{
   getArrCopy(_geoMesh.mesh->GetCellData(), arrayName, arrayIdx, array);
 }
getCellDataArrayCopy() [2/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getCellDataArrayCopy (const std::string & arrayName, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
arrayIdx array index
Returns
pointer to copy of array
Definition at line 186 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetCellData(), arrayName, arrayIdx);
 }
getCellDataArrayCopy() [3/4]
void NEM::MSH::geoMeshBase::getCellDataArrayCopy (int arrayIdx, vtkAbstractArray * array) const inherited
Parameters
arrayIdx array index
array cell data array
Definition at line 191 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   getArrCopy(_geoMesh.mesh->GetCellData(), arrayIdx, array);
 }
getCellDataArrayCopy() [4/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getCellDataArrayCopy (int arrayIdx) const inherited
Parameters
arrayIdx array index
Returns
pointer to copy of array
Definition at line 196 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetCellData(), arrayIdx);
 }
getCellNeighbors()
void NEM::MSH::geoMeshBase::getCellNeighbors (nemId_t cellId, vtkIdList * ptIds, vtkIdList * cellIds) const inline inherited
Parameters
cellId id of cell to exclude
ptIds point id
cellIds list of cell ids
Definition at line 273 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellNeighbors(cellId, ptIds, cellIds);
   }
getCellPoints()
void NEM::MSH::geoMeshBase::getCellPoints (nemId_t cellId, vtkIdList * ptIds) const inline inherited
Parameters
cellId cell id
ptIds list of point ids
Definition at line 256 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellPoints(cellId, ptIds);
   }
getCellType()
VTKCellType NEM::MSH::geoMeshBase::getCellType (nemId_t cellId) const inline inherited
Parameters
cellId cell id
Returns
VTK cell type (see vtk documentation for specifics)
Definition at line 248 of file geoMeshBase.H.
{
     return static_cast<VTKCellType>(_geoMesh.mesh->GetCellType(cellId));
   }
getElSets()
decltype(InpSets::elSets) & NEM::MSH::inpGeoMesh::getElSets () inline
Definition at line 75 of file inpGeoMesh.H.
 { return inpSets_.elSets; }
getFieldDataArrayCopy() [1/4]
void NEM::MSH::geoMeshBase::getFieldDataArrayCopy (const std::string & arrayName, vtkAbstractArray * array, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
array field data array
arrayIdx array index
Definition at line 201 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   getArrCopy(_geoMesh.mesh->GetFieldData(), arrayName, arrayIdx, array);
 }
getFieldDataArrayCopy() [2/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getFieldDataArrayCopy (const std::string & arrayName, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
arrayIdx array index
Returns
pointer to copy of array
Definition at line 207 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetFieldData(), arrayName, arrayIdx);
 }
getFieldDataArrayCopy() [3/4]
void NEM::MSH::geoMeshBase::getFieldDataArrayCopy (int arrayIdx, vtkAbstractArray * array) const inherited
Parameters
arrayIdx array index
array field data array
Definition at line 212 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   getArrCopy(_geoMesh.mesh->GetFieldData(), arrayIdx, array);
 }
getFieldDataArrayCopy() [4/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getFieldDataArrayCopy (int arrayIdx) const inherited
Parameters
arrayIdx array index
Returns
pointer to copy of array
Definition at line 217 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetFieldData(), arrayIdx);
 }
getGeoEntArrayName()
const std::string& NEM::MSH::geoMeshBase::getGeoEntArrayName () const inline inherited
Returns
name of geometric entities array
Definition at line 157 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
 { return _geoMesh.link; }
getGeoMesh()
const GeoMesh& NEM::MSH::geoMeshBase::getGeoMesh () const inline protected inherited
Note
This is not a copy; Gmsh does not support cloning a model.
Definition at line 533 of file geoMeshBase.H.
Referenced by NEM::MSH::exoGeoMesh::addCellsToBlock(), NEM::MSH::exoGeoMesh::addElemBlock(), NEM::MSH::exoGeoMesh::addElemBlockProperty(), NEM::MSH::exoGeoMesh::addNodeSet(), NEM::MSH::exoGeoMesh::addSideSet(), NEM::MSH::exoGeoMesh::exoGeoMesh(), NEM::MSH::exoGeoMesh::getElemBlock(), NEM::MSH::exoGeoMesh::getElemBlockId(), NEM::MSH::exoGeoMesh::getSideSet(), NEM::MSH::vtkGeoMesh::getVtkMesh(), inpGeoMesh(), NEM::MSH::exoGeoMesh::reassignCells(), NEM::MSH::oshGeoMesh::reconstructGeo(), NEM::MSH::exoGeoMesh::reconstructGeo(), NEM::MSH::geoMeshBase::report(), NEM::MSH::exoGeoMesh::resetElemBlocks(), NEM::MSH::smeshGeoMesh::resetNative(), NEM::MSH::gmshGeoMesh::resetNative(), resetNative(), NEM::MSH::foamGeoMesh::resetNative(), NEM::MSH::oshGeoMesh::resetNative(), NEM::MSH::exoGeoMesh::resetNative(), NEM::MSH::exoGeoMesh::scaleNodes(), NEM::MSH::oshGeoMesh::setOshMesh(), NEM::MSH::exoGeoMesh::setPhysGrpPropertyName(), NEM::MSH::exoGeoMesh::setSideSetObjId(), NEM::MSH::exoGeoMesh::stitch(), NEM::MSH::vtkGeoMesh::write(), NEM::MSH::gmshGeoMesh::write(), and NEM::MSH::exoGeoMesh::write().
 { return _geoMesh; }
getNSets()
decltype(InpSets::nodeSets) & NEM::MSH::inpGeoMesh::getNSets () inline
Definition at line 74 of file inpGeoMesh.H.
 { return inpSets_.nodeSets; }
getNumberOfCellDataArrays()
int NEM::MSH::geoMeshBase::getNumberOfCellDataArrays () const inline inherited
Returns
number of arrays in the cell data
Definition at line 318 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     return _geoMesh.mesh->GetCellData()->GetNumberOfArrays();
   }
getNumberOfCells()
nemId_t NEM::MSH::geoMeshBase::getNumberOfCells () const inline inherited
Returns
number of cells in mesh
Definition at line 190 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
 { return _geoMesh.mesh->GetNumberOfCells(); }
getNumberOfFieldDataArrays()
int NEM::MSH::geoMeshBase::getNumberOfFieldDataArrays () const inline inherited
Returns
number of arrays in the field data
Definition at line 355 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetFieldData()->GetNumberOfArrays();
   }
getNumberOfPointDataArrays()
int NEM::MSH::geoMeshBase::getNumberOfPointDataArrays () const inline inherited
Returns
number of arrays in the point data
Definition at line 281 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     return _geoMesh.mesh->GetPointData()->GetNumberOfArrays();
   }
getNumberOfPoints()
nemId_t NEM::MSH::geoMeshBase::getNumberOfPoints () const inline inherited
Returns
number of points in mesh
Definition at line 183 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     return _geoMesh.mesh->GetNumberOfPoints();
   }
getPoint() [1/2]
void NEM::MSH::geoMeshBase::getPoint (nemId_t id, std::array< double, 3 > * x) const inline inherited
Parameters
id point id
x array of coordinates as (x,y,z)
Definition at line 196 of file geoMeshBase.H.
Referenced by NEM::MSH::diffMesh().
{
     _geoMesh.mesh->GetPoint(id, x->data());
   }
getPoint() [2/2]
std::array<double, 3> NEM::MSH::geoMeshBase::getPoint (nemId_t id) const inline inherited
Parameters
id point id
Returns
array of coordinates as (x,y,z)
Definition at line 204 of file geoMeshBase.H.
{
     std::array<double, 3> x{};
     getPoint(id, &x);
     return x;
   }
getPointCells()
void NEM::MSH::geoMeshBase::getPointCells (nemId_t ptId, vtkIdList * cellIds) const inline inherited
Parameters
ptId point id
cellIds list of cell ids
Definition at line 264 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetPointCells(ptId, cellIds);
   }
getPointDataArrayCopy() [1/4]
void NEM::MSH::geoMeshBase::getPointDataArrayCopy (const std::string & arrayName, vtkAbstractArray * array, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
array point data array
arrayIdx array index
Definition at line 159 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
Referenced by NEM::MSH::diffMesh().
{
   getArrCopy(_geoMesh.mesh->GetPointData(), arrayName, arrayIdx, array);
 }
getPointDataArrayCopy() [2/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getPointDataArrayCopy (const std::string & arrayName, int * arrayIdx = nullptr) const inherited
Optionally, get array index.
Parameters
arrayName array name
arrayIdx array index
Returns
pointer to copy of array
Definition at line 165 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetPointData(), arrayName, arrayIdx);
 }
getPointDataArrayCopy() [3/4]
void NEM::MSH::geoMeshBase::getPointDataArrayCopy (int arrayIdx, vtkAbstractArray * array) const inherited
Parameters
arrayIdx array index
array point data array
Definition at line 170 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   getArrCopy(_geoMesh.mesh->GetPointData(), arrayIdx, array);
 }
getPointDataArrayCopy() [4/4]
vtkSmartPointer< vtkAbstractArray > NEM::MSH::geoMeshBase::getPointDataArrayCopy (int arrayIdx) const inherited
Parameters
arrayIdx array index
Returns
pointer to copy of array
Definition at line 175 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
{
   return getArrCopy(_geoMesh.mesh->GetPointData(), arrayIdx);
 }
getSurfaces()
decltype(InpSets::surfaces) & NEM::MSH::inpGeoMesh::getSurfaces () inline
Definition at line 76 of file inpGeoMesh.H.
References mesh.
 { return inpSets_.surfaces; }
inp2GM()
std::pair< geoMeshBase::GeoMesh, inpGeoMesh::InpSets > NEM::MSH::inpGeoMesh::inp2GM (const std::string & fileName) static private
Definition at line 719 of file inpGeoMesh.C.
References NEM::MSH::geoMeshBase::GEO_ENT_DEFAULT_NAME, nemAux::getRandomString(), NEM::MSH::GmshInterface::Initialize(), mesh, NEM::MSH::New(), and points.
{
   auto mesh = vtkSmartPointer<vtkUnstructuredGrid>::New();
   std::map<std::string, std::set<vtkIdType>> outNSets, outElSets, outSurfaces;
   SideSet sideSet{};
   std::string geoName{};
   std::string linkName{};
   if (fileName.empty()) { return {{mesh, {}, {}, {}}, {}}; }
   std::ifstream inFile(fileName);
   std::string line;
   InpParser parser{};
   while (std::getline(inFile, line)) { parser.parseLine(line); }
   auto parserMesh = parser.getMesh();
   std::map<vtkIdType, vtkIdType> nodeInpId2GMIdx;
   if (!parserMesh.nodes.empty()) {
     vtkNew<vtkPoints> points;
     points->Allocate(parserMesh.nodes.size());
     for (const auto &parserNode : parserMesh.nodes) {
       nodeInpId2GMIdx[parserNode.first] =
           points->InsertNextPoint(parserNode.second.data());
     }
     mesh->SetPoints(points);
   }
   auto nodeMapper = [&nodeInpId2GMIdx](vtkIdType x) {
     return nodeInpId2GMIdx.at(x);
   };
   for (const auto &nSet : parserMesh.nodeSets) {
     auto &outNSet = outNSets[nSet.first];
     std::transform(nSet.second.begin(), nSet.second.end(),
                    std::inserter(outNSet, outNSet.end()), nodeMapper);
   }
   std::map<vtkIdType, vtkIdType> inpId2GMIdx;
   if (!parserMesh.elems.empty()) {
     mesh->Allocate(parserMesh.elems.size());
 #ifdef HAVE_GMSH
     GmshInterface::Initialize();
     geoName = "geoMesh_" + nemAux::getRandomString(6);
     gmsh::model::add(geoName);
     gmsh::model::setCurrent(geoName);
 #endif
     linkName = GEO_ENT_DEFAULT_NAME;
     vtkNew<vtkIntArray> geoEntArr;
     geoEntArr->SetName(linkName.c_str());
 #ifndef HAVE_GMSH
     int entTag = 1;
 #endif
     for (const auto &elemSet : parserMesh.elems) {
 #ifdef HAVE_GMSH
       auto entTag = gmsh::model::addDiscreteEntity(parserMesh.maxDim);
       gmsh::model::setEntityName(parserMesh.maxDim, entTag, elemSet.first);
 #endif
       for (const auto &elem : elemSet.second) {
         auto points = elem.points;
         std::transform(points.begin(), points.end(), points.begin(),
                        nodeMapper);
         if (elem.cellType == VTK_WEDGE) {
           std::swap(points.at(1), points.at(2));
           std::swap(points.at(4), points.at(5));
         }
         inpId2GMIdx[elem.id] =
             mesh->InsertNextCell(elem.cellType, points.size(), points.data());
         geoEntArr->InsertNextValue(entTag);
       }
 #ifndef HAVE_GMSH
       ++entTag;
 #endif
     }
     mesh->GetCellData()->AddArray(geoEntArr);
   }
   for (const auto &elSet : parserMesh.elSets) {
     auto &outElSet = outElSets[elSet.first];
     for (const auto &elem : elSet.second) {
       auto iterCellIdxMap = inpId2GMIdx.find(elem);
       if (iterCellIdxMap != inpId2GMIdx.end()) {
         outElSet.emplace(iterCellIdxMap->second);
       }
     }
   }
   if (!parserMesh.surfaces.empty()) {
     auto sideSetPD = vtkSmartPointer<vtkPolyData>::New();
     sideSetPD->SetPoints(mesh->GetPoints());
     sideSetPD->Allocate();
     vtkNew<vtkIntArray> entArr;
     vtkNew<vtkIdTypeArray> origCellArr;
     origCellArr->SetNumberOfComponents(2);
     vtkNew<vtkIntArray> cellFaceArr;
     cellFaceArr->SetNumberOfComponents(2);
 #ifndef HAVE_GMSH
     int entTag = 1;
 #endif
     for (const auto &surf : parserMesh.surfaces) {
       auto &outSurface = outSurfaces[surf.first];
 #ifdef HAVE_GMSH
       auto entTag = gmsh::model::addDiscreteEntity(parserMesh.maxDim - 1);
       auto phyGroupTag =
           gmsh::model::addPhysicalGroup(parserMesh.maxDim - 1, {entTag});
       gmsh::model::setPhysicalName(parserMesh.maxDim - 1, phyGroupTag,
                                    surf.first);
 #endif
       for (const auto &side : surf.second) {
         auto iterCellIdxMap = inpId2GMIdx.find(side.first);
         if (iterCellIdxMap != inpId2GMIdx.end()) {
           auto origCell = mesh->GetCell(iterCellIdxMap->second);
           auto vtkSide = inpSide2vtkSide(
               static_cast<VTKCellType>(origCell->GetCellType()), side.second);
           auto sideCell = origCell->GetCellDimension() == 2
                               ? origCell->GetEdge(vtkSide)
                               : origCell->GetFace(vtkSide);
           auto sideIdx = sideSetPD->InsertNextCell(sideCell->GetCellType(),
                                                    sideCell->GetPointIds());
           entArr->InsertTypedComponent(sideIdx, 0, entTag);
           origCellArr->InsertTuple2(sideIdx, iterCellIdxMap->second, -1);
           cellFaceArr->InsertTuple2(sideIdx, vtkSide, -1);
           outSurface.emplace(sideIdx);
         }
       }
 #ifndef HAVE_GMSH
       ++entTag;
 #endif
     }
     sideSet = {sideSetPD, entArr, origCellArr, cellFaceArr};
   }
   return {{mesh, std::move(geoName), std::move(linkName), sideSet},
           {std::move(outElSets), std::move(outNSets), std::move(outSurfaces)}};
 }
mergeGeoMesh()
void NEM::MSH::geoMeshBase::mergeGeoMesh (geoMeshBase * otherGeoMesh) virtual inherited
Deletes the data from the new geoMesh pointer
Parameters
otherGeoMesh A new geoMesh data to merge
Definition at line 113 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, NEM::MSH::geoMeshBase::GeoMesh::mesh, NEM::MSH::New(), and NEM::MSH::geoMeshBase::resetNative().
{
   vtkSmartPointer<vtkAppendFilter> appendFilter =
       vtkSmartPointer<vtkAppendFilter>::New();
   appendFilter->AddInputData(_geoMesh.mesh);
   appendFilter->AddInputData(otherGeoMesh->_geoMesh.mesh);
   appendFilter->MergePointsOn();
   appendFilter->Update();
   _geoMesh.mesh = appendFilter->GetOutput();
   otherGeoMesh->_geoMesh = {
       vtkSmartPointer<vtkUnstructuredGrid>::New(), {}, {}, {}};
   otherGeoMesh->resetNative();
 }
New()
static inpGeoMesh* NEM::MSH::inpGeoMesh::New () static
Referenced by NEM::MSH::New(), and NEM::SRV::srvBase::RequestDataObject().
Read()
static inpGeoMesh* NEM::MSH::inpGeoMesh::Read (const std::string & fileName) static
Referenced by NEM::MSH::Read().
reconstructGeo()
void NEM::MSH::inpGeoMesh::reconstructGeo () override protected virtual
Sets geometry, link, and side set. Does not alter the mesh.
Reimplemented from NEM::MSH::geoMeshBase.
Definition at line 673 of file inpGeoMesh.C.
References NEM::MSH::geoMeshBase::reconstructGeo(), and resetNative().
{
   this->geoMeshBase::reconstructGeo();
   this->resetNative();
 }
report()
void NEM::MSH::geoMeshBase::report (std::ostream & out) const pure virtual inherited
Parameters
out stream
Implemented in NEM::MSH::oshGeoMesh, NEM::MSH::exoGeoMesh, NEM::MSH::foamGeoMesh, NEM::MSH::gmshGeoMesh, and NEM::MSH::vtkGeoMesh.
Definition at line 97 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::getGeoMesh(), mesh, and NEM::MSH::geoMeshBase::GeoMesh::mesh.
Referenced by inpGeoMesh(), NEM::MSH::mesh_(), NEM::MSH::vtkGeoMesh::report(), NEM::MSH::gmshGeoMesh::report(), NEM::MSH::foamGeoMesh::report(), NEM::MSH::exoGeoMesh::report(), and NEM::MSH::oshGeoMesh::report().
{
   out << this->GetClassName() << ":\n";
   auto mesh = getGeoMesh().mesh;
   out << "Nodes:\t" << mesh->GetNumberOfPoints() << '\n';
   out << "Elements:\t" << mesh->GetNumberOfCells() << '\n';
 }
resetNative()
void NEM::MSH::inpGeoMesh::resetNative () override private virtual
Implements NEM::MSH::geoMeshBase.
Definition at line 678 of file inpGeoMesh.C.
References NEM::MSH::inpGeoMesh::InpSets::elSets, NEM::MSH::geoMeshBase::getGeoMesh(), inpSets_, NEM::MSH::geoMeshBase::GeoMesh::mesh, NEM::MSH::inpGeoMesh::InpSets::nodeSets, NEM::MSH::geoMeshBase::SideSet::sides, NEM::MSH::geoMeshBase::GeoMesh::sideSet, and NEM::MSH::inpGeoMesh::InpSets::surfaces.
Referenced by reconstructGeo().
{
   this->inpSets_.nodeSets.clear();
   this->inpSets_.elSets.clear();
   this->inpSets_.surfaces.clear();
   // Default behavior:
   // Convert mesh entities to element sets and mesh physical groups to element
   // sets and node sets
   // Convert sideSet physical groups to surfaces and node sets
   auto gm = getGeoMesh();
 #ifdef HAVE_GMSH
   if (!gm.geo.empty()) {
     gmsh::model::setCurrent(gm.geo);
     if (!gm.link.empty() && gm.mesh->GetNumberOfCells() > 0) {
       eachGmshPhyGroup(
           gm.mesh, gm.mesh->GetCellData()->GetArray(gm.link.c_str()),
           gm.mesh->GetCell(0)->GetCellDimension(),
           [this](const std::string &phyGroup, vtkIdType cellIdx) {
             this->inpSets_.elSets[phyGroup].emplace(cellIdx);
             auto cell = this->getGeoMesh().mesh->GetCell(cellIdx);
             for (vtkIdType i = 0; i < cell->GetNumberOfPoints(); ++i) {
               this->inpSets_.nodeSets[phyGroup].emplace(cell->GetPointId(i));
             }
           });
     }
     if (gm.sideSet.sides && gm.sideSet.sides->GetNumberOfCells() > 0) {
       gm.findSide2OrigCell();
       eachGmshPhyGroup(
           gm.sideSet.sides, gm.sideSet.getGeoEntArr(),
           gm.sideSet.sides->GetCell(0)->GetCellDimension(),
           [this](const std::string &phyGroup, vtkIdType cellIdx) {
             this->inpSets_.surfaces[phyGroup].emplace(cellIdx);
             auto cell = this->getGeoMesh().sideSet.sides->GetCell(cellIdx);
             for (vtkIdType i = 0; i < cell->GetNumberOfPoints(); ++i) {
               this->inpSets_.nodeSets[phyGroup].emplace(cell->GetPointId(i));
             }
           });
     }
   }
 #endif
 }
setAngleThreshold()
void NEM::MSH::geoMeshBase::setAngleThreshold (double angleThreshold) inline inherited
Parameters
angleThreshold (in radians)
Definition at line 176 of file geoMeshBase.H.
{
     _angleThreshold = angleThreshold;
   }
setCellDataArray()
int NEM::MSH::geoMeshBase::setCellDataArray (vtkAbstractArray * array) inline protected inherited
Parameters
array array pointer
Returns
array index
Definition at line 473 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetCellData()->AddArray(array);
   }
setFieldDataArray()
int NEM::MSH::geoMeshBase::setFieldDataArray (vtkAbstractArray * array) inline protected inherited
Parameters
array array pointer
Returns
array index
Definition at line 481 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetFieldData()->AddArray(array);
   }
setGeoEntArrayName()
void NEM::MSH::geoMeshBase::setGeoEntArrayName (const std::string & geoEntArrayName) inline inherited
Parameters
geoEntArrayName name of geometric entities array
Definition at line 162 of file geoMeshBase.H.
{
     auto a = _geoMesh.mesh->GetCellData()->GetArray(_geoMesh.link.c_str());
     if (a) a->SetName(geoEntArrayName.c_str());
     _geoMesh.link = geoEntArrayName;
   }
setGeoMesh()
void NEM::MSH::geoMeshBase::setGeoMesh (const geoMeshBase::GeoMesh & geoMesh) inline protected inherited
Parameters
geoMesh a mesh and geometry
Definition at line 538 of file geoMeshBase.H.
References NEM::MSH::geoMeshBase::GeoMesh::mesh, NEM::MSH::geoMeshBase::SideSet::sides, and NEM::MSH::geoMeshBase::GeoMesh::sideSet.
Referenced by NEM::MSH::exoGeoMesh::addCellsToBlock(), NEM::MSH::exoGeoMesh::addElemBlock(), NEM::MSH::exoGeoMesh::addSideSet(), NEM::MSH::exoGeoMesh::reassignCells(), NEM::MSH::exoGeoMesh::reconstructGeo(), NEM::MSH::gmshGeoMesh::resetNative(), NEM::MSH::exoGeoMesh::resetNative(), NEM::MSH::exoGeoMesh::scaleNodes(), NEM::MSH::foamGeoMesh::setFoamMesh(), NEM::MSH::oshGeoMesh::setOshMesh(), NEM::MSH::smeshGeoMesh::setSMeshMesh(), NEM::MSH::vtkGeoMesh::setVtkMesh(), NEM::MSH::exoGeoMesh::stitch(), NEM::MSH::oshGeoMesh::takeGeoMesh(), and NEM::MSH::exoGeoMesh::takeGeoMesh().
{
     assert(geoMesh.mesh->GetNumberOfCells() == 0 ||
            geoMesh.mesh->GetNumberOfPoints() == 0 ||
            geoMesh.sideSet.sides == nullptr ||
            geoMesh.sideSet.sides->GetPoints() == geoMesh.mesh->GetPoints());
     _geoMesh = geoMesh;
   }
setPointDataArray()
int NEM::MSH::geoMeshBase::setPointDataArray (vtkAbstractArray * array) inline protected inherited
Parameters
array array pointer
Returns
array index
Definition at line 465 of file geoMeshBase.H.
{
     return _geoMesh.mesh->GetPointData()->AddArray(array);
   }
takeGeoMesh()
void NEM::MSH::geoMeshBase::takeGeoMesh (geoMeshBase * otherGeoMesh) virtual inherited
Note that otherGeoMesh will be left with an empty mesh.
Parameters
otherGeoMesh other geoMeshBase object; mesh will be left empty
Reimplemented in NEM::MSH::exoGeoMesh, and NEM::MSH::oshGeoMesh.
Definition at line 104 of file geoMeshBase.C.
References NEM::MSH::geoMeshBase::_geoMesh, NEM::MSH::New(), and NEM::MSH::geoMeshBase::resetNative().
Referenced by NEM::MSH::oshGeoMesh::takeGeoMesh(), and NEM::MSH::exoGeoMesh::takeGeoMesh().
{
   _geoMesh = std::move(otherGeoMesh->_geoMesh);
   otherGeoMesh->_geoMesh = {
       vtkSmartPointer<vtkUnstructuredGrid>::New(), {}, {}, {}};
   otherGeoMesh->resetNative();
   resetNative();
 }
unsetCellDataArray() [1/2]
void NEM::MSH::geoMeshBase::unsetCellDataArray (int arrayIdx) inline protected inherited
Parameters
arrayIdx array index
Definition at line 503 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellData()->RemoveArray(arrayIdx);
   }
unsetCellDataArray() [2/2]
void NEM::MSH::geoMeshBase::unsetCellDataArray (const std::string & arrayName) inline protected inherited
Parameters
arrayName array name
Definition at line 510 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetCellData()->RemoveArray(arrayName.c_str());
   }
unsetFieldDataArray() [1/2]
void NEM::MSH::geoMeshBase::unsetFieldDataArray (int arrayIdx) inline protected inherited
Parameters
arrayIdx array index
Definition at line 517 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetFieldData()->RemoveArray(arrayIdx);
   }
unsetFieldDataArray() [2/2]
void NEM::MSH::geoMeshBase::unsetFieldDataArray (const std::string & arrayName) inline protected inherited
Parameters
arrayName array name
Definition at line 524 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetFieldData()->RemoveArray(arrayName.c_str());
   }
unsetPointDataArray() [1/2]
void NEM::MSH::geoMeshBase::unsetPointDataArray (int arrayIdx) inline protected inherited
Parameters
arrayIdx array index
Definition at line 489 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetPointData()->RemoveArray(arrayIdx);
   }
unsetPointDataArray() [2/2]
void NEM::MSH::geoMeshBase::unsetPointDataArray (const std::string & arrayName) inline protected inherited
Parameters
arrayName array name
Definition at line 496 of file geoMeshBase.H.
{
     _geoMesh.mesh->GetPointData()->RemoveArray(arrayName.c_str());
   }
write()
virtual void NEM::MSH::geoMeshBase::write (const std::string & fileName) pure virtual inherited
Parameters
fileName file name
Implemented in NEM::MSH::oshGeoMesh, NEM::MSH::exoGeoMesh, NEM::MSH::foamGeoMesh, NEM::MSH::gmshGeoMesh, and NEM::MSH::vtkGeoMesh.
Referenced by inpGeoMesh(), and NEM::MSH::mesh_().
Member Data Documentation
GEO_ENT_DEFAULT_NAME
constexpr auto NEM::MSH::geoMeshBase::GEO_ENT_DEFAULT_NAME = "GeoEnt" static protected inherited
Definition at line 446 of file geoMeshBase.H.
Referenced by NEM::MSH::gmshGeoMesh::gmsh2GM(), inp2GM(), NEM::MSH::oshGeoMesh::osh2GM(), NEM::MSH::exoGeoMesh::reconstructGeo(), NEM::MSH::geoMeshBase::reconstructGeo(), and NEM::MSH::gmshGeoMesh::resetNative().
inpSets_
InpSets NEM::MSH::inpGeoMesh::inpSets_ private
Definition at line 96 of file inpGeoMesh.H.
Referenced by inpGeoMesh(), and resetNative().
The documentation for this class was generated from the following files:
inpGeoMesh.H
inpGeoMesh.C