NEMoSys: NEM::GEO::convexContainer Class Reference
NEM::GEO::convexContainer Class Reference
An implementation of convex container object for point The class implements methods to generate a convex hull for a point cloud, perform point location, and output to STL format.
Detailed Description
Note
Only use for convex objects.
Definition at line 113 of file convexContainer.H.
Public Member Functions
convexContainer ()
default constructor
convexContainer (std::vector< std::vector< double > > &verts)
construct from a vector point coordinates
convexContainer (std::vector< quickhull::Vector3< double > > &verts)
virtual ~convexContainer ()
virtual void setVertex (std::vector< std::vector< double > > &verts)
re-/setting vertice coordinates
virtual void computeConvexHull ()
calculating the convex hull
bool isInConvexPoly (NEM::MTH::Vector const &p)
check for point containment
bool isInConvexPoly (const std::vector< double > &p)
void toSTL (std::string file_name) const
generate STL triangulation from the convex hull
Private Attributes
bool _isReady
std::vector< quickhull::Vector3< double > > vrts
quickhull::QuickHull< double > * qHull
std::vector< Face > fv
Constructor & Destructor Documentation
convexContainer() [1/3]
NEM::GEO::convexContainer::convexContainer ()
Definition at line 38 of file convexContainer.C.
                                 :
     _isReady(false)
 {}
convexContainer() [2/3]
NEM::GEO::convexContainer::convexContainer (std::vector< std::vector< double > > & verts)
Parameters
verts vector of vector of doubles of point coordinats
Definition at line 43 of file convexContainer.C.
References setVertex().
 {
     // deep copying
     setVertex(inVrts);
 }
convexContainer() [3/3]
NEM::GEO::convexContainer::convexContainer (std::vector< quickhull::Vector3< double > > & verts)
Definition at line 49 of file convexContainer.C.
References vrts.
 {
     // deep copying
     for (auto itr=inVrts.begin(); itr!=inVrts.end(); itr++)
         vrts.emplace_back(*itr);
 }
~convexContainer()
virtual NEM::GEO::convexContainer::~convexContainer () inline virtual
Definition at line 127 of file convexContainer.H.
 {};
Member Function Documentation
computeConvexHull()
void NEM::GEO::convexContainer::computeConvexHull () virtual
Definition at line 63 of file convexContainer.C.
References _isReady, fv, qHull, NEM::GEO::Face::v, vrts, NEM::MTH::Vector::x, NEM::MTH::Vector::y, and NEM::MTH::Vector::z.
Referenced by isInConvexPoly().
 {
     // computes/re-computes convex hull of the verices
     std::vector<size_t> indxBuf;
     quickhull::VertexDataSource<double> vrtBuf;
     qHull = new quickhull::QuickHull<double>();
     auto hull = qHull->getConvexHull(vrts, false, false, 1.e-14);
     indxBuf = hull.getIndexBuffer();
     vrtBuf = hull.getVertexBuffer();
     // converting to face-vector format
     //std::cout << "Size of index buffer = "
     //    << indxBuf.size() << std::endl;
     // saving to vf
     for (int it=0; it<indxBuf.size(); it+=3)
     {
         Face f;
         for (int idx=0; idx<3; idx++)
         {
             NEM::MTH::Vector pnt;
             pnt.x = (vrtBuf[indxBuf[it+idx]]).x;
             pnt.y = (vrtBuf[indxBuf[it+idx]]).y;
             pnt.z = (vrtBuf[indxBuf[it+idx]]).z;
             f.v.push_back(pnt);
         }
         fv.push_back(f);
     }
     _isReady = true;
 }
isInConvexPoly() [1/2]
bool NEM::GEO::convexContainer::isInConvexPoly (NEM::MTH::Vector const & p)
Parameters
p vector of coordinates of the point
Definition at line 96 of file convexContainer.C.
References _isReady, computeConvexHull(), NEM::MTH::Vector::dot(), fv, and NEM::MTH::Vector::norm().
Referenced by isInConvexPoly().
{
     // check readiness
     if (!_isReady)
         computeConvexHull();
     // looping through faces
     for (Face const& f : fv) {
         NEM::MTH::Vector p2f = f.v[0] - p;         // f.v[0] is an arbitrary point on f
         double d = p2f.dot(f.normal());
         d /= p2f.norm();                 // for numeric stability
         constexpr double bound = -1e-15; // use 1e15 to exclude boundaries
         if (d < bound)
           return false;
     }
     return true;
 }
isInConvexPoly() [2/2]
bool NEM::GEO::convexContainer::isInConvexPoly (const std::vector< double > & p)
Definition at line 114 of file convexContainer.C.
References isInConvexPoly(), NEM::MTH::Vector::x, NEM::MTH::Vector::y, and NEM::MTH::Vector::z.
{
     if (p.size() != 3)
         throw;
     NEM::MTH::Vector pnt;
     pnt.x = p[0];
     pnt.y = p[1];
     pnt.z = p[2];
     return(isInConvexPoly(pnt));
 }
setVertex()
void NEM::GEO::convexContainer::setVertex (std::vector< std::vector< double > > & verts) virtual
Parameters
verts vector of vector of doubles of point coordinats
Definition at line 56 of file convexContainer.C.
References vrts.
Referenced by convexContainer().
 {
     // deep copying
     for (auto itr=inVrts.begin(); itr!=inVrts.end(); itr++)
         vrts.emplace_back((*itr)[0], (*itr)[1], (*itr)[2]);
 }
toSTL()
void NEM::GEO::convexContainer::toSTL (std::string file_name) const
Parameters
file_name full path to the output STL file
Definition at line 124 of file convexContainer.C.
References fv, NEM::MTH::Vector::x, NEM::MTH::Vector::y, and NEM::MTH::Vector::z.
{
     //ascii file
     std::ofstream myfile;
     myfile.open((file_name + ".stl").c_str(),  std::ios::out | std::ios::binary);
     myfile << "solid "
            << file_name
            << "\n";
     //write down every triangle
     for (auto it = fv.begin(); it!=fv.end(); it++){
         //normal vector coordinates
         NEM::MTH::Vector n = it->normal();
         myfile << "facet normal ";
         myfile << n.x << " " << n.y << " " << n.z << "\n";
         myfile << "\touter loop\n";
         //vertex coordinates
         for (int iv=0; iv<3; iv++)
         {
             myfile << "\t\tvertex "
                    << (it->v[iv]).x << " "
                    << (it->v[iv]).y << " "
                    << (it->v[iv]).z << "\n";
         }
         myfile << "\tendloop\n";
         myfile << "endfacet\n";
     }
     myfile << "endsolid " << file_name << "\n";
     myfile.close();
 }
Member Data Documentation
_isReady
bool NEM::GEO::convexContainer::_isReady private
Definition at line 153 of file convexContainer.H.
Referenced by computeConvexHull(), and isInConvexPoly().
fv
std::vector<Face> NEM::GEO::convexContainer::fv private
Definition at line 156 of file convexContainer.H.
Referenced by computeConvexHull(), isInConvexPoly(), and toSTL().
qHull
quickhull::QuickHull<double>* NEM::GEO::convexContainer::qHull private
Definition at line 155 of file convexContainer.H.
Referenced by computeConvexHull().
vrts
std::vector<quickhull::Vector3<double> > NEM::GEO::convexContainer::vrts private
Definition at line 154 of file convexContainer.H.
Referenced by computeConvexHull(), convexContainer(), and setVertex().
The documentation for this class was generated from the following files:
convexContainer.H
convexContainer.C