NEMoSys: NEM::SRV::NucMeshSrv Class Reference
NEM::SRV::NucMeshSrv Class Reference abstract
Detailed Description
Definition at line 92 of file NucMeshSrv.H.
Public Member Functions
void SetConfiguration (const NucMeshConf &configuration)
const NucMeshConf & GetConfiguration () const
vtkTypeMacro(NucMeshSrv, srvBase) protected int FillOutputPortInformation (int port, vtkInformation *info) override
NucMeshSrv ()
vtkAbstractTypeMacro(srvBase, vtkAlgorithm) public NEM::MSH::geoMeshBase * GetOutput ()
Get the output GeoMeshBase for a port on this algorithm.
NEM::MSH::geoMeshBase * GetOutput (int)
Static Public Member Functions
static NucMeshSrv * New ()
Public Attributes
NucMeshConf conf_
Protected Member Functions
virtual int RequestInformation (vtkInformation *request, vtkInformationVector **inputVector, vtkInformationVector *outputVector)
virtual int RequestDataObject (vtkInformation *request, vtkInformationVector **inputVector, vtkInformationVector *outputVector)
This is called by the superclass.
virtual int RequestData (vtkInformation *request, vtkInformationVector **inputVector, vtkInformationVector *outputVector)=0
This is called by the superclass.
virtual int RequestUpdateExtent (vtkInformation *request, vtkInformationVector **inputVector, vtkInformationVector *outputVector)
This is called by the superclass.
Inherits NEM::SRV::srvBase.
Constructor & Destructor Documentation
NucMeshSrv()
NEM::SRV::NucMeshSrv::NucMeshSrv ()
Member Function Documentation
FillOutputPortInformation()
int NEM::SRV::NucMeshSrv::FillOutputPortInformation (int port, vtkInformation * info) override
Definition at line 64 of file NucMeshSrv.C.
References NEM::NUCMESH::NucMeshGeo::computeMesh(), conf_, NEM::MSH::containerWrapper(), NEM::SRV::NucMeshConf::extrudeSteps, NEM::SRV::NucMeshConf::generator, NEM::SRV::NucMeshConf::geometryAndMesh, NEM::NUCMESH::ShapeBase::mergeGeo(), mesh, NEM::SRV::srvBase::RequestData(), and NEM::MSH::smeshGeoMesh::setSMeshMesh().
{
   if (port == 0) {
     info->Set(vtkDataObject::DATA_TYPE_NAME(), "smeshGeoMesh");
     return 1;
   } else {
     return 0;
   }
 }
GetConfiguration()
const NucMeshConf & NEM::SRV::NucMeshSrv::GetConfiguration () const
Definition at line 62 of file NucMeshSrv.C.
References conf_.
 { return conf_; }
GetOutput() [1/2]
NEM::MSH::geoMeshBase * NEM::SRV::srvBase::GetOutput () inherited
Definition at line 104 of file srvBase.C.
 { return this->GetOutput(0); }
GetOutput() [2/2]
NEM::MSH::geoMeshBase * NEM::SRV::srvBase::GetOutput (int port) inherited
Definition at line 106 of file srvBase.C.
{
   return NEM::MSH::geoMeshBase::SafeDownCast(this->GetOutputDataObject(port));
 }
New()
static NucMeshSrv* NEM::SRV::NucMeshSrv::New () static
RequestData()
virtual int NEM::SRV::srvBase::RequestData (vtkInformation * request, vtkInformationVector ** inputVector, vtkInformationVector * outputVector) protected pure virtual inherited
This is the method you should override.
Implemented in NEM::SRV::omegahRefineSrv.
Referenced by FillOutputPortInformation(), and NEM::SRV::srvBase::~srvBase().
RequestDataObject()
int NEM::SRV::srvBase::RequestDataObject (vtkInformation * request, vtkInformationVector ** inputVector, vtkInformationVector * outputVector) protected virtual inherited
Definition at line 110 of file srvBase.C.
References NEM::MSH::gmshGeoMesh::New(), NEM::MSH::vtkGeoMesh::New(), NEM::MSH::smeshGeoMesh::New(), NEM::MSH::foamGeoMesh::New(), NEM::MSH::exoGeoMesh::New(), NEM::MSH::inpGeoMesh::New(), and NEM::MSH::oshGeoMesh::New().
Referenced by NEM::SRV::srvBase::~srvBase().
{
   for (int i = 0; i < outputVector->GetNumberOfInformationObjects(); ++i) {
     auto outInfo = outputVector->GetInformationObject(i);
     auto outAlgInfo = this->GetOutputPortInformation(i);
     if (!outAlgInfo->Has(vtkDataObject::DATA_TYPE_NAME())) {
       return 0;
     }
     std::string typeName = outAlgInfo->Get(vtkDataObject::DATA_TYPE_NAME());
     MSH::geoMeshBase *output = nullptr;
     if (typeName == "vtkGeoMesh") {
       output = MSH::vtkGeoMesh::New();
     } else if (typeName == "gmshGeoMesh") {
 #ifdef HAVE_GMSH
       output = MSH::gmshGeoMesh::New();
 #endif
     } else if (typeName == "oshGeoMesh") {
       output = MSH::oshGeoMesh::New();
     } else if (typeName == "exoGeoMesh") {
       output = MSH::exoGeoMesh::New();
     } else if (typeName == "inpGeoMesh") {
       output = MSH::inpGeoMesh::New();
     } else if (typeName == "foamGeoMesh") {
 #ifdef HAVE_CFMSH
       output = MSH::foamGeoMesh::New();
 #endif
     } else if (typeName == "smeshGeoMesh") {
 #ifdef HAVE_OCC
       output = MSH::smeshGeoMesh::New();
 #endif
     } else if (typeName == "geoMeshBase") {
       if (i < this->GetNumberOfInputPorts() &&
           inputVector[i]->GetNumberOfInformationObjects() > 0) {
         auto inObj = inputVector[i]
                 ->GetInformationObject(0)
                 ->Get(vtkDataObject::DATA_OBJECT());
         if (inObj) {
           output = MSH::geoMeshBase::SafeDownCast(inObj->NewInstance());
         }
       }
     }
     if (!output) {
       return 0;
     }
     outInfo->Set(vtkDataObject::DATA_OBJECT(), output);
     output->FastDelete();
     this->GetOutputPortInformation(i)->Set(
         vtkDataObject::DATA_EXTENT_TYPE(), output->GetExtentType());
   }
   return 1;
 }
RequestInformation()
int NEM::SRV::srvBase::RequestInformation (vtkInformation * request, vtkInformationVector ** inputVector, vtkInformationVector * outputVector) protected virtual inherited
Definition at line 97 of file srvBase.C.
Referenced by NEM::SRV::srvBase::~srvBase().
{
   // do nothing let subclasses handle it
   return 1;
 }
RequestUpdateExtent()
int NEM::SRV::srvBase::RequestUpdateExtent (vtkInformation * request, vtkInformationVector ** inputVector, vtkInformationVector * outputVector) protected virtual inherited
Definition at line 163 of file srvBase.C.
Referenced by NEM::SRV::srvBase::~srvBase().
{
   int numInputPorts = this->GetNumberOfInputPorts();
   for (int i = 0; i < numInputPorts; i++) {
     int numInputConnections = this->GetNumberOfInputConnections(i);
     for (int j = 0; j < numInputConnections; j++) {
       vtkInformation *inputInfo = inputVector[i]->GetInformationObject(j);
       inputInfo->Set(vtkStreamingDemandDrivenPipeline::EXACT_EXTENT(), 1);
     }
   }
   return 1;
 }
SetConfiguration()
void NEM::SRV::NucMeshSrv::SetConfiguration (const NucMeshConf & configuration)
Definition at line 57 of file NucMeshSrv.C.
References conf_.
{
   conf_ = configuration;
   this->Modified();
 }
Member Data Documentation
conf_
NucMeshConf NEM::SRV::NucMeshSrv::conf_
Definition at line 104 of file NucMeshSrv.H.
Referenced by FillOutputPortInformation(), GetConfiguration(), and SetConfiguration().
The documentation for this class was generated from the following files:
NucMeshSrv.H
NucMeshSrv.C