NEMoSys: meshStitcher Class Reference
meshStitcher Class Reference
Detailed Description
Definition at line 48 of file meshStitcher.H.
Public Member Functions
meshStitcher (std::vector< std::string > cgFileNames, bool surf)
~meshStitcher ()=default
meshStitcher (const meshStitcher &that)=delete
meshStitcher & operator= (const meshStitcher &that)=delete
std::shared_ptr< cgnsAnalyzer > getStitchedCGNS () const
std::shared_ptr< meshBase > getStitchedMB () const
Private Member Functions
void initSurfCgObj ()
void initVolCgObj ()
Private Attributes
const std::vector< std::string > cgFileNames
std::vector< std::shared_ptr< cgnsAnalyzer > > partitions
std::shared_ptr< meshBase > stitchedMesh
std::shared_ptr< rocstarCgns > cgObj
Constructor & Destructor Documentation
meshStitcher() [1/2]
meshStitcher::meshStitcher (std::vector< std::string > cgFileNames, bool surf)
Definition at line 36 of file meshStitcher.C.
References cgFileNames, initSurfCgObj(), and initVolCgObj().
     : cgFileNames(std::move(_cgFileNames)),
       stitchedMesh(nullptr),
       cgObj(nullptr) {
   if (!cgFileNames.empty()) {
     if (surf)
       initSurfCgObj();
     else
       initVolCgObj();
   }
 }
~meshStitcher()
meshStitcher::~meshStitcher () default
meshStitcher() [2/2]
meshStitcher::meshStitcher (const meshStitcher & that) delete
Member Function Documentation
getStitchedCGNS()
std::shared_ptr< cgnsAnalyzer > meshStitcher::getStitchedCGNS () const
Definition at line 176 of file meshStitcher.C.
References cgObj, and partitions.
{
   if (!partitions.empty())
     return partitions[0];
   else if (cgObj)
     return cgObj;
   else {
     std::cerr << "No stitched mesh to return!" << std::endl;
     exit(1);
   }
 }
getStitchedMB()
std::shared_ptr< meshBase > meshStitcher::getStitchedMB () const
Definition at line 167 of file meshStitcher.C.
References stitchedMesh.
{
   if (stitchedMesh)
     return stitchedMesh;
   else {
     std::cerr << "No stitched mesh to return!" << std::endl;
     exit(1);
   }
 }
initSurfCgObj()
void meshStitcher::initSurfCgObj () private
Definition at line 122 of file meshStitcher.C.
References cgFileNames, cgObj, meshBase::CreateShared(), NODAL, stitchedMesh, and nemAux::trim_fname().
Referenced by meshStitcher().
{
   cgObj = std::make_shared<rocstarCgns>(cgFileNames);
   // different read for burn files
   if (cgFileNames[0].find("burn") != std::string::npos)
     cgObj->setBurnBool(true);
   cgObj->loadCgSeries();
   cgObj->stitchGroup();
   // cgObj->closeCG();
   std::cout << "Surface mesh stitched successfully." << std::endl;
   std::cout << "Exporting stitched mesh to VTK format." << std::endl;
   std::string newname(cgFileNames[0]);
   std::size_t pos = newname.find_last_of('/');
   newname = newname.substr(pos + 1);
   newname = nemAux::trim_fname(newname, "stitched.vtu");
   stitchedMesh = meshBase::CreateShared(cgObj->getVTKMesh(), newname);
   std::cout << "Transferring physical quantities to vtk mesh." << std::endl;
   // figure out what exists on the stitched grid
   int outNData, outNDim;
   std::vector<std::string> slnNameList;
   std::vector<std::string> appSlnNameList;
   cgObj->getSolutionDataNames(slnNameList);
   cgObj->getAppendedSolutionDataName(appSlnNameList);
   slnNameList.insert(slnNameList.end(), appSlnNameList.begin(),
                      appSlnNameList.end());
   // write all data into vtk file
   for (auto is = slnNameList.begin(); is < slnNameList.end(); is++) {
     std::vector<double> physData;
     cgObj->getSolutionDataStitched(*is, physData, outNData, outNDim);
     solution_type_t dt = cgObj->getSolutionDataObj(*is)->getDataType();
     if (dt == solution_type_t::NODAL) {
       std::cout << "Embedding nodal " << *is << std::endl;
       stitchedMesh->setPointDataArray((*is).c_str(), physData);
     } else {
       // gs field is 'weird' in irocstar files- we don't write it back
       // if (!(*is).compare("gs"))
       if (*is == "mdot_old") { continue; }
       std::cout << "Embedding cell-based " << *is << std::endl;
       stitchedMesh->setCellDataArray((*is).c_str(), physData);
     }
   }
   stitchedMesh->report();
   // TODO: expensive IO, need to be refactored
   stitchedMesh->write();
 }
initVolCgObj()
void meshStitcher::initVolCgObj () private
Definition at line 48 of file meshStitcher.C.
References cgFileNames, meshBase::CreateShared(), ELEMENTAL, NODAL, partitions, stitchedMesh, and nemAux::trim_fname().
Referenced by meshStitcher().
{
   partitions.resize(cgFileNames.size(), nullptr);
   for (int iCg = 0; iCg < cgFileNames.size(); ++iCg) {
     partitions[iCg] = std::make_shared<cgnsAnalyzer>(cgFileNames[iCg]);
     partitions[iCg]->loadGrid(1);
     // defining partition flags
     std::vector<double> slnData(partitions[iCg]->getNElement(), iCg);
     // append partition number data if not already existing
     bool exists = false;
     std::vector<std::string> slnNamelist;
     partitions[iCg]->getSolutionDataNames(slnNamelist);
     for (const auto &in : slnNamelist)
       if (in == "partitionOld") {
         exists = true;
         break;
       }
     if (!exists)
       partitions[iCg]->appendSolutionData("partitionOld", slnData,
                                           solution_type_t::ELEMENTAL,
                                           partitions[iCg]->getNElement(), 1);
     // stitching new partitions to partition 0
     // close partition CGNS file to avoid clutter
     // MS: writing ghost mesh before closing
     // std::vector<std::string> secNames;
     // partitions[iCg]->getSectionNames(secNames);
     // auto its = std::find(secNames.begin(), secNames.end(), ":T4:virtual");
     // if (its != secNames.end())
     //  meshBase::Create(partitions[iCg]->getSectionMesh(*its),
     //                   "_virtual_" + nemAux::find_name(cgFileNames[iCg]) +
     //                   ".vtu")->write();
     // End of ghost mesh
     if (iCg) {
       partitions[0]->stitchMesh(partitions[iCg].get(), true);
       partitions[iCg]->closeCG();
     }
   }
   std::cout << "Meshes stitched successfully." << std::endl;
   std::cout << "Exporting stitched mesh to VTK format." << std::endl;
   std::string newname(cgFileNames[0]);
   std::size_t pos = newname.find_last_of('/');
   newname = newname.substr(pos + 1);
   newname = nemAux::trim_fname(newname, "stitched.vtu");
   stitchedMesh = meshBase::CreateShared(partitions[0]->getVTKMesh(), newname);
   std::cout << "Transferring physical quantities to vtk mesh." << std::endl;
   // figure out what is existing on the stitched grid
   int outNData, outNDim;
   std::vector<std::string> slnNameList;
   std::vector<std::string> appSlnNameList;
   partitions[0]->getSolutionDataNames(slnNameList);
   partitions[0]->getAppendedSolutionDataName(appSlnNameList);
   slnNameList.insert(slnNameList.end(), appSlnNameList.begin(),
                      appSlnNameList.end());
   // write all data into vtk file
   for (auto is = slnNameList.begin(); is < slnNameList.end(); is++) {
     std::vector<double> physData;
     partitions[0]->getSolutionDataStitched(*is, physData, outNData, outNDim);
     solution_type_t dt = partitions[0]->getSolutionDataObj(*is)->getDataType();
     if (dt == solution_type_t::NODAL) {
       std::cout << "Embedding nodal " << *is << std::endl;
       stitchedMesh->setPointDataArray((*is).c_str(), physData);
     } else {
       // gs field is 'weird' in irocstar files- we don't write it back
       // if (!(*is).compare("gs"))
       //  continue;
       std::cout << "Embedding cell-based " << *is << std::endl;
       stitchedMesh->setCellDataArray((*is).c_str(), physData);
     }
   }
   stitchedMesh->report();
   // TODO: Expensive IO, refactoring needed
   stitchedMesh->write();
 }
operator=()
meshStitcher& meshStitcher::operator= (const meshStitcher & that) delete
Member Data Documentation
cgFileNames
const std::vector<std::string> meshStitcher::cgFileNames private
Definition at line 65 of file meshStitcher.H.
Referenced by initSurfCgObj(), initVolCgObj(), and meshStitcher().
cgObj
std::shared_ptr<rocstarCgns> meshStitcher::cgObj private
Definition at line 71 of file meshStitcher.H.
Referenced by getStitchedCGNS(), and initSurfCgObj().
partitions
std::vector<std::shared_ptr<cgnsAnalyzer> > meshStitcher::partitions private
Definition at line 67 of file meshStitcher.H.
Referenced by getStitchedCGNS(), and initVolCgObj().
stitchedMesh
std::shared_ptr<meshBase> meshStitcher::stitchedMesh private
Definition at line 69 of file meshStitcher.H.
Referenced by getStitchedMB(), initSurfCgObj(), and initVolCgObj().
The documentation for this class was generated from the following files:
meshStitcher.H
meshStitcher.C