NEMoSys: hdf5Reader Class Reference
hdf5Reader Class Reference
Class for reading data from HDF5 files.
Detailed Description
Definition at line 60 of file hdf5Reader.H.
Public Member Functions
hdf5Reader (std::string fname, std::string _outputFname, int _verb=0)
Construct HDF5 reader object.
virtual ~hdf5Reader ()
int openFile ()
Open HDF5 file.
int closeFile ()
Close HDF5 file.
int readTopDataSet (std::string dsetName, std::string &buffer)
Read string data from top level HDF5 DataSet.
int readDataSet (DataSet dset, std::string &buffer)
Read string data from generic HDF5 DataSet.
template<class T >
int readTopDataSet (std::string dsetName, std::vector< T > &buffer)
Read numeric data from top level HDF5 DataSet.
template<class T >
int readDataSet (DataSet dset, std::vector< T > &buffer)
Read numeric data from generic HDF5 DataSet.
int readGroup (std::string groupName, Group &group)
Read existing HDF5 Group.
template<class T >
int readGroupDataSet (std::string dsetName, Group &group, std::vector< T > &buffer)
Read numeric data from HDF5 group.
std::string getFileName ()
Get HDF5 filename.
template<class T >
void flattenBuffer2d (std::vector< std::vector< T >> originalBuffer, std::vector< T > &flatBuffer)
Flatten 2d data buffer.
template<class T >
void unflattenBuffer2d (std::vector< T > flatBuffer, std::vector< std::vector< T >> &originalBuffer)
Unflatten 2d data buffer.
void exportToVTKMesh ()
Export to VTK format.
vtkSmartPointer< vtkDataSet > getVTKMesh ()
Get VTK mesh object.
void exportToMeshBase ()
Export HDF5 mesh to meshBase object.
meshBase * getMeshBase ()
Get meshBase object.
void writeVTK ()
Write mesh to VTK file.
void setFields (meshBase *myMeshBase, std::vector< std::string > dataNames, std::vector< std::vector< double >> data, int pointOrCell)
Set meshBase field data.
void setNumberOfVertices (int numVertices)
Set number of vertices in meshBase.
void setNumberOfElements (int numElements)
Set number of elements in meshBase.
void setNumberOfDimensions (int numDimensions)
Set number of spatial dimensions in meshBase.
void setCoordinates (std::vector< double > xCrd)
Set meshBase 1d coordinate data.
void setCoordinates (std::vector< double > xCrd, std::vector< double > yCrd)
Set meshBase 2d coordinate data.
void setCoordinates (std::vector< double > xCrd, std::vector< double > yCrd, std::vector< double > zCrd)
Set meshBase 3d coordinate data.
void setConnectivities (std::vector< std::map< int, std::vector< int >>> elementConnectivity)
Set meshBase element connectivity table.
void setElementTypes (std::vector< int > vtkElementTypes)
Set VTK element types for each element.
void setElementTypesList (std::vector< int > vtkElementTypesList)
Set list of each unique type of VTK element in mesh.
std::vector< int > getElementConnectivity (int elementId)
Get element connectivity for global element ID.
Protected Attributes
std::string h5FileName
HDF5 filename.
std::string baseH5FileName
base of HDF5 filename
std::string outputFname
VTK output filename.
int verb
verbosity flag
H5File file
HDF5 file object.
vtkSmartPointer< vtkDataSet > vtkMesh
VTK DataSet object.
meshBase * myMeshBase
meshBase object
std::vector< double > xCrd
std::vector< double > yCrd
std::vector< double > zCrd
vector of coordinates
std::vector< std::map< int, std::vector< int > > > elementConnectivity
element connectivity table
int numVertices
number of vertices in mesh
int numElements
number of elements in mesh
int numDimensions
number of spatial dimensions
std::vector< int > vtkElementTypes
vector of VTK element type for each element
std::vector< int > vtkElementTypesList
vector storing list of each unique VTK element type
Inherited by proteusHdf5.
Constructor & Destructor Documentation
hdf5Reader()
hdf5Reader::hdf5Reader (std::string fname, std::string _outputFname, int _verb = 0) inline
Parameters
fname HDF5 filename
_outputFName Filename for VTK output file
_verb Boolean verbosity flag
Definition at line 67 of file hdf5Reader.H.
       :  // Initialization of class variables
         h5FileName(fname),
         outputFname(_outputFname),
         verb(_verb),
         vtkMesh(0) {
     // Parse filename
     std::size_t _loc = h5FileName.find_last_of(".");
     baseH5FileName = h5FileName.substr(0, _loc);
   };
~hdf5Reader()
virtual hdf5Reader::~hdf5Reader () inline virtual
Definition at line 79 of file hdf5Reader.H.
 {};
Member Function Documentation
closeFile()
int hdf5Reader::closeFile ()
Returns
Integer flag: 0 (failure) or 1 (success)
Definition at line 63 of file hdf5Reader.C.
References file, and h5FileName.
Referenced by proteusHdf5::proteusHdf5().
{
   std::cout << "Closing HDF5 file " << h5FileName << std::endl;
   try {
     // Close HDF5 file
     file.close();
   } catch (FileIException error) {
 #if H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 8 && H5_VERS_RELEASE >= 20
     error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 10 && H5_VERS_RELEASE >= 2
     error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 11 && H5_VERS_RELEASE >= 0
       error.printErrorStack();
 #else
     error.printError();
 #endif
     return -1;
   }
   return 0;
 }
exportToMeshBase()
void hdf5Reader::exportToMeshBase ()
Definition at line 313 of file hdf5Reader.C.
References meshBase::Create(), exportToVTKMesh(), myMeshBase, and outputFname.
Referenced by proteusHdf5::proteusHdf5(), and writeVTK().
{
   std::cout << "Exporting hdf5Reader object to meshBase format..." << std::endl;
   if (!vtkMesh) {
     exportToVTKMesh();
   }
   myMeshBase = meshBase::Create(vtkMesh, outputFname);
 }
exportToVTKMesh()
void hdf5Reader::exportToVTKMesh ()
Definition at line 241 of file hdf5Reader.C.
References getElementConnectivity(), NEM::MSH::New(), numDimensions, numElements, numVertices, points, vtkElementTypes, xCrd, yCrd, and zCrd.
Referenced by exportToMeshBase(), getVTKMesh(), and proteusHdf5::proteusHdf5().
{
   std::cout << "Exporting hdf5Reader object to VTK format..." << std::endl;
   if (!vtkMesh) {
     // declare vtk dataset
     auto dataSet_tmp = vtkSmartPointer<vtkUnstructuredGrid>::New();
     // points to be pushed into dataSet
     auto points = vtkSmartPointer<vtkPoints>::New();
     // set double precision points
     points->SetDataTypeToDouble();
     // allocate size for vtk point container
     points->SetNumberOfPoints(numVertices);
     if (numDimensions == 2) {
       for (int i = 0; i < numVertices; ++i) {
         points->SetPoint(i, xCrd[i], yCrd[i], 0.0);
       }
     } else {
       for (int i = 0; i < numVertices; ++i) {
         points->SetPoint(i, xCrd[i], yCrd[i], zCrd[i]);
       }
     }
     // add points to vtk mesh data structure
     std::cout << "    setting VTK point data..." << std::endl;
     dataSet_tmp->SetPoints(points);
     // allocate space for elements
     std::cout << "    allocating memory for elements..." << std::endl;
     dataSet_tmp->Allocate(numElements);
     // add the elements
     std::cout << "    adding VTK elements..." << std::endl;
     for (int i = 0; i < numElements; ++i) {
       auto vtkElmIds = vtkSmartPointer<vtkIdList>::New();
       std::vector<int> elmIds(getElementConnectivity(i));
       vtkElmIds->SetNumberOfIds(elmIds.size());
       for (int j = 0; j < elmIds.size(); ++j) {
         vtkElmIds->SetId(j, elmIds[j] - 0);
       }
       switch (vtkElementTypes[i]) {
 #if VTK_MAJOR_VERSION > 8 || (VTK_MAJOR_VERSION == 8 && VTK_MINOR_VERSION >= 1)
         case VTK_LAGRANGE_QUADRILATERAL:
           dataSet_tmp->InsertNextCell(VTK_LAGRANGE_QUADRILATERAL, vtkElmIds);
           break;
 #endif
         case VTK_QUAD:
           dataSet_tmp->InsertNextCell(VTK_QUAD, vtkElmIds);
           break;
         case VTK_TRIANGLE:
           dataSet_tmp->InsertNextCell(VTK_TRIANGLE, vtkElmIds);
           break;
         default:
           std::cerr << "Unknown element type " << vtkElementTypes[i]
                     << std::endl;
           break;
       }
     }
     // build links - element incidences
     dataSet_tmp->BuildLinks();
     vtkMesh = dataSet_tmp;
   }
 }
flattenBuffer2d()
template<class T > void hdf5Reader::flattenBuffer2d (std::vector< std::vector< T >> originalBuffer, std::vector< T > & flatBuffer) inline
Parameters
originalBuffer Original unflattened data
flatBuffer Output flattened data
Definition at line 241 of file hdf5Reader.H.
{
     // Populate flat buffer
     for (auto bufItr1 = originalBuffer.begin(); bufItr1 != originalBuffer.end();
          bufItr1++) {
       for (auto bufItr2 = (*bufItr1).begin(); bufItr2 != (*bufItr1).end();
            bufItr2++) {
         flatBuffer.push_back(*bufItr2);
       }
     }
   }
getElementConnectivity()
std::vector< int > hdf5Reader::getElementConnectivity (int elementId)
Parameters
elementId Element ID
Returns
Element connectivity table
Definition at line 195 of file hdf5Reader.C.
References elementConnectivity, vtkElementTypes, and vtkElementTypesList.
Referenced by exportToVTKMesh().
{
   int nVerts;
   int connId = -1;
 #if VTK_MAJOR_VERSION > 8 || (VTK_MAJOR_VERSION == 8 && VTK_MINOR_VERSION >= 1)
   if (vtkElementTypes[elementId] == VTK_LAGRANGE_QUADRILATERAL) {
     nVerts = 16;
     auto itr = std::find(vtkElementTypesList.begin(), vtkElementTypesList.end(),
                          VTK_LAGRANGE_QUADRILATERAL);
     if (itr != vtkElementTypesList.end()) {
       connId = distance(vtkElementTypesList.begin(), itr);
     }
   } else if (vtkElementTypes[elementId] == VTK_QUAD)
 #else
   if (vtkElementTypes[elementId] == VTK_QUAD)
 #endif
   {
     nVerts = 4;
     auto itr = std::find(vtkElementTypesList.begin(), vtkElementTypesList.end(),
                          VTK_QUAD);
     if (itr != vtkElementTypesList.end()) {
       connId = distance(vtkElementTypesList.begin(), itr);
     }
   } else if (vtkElementTypes[elementId] == VTK_TRIANGLE) {
     nVerts = 3;
     auto itr = std::find(vtkElementTypesList.begin(), vtkElementTypesList.end(),
                          VTK_TRIANGLE);
     if (itr != vtkElementTypesList.end()) {
       connId = distance(vtkElementTypesList.begin(), itr);
     }
   } else {
     std::cerr << "Element type not supported: " << vtkElementTypes[elementId]
               << std::endl;
     exit(-1);
   }
   if (connId != -1) {
     std::vector<int> subConnectivity(
         elementConnectivity[connId][elementId].begin(),
         elementConnectivity[connId][elementId].begin() + nVerts);
     return subConnectivity;
   } else {
     std::cerr << "Element type " << vtkElementTypes[elementId]
               << " not found in connectivity table" << std::endl;
     exit(-1);
   }
 }
getFileName()
std::string hdf5Reader::getFileName ()
Returns
HDF5 filename
Definition at line 39 of file hdf5Reader.C.
References h5FileName.
 { return h5FileName; }
getMeshBase()
meshBase * hdf5Reader::getMeshBase ()
Returns
meshBase object
Definition at line 321 of file hdf5Reader.C.
References myMeshBase.
Referenced by proteusHdf5::proteusHdf5().
 { return myMeshBase; }
getVTKMesh()
vtkSmartPointer< vtkDataSet > hdf5Reader::getVTKMesh ()
Returns
Pointer to vtkDataSet
Definition at line 304 of file hdf5Reader.C.
References exportToVTKMesh(), and vtkMesh.
{
   if (vtkMesh)
     return vtkMesh;
   else {
     exportToVTKMesh();
     return vtkMesh;
   }
 }
openFile()
int hdf5Reader::openFile ()
Returns
Integer flag: 0 (failure) or 1 (success)
Definition at line 41 of file hdf5Reader.C.
References file, and h5FileName.
Referenced by proteusHdf5::proteusHdf5().
{
   std::cout << "Opening HDF5 file " << h5FileName << std::endl;
   try {
     // Open HDF5 file
     H5std_string h5FileName_(h5FileName);
     file.openFile(h5FileName_, H5F_ACC_RDWR);
   } catch (FileIException error) {
 #if H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 8 && H5_VERS_RELEASE >= 20
     error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 10 && H5_VERS_RELEASE >= 2
     error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 11 && H5_VERS_RELEASE >= 0
       error.printErrorStack();
 #else
     error.printError();
 #endif
     return -1;
   }
   return 0;
 }
readDataSet() [1/2]
int hdf5Reader::readDataSet (DataSet dset, std::string & buffer)
Parameters
dset HDF5 dataset
buffer Buffer into which data is read
Returns
Integer flag: 0 (failure) or 1 (success)
Definition at line 109 of file hdf5Reader.C.
Referenced by readTopDataSet().
{
   try {
     // Get type of data
     DataType dtype = dset.getDataType();
     // Read data
     dset.read(buffer, dtype);
     // Close dataset
     dset.close();
   }
   // catch failure caused by the H5File operations
   catch (DataSetIException error) {
 #if H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 8 && H5_VERS_RELEASE >= 20
     error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 10 && H5_VERS_RELEASE >= 2
     error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 11 && H5_VERS_RELEASE >= 0
       error.printErrorStack();
 #else
     error.printError();
 #endif
     return -1;
   }
   return 0;
 }
readDataSet() [2/2]
template<class T > int hdf5Reader::readDataSet (DataSet dset, std::vector< T > & buffer) inline
Parameters
dset HDF5 dataset
buffer Buffer into which numeric data is read
Returns
Integer flag: 0 (failure) or 1 (success)
Definition at line 148 of file hdf5Reader.H.
{
     try {
       // Get type of data
       DataType dtype = dset.getDataType();
       // Read data
       dset.read(&buffer[0], dtype);
       // Close dataset
       dset.close();
     }
     // catch failure caused by the H5File operations
     catch (DataSetIException error) {
 #if H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 8 && H5_VERS_RELEASE >= 20
       error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 10 && H5_VERS_RELEASE >= 2
       error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 11 && H5_VERS_RELEASE >= 0
       error.printErrorStack();
 #else
       error.printError();
 #endif
       return -1;
     }
     return 0;
   }
readGroup()
int hdf5Reader::readGroup (std::string groupName, Group & group)
Parameters
groupName HDF5 group object name
group HDF5 group object
Returns
Integer flag: 0 (failure) or 1 (success)
Definition at line 135 of file hdf5Reader.C.
References file.
Referenced by proteusHdf5::getBlocks().
{
   try {
     // Open group
     group = Group(file.openGroup(groupName));
   } catch (FileIException error) {
 #if H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 8 && H5_VERS_RELEASE >= 20
     error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 10 && H5_VERS_RELEASE >= 2
     error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 11 && H5_VERS_RELEASE >= 0
       error.printErrorStack();
 #else
     error.printError();
 #endif
     return -1;
   }
   return 0;
 }
readGroupDataSet()
template<class T > int hdf5Reader::readGroupDataSet (std::string dsetName, Group & group, std::vector< T > & buffer) inline
Parameters
dsetName DataSet name
group HDF5 group object
buffer Buffer into which numeric data is read
Returns
Integer flag: 0 (failure) or 1 (success)
Definition at line 190 of file hdf5Reader.H.
Referenced by proteusHdf5::getBlockElementData(), proteusHdf5::getBlockGlobalID(), proteusHdf5::getBlockInfo(), proteusHdf5::getBlockVertexData(), and proteusHdf5::getBlockXYZ().
{
     try {
       // Open dataset
       DataSet dset = group.openDataSet(dsetName);
       // Get type of data
       DataType dtype = dset.getDataType();
       // Read data
       dset.read(&buffer[0], dtype);
       // Close dataset
       dset.close();
     }
     // catch failure caused by the H5File operations
     catch (GroupIException error) {
 #if H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 8 && H5_VERS_RELEASE >= 20
       error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 10 && H5_VERS_RELEASE >= 2
       error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 11 && H5_VERS_RELEASE >= 0
       error.printErrorStack();
 #else
       error.printError();
 #endif
       return -1;
     } catch (DataSetIException error) {
 #if H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 8 && H5_VERS_RELEASE >= 20
       error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 10 && H5_VERS_RELEASE >= 2
       error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 11 && H5_VERS_RELEASE >= 0
       error.printErrorStack();
 #else
       error.printError();
 #endif
       return -1;
     }
     return 0;
   }
readTopDataSet() [1/2]
int hdf5Reader::readTopDataSet (std::string dsetName, std::string & buffer)
Parameters
dsetName Dataset name
buffer Buffer into which string data is read
Returns
Integer flag: 0 (failure) or 1 (success)
Definition at line 85 of file hdf5Reader.C.
References file, and readDataSet().
Referenced by proteusHdf5::getControlInformation(), and proteusHdf5::getVectorNames().
{
   try {
     // Open dataset
     DataSet dset = file.openDataSet(dsetName);
     // Read dataset
     readDataSet(dset, buffer);
   }
   // catch failure caused by the H5File operations
   catch (FileIException error) {
 #if H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 8 && H5_VERS_RELEASE >= 20
     error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 10 && H5_VERS_RELEASE >= 2
     error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 11 && H5_VERS_RELEASE >= 0
       error.printErrorStack();
 #else
     error.printError();
 #endif
     return -1;
   }
   return 0;
 }
readTopDataSet() [2/2]
template<class T > int hdf5Reader::readTopDataSet (std::string dsetName, std::vector< T > & buffer) inline
Parameters
dsetName Dataset name
buffer Buffer into which numeric data is read
Returns
Integer flag: 0 (failure) or 1 (success)
Definition at line 115 of file hdf5Reader.H.
{
     try {
       std::cout << "H5_VERS_MAJOR = " << H5_VERS_MAJOR << std::endl;
       std::cout << "H5_VERS_MINOR = " << H5_VERS_MINOR << std::endl;
       std::cout << "H5_VERS_RELEASE = " << H5_VERS_RELEASE << std::endl;
       std::cout << "H5_VERS_SUBRELEASE = " << H5_VERS_SUBRELEASE << std::endl;
       // Open dataset
       DataSet dset = file.openDataSet(dsetName);
       readDataSet(dset, buffer);
     }
     // catch failure caused by the H5File operations
     catch (FileIException error) {
 #if H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 8 && H5_VERS_RELEASE >= 20
       error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 10 && H5_VERS_RELEASE >= 2
       error.printErrorStack();
 #elif H5_VERS_MAJOR >= 1 && H5_VERS_MINOR >= 11 && H5_VERS_RELEASE >= 0
       error.printErrorStack();
 #else
       error.printError();
 #endif
       return -1;
     }
     return 0;
   }
setConnectivities()
void hdf5Reader::setConnectivities (std::vector< std::map< int, std::vector< int >>> elementConnectivity)
Parameters
elementConnectivity Element connectivity table
Definition at line 190 of file hdf5Reader.C.
References elementConnectivity.
Referenced by proteusHdf5::proteusHdf5().
{
   elementConnectivity = _elementConnectivity;
 }
setCoordinates() [1/3]
void hdf5Reader::setCoordinates (std::vector< double > xCrd)
Parameters
xCrd vector of x-coordinates
Definition at line 166 of file hdf5Reader.C.
References xCrd.
Referenced by proteusHdf5::proteusHdf5().
 { xCrd = _xCrd; }
setCoordinates() [2/3]
void hdf5Reader::setCoordinates (std::vector< double > xCrd, std::vector< double > yCrd)
Parameters
xCrd vector of x-coordinates
yCrd vector of y-coordinates
Definition at line 168 of file hdf5Reader.C.
References xCrd, and yCrd.
{
   xCrd = _xCrd;
   yCrd = _yCrd;
 }
setCoordinates() [3/3]
void hdf5Reader::setCoordinates (std::vector< double > xCrd, std::vector< double > yCrd, std::vector< double > zCrd)
Parameters
xCrd vector of x-coordinates
yCrd vector of y-coordinates
zCrd vector of z-coordinates
Definition at line 174 of file hdf5Reader.C.
References xCrd, yCrd, and zCrd.
{
   xCrd = _xCrd;
   yCrd = _yCrd;
   zCrd = _zCrd;
 }
setElementTypes()
void hdf5Reader::setElementTypes (std::vector< int > vtkElementTypes)
Parameters
vtkElementTypes Vector of VTK element types for each element
Definition at line 182 of file hdf5Reader.C.
References vtkElementTypes.
Referenced by proteusHdf5::proteusHdf5().
{
   vtkElementTypes = _vtkElementTypes;
 }
setElementTypesList()
void hdf5Reader::setElementTypesList (std::vector< int > vtkElementTypesList)
Parameters
vtkElementTypesList Vector of each unique VTK element type in mesh
Definition at line 186 of file hdf5Reader.C.
References vtkElementTypesList.
Referenced by proteusHdf5::proteusHdf5().
{
   vtkElementTypesList = _vtkElementTypesList;
 }
setFields()
void hdf5Reader::setFields (meshBase * myMeshBase, std::vector< std::string > dataNames, std::vector< std::vector< double >> data, int pointOrCell)
Parameters
myMeshBase meshBase object
dataNames Vector of names of data fields
data Vector storing data
pointOrCell Boolean indicating point or cell data
Definition at line 323 of file hdf5Reader.C.
References data, meshBase::setCellDataArray(), and meshBase::setPointDataArray().
Referenced by proteusHdf5::proteusHdf5().
{
   if (pointOrCell == 0) {
     std::cout << "Setting hdf5Reader object point fields..." << std::endl;
   } else if (pointOrCell == 1) {
     std::cout << "Setting hdf5Reader object cell fields..." << std::endl;
   }
   // Set element data
   auto dataNameItr = dataNames.begin();
   auto dataItr = data.begin();
   while (dataNameItr != dataNames.end() || dataItr != data.end()) {
     std::cout << "    " << *dataNameItr << std::endl;
     if (pointOrCell == 0) {
       myMeshBase->setPointDataArray((*dataNameItr).c_str(), *dataItr);
     } else if (pointOrCell == 1) {
       myMeshBase->setCellDataArray((*dataNameItr).c_str(), *dataItr);
     }
     if (dataNameItr != dataNames.end()) {
       dataNameItr++;
     }
     if (dataItr != data.end()) {
       dataItr++;
     }
   }
 }
setNumberOfDimensions()
void hdf5Reader::setNumberOfDimensions (int numDimensions)
Parameters
numDimensions Number of spatial dimensions
Definition at line 162 of file hdf5Reader.C.
References numDimensions.
Referenced by proteusHdf5::proteusHdf5().
{
   numDimensions = _numDimensions;
 }
setNumberOfElements()
void hdf5Reader::setNumberOfElements (int numElements)
Parameters
numElements Number of elements
Definition at line 158 of file hdf5Reader.C.
References numElements.
Referenced by proteusHdf5::proteusHdf5().
{
   numElements = _numElements;
 }
setNumberOfVertices()
void hdf5Reader::setNumberOfVertices (int numVertices)
Parameters
numVertices Number of vertices
Definition at line 154 of file hdf5Reader.C.
References numVertices.
Referenced by proteusHdf5::proteusHdf5().
{
   numVertices = _numVertices;
 }
unflattenBuffer2d()
template<class T > void hdf5Reader::unflattenBuffer2d (std::vector< T > flatBuffer, std::vector< std::vector< T >> & originalBuffer) inline
Parameters
flatBuffer Original flattened data
originalBuffer Output unflattened data
Definition at line 258 of file hdf5Reader.H.
References data.
Referenced by proteusHdf5::getBlockElementData(), and proteusHdf5::getBlockVertexData().
{
     // Populate original buffer
     auto flatItr = flatBuffer.begin();
     for (auto bufItr1 = originalBuffer.begin(); bufItr1 != originalBuffer.end();
          bufItr1++) {
       for (auto bufItr2 = (*bufItr1).begin(); bufItr2 != (*bufItr1).end();
            bufItr2++) {
         *bufItr2 = *flatItr;
         flatItr++;
       }
     }
   }
writeVTK()
void hdf5Reader::writeVTK ()
Definition at line 354 of file hdf5Reader.C.
References exportToMeshBase(), myMeshBase, and meshBase::write().
{
   std::cout << "Writing hdf5Reader object to VTK file" << std::endl;
   if (!myMeshBase) {
     exportToMeshBase();
   }
   myMeshBase->write();
 }
Member Data Documentation
baseH5FileName
std::string hdf5Reader::baseH5FileName protected
Definition at line 373 of file hdf5Reader.H.
elementConnectivity
std::vector<std::map<int, std::vector<int> > > hdf5Reader::elementConnectivity protected
Definition at line 383 of file hdf5Reader.H.
Referenced by getElementConnectivity(), proteusHdf5::mergeBlocks(), and setConnectivities().
file
H5File hdf5Reader::file protected
Definition at line 376 of file hdf5Reader.H.
Referenced by closeFile(), openFile(), readGroup(), and readTopDataSet().
h5FileName
std::string hdf5Reader::h5FileName protected
Definition at line 372 of file hdf5Reader.H.
Referenced by closeFile(), getFileName(), and openFile().
myMeshBase
meshBase* hdf5Reader::myMeshBase protected
Definition at line 378 of file hdf5Reader.H.
Referenced by exportToMeshBase(), getMeshBase(), proteusHdf5::proteusHdf5(), and writeVTK().
numDimensions
int hdf5Reader::numDimensions protected
Definition at line 386 of file hdf5Reader.H.
Referenced by exportToVTKMesh(), and setNumberOfDimensions().
numElements
int hdf5Reader::numElements protected
Definition at line 385 of file hdf5Reader.H.
Referenced by exportToVTKMesh(), and setNumberOfElements().
numVertices
int hdf5Reader::numVertices protected
Definition at line 384 of file hdf5Reader.H.
Referenced by exportToVTKMesh(), and setNumberOfVertices().
outputFname
std::string hdf5Reader::outputFname protected
Definition at line 374 of file hdf5Reader.H.
Referenced by exportToMeshBase().
verb
int hdf5Reader::verb protected
Definition at line 375 of file hdf5Reader.H.
vtkElementTypes
std::vector<int> hdf5Reader::vtkElementTypes protected
Definition at line 388 of file hdf5Reader.H.
Referenced by exportToVTKMesh(), getElementConnectivity(), and setElementTypes().
vtkElementTypesList
std::vector<int> hdf5Reader::vtkElementTypesList protected
Definition at line 389 of file hdf5Reader.H.
Referenced by getElementConnectivity(), and setElementTypesList().
vtkMesh
vtkSmartPointer<vtkDataSet> hdf5Reader::vtkMesh protected
Definition at line 377 of file hdf5Reader.H.
Referenced by getVTKMesh().
xCrd
std::vector<double> hdf5Reader::xCrd protected
Definition at line 381 of file hdf5Reader.H.
Referenced by exportToVTKMesh(), and setCoordinates().
yCrd
std::vector<double> hdf5Reader::yCrd protected
Definition at line 381 of file hdf5Reader.H.
Referenced by exportToVTKMesh(), and setCoordinates().
zCrd
std::vector<double> hdf5Reader::zCrd protected
Definition at line 381 of file hdf5Reader.H.
Referenced by exportToVTKMesh(), and setCoordinates().
The documentation for this class was generated from the following files:
hdf5Reader.H
hdf5Reader.C