NEMoSys: nemAux::Timer Class Reference
nemAux::Timer Class Reference
Detailed Description
Definition at line 55 of file AuxiliaryFunctions.H.
Public Member Functions
Timer ()
time_t start ()
time_t stop ()
double elapsed ()
Private Types
using time_t = std::chrono::time_point< std::chrono::system_clock >
Private Attributes
time_t startTime
time_t stopTime
Member Typedef Documentation
time_t
using nemAux::Timer::time_t = std::chrono::time_point<std::chrono::system_clock> private
Definition at line 57 of file AuxiliaryFunctions.H.
Constructor & Destructor Documentation
Timer()
nemAux::Timer::Timer () inline
Definition at line 60 of file AuxiliaryFunctions.H.
 : startTime(), stopTime() {}
Member Function Documentation
elapsed()
double nemAux::Timer::elapsed () inline
Definition at line 66 of file AuxiliaryFunctions.H.
References startTime, and stopTime.
Referenced by NEM::MSH::EXOMesh::exoMesh::combineElmBlks(), orthoPoly3D::computeA(), ConservativeVolumeTransfer::constructLoadVector(), ConservativeVolumeTransfer::constructMassMatrix(), ConservativeVolumeTransfer::constructMixedMassMatrix(), ConservativeVolumeTransfer::constructSupermesh(), NEM::DRV::TemplateMeshDriver::execute(), NEM::DRV::TransferDriver::execute(), NEM::ADP::Refine::initAdaptive(), NEM::ADP::Refine::initUniform(), orthoPoly3D::operator()(), ConservativeVolumeTransfer::transfer(), and FETransfer::transferPointData().
                    {
     return std::chrono::duration_cast<std::chrono::milliseconds>(stopTime -
                                                                  startTime)
         .count();
   }
start()
time_t nemAux::Timer::start () inline
Definition at line 62 of file AuxiliaryFunctions.H.
References startTime.
Referenced by NEM::MSH::EXOMesh::exoMesh::combineElmBlks(), orthoPoly3D::computeA(), ConservativeVolumeTransfer::constructLoadVector(), ConservativeVolumeTransfer::constructMassMatrix(), ConservativeVolumeTransfer::constructMixedMassMatrix(), ConservativeVolumeTransfer::constructSupermesh(), NEM::DRV::InputGenDriver::execute(), NEM::DRV::TemplateMeshDriver::execute(), NEM::DRV::TransferDriver::execute(), NEM::ADP::Refine::initAdaptive(), NEM::ADP::Refine::initUniform(), orthoPoly3D::operator()(), ConservativeVolumeTransfer::transfer(), and FETransfer::transferPointData().
 { return startTime = std::chrono::system_clock::now(); }
stop()
time_t nemAux::Timer::stop () inline
Definition at line 64 of file AuxiliaryFunctions.H.
References stopTime.
Referenced by NEM::MSH::EXOMesh::exoMesh::combineElmBlks(), orthoPoly3D::computeA(), ConservativeVolumeTransfer::constructLoadVector(), ConservativeVolumeTransfer::constructMassMatrix(), ConservativeVolumeTransfer::constructMixedMassMatrix(), ConservativeVolumeTransfer::constructSupermesh(), NEM::DRV::InputGenDriver::execute(), NEM::DRV::TemplateMeshDriver::execute(), NEM::DRV::TransferDriver::execute(), NEM::ADP::Refine::initAdaptive(), NEM::ADP::Refine::initUniform(), orthoPoly3D::operator()(), ConservativeVolumeTransfer::transfer(), and FETransfer::transferPointData().
 { return stopTime = std::chrono::system_clock::now(); }
Member Data Documentation
startTime
time_t nemAux::Timer::startTime private
Definition at line 73 of file AuxiliaryFunctions.H.
Referenced by elapsed(), and start().
stopTime
time_t nemAux::Timer::stopTime private
Definition at line 73 of file AuxiliaryFunctions.H.
Referenced by elapsed(), and stop().
The documentation for this class was generated from the following file:
AuxiliaryFunctions.H