NEMoSys: NEM::DRV::NucMeshDriver Class Reference
NEM::DRV::NucMeshDriver Class Reference
Class to create 2d geometry from polygons and circles and mesh it.
Detailed Description
Definition at line 50 of file NucMeshDriver.H.
Public Types
using Files = DriverOutFile
using Opts = NEM::SRV::NucMeshConf
Public Member Functions
NucMeshDriver (Files file, Opts opts)
NucMeshDriver ctor.
const Files & getFiles () const
Get the output file name.
void setFiles (Files files)
Set the output file for the driver.
const Opts & getOpts () const
Get the options set on a driver object.
void setOpts (Opts opts)
Set the geometry/mesh and extrusion to execute.
vtkSmartPointer< NEM::MSH::geoMeshBase > draw () const
Construct the mesh.
void execute () const override
Construct the mesh and write to file.
Static Public Member Functions
static std::unique_ptr< NemDriver > readJSON (const jsoncons::json &inputjson)
Factory method for all drivers.
Private Member Functions
NucMeshDriver ()
jsoncons::string_view getProgramType () const override
Private Attributes
Files file_
Opts opts_
Static Private Attributes
static constexpr const char * programType = "NucMesh Generation"
Inherits NEM::DRV::NemDriver.
Member Typedef Documentation
Files
using NEM::DRV::NucMeshDriver::Files = DriverOutFile
Definition at line 52 of file NucMeshDriver.H.
Opts
using NEM::DRV::NucMeshDriver::Opts = NEM::SRV::NucMeshConf
Definition at line 54 of file NucMeshDriver.H.
Constructor & Destructor Documentation
NucMeshDriver() [1/2]
NEM::DRV::NucMeshDriver::NucMeshDriver (Files file, Opts opts) explicit
Parameters
file Output file. Should end in ".vtu"
opts Specify shapes and extrusion.
Definition at line 38 of file NucMeshDriver.C.
     : file_(std::move(file)), opts_(std::move(opts)) {}
NucMeshDriver() [2/2]
NEM::DRV::NucMeshDriver::NucMeshDriver () private
Definition at line 41 of file NucMeshDriver.C.
 : NucMeshDriver(Files{std::string{}}, Opts{}) {}
Member Function Documentation
draw()
vtkSmartPointer< NEM::MSH::geoMeshBase > NEM::DRV::NucMeshDriver::draw () const
Returns
geoMeshBase with 1d and 2d cells (and 3d if any extrusion)
Definition at line 55 of file NucMeshDriver.C.
References opts_.
Referenced by execute().
{
   vtkNew<NEM::SRV::NucMeshSrv> nucMeshRunner{};
   nucMeshRunner->SetConfiguration(opts_);
   nucMeshRunner->Update();
   return NEM::MSH::smeshGeoMesh::SafeDownCast(nucMeshRunner->GetOutput());
 }
execute()
void NEM::DRV::NucMeshDriver::execute () const override virtual
Implements NEM::DRV::NemDriver.
Definition at line 62 of file NucMeshDriver.C.
References draw(), file_, NEM::MSH::New(), and NEM::DRV::DriverOutFile::outputFile.
{
   auto outNative = this->draw();
   auto outType = vtkSmartPointer<NEM::MSH::geoMeshBase>::Take(
       NEM::MSH::New(file_.outputFile));
   outType->takeGeoMesh(outNative);
   outType->write(file_.outputFile);
 }
getFiles()
const NucMeshDriver::Files & NEM::DRV::NucMeshDriver::getFiles () const
Returns
output file object containing file name
Definition at line 43 of file NucMeshDriver.C.
References file_.
 { return file_; }
getOpts()
const NucMeshDriver::Opts & NEM::DRV::NucMeshDriver::getOpts () const
Returns
geometry, meshing options, and extrusion steps
Definition at line 47 of file NucMeshDriver.C.
References opts_.
 { return opts_; }
getProgramType()
jsoncons::string_view NEM::DRV::NucMeshDriver::getProgramType () const override private virtual
Implements NEM::DRV::NemDriver.
Definition at line 51 of file NucMeshDriver.C.
References programType.
{
   return programType;
 }
readJSON()
std::unique_ptr< NemDriver > NEM::DRV::NemDriver::readJSON (const jsoncons::json & inputjson) static inherited
Parameters
inputjson json input with "Program Type" key
Returns
pointer to base NemDriver class
Definition at line 37 of file NemDriver.C.
Referenced by NEM::DRV::MeshGenDriver::MeshGenDriver().
{
   return inputjson.as<std::unique_ptr<NemDriver>>();
 }
setFiles()
void NEM::DRV::NucMeshDriver::setFiles (Files files)
Parameters
files NEM::DRV::NucMeshDriver::Files object containing output file
Definition at line 45 of file NucMeshDriver.C.
References file_.
 { file_ = std::move(files); }
setOpts()
void NEM::DRV::NucMeshDriver::setOpts (Opts opts)
Parameters
opts geometry/mesh options
Definition at line 49 of file NucMeshDriver.C.
References opts_.
 { opts_ = std::move(opts); }
Member Data Documentation
file_
Files NEM::DRV::NucMeshDriver::file_ private
Definition at line 100 of file NucMeshDriver.H.
Referenced by execute(), getFiles(), and setFiles().
opts_
Opts NEM::DRV::NucMeshDriver::opts_ private
Definition at line 101 of file NucMeshDriver.H.
Referenced by draw(), getOpts(), and setOpts().
programType
constexpr const char* NEM::DRV::NucMeshDriver::programType = "NucMesh Generation" static private
Definition at line 103 of file NucMeshDriver.H.
Referenced by NEM::DRV::JSON::as_shape(), and getProgramType().
The documentation for this class was generated from the following files:
NucMeshDriver.H
NucMeshDriver.C