NEMoSys: meshBase.H File Reference
meshBase.H File Reference
Classes
class meshBase
A brief description of meshBase.
struct sortNemId_tVec_compare
sum comparison for vectors representing faces inserted into map
Typedefs
using nemId_t = std::size_t
Functions
NEMOSYS_EXPORT int diffMesh (meshBase *mesh1, meshBase *mesh2)
compares two meshBase classes.
NEMOSYS_EXPORT void writePatchMap (const std::string &mapFile, const std::map< int, int > &patchMap)
write patch map file for roc prep (trivial identity mapping)
NEMOSYS_EXPORT void writePatchMap (std::ofstream &outputStream, const std::map< int, int > &patchMap)
write patch map file for roc prep (trivial identity mapping)
Typedef Documentation
nemId_t
using nemId_t = std::size_t
Definition at line 51 of file meshBase.H.
Function Documentation
diffMesh()
NEMOSYS_EXPORT int diffMesh (meshBase * mesh1, meshBase * mesh2)
used in testing
Parameters
mesh1 <>
mesh2 <>
Definition at line 1665 of file meshBase.C.
References meshBase::getCellVec(), meshBase::getDataSet(), meshBase::getNumberOfCells(), meshBase::getNumberOfPoints(), meshBase::getPoint(), and NEM::MSH::New().
{
   // double tol = 1e-14;
   double tol = 3e-2;
   if (mesh1->getNumberOfPoints() != mesh2->getNumberOfPoints() ||
       mesh1->getNumberOfCells() != mesh2->getNumberOfCells()) {
     std::cerr << "Meshes don't have the same number of points or cells"
               << std::endl;
     return 1;
   }
   for (int i = 0; i < mesh1->getNumberOfPoints(); ++i) {
     std::vector<double> coord1 = mesh1->getPoint(i);
     std::vector<double> coord2 = mesh2->getPoint(i);
     for (int j = 0; j < 3; ++j) {
       if (std::fabs((coord1[j] - coord2[j]) / coord2[j]) > tol) {
         std::cerr << "Meshes differ in point coordinates" << std::endl;
         std::cerr << "Index " << i << " Component " << j << std::endl;
         std::cerr << "Coord 1 " << std::setprecision(15) << coord1[j]
                   << " Coord 2 " << std::setprecision(15) << coord2[j]
                   << std::endl;
         std::cerr << "Meshes differ in point coordinates" << std::endl;
         return 1;
       }
     }
   }
   for (int i = 0; i < mesh1->getNumberOfCells(); ++i) {
     std::vector<std::vector<double>> cell1 = mesh1->getCellVec(i);
     std::vector<std::vector<double>> cell2 = mesh2->getCellVec(i);
     if (cell1.size() != cell2.size()) {
       std::cerr << "Meshes differ in cells" << std::endl;
       return 1;
     }
     for (int j = 0; j < cell1.size(); ++j) {
       for (int k = 0; k < 3; ++k) {
         if (std::fabs((cell1[j][k] - cell2[j][k]) / cell2[j][k]) > tol) {
           std::cerr << "Meshes differ in cells" << std::endl;
           return 1;
         }
       }
     }
   }
   vtkSmartPointer<vtkPointData> pd1 = vtkSmartPointer<vtkPointData>::New();
   pd1 = mesh1->getDataSet()->GetPointData();
   vtkSmartPointer<vtkPointData> pd2 = vtkSmartPointer<vtkPointData>::New();
   pd2 = mesh2->getDataSet()->GetPointData();
   int numArr1 = pd1->GetNumberOfArrays();
   int numArr2 = pd2->GetNumberOfArrays();
   if (numArr1 != numArr2) {
     std::cerr << "Meshes have different numbers of point data" << std::endl;
     std::cerr << "Mesh 1 has " << numArr1 << std::endl;
     std::cerr << "Mesh 2 has " << numArr2 << std::endl;
     return 1;
   }
   for (int i = 0; i < numArr1; ++i) {
     vtkDataArray *da1 = pd1->GetArray(i);
     std::cerr << "checking array " << da1->GetName() << std::endl;
     vtkDataArray *da2 = pd2->GetArray(pd1->GetArrayName(i));
     double range[2];
     double abs_error;
     double rel_error;
     int numComponent = da1->GetNumberOfComponents();
     for (int j = 0; j < mesh1->getNumberOfPoints(); ++j) {
       double *comps1 = new double[numComponent];
       double *comps2 = new double[numComponent];
       da1->GetTuple(j, comps1);
       da2->GetTuple(j, comps2);
       for (int k = 0; k < numComponent; ++k) {
         da1->GetRange(range, k);
         abs_error = std::fabs(comps1[k] - comps2[k]);
         double max_val = std::max(std::abs(range[0]), std::abs(range[1]));
         rel_error = abs_error / std::max(1.0, max_val);
         if (rel_error > tol) {
           std::cerr << "For point data array " << da1->GetName() << std::endl;
           std::cerr << "Meshes differ in point data values at point " << j
                     << " component " << k << std::endl;
           std::cerr << std::setprecision(15) << "Mesh 1 value : " << comps1[k]
                     << std::endl;
           std::cerr << std::setprecision(15) << "Mesh 2 value : " << comps2[k]
                     << std::endl;
           return 1;
         }
       }
       delete[] comps1;
       delete[] comps2;
     }
   }
   std::cerr << "Meshes are the same" << std::endl;
   return 0;
 }
writePatchMap() [1/2]
NEMOSYS_EXPORT void writePatchMap (const std::string & mapFile, const std::map< int, int > & patchMap)
Parameters
mapFile <>
patchMap <>
Definition at line 1376 of file meshBase.C.
References writePatchMap().
Referenced by meshBase::writeCobalt(), and writePatchMap().
{
   std::ofstream outputStream(mapFile);
   if (!outputStream.good()) {
     std::cout << "Error opening file " << mapFile << std::endl;
     exit(1);
   }
   writePatchMap(outputStream, patchMap);
 }
writePatchMap() [2/2]
NEMOSYS_EXPORT void writePatchMap (std::ofstream & outputStream, const std::map< int, int > & patchMap)
Parameters
outputStream <>
patchMap <>
Definition at line 1388 of file meshBase.C.
{
   outputStream << patchMap.size() << std::endl;
   outputStream << patchMap.size() << std::endl;
   auto it = patchMap.begin();
   int normPatchNo = 1;
   while (it != patchMap.end()) {
     for (int i = 0; i < 2; ++i) {
       outputStream << std::setw(2) << std::left << it->first << " ";
     }
     outputStream << std::setw(2) << std::left << normPatchNo << " ";
     outputStream << std::endl;
     ++it;
     normPatchNo++;
   }
 }