NEMoSys: NEM::MSH::EXOMesh Namespace Reference
NEM::MSH::EXOMesh Namespace Reference
Classes
struct elmBlkType
Stores element block information.
class exoMesh
A complete I/O class for EXODUS II file format.
struct ndeSetType
Stores node set information.
struct sdeSetType
Stores side set information.
Typedefs
using ndeSets = std::vector< ndeSetType >
using elmBlks = std::vector< elmBlkType >
using sdeSets = std::vector< sdeSetType >
Functions
VTKCellType e2vEMap (elementType et)
Convert EXODUS element type to VTK cell type.
elementType v2eEMap (VTKCellType vt)
Convert VTK cell type to EXODUS element type.
surfaceBCTag bcTagNum (std::string &tag)
std::string bcTagStr (surfaceBCTag tag)
elementType elmTypeNum (std::string tag)
Convert string to EXODUS element type.
std::string elmTypeStr (elementType et)
Convert EXODUS element type to string tab.
int elmNumNde (elementType et, int order)
Get number of nodes given EXODUS element type and order.
int elmNumSrf (elementType et)
Get number of surfaces given EXODUS element type.
void wrnErrMsg (int errCode, const std::string &errMsg="None")
Logging method.
Typedef Documentation
elmBlks
using NEM::MSH::EXOMesh::elmBlks = typedef std::vector<elmBlkType>
Definition at line 107 of file exoMesh.H.
ndeSets
using NEM::MSH::EXOMesh::ndeSets = typedef std::vector<ndeSetType>
Definition at line 106 of file exoMesh.H.
sdeSets
using NEM::MSH::EXOMesh::sdeSets = typedef std::vector<sdeSetType>
Definition at line 108 of file exoMesh.H.
Function Documentation
bcTagNum()
surfaceBCTag NEMOSYS_EXPORT NEM::MSH::EXOMesh::bcTagNum (std::string & tag)
Parameters
tag
Returns
Definition at line 76 of file exoMesh.C.
References FIXED, SYMMX, SYMMY, and nemAux::toLower().
{
   nemAux::toLower(tag);
   if (tag == "fixed") return surfaceBCTag::FIXED;
   if (tag == "symmx") return surfaceBCTag::SYMMX;
   if (tag == "symmy") return surfaceBCTag::SYMMY;
   if (tag == "symmz") return surfaceBCTag::SYMMZ;
   std::cerr << "Unknown surface tag " << tag << std::endl;
   throw;
 }
bcTagStr()
std::string NEMOSYS_EXPORT NEM::MSH::EXOMesh::bcTagStr (surfaceBCTag tag)
Parameters
tag
Returns
Definition at line 86 of file exoMesh.C.
References FIXED, SYMMX, and SYMMY.
{
   switch (tag) {
     case surfaceBCTag::FIXED: return "FIXED";
     case surfaceBCTag::SYMMX: return "SYMMX";
     case surfaceBCTag::SYMMY: return "SYMMY";
     case surfaceBCTag::SYMMZ: return "SYMMZ";
   }
   std::cerr << "Unknown surface tag." << std::endl;
   throw;
 }
e2vEMap()
VTKCellType NEMOSYS_EXPORT NEM::MSH::EXOMesh::e2vEMap (elementType et)
Parameters
et EXODUS element type
Returns
VTK cell type
Definition at line 50 of file exoMesh.C.
References HEX, QUAD, TETRA, TRIANGLE, and WEDGE.
Referenced by meshBase::exportExoToVtk().
{
   std::map<elementType, VTKCellType> eMap = {
       {elementType::TRIANGLE, VTK_TRIANGLE},
       {elementType::QUAD, VTK_QUAD},
       {elementType::TETRA, VTK_TETRA},
       {elementType::HEX, VTK_HEXAHEDRON},
       {elementType::WEDGE, VTK_WEDGE},
       {elementType::OTHER, VTK_EMPTY_CELL}};
   return eMap[et];
 }
elmNumNde()
int NEMOSYS_EXPORT NEM::MSH::EXOMesh::elmNumNde (elementType et, int order)
Parameters
et EXODUS element type
order element order
Returns
number of nodes
Definition at line 138 of file exoMesh.C.
References elmTypeStr(), HEX, QUAD, TETRA, TRIANGLE, and WEDGE.
{
   if (tag == elementType::TRIANGLE && order == 1) return 3;
   if (tag == elementType::TRIANGLE && order == 2) return 6;
   if (tag == elementType::QUAD && order == 1) return 4;
   if (tag == elementType::QUAD && order == 2) return 9;
   if (tag == elementType::TETRA && order == 1) return 4;
   if (tag == elementType::TETRA && order == 2) return 10;
   if (tag == elementType::HEX && order == 1) return 8;
   if (tag == elementType::HEX && order == 2) return 21;
   if (tag == elementType::WEDGE && order == 1) return 6;
   if (tag == elementType::WEDGE && order == 2) return 16;
   std::cerr << "Unknown element/order combination " << elmTypeStr(tag) << " " << order
             << "\n";
   throw;
 }
elmNumSrf()
int NEMOSYS_EXPORT NEM::MSH::EXOMesh::elmNumSrf (elementType et)
Parameters
et EXODUS element type
Returns
number of surfaces
Definition at line 154 of file exoMesh.C.
References elmTypeStr(), HEX, QUAD, TETRA, TRIANGLE, and WEDGE.
{
   switch (tag) {
     case elementType::TRIANGLE: return 3;
     case elementType::QUAD: return 4;
     case elementType::TETRA: return 4;
     case elementType::HEX: return 8;
     case elementType::WEDGE: return 5;
     case elementType::OTHER: break;
   }
   std::cerr << "Unknown element type " << elmTypeStr(tag) << "\n";
   throw;
 }
elmTypeNum()
elementType NEMOSYS_EXPORT NEM::MSH::EXOMesh::elmTypeNum (std::string tag)
Parameters
tag string tag of an element type
Returns
EXODUS element type
Definition at line 97 of file exoMesh.C.
References HEX, QUAD, TETRA, nemAux::toLower(), TRIANGLE, and WEDGE.
Referenced by meshBase::exportExoToVtk(), and NEM::MSH::EXOMesh::exoMesh::read().
{
   nemAux::toLower(tag);
   if (tag == "triangle") return elementType::TRIANGLE;
   if (tag == "tri") return elementType::TRIANGLE;
   if (tag == "tri3") return elementType::TRIANGLE;
   if (tag == "trishell3") return elementType::TRIANGLE;
   if (tag == "quadrilateral") return elementType::QUAD;
   if (tag == "quad") return elementType::QUAD;
   if (tag == "quad4") return elementType::QUAD;
   if (tag == "shell4") return elementType::QUAD;
   if (tag == "tetrahedron") return elementType::TETRA;
   if (tag == "tetrahedral") return elementType::TETRA;
   if (tag == "tetra") return elementType::TETRA;
   if (tag == "tetra4") return elementType::TETRA;
   if (tag == "hexahedron") return elementType::HEX;
   if (tag == "hexahedral") return elementType::HEX;
   if (tag == "brick") return elementType::HEX;
   if (tag == "hex") return elementType::HEX;
   if (tag == "hex8") return elementType::HEX;
   if (tag == "wedge") return elementType::WEDGE;
   if (tag == "prismatic") return elementType::WEDGE;
   if (tag == "prism") return elementType::WEDGE;
   std::cout << "Warning : Element type " << tag << " may be unsupported.\n";
   return elementType::OTHER;
 }
elmTypeStr()
std::string NEMOSYS_EXPORT NEM::MSH::EXOMesh::elmTypeStr (elementType et)
Parameters
et EXODUS element type
Returns
string tag of an element type
Definition at line 128 of file exoMesh.C.
References HEX, QUAD, TETRA, TRIANGLE, and WEDGE.
Referenced by elmNumNde(), elmNumSrf(), NEM::MSH::EXOMesh::exoMesh::report(), and NEM::MSH::EXOMesh::exoMesh::write().
{
   if (et == elementType::QUAD) return "QUAD";
   if (et == elementType::TRIANGLE) return "TRIANGLE";
   if (et == elementType::QUAD) return "QUAD";
   if (et == elementType::TETRA) return "TETRA";
   if (et == elementType::HEX) return "HEX";
   if (et == elementType::WEDGE) return "WEDGE";
   return "OTHER";
 }
v2eEMap()
elementType NEMOSYS_EXPORT NEM::MSH::EXOMesh::v2eEMap (VTKCellType vt)
Parameters
vt VTK cell type
Returns
EXODUS element type
Definition at line 61 of file exoMesh.C.
References HEX, QUAD, TETRA, TRIANGLE, and WEDGE.
Referenced by NEM::DRV::ConversionDriver::genExo().
{
   std::map<VTKCellType, elementType> eMap = {
       {VTK_TRIANGLE, elementType::TRIANGLE},
       {VTK_QUAD, elementType::QUAD},
       {VTK_TETRA, elementType::TETRA},
       {VTK_HEXAHEDRON, elementType::HEX},
       {VTK_WEDGE, elementType::WEDGE},
       {VTK_QUADRATIC_TRIANGLE, elementType::TRIANGLE},
       {VTK_QUADRATIC_QUAD, elementType::QUAD},
       {VTK_QUADRATIC_TETRA, elementType::TETRA},
       {VTK_QUADRATIC_HEXAHEDRON, elementType::HEX},
       {VTK_EMPTY_CELL, elementType::OTHER}};
   return eMap[vt];
 }
wrnErrMsg()
void NEMOSYS_EXPORT NEM::MSH::EXOMesh::wrnErrMsg (int errCode, const std::string & errMsg = "None")
Parameters
errCode If <0, then error and throw. If =0, continue. If >0, warning.
errMsg Message to output explaining error.
Definition at line 202 of file exoMesh.C.
Referenced by NEM::MSH::EXOMesh::exoMesh::addElmBlkByElmIdLst(), meshBase::exportExoToVtk(), NEM::MSH::EXOMesh::exoMesh::read(), NEM::MSH::EXOMesh::exoMesh::removeByElmIdLst(), and NEM::MSH::EXOMesh::exoMesh::write().
{
   if (errCode < 0) {
     std::cerr << "Error: " << msg << " with error code " << errCode
               << std::endl;
     throw;
   } else if (errCode > 0) {
     std::cerr << "Warning: " << msg << " with warning code " << errCode
               << std::endl;
   }
 }