NEMoSys: NEM::DRV::JSON Namespace Reference
NEM::DRV::JSON Namespace Reference
Classes
struct colorMapPair
struct function_traits
struct function_traits< R(*)(Args...)>
struct function_traits< R(Args...)>
struct function_traits< R(T::*)(Args...)>
Typedefs
template<typename T >
using first_argument_type = typename std::tuple_element< 0, typename function_traits< T >::argument_types >::type
Functions
std::vector< PNTMesh::surfaceBCTag > pntMeshBcTagFromJSON (const std::string &input)
std::string pntMeshBcTagToJSON (const std::vector< PNTMesh::surfaceBCTag > &input)
std::vector< int > rangeToVec (const std::pair< int, int > &input)
std::vector< colorMapPair > gmshColorMapToJSON (const std::map< std::array< int, 3 >, std::string > &colorMap)
std::map< std::array< int, 3 >, std::string > gmshColorMapFromJSON (const std::vector< colorMapPair > &colorMap)
template<typename T , typename R , typename... Args>
void setter_helper (T &obj, R(T::*setter)(Args...), const jsoncons::json &json, jsoncons::string_view key, bool checkContains)
template<typename T >
std::unique_ptr< NEM::NUCMESH::ShapeBase > construct_helper (const jsoncons::json &json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes)
std::unique_ptr< NEM::NUCMESH::ShapeBase > as_shape (const jsoncons::json &json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes)
template<typename T >
std::enable_if< std::is_base_of< NEM::NUCMESH::ShapeBase, T >::value, void >::type modify_helper (const jsoncons::json &json, T &shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes, bool checkRequired)
template<>
void modify_helper (const jsoncons::json &json, NEM::NUCMESH::ShapeBase &shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &, bool)
template<>
void modify_helper (const jsoncons::json &json, NEM::NUCMESH::Circles &shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes, bool checkRequired)
template<>
std::unique_ptr< NEM::NUCMESH::ShapeBase > construct_helper< NEM::NUCMESH::Circles > (const jsoncons::json &json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes)
template<>
void modify_helper (const jsoncons::json &json, NEM::NUCMESH::CirclesAndPolys &shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes, bool checkRequired)
template<>
std::unique_ptr< NEM::NUCMESH::ShapeBase > construct_helper< NEM::NUCMESH::CirclesAndPolys > (const jsoncons::json &json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes)
template<>
void modify_helper (const jsoncons::json &json, NEM::NUCMESH::ShapesArray &shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes, bool checkRequired)
template<>
void modify_helper (const jsoncons::json &json, NEM::NUCMESH::PolarArray &shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes, bool checkRequired)
template<>
std::unique_ptr< NEM::NUCMESH::ShapeBase > construct_helper< NEM::NUCMESH::PolarArray > (const jsoncons::json &json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes)
template<>
void modify_helper (const jsoncons::json &json, NEM::NUCMESH::RectangularArray &shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes, bool checkRequired)
template<>
std::unique_ptr< NEM::NUCMESH::ShapeBase > construct_helper< NEM::NUCMESH::RectangularArray > (const jsoncons::json &json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes)
template<>
void modify_helper (const jsoncons::json &json, NEM::NUCMESH::HexagonalArray &shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes, bool checkRequired)
template<>
std::unique_ptr< NEM::NUCMESH::ShapeBase > construct_helper< NEM::NUCMESH::HexagonalArray > (const jsoncons::json &json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes)
template<typename T >
std::unique_ptr< NEM::NUCMESH::ShapeBase > construct_from_alias_helper (const jsoncons::json &json, const T *const aliasShape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes)
std::unique_ptr< NEM::NUCMESH::ShapeBase > construct_from_alias (const jsoncons::json &json, const NEM::NUCMESH::ShapeBase *const aliasShape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> &savedShapes)
Variables
static constexpr auto convOptions = "Conversion Options"
static constexpr auto convMethod = "Method"
static constexpr auto programType = "Program Type"
static constexpr auto meshFiles = "Mesh File Options"
static constexpr auto inMeshFile = "Input Mesh File"
static constexpr auto inGeoFile = "Input Geometry File"
static constexpr auto outMeshFile = "Output Mesh File"
static constexpr auto bmParams = "blockMesh Parameters"
static constexpr auto smParams = "snappyHexMesh Parameters"
static constexpr auto meshGenOpts = "Mesh Generation Options"
static constexpr auto meshGenEngine = "Mesh Generation Engine"
static constexpr auto meshQualOpts = "Mesh Quality Options"
static constexpr auto meshQualEngine = "Mesh Quality Engine"
static constexpr auto shapeType = "Type"
static constexpr auto arrayPattern = "Pattern"
static constexpr auto arrayShapes = "Shapes"
static constexpr auto packMeshOpts = "Pack Mesh Options"
static constexpr auto refOpts = "Refinement Options"
static constexpr auto refOperator = "Refinement Operator"
static constexpr auto refMethod = "Refinement Method"
static constexpr auto refTransferData = "Transfer Data"
Typedef Documentation
first_argument_type
template<typename T > using NEM::DRV::JSON::first_argument_type = typedef typename std::tuple_element< 0, typename function_traits<T>::argument_types>::type
Definition at line 79 of file NucMeshJson.H.
Function Documentation
as_shape()
std::unique_ptr< NEM::NUCMESH::ShapeBase > NEM::DRV::JSON::as_shape (const jsoncons::json & json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes) inline
Definition at line 371 of file NucMeshJson.H.
References arrayShapes, construct_from_alias(), meshFiles, NEM_JSON_N_GETTER_SETTER_NAME_TRAITS_FINAL, NEM_JSON_RDONLY_OVERRIDE, programType, NEM::DRV::NucMeshDriver::programType, and QUAD.
Referenced by modify_helper(), and setter_helper().
                       {
   if (json.is_null()) {
     return nullptr;
   }
   static constexpr auto loadSavedStr = "Saved Object";
   if (json.contains(loadSavedStr)) {
     auto findIter = savedShapes.find(json.at(loadSavedStr).as_string());
     if (findIter != savedShapes.end() && findIter->second) {
       return construct_from_alias(json, findIter->second.get(), savedShapes);
     }
   }
   static constexpr auto typeStr = "Type";
   if (json.contains(typeStr)) {
     auto jsonType = json.at(typeStr).as_string_view();
     if (jsonType == "Circles") {
       return construct_helper<NEM::NUCMESH::Circles>(json, savedShapes);
     } else if (jsonType == "Circles And Polys") {
       return construct_helper<NEM::NUCMESH::CirclesAndPolys>(json, savedShapes);
     } else if (jsonType == "Polar Array") {
       return construct_helper<NEM::NUCMESH::PolarArray>(json, savedShapes);
     } else if (jsonType == "Rectangular Array") {
       return construct_helper<NEM::NUCMESH::RectangularArray>(json,
                                                               savedShapes);
     } else if (jsonType == "Hexagonal Array") {
       return construct_helper<NEM::NUCMESH::HexagonalArray>(json, savedShapes);
     }
   }
   throw jsoncons::convert_error(jsoncons::convert_errc::conversion_failed,
                                 "Not a NEM::NUCMESH::ShapeBase");
 }
construct_from_alias()
std::unique_ptr<NEM::NUCMESH::ShapeBase> NEM::DRV::JSON::construct_from_alias (const jsoncons::json & json, const NEM::NUCMESH::ShapeBase *const aliasShape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes) inline
Definition at line 347 of file NucMeshJson.H.
References construct_from_alias_helper().
Referenced by as_shape().
                       {
   if (auto circles = dynamic_cast<const NEM::NUCMESH::Circles *>(aliasShape)) {
     return construct_from_alias_helper(json, circles, savedShapes);
   } else if (auto circlesAndPolys =
                  dynamic_cast<const NEM::NUCMESH::CirclesAndPolys *>(
                      aliasShape)) {
     return construct_from_alias_helper(json, circlesAndPolys, savedShapes);
   } else if (auto polar =
                  dynamic_cast<const NEM::NUCMESH::PolarArray *>(aliasShape)) {
     return construct_from_alias_helper(json, polar, savedShapes);
   } else if (auto rect = dynamic_cast<const NEM::NUCMESH::RectangularArray *>(
                  aliasShape)) {
     return construct_from_alias_helper(json, rect, savedShapes);
   } else if (auto hex = dynamic_cast<const NEM::NUCMESH::HexagonalArray *>(
                  aliasShape)) {
     return construct_from_alias_helper(json, hex, savedShapes);
   }
   throw jsoncons::convert_error(jsoncons::convert_errc::conversion_failed,
                                 "Not a NEM::NUCMESH::ShapeBase");
 }
construct_from_alias_helper()
template<typename T > std::unique_ptr<NEM::NUCMESH::ShapeBase> NEM::DRV::JSON::construct_from_alias_helper (const jsoncons::json & json, const T *const aliasShape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes)
Definition at line 338 of file NucMeshJson.H.
References modify_helper().
Referenced by construct_from_alias().
                       {
   auto output = new T{*aliasShape};
   modify_helper(json, *output, savedShapes, false);
   return std::unique_ptr<NEM::NUCMESH::ShapeBase>{output};
 }
construct_helper()
template<typename T > std::unique_ptr<NEM::NUCMESH::ShapeBase> NEM::DRV::JSON::construct_helper (const jsoncons::json & json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes)
Referenced by setter_helper().
construct_helper< NEM::NUCMESH::Circles >()
template<> std::unique_ptr<NEM::NUCMESH::ShapeBase> NEM::DRV::JSON::construct_helper< NEM::NUCMESH::Circles > (const jsoncons::json & json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes)
Definition at line 149 of file NucMeshJson.H.
References modify_helper().
                       {
   auto shape = new NEM::NUCMESH::Circles{{}};
   std::unique_ptr<NEM::NUCMESH::ShapeBase> out{shape};
   modify_helper(json, *shape, savedShapes, true);
   return out;
 }
construct_helper< NEM::NUCMESH::CirclesAndPolys >()
template<> std::unique_ptr<NEM::NUCMESH::ShapeBase> NEM::DRV::JSON::construct_helper< NEM::NUCMESH::CirclesAndPolys > (const jsoncons::json & json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes)
Definition at line 175 of file NucMeshJson.H.
References modify_helper().
                       {
   auto shape = new NEM::NUCMESH::CirclesAndPolys{{}, {}};
   std::unique_ptr<NEM::NUCMESH::ShapeBase> out{shape};
   modify_helper(json, *shape, savedShapes, true);
   return out;
 }
construct_helper< NEM::NUCMESH::HexagonalArray >()
template<> std::unique_ptr<NEM::NUCMESH::ShapeBase> NEM::DRV::JSON::construct_helper< NEM::NUCMESH::HexagonalArray > (const jsoncons::json & json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes)
Definition at line 326 of file NucMeshJson.H.
References modify_helper().
                       {
   auto shape = new NEM::NUCMESH::HexagonalArray{
       json.at("Pattern").array_value()[0].size(), {}};
   std::unique_ptr<NEM::NUCMESH::ShapeBase> out{shape};
   modify_helper(json, *shape, savedShapes, true);
   return out;
 }
construct_helper< NEM::NUCMESH::PolarArray >()
template<> std::unique_ptr<NEM::NUCMESH::ShapeBase> NEM::DRV::JSON::construct_helper< NEM::NUCMESH::PolarArray > (const jsoncons::json & json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes)
Definition at line 246 of file NucMeshJson.H.
References modify_helper().
                       {
   auto shape = new NEM::NUCMESH::PolarArray{
       json.at("Pattern").array_value().size(), {}, {}, {}};
   std::unique_ptr<NEM::NUCMESH::ShapeBase> out{shape};
   modify_helper(json, *shape, savedShapes, true);
   return out;
 }
construct_helper< NEM::NUCMESH::RectangularArray >()
template<> std::unique_ptr<NEM::NUCMESH::ShapeBase> NEM::DRV::JSON::construct_helper< NEM::NUCMESH::RectangularArray > (const jsoncons::json & json, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes)
Definition at line 286 of file NucMeshJson.H.
References modify_helper().
                       {
   auto patternJson = json.at("Pattern").array_value();
   auto shape = new NEM::NUCMESH::RectangularArray{
       {patternJson[0].size(), patternJson.size()}, {}};
   std::unique_ptr<NEM::NUCMESH::ShapeBase> out{shape};
   modify_helper(json, *shape, savedShapes, true);
   return out;
 }
gmshColorMapFromJSON()
std::map<std::array<int, 3>, std::string> NEM::DRV::JSON::gmshColorMapFromJSON (const std::vector< colorMapPair > & colorMap) inline
Definition at line 96 of file MeshGenJson.H.
References bmParams, NEM::DRV::JSON::colorMapPair::color, gmshColorMapToJSON(), NEM::DRV::JSON::colorMapPair::group, IF_CFMSH, IF_GMSH, IF_NGEN, inGeoFile, NEM::DRV::BlockMeshMeshGenDriver::Opts::meshEngine, NEM::DRV::CFMeshMeshGenDriver::Opts::meshEngine, NEM::DRV::SnappyMeshMeshGenDriver::Opts::meshEngine, NEM::DRV::GmshMeshGenDriver::Opts::meshEngine, NEM::DRV::NetgenMeshGenDriver::Opts::meshEngine, meshFiles, meshGenEngine, meshGenOpts, NEM_JSON_CHECK_KEY_ONLY, NEM_JSON_N_GETTER_SETTER_NAME_TRAITS_FINAL, NEM_JSON_N_GETTER_SETTER_NAME_TRAITS_INTERMEDIATE, NEM_JSON_N_MEMBER_NAME_TRAITS_BASE, NEM_JSON_N_MEMBER_NAME_TRAITS_FINAL, NEM_JSON_RDONLY_OVERRIDE, NEM_JSON_SMART_PTR_VAL, NEM_JSON_WRAP_SMART_PTR, outMeshFile, NEM::DRV::MeshGenDriver::programType, programType, and smParams.
{
   std::map<std::array<int, 3>, std::string> out;
   for (const auto &color : colorMap) {
     out.emplace(color.color, color.group);
   }
   return out;
 }
gmshColorMapToJSON()
std::vector<colorMapPair> NEM::DRV::JSON::gmshColorMapToJSON (const std::map< std::array< int, 3 >, std::string > & colorMap) inline
Definition at line 86 of file MeshGenJson.H.
Referenced by gmshColorMapFromJSON().
{
   std::vector<colorMapPair> out(colorMap.size());
   std::transform(colorMap.begin(), colorMap.end(), out.begin(),
                  [](const std::pair<const std::array<int, 3>, std::string> &x) {
                    return colorMapPair{x.first, x.second};
                  });
   return out;
 }
modify_helper() [1/8]
template<typename T > std::enable_if<std::is_base_of<NEM::NUCMESH::ShapeBase, T>::value, void>::type NEM::DRV::JSON::modify_helper (const jsoncons::json & json, T & shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes, bool checkRequired)
Definition at line 112 of file NucMeshJson.H.
Referenced by construct_from_alias_helper(), construct_helper< NEM::NUCMESH::Circles >(), construct_helper< NEM::NUCMESH::CirclesAndPolys >(), construct_helper< NEM::NUCMESH::HexagonalArray >(), construct_helper< NEM::NUCMESH::PolarArray >(), construct_helper< NEM::NUCMESH::RectangularArray >(), and modify_helper().
                         {}
modify_helper() [2/8]
template<> void NEM::DRV::JSON::modify_helper (const jsoncons::json & json, NEM::NUCMESH::ShapeBase & shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & , bool)
Definition at line 119 of file NucMeshJson.H.
References NEM::NUCMESH::ShapeBase::getRotatedPoint(), and NEM::NUCMESH::ShapeBase::setCenter().
           {
   if (json.contains("Center")) {
     auto centerSize = json.at("Center").array_value().size();
     if (centerSize == 3) {
       shape.setCenter(json.at("Center").as<std::array<double, 3>>());
     } else if (centerSize == 5) {
       auto center = json.at("Center").as<std::array<double, 5>>();
       shape.setCenter(NEM::NUCMESH::ShapeBase::getRotatedPoint(
           {center[0], center[1], center[2]}, {center[3], center[4]}));
     }
   }
 }
modify_helper() [3/8]
template<> void NEM::DRV::JSON::modify_helper (const jsoncons::json & json, NEM::NUCMESH::Circles & shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes, bool checkRequired)
Definition at line 136 of file NucMeshJson.H.
References modify_helper(), NEM::NUCMESH::Circles::setRings(), and setter_helper().
{
   setter_helper(shape, &NEM::NUCMESH::Circles::setRings, json, "Rings",
                 checkRequired);
   modify_helper(json, dynamic_cast<NEM::NUCMESH::ShapeBase &>(shape),
                 savedShapes, checkRequired);
 }
modify_helper() [4/8]
template<> void NEM::DRV::JSON::modify_helper (const jsoncons::json & json, NEM::NUCMESH::CirclesAndPolys & shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes, bool checkRequired)
Definition at line 160 of file NucMeshJson.H.
References modify_helper(), NEM::NUCMESH::CirclesAndPolys::setNumSides(), NEM::NUCMESH::CirclesAndPolys::setRings(), and setter_helper().
{
   setter_helper(shape, &NEM::NUCMESH::CirclesAndPolys::setNumSides, json,
                 "Number of Sides", checkRequired);
   setter_helper(shape, &NEM::NUCMESH::CirclesAndPolys::setRings, json, "Rings",
                 checkRequired);
   modify_helper(json, dynamic_cast<NEM::NUCMESH::ShapeBase &>(shape),
                 savedShapes, checkRequired);
 }
modify_helper() [5/8]
template<> void NEM::DRV::JSON::modify_helper (const jsoncons::json & json, NEM::NUCMESH::ShapesArray & shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes, bool checkRequired)
Definition at line 186 of file NucMeshJson.H.
References as_shape(), NEM::NUCMESH::ShapesArray::getNumPatternShapes(), modify_helper(), and NEM::NUCMESH::ShapesArray::setPatternShape().
{
   if (json.contains(arrayShapes) && json.at(arrayShapes).is_array()) {
     std::size_t idx = 0;
     for (auto &shapeJson : json.at(arrayShapes).array_range()) {
       shape.setPatternShape(idx, as_shape(shapeJson, savedShapes));
       ++idx;
     }
     for (; idx < shape.getNumPatternShapes(); ++idx) {
       shape.setPatternShape(idx, nullptr);
     }
   } else if (checkRequired) {
     throw jsoncons::convert_error(jsoncons::convert_errc::conversion_failed,
                                   "Not a NEM::NUCMESH::ShapesArray");
   }
   modify_helper(json, dynamic_cast<NEM::NUCMESH::ShapeBase &>(shape),
                 savedShapes, checkRequired);
 }
modify_helper() [6/8]
template<> void NEM::DRV::JSON::modify_helper (const jsoncons::json & json, NEM::NUCMESH::PolarArray & shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes, bool checkRequired)
Definition at line 209 of file NucMeshJson.H.
References NEM::NUCMESH::PolarArray::getNumSubshapes(), modify_helper(), NEM::NUCMESH::PolarArray::setEndAngle(), NEM::NUCMESH::ShapesArray::setPattern(), NEM::NUCMESH::PolarArray::setRadius(), NEM::NUCMESH::PolarArray::setRotateWithArray(), NEM::NUCMESH::PolarArray::setStartAngle(), and setter_helper().
{
   setter_helper(shape, &NEM::NUCMESH::PolarArray::setRadius, json, "Radius",
                 checkRequired);
   setter_helper(shape, &NEM::NUCMESH::PolarArray::setStartAngle, json,
                 "Start Angle", checkRequired);
   setter_helper(shape, &NEM::NUCMESH::PolarArray::setEndAngle, json,
                 "End Angle", checkRequired);
   setter_helper(shape, &NEM::NUCMESH::PolarArray::setRotateWithArray, json,
                 "Rotate with Array", false);
   if (json.contains(arrayPattern)) {
     auto patternIdJson = json.at(arrayPattern).array_value();
     if (!patternIdJson.empty()) {
       auto patternIdIter = patternIdJson.begin();
       const auto patternIdEnd = patternIdJson.end();
       for (std::size_t patternIdx = 0; patternIdx < shape.getNumSubshapes();
            ++patternIdx) {
         shape.setPattern(patternIdx, patternIdIter->as<std::size_t>());
         ++patternIdIter;
         if (patternIdIter == patternIdEnd) {
           patternIdIter = patternIdJson.begin();
         }
       }
     }
   } else if (checkRequired) {
     throw jsoncons::convert_error(jsoncons::convert_errc::conversion_failed,
                                   "Not a NEM::NUCMESH::PolarArray");
   }
   modify_helper(json, dynamic_cast<NEM::NUCMESH::ShapesArray &>(shape),
                 savedShapes, checkRequired);
 }
modify_helper() [7/8]
template<> void NEM::DRV::JSON::modify_helper (const jsoncons::json & json, NEM::NUCMESH::RectangularArray & shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes, bool checkRequired)
Definition at line 258 of file NucMeshJson.H.
References NEM::NUCMESH::RectangularArray::getGridDims(), modify_helper(), NEM::NUCMESH::RectangularArray::setGridDistance(), NEM::NUCMESH::RectangularArray::setPattern(), and setter_helper().
{
   setter_helper(shape, &NEM::NUCMESH::RectangularArray::setGridDistance, json,
                 "Grid Distance", checkRequired);
   if (json.contains(arrayPattern)) {
     const auto gridSize = shape.getGridDims();
     auto y = gridSize[1] - 1;
     for (auto &patternRow : json.at(arrayPattern).array_range()) {
       std::size_t x = 0;
       for (auto &patternJson : patternRow.array_range()) {
         shape.setPattern(x, y, patternJson.as<std::size_t>());
         ++x;
       }
       --y;
     }
   } else if (checkRequired) {
     throw jsoncons::convert_error(jsoncons::convert_errc::conversion_failed,
                                   "Not a NEM::NUCMESH::RectangularArray");
   }
   modify_helper(json, dynamic_cast<NEM::NUCMESH::ShapesArray &>(shape),
                 savedShapes, checkRequired);
 }
modify_helper() [8/8]
template<> void NEM::DRV::JSON::modify_helper (const jsoncons::json & json, NEM::NUCMESH::HexagonalArray & shape, const std::map< std::string, std::unique_ptr< NEM::NUCMESH::ShapeBase >> & savedShapes, bool checkRequired)
Definition at line 299 of file NucMeshJson.H.
References modify_helper(), NEM::NUCMESH::HexagonalArray::setGridDistance(), NEM::NUCMESH::HexagonalArray::setPatternRowCol(), and setter_helper().
{
   setter_helper(shape, &NEM::NUCMESH::HexagonalArray::setGridDistance, json,
                 "Grid Distance", checkRequired);
   if (json.contains(arrayPattern)) {
     int x = 0;
     for (auto &patternRow : json.at(arrayPattern).array_range()) {
       int y = 0;
       for (auto &patternJson : patternRow.array_range()) {
         shape.setPatternRowCol(x, y, patternJson.as<std::size_t>());
         ++y;
       }
       ++x;
     }
   } else if (checkRequired) {
     throw jsoncons::convert_error(jsoncons::convert_errc::conversion_failed,
                                   "Not a NEM::NUCMESH::HexagonalArray");
   }
   modify_helper(json, dynamic_cast<NEM::NUCMESH::ShapesArray &>(shape),
                 savedShapes, checkRequired);
 }
pntMeshBcTagFromJSON()
std::vector<PNTMesh::surfaceBCTag> NEM::DRV::JSON::pntMeshBcTagFromJSON (const std::string & input) inline
Definition at line 72 of file ConversionJson.H.
References PNTMesh::bcTagNum().
Referenced by rangeToVec().
{
   return {PNTMesh::bcTagNum(input)};
 }
pntMeshBcTagToJSON()
std::string NEM::DRV::JSON::pntMeshBcTagToJSON (const std::vector< PNTMesh::surfaceBCTag > & input) inline
Definition at line 77 of file ConversionJson.H.
References PNTMesh::bcTagStr().
Referenced by rangeToVec().
{
   return input.empty() ? std::string{} : PNTMesh::bcTagStr(input.at(0));
 }
rangeToVec()
std::vector<int> NEM::DRV::JSON::rangeToVec (const std::pair< int, int > & input) inline
Definition at line 82 of file ConversionJson.H.
References NEM::DRV::VtkToPatranConversionDriver::FaceBC::bcType, NEM::DRV::VtkToPatranConversionDriver::NodeBC::bcType, convMethod, convOptions, PNTMesh::elmTypeNum(), PNTMesh::elmTypeStr(), IF_CFMSH, IF_CFMSH_GMSH, inMeshFile, meshFiles, NEM::DRV::VtkToPntConversionDriver::Opts::methodName, NEM::DRV::ManipExoConversionDriver::Opts::methodName, NEM::DRV::FoamToMshConversionDriver::Opts::methodName, NEM::DRV::FoamToVtkConversionDriver::Opts::methodName, NEM::DRV::GmshToVtkConversionDriver::Opts::methodName, NEM::DRV::SmartConversionDriver::Opts::methodName, NEM::DRV::VtkHexToTetConversionDriver::Opts::methodName, NEM::DRV::VtkToFoamConversionDriver::Opts::methodName, NEM::DRV::VtkToCobaltConversionDriver::Opts::methodName, NEM::DRV::GmshToExoConversionDriver::Opts::methodName, NEM::DRV::VtkToPatranConversionDriver::Opts::methodName, NEM_JSON_CHECK_KEY_ONLY, NEM_JSON_N_GETTER_SETTER_NAME_TRAITS_FINAL, NEM_JSON_N_GETTER_SETTER_NAME_TRAITS_INTERMEDIATE, NEM_JSON_N_MEMBER_NAME_TRAITS_BASE, NEM_JSON_N_MEMBER_NAME_TRAITS_FINAL, NEM_JSON_N_MEMBER_NAME_TRAITS_VAL, NEM_JSON_RDONLY_OVERRIDE, NEM_JSON_RDWR_OVERRIDE, NEM_JSON_WRAP_SMART_PTR, outMeshFile, PAIR_INT_DUMMY_FUNC, pntMeshBcTagFromJSON(), pntMeshBcTagToJSON(), NEM::DRV::ConversionDriver::programType, and programType.
{
   std::vector<int> out(input.second - input.first + 1);
   std::iota(out.begin(), out.end(), input.first);
   return out;
 }
setter_helper()
template<typename T , typename R , typename... Args> void NEM::DRV::JSON::setter_helper (T & obj, R(T::*)(Args...) setter, const jsoncons::json & json, jsoncons::string_view key, bool checkContains)
Definition at line 86 of file NucMeshJson.H.
References as_shape(), and construct_helper().
Referenced by modify_helper().
{
   if (json.contains(key)) {
     (obj.*setter)(json.at(key)
                       .as<typename std::decay<
                           first_argument_type<decltype(setter)>>::type>());
   } else if (checkContains) {
     throw jsoncons::convert_error(jsoncons::convert_errc::conversion_failed,
                                   "Not a NEM::NUCMESH::ShapeBase");
   }
 }
Variable Documentation
arrayPattern
constexpr auto NEM::DRV::JSON::arrayPattern = "Pattern" static
Definition at line 82 of file NucMeshJson.H.
arrayShapes
constexpr auto NEM::DRV::JSON::arrayShapes = "Shapes" static
Definition at line 83 of file NucMeshJson.H.
Referenced by as_shape().
bmParams
constexpr auto NEM::DRV::JSON::bmParams = "blockMesh Parameters" static
Definition at line 89 of file DriverJsonTypeTraits.H.
Referenced by gmshColorMapFromJSON().
convMethod
constexpr auto NEM::DRV::JSON::convMethod = "Method" static
Definition at line 70 of file ConversionJson.H.
Referenced by rangeToVec().
convOptions
constexpr auto NEM::DRV::JSON::convOptions = "Conversion Options" static
Definition at line 69 of file ConversionJson.H.
Referenced by rangeToVec().
inGeoFile
constexpr auto NEM::DRV::JSON::inGeoFile = "Input Geometry File" static
Definition at line 87 of file DriverJsonTypeTraits.H.
Referenced by gmshColorMapFromJSON().
inMeshFile
constexpr auto NEM::DRV::JSON::inMeshFile = "Input Mesh File" static
Definition at line 86 of file DriverJsonTypeTraits.H.
Referenced by rangeToVec().
meshFiles
constexpr auto NEM::DRV::JSON::meshFiles = "Mesh File Options" static
Definition at line 85 of file DriverJsonTypeTraits.H.
Referenced by as_shape(), gmshColorMapFromJSON(), and rangeToVec().
meshGenEngine
constexpr auto NEM::DRV::JSON::meshGenEngine = "Mesh Generation Engine" static
Definition at line 79 of file MeshGenJson.H.
Referenced by gmshColorMapFromJSON().
meshGenOpts
constexpr auto NEM::DRV::JSON::meshGenOpts = "Mesh Generation Options" static
Definition at line 78 of file MeshGenJson.H.
Referenced by gmshColorMapFromJSON().
meshQualEngine
constexpr auto NEM::DRV::JSON::meshQualEngine = "Mesh Quality Engine" static
Definition at line 48 of file MeshQualityJson.H.
meshQualOpts
constexpr auto NEM::DRV::JSON::meshQualOpts = "Mesh Quality Options" static
Definition at line 47 of file MeshQualityJson.H.
outMeshFile
constexpr auto NEM::DRV::JSON::outMeshFile = "Output Mesh File" static
Definition at line 88 of file DriverJsonTypeTraits.H.
Referenced by gmshColorMapFromJSON(), and rangeToVec().
packMeshOpts
constexpr auto NEM::DRV::JSON::packMeshOpts = "Pack Mesh Options" static
Definition at line 55 of file PackMeshJson.H.
programType
constexpr auto NEM::DRV::JSON::programType = "Program Type" static
Definition at line 84 of file DriverJsonTypeTraits.H.
Referenced by as_shape(), gmshColorMapFromJSON(), and rangeToVec().
refMethod
constexpr auto NEM::DRV::JSON::refMethod = "Refinement Method" static
Definition at line 66 of file RefineJson.H.
refOperator
constexpr auto NEM::DRV::JSON::refOperator = "Refinement Operator" static
Definition at line 65 of file RefineJson.H.
refOpts
constexpr auto NEM::DRV::JSON::refOpts = "Refinement Options" static
Definition at line 64 of file RefineJson.H.
refTransferData
constexpr auto NEM::DRV::JSON::refTransferData = "Transfer Data" static
Definition at line 67 of file RefineJson.H.
shapeType
constexpr auto NEM::DRV::JSON::shapeType = "Type" static
Definition at line 81 of file NucMeshJson.H.
Referenced by NEM::NUCMESH::ShapesArray::basicTransformation(), NEM::NUCMESH::NucMeshGeo::computeMesh(), NEM::NUCMESH::ShapeBase::mergeGeo(), NEM::GEO::GeoManager::modify(), NEM::GEO::modifyTempl(), and NEM::NUCMESH::PolyRing::PolyRing().
smParams
constexpr auto NEM::DRV::JSON::smParams = "snappyHexMesh Parameters" static
Definition at line 90 of file DriverJsonTypeTraits.H.
Referenced by gmshColorMapFromJSON().