NEMoSys: PNTMesh Namespace Reference
PNTMesh Namespace Reference
Classes
struct blockType
class pntMesh
Typedefs
using idTyp = int
using BlockMap = std::vector< blockType >
Enumerations
enum elementType {
elementType::BAR, elementType::QUADRILATERAL, elementType::TRIANGLE, elementType::HEXAGON,
elementType::SPHERICAL, elementType::CYLINDRICAL, elementType::BRICK, elementType::LAGRANGE_BRICK,
elementType::TETRAHEDRON, elementType::HEXPRISM, elementType::PRISMATIC, elementType::OTHER
}
enum surfaceBCTag { surfaceBCTag::REFLECTIVE, surfaceBCTag::VOID }
Functions
VTKCellType p2vEMap (elementType et)
elementType v2pEMap (VTKCellType vt)
surfaceBCTag bcTagNum (const std::string &tag)
std::string bcTagStr (surfaceBCTag tag)
elementType elmTypeNum (const std::string &tag)
std::string elmTypeStr (elementType tag)
int elmNumNde (elementType et, int order)
int elmNumSrf (elementType et)
Typedef Documentation
BlockMap
using PNTMesh::BlockMap = typedef std::vector<blockType>
Definition at line 86 of file pntMesh.H.
idTyp
using PNTMesh::idTyp = typedef int
Definition at line 45 of file pntMesh.H.
Enumeration Type Documentation
elementType
enum PNTMesh::elementType strong
Enumerator
BAR
QUADRILATERAL
TRIANGLE
HEXAGON
SPHERICAL
CYLINDRICAL
BRICK
LAGRANGE_BRICK
TETRAHEDRON
HEXPRISM
PRISMATIC
OTHER
Definition at line 47 of file pntMesh.H.
{
   BAR,
   QUADRILATERAL,
   TRIANGLE,
   HEXAGON,
   SPHERICAL,
   CYLINDRICAL,
   BRICK,
   LAGRANGE_BRICK,
   TETRAHEDRON,
   HEXPRISM,
   PRISMATIC,
   OTHER
 };
surfaceBCTag
enum PNTMesh::surfaceBCTag strong
Enumerator
REFLECTIVE
VOID
Definition at line 62 of file pntMesh.H.
{
   REFLECTIVE,
   VOID
 };
Function Documentation
bcTagNum()
PNTMesh::surfaceBCTag PNTMesh::bcTagNum (const std::string & tag)
Definition at line 78 of file pntMesh.C.
References nemAux::toLower().
Referenced by PNTMesh::pntMesh::pntMesh(), and NEM::DRV::JSON::pntMeshBcTagFromJSON().
 {
   std::string tag = _tag;
   nemAux::toLower(tag);
   if (tag == "reflective") return surfaceBCTag::REFLECTIVE;
   if (tag == "void") return surfaceBCTag::VOID;
   std::cerr << "Unknown surface tag " << tag << std::endl;
   throw;
 }
bcTagStr()
std::string PNTMesh::bcTagStr (surfaceBCTag tag)
Definition at line 88 of file pntMesh.C.
Referenced by NEM::DRV::JSON::pntMeshBcTagToJSON(), and PNTMesh::pntMesh::write().
 {
   switch (tag) {
     case surfaceBCTag::REFLECTIVE: return "REFLECTIVE";
     case surfaceBCTag::VOID: return "VOID";
   }
   throw;
 }
elmNumNde()
int PNTMesh::elmNumNde (elementType et, int order)
Definition at line 133 of file pntMesh.C.
References TRIANGLE.
Referenced by PNTMesh::pntMesh::pntMesh().
 {
   if (tag == elementType::BAR) return (2 + order - 1);
   if (tag == elementType::QUADRILATERAL && order == 1) return 4;
   if (tag == elementType::QUADRILATERAL && order == 2) return 8;
   if (tag == elementType::TRIANGLE && order == 1) return 3;
   if (tag == elementType::TRIANGLE && order == 2) return 6;
   if (tag == elementType::HEXAGON && order == 1) return 8;
   if (tag == elementType::HEXAGON && order == 2) return 27;
   if (tag == elementType::BRICK && order == 1) return 8;
   if (tag == elementType::BRICK && order == 2) return 27;
   if (tag == elementType::LAGRANGE_BRICK && order == 1) return 8;
   if (tag == elementType::LAGRANGE_BRICK && order == 2) return 27;
   if (tag == elementType::TETRAHEDRON && order == 1) return 4;
   if (tag == elementType::TETRAHEDRON && order == 2) return 10;
   if (tag == elementType::HEXPRISM && order == 1) return 16;
   if (tag == elementType::PRISMATIC && order == 1) return 6;
   if (tag == elementType::PRISMATIC && order == 2) return 15;
   std::cerr << "Unknown element/order combination\n";
   throw;
 }
elmNumSrf()
int PNTMesh::elmNumSrf (elementType et)
Definition at line 155 of file pntMesh.C.
References TRIANGLE.
Referenced by PNTMesh::pntMesh::pntMesh().
 {
   if (tag == elementType::BAR) return 2;
   if (tag == elementType::QUADRILATERAL) return 4;
   if (tag == elementType::TRIANGLE) return 3;
   if (tag == elementType::HEXAGON) return 8;
   if (tag == elementType::BRICK) return 6;
   if (tag == elementType::LAGRANGE_BRICK) return 6;
   if (tag == elementType::TETRAHEDRON) return 4;
   if (tag == elementType::HEXPRISM) return 10;
   if (tag == elementType::PRISMATIC) return 6;
   std::cerr << "Unknown element type\n";
   throw;
 }
elmTypeNum()
PNTMesh::elementType PNTMesh::elmTypeNum (const std::string & tag)
Definition at line 97 of file pntMesh.C.
References nemAux::toLower(), and TRIANGLE.
Referenced by PNTMesh::pntMesh::pntMesh(), and NEM::DRV::JSON::rangeToVec().
 {
   std::string tag = _tag;
   nemAux::toLower(tag);
   if (tag == "bar") return elementType::BAR;
   if (tag == "quadrilateral") return elementType::QUADRILATERAL;
   if (tag == "triangle") return elementType::TRIANGLE;
   if (tag == "hexagon") return elementType::HEXAGON;
   if (tag == "spherical") return elementType::SPHERICAL;
   if (tag == "cylindrical") return elementType::CYLINDRICAL;
   if (tag == "brick") return elementType::BRICK;
   if (tag == "lagrange_brick") return elementType::LAGRANGE_BRICK;
   if (tag == "tetrahedron") return elementType::TETRAHEDRON;
   if (tag == "hexprism") return elementType::HEXPRISM;
   if (tag == "prismatic") return elementType::PRISMATIC;
   std::cout << "Warning : Element type " << tag << " may be not supported"
             << std::endl;
   return elementType::OTHER;
 }
elmTypeStr()
std::string PNTMesh::elmTypeStr (elementType tag)
Definition at line 117 of file pntMesh.C.
References TRIANGLE.
Referenced by PNTMesh::pntMesh::pntMesh(), NEM::DRV::JSON::rangeToVec(), and PNTMesh::pntMesh::write().
 {
   if (tag == elementType::BAR) return "BAR";
   if (tag == elementType::QUADRILATERAL) return "QUADRILATERAL";
   if (tag == elementType::TRIANGLE) return "TRIANGLE";
   if (tag == elementType::HEXAGON) return "HEXAGON";
   if (tag == elementType::SPHERICAL) return "SPHERICAL";
   if (tag == elementType::CYLINDRICAL) return "CYLINDRICAL";
   if (tag == elementType::BRICK) return "BRICK";
   if (tag == elementType::LAGRANGE_BRICK) return "LAGRANGE_BRICK";
   if (tag == elementType::TETRAHEDRON) return "TETRAHEDRON";
   if (tag == elementType::HEXPRISM) return "HEXPRISM";
   if (tag == elementType::PRISMATIC) return "PRISMATIC";
   return "OTHER";
 }
p2vEMap()
VTKCellType PNTMesh::p2vEMap (elementType et)
Definition at line 38 of file pntMesh.C.
References TRIANGLE.
 {
   std::map<elementType, VTKCellType> eMap =
       {
           {elementType::BAR,            VTK_LINE},
           {elementType::QUADRILATERAL,  VTK_QUAD},
           {elementType::TRIANGLE,       VTK_TRIANGLE},
           {elementType::HEXAGON,        VTK_HEXAHEDRON},
           {elementType::SPHERICAL,      VTK_EMPTY_CELL},
           {elementType::CYLINDRICAL,    VTK_EMPTY_CELL},
           {elementType::BRICK,          VTK_HEXAHEDRON},
           {elementType::LAGRANGE_BRICK, VTK_HEXAHEDRON},
           {elementType::TETRAHEDRON,    VTK_TETRA},
           {elementType::HEXPRISM,       VTK_HEXAGONAL_PRISM},
           {elementType::PRISMATIC,      VTK_WEDGE},
           {elementType::OTHER,          VTK_EMPTY_CELL}
       };
   return eMap[et];
 }
v2pEMap()
PNTMesh::elementType PNTMesh::v2pEMap (VTKCellType vt)
Definition at line 58 of file pntMesh.C.
References TRIANGLE.
Referenced by PNTMesh::pntMesh::pntMesh().
 {
   std::map<VTKCellType, elementType> eMap =
       {
           {VTK_LINE,                 elementType::BAR},
           {VTK_QUAD,                 elementType::QUADRILATERAL},
           {VTK_QUADRATIC_QUAD,       elementType::QUADRILATERAL},
           {VTK_TRIANGLE,             elementType::TRIANGLE},
           {VTK_QUADRATIC_TRIANGLE,   elementType::TRIANGLE},
           {VTK_HEXAHEDRON,           elementType::HEXAGON},
           {VTK_QUADRATIC_HEXAHEDRON, elementType::HEXAGON},
           {VTK_TETRA,                elementType::TETRAHEDRON},
           {VTK_QUADRATIC_TETRA,      elementType::TETRAHEDRON},
           {VTK_HEXAGONAL_PRISM,      elementType::HEXPRISM},
           {VTK_WEDGE,                elementType::PRISMATIC},
           {VTK_EMPTY_CELL,           elementType::OTHER}
       };
   return eMap[vt];
 }