NEMoSys: orthoPoly3D.C File Reference
orthoPoly3D.C File Reference
Functions
void removeColumn (MatrixXd &matrix, unsigned int colToRemove)
void removeColumn (const MatrixXd &matrix, MatrixXd &matrix_red, const std::vector< unsigned int > &toRemove)
void removeRowT (const MatrixXd &matrix, MatrixXdRM &matrix_red, const std::vector< unsigned int > &toRemove)
Function Documentation
removeColumn() [1/2]
void removeColumn (MatrixXd & matrix, unsigned int colToRemove)
Definition at line 42 of file orthoPoly3D.C.
Referenced by orthoPoly3D::eval(), and orthoPoly3D::operator()().
 {
   unsigned int numRows = matrix.rows();
   unsigned int numCols = matrix.cols() - 1;
   if (colToRemove < numCols)
     matrix.block(0, colToRemove, numRows, numCols - colToRemove) =
         matrix.rightCols(numCols - colToRemove);
   matrix.conservativeResize(numRows, numCols);
 }
removeColumn() [2/2]
void removeColumn (const MatrixXd & matrix, MatrixXd & matrix_red, const std::vector< unsigned int > & toRemove)
Definition at line 57 of file orthoPoly3D.C.
 {
   int m = 0;
   for (int i = 0; i < matrix.cols(); ++i)
   {
     bool remove = false;
     for (unsigned int k : toRemove)
     {
       if (i == k)
       {
         remove = true;
         break;
       }
     }
     if (!remove)
     {
       matrix_red.col(m) = matrix.col(i);
       m += 1;
     }
   }
 }
removeRowT()
void removeRowT (const MatrixXd & matrix, MatrixXdRM & matrix_red, const std::vector< unsigned int > & toRemove)
Definition at line 85 of file orthoPoly3D.C.
Referenced by orthoPoly3D::computeA().
 {
   int m = 0;
   for (int i = 0; i < matrix.cols(); ++i)
   {
     bool remove = false;
     for (unsigned int k : toRemove)
     {
       if (i == k)
       {
         remove = true;
         break;
       }
     }
     if (!remove)
     {
       matrix_red.row(m) = matrix.col(i);
       m += 1;
     }
   }
 }