NEMoSys: NEM::DRV::HexPackMeshDriver::Files Struct Reference
NEM::DRV::HexPackMeshDriver::Files Struct Reference
Detailed Description
Definition at line 61 of file HexPackMeshDriver.H.
Public Member Functions
Files (std::string inputFile, bool isRocpack, std::string outPackMeshFile, std::string outSurroundingFile)
void setRocpackFile (std::string rocpackFile)
void setGeoFile (std::string geoFile)
const std::string & getInputFile () const
bool isInputRocpackFile () const
Public Attributes
std::string outPackMeshFile {}
std::string outSurroundingFile {}
std::string outCombinedFile {"PackMesh.vtu"}
Combined mesh file name.
Private Member Functions
Files ()=default
Private Attributes
std::string rocpackOrGeoFile {}
bool useRocpack {}
Constructor & Destructor Documentation
Files() [1/2]
NEM::DRV::HexPackMeshDriver::Files::Files (std::string inputFile, bool isRocpack, std::string outPackMeshFile, std::string outSurroundingFile)
Parameters
inputFile Input surface file name
isRocpack Boolean for using rocpack to generate an STL
outPackMeshFile Pack mesh output filename.extension
outSurroundingFile Surrounding mesh output filename.extension
Definition at line 43 of file HexPackMeshDriver.C.
     : outPackMeshFile(std::move(outPackMeshFile)),
       outSurroundingFile(std::move(outSurroundingFile)),
       rocpackOrGeoFile(std::move(inputFile)),
       useRocpack(isRocpack) {}
Files() [2/2]
NEM::DRV::HexPackMeshDriver::Files::Files () private default
Member Function Documentation
getInputFile()
const std::string & NEM::DRV::HexPackMeshDriver::Files::getInputFile () const
Definition at line 61 of file HexPackMeshDriver.C.
References rocpackOrGeoFile.
Referenced by NEM::DRV::HexPackMeshDriver::execute(), NEM::DRV::HexPackMeshDriver::setFiles(), and NEM::DRV::HexPackMeshDriver::setOpts().
{
   return rocpackOrGeoFile;
 }
isInputRocpackFile()
bool NEM::DRV::HexPackMeshDriver::Files::isInputRocpackFile () const
Definition at line 65 of file HexPackMeshDriver.C.
References useRocpack.
Referenced by NEM::DRV::HexPackMeshDriver::execute(), NEM::DRV::HexPackMeshDriver::setFiles(), and NEM::DRV::HexPackMeshDriver::setOpts().
 { return useRocpack; }
setGeoFile()
void NEM::DRV::HexPackMeshDriver::Files::setGeoFile (std::string geoFile)
Definition at line 56 of file HexPackMeshDriver.C.
References rocpackOrGeoFile, and useRocpack.
{
   rocpackOrGeoFile = std::move(geoFile);
   useRocpack = false;
 }
setRocpackFile()
void NEM::DRV::HexPackMeshDriver::Files::setRocpackFile (std::string rocpackFile)
Definition at line 51 of file HexPackMeshDriver.C.
References rocpackOrGeoFile, and useRocpack.
{
   rocpackOrGeoFile = std::move(rocpackFile);
   useRocpack = true;
 }
Member Data Documentation
outCombinedFile
std::string NEM::DRV::HexPackMeshDriver::Files::outCombinedFile {"PackMesh.vtu"}
Definition at line 81 of file HexPackMeshDriver.H.
Referenced by NEM::DRV::HexPackMeshDriver::execute().
outPackMeshFile
std::string NEM::DRV::HexPackMeshDriver::Files::outPackMeshFile {}
Definition at line 76 of file HexPackMeshDriver.H.
outSurroundingFile
std::string NEM::DRV::HexPackMeshDriver::Files::outSurroundingFile {}
Definition at line 77 of file HexPackMeshDriver.H.
rocpackOrGeoFile
std::string NEM::DRV::HexPackMeshDriver::Files::rocpackOrGeoFile {} private
Definition at line 85 of file HexPackMeshDriver.H.
Referenced by getInputFile(), setGeoFile(), and setRocpackFile().
useRocpack
bool NEM::DRV::HexPackMeshDriver::Files::useRocpack {} private
Definition at line 86 of file HexPackMeshDriver.H.
Referenced by isInputRocpackFile(), setGeoFile(), and setRocpackFile().
The documentation for this struct was generated from the following files:
HexPackMeshDriver.H
HexPackMeshDriver.C