NEMoSys: NEM::MSH::geoMeshBase::SideSet Struct Reference
NEM::MSH::geoMeshBase::SideSet Struct Reference
Detailed Description
Definition at line 390 of file geoMeshBase.H.
Public Member Functions
SideSet (vtkPolyData *sideSet, vtkIntArray *geoEnt, vtkIdTypeArray *origCell=nullptr, vtkIntArray *cellFace=nullptr, vtkStringArray *setNames=nullptr)
SideSet ()=default
SideSet (vtkPolyData *sides)
vtkSmartPointer< vtkIntArray > getGeoEntArr () const
void setGeoEntArr (vtkIntArray *arr)
vtkSmartPointer< vtkIdTypeArray > getOrigCellArr () const
void setOrigCellArr (vtkIdTypeArray *arr)
vtkSmartPointer< vtkIntArray > getCellFaceArr () const
void setCellFaceArr (vtkIntArray *arr)
vtkSmartPointer< vtkStringArray > getSideSetNames () const
void setSideSetNamesArr (vtkStringArray *arr)
Public Attributes
vtkSmartPointer< vtkPolyData > sides {nullptr}
Cells represent edges/faces of some GeoMesh.
Static Private Attributes
static constexpr auto GEO_ENT_NAME = "GeoEnt"
static constexpr auto ORIG_CELL_NAME = "OrigCellIds"
static constexpr auto CELL_FACE_NAME = "CellFaceIds"
static constexpr auto NAME_ARR_NAME = "Side Set Names"
Constructor & Destructor Documentation
SideSet() [1/3]
NEM::MSH::geoMeshBase::SideSet::SideSet (vtkPolyData * sideSet, vtkIntArray * geoEnt, vtkIdTypeArray * origCell = nullptr, vtkIntArray * cellFace = nullptr, vtkStringArray * setNames = nullptr)
Definition at line 239 of file geoMeshBase.C.
References GEO_ENT_NAME, setCellFaceArr(), setGeoEntArr(), setOrigCellArr(), and setSideSetNamesArr().
     : sides(sideSet) {
   assert(geoEnt || sideSet->GetCellData()->HasArray(GEO_ENT_NAME));
   if (geoEnt) { setGeoEntArr(geoEnt); }
   if (origCell) { setOrigCellArr(origCell); }
   if (cellFace) { setCellFaceArr(cellFace); }
   if (setNames) { setSideSetNamesArr(setNames); }
 }
SideSet() [2/3]
NEM::MSH::geoMeshBase::SideSet::SideSet () default
SideSet() [3/3]
NEM::MSH::geoMeshBase::SideSet::SideSet (vtkPolyData * sides) explicit
Definition at line 250 of file geoMeshBase.C.
 : SideSet(sides, nullptr) {}
Member Function Documentation
getCellFaceArr()
vtkSmartPointer< vtkIntArray > NEM::MSH::geoMeshBase::SideSet::getCellFaceArr () const
Definition at line 281 of file geoMeshBase.C.
References CELL_FACE_NAME, and sides.
{
   return sides ? vtkIntArray::FastDownCast(
                      sides->GetCellData()->GetAbstractArray(CELL_FACE_NAME))
                : nullptr;
 }
getGeoEntArr()
vtkSmartPointer< vtkIntArray > NEM::MSH::geoMeshBase::SideSet::getGeoEntArr () const
Definition at line 252 of file geoMeshBase.C.
References GEO_ENT_NAME, and sides.
Referenced by NEM::MSH::exoGeoMesh::addSideSet(), NEM::MSH::gmshGeoMesh::GM2gmsh(), NEM::MSH::oshGeoMesh::GM2osh(), NEM::MSH::smeshGeoMesh::GMToSMESH(), and NEM::MSH::exoGeoMesh::stitch().
{
   return sides ? vtkIntArray::FastDownCast(
                      sides->GetCellData()->GetArray(GEO_ENT_NAME))
                : nullptr;
 }
getOrigCellArr()
vtkSmartPointer< vtkIdTypeArray > NEM::MSH::geoMeshBase::SideSet::getOrigCellArr () const
Definition at line 264 of file geoMeshBase.C.
References ORIG_CELL_NAME, and sides.
{
   return sides ? vtkIdTypeArray::FastDownCast(
                      sides->GetCellData()->GetAbstractArray(ORIG_CELL_NAME))
                : nullptr;
 }
getSideSetNames()
vtkSmartPointer< vtkStringArray > NEM::MSH::geoMeshBase::SideSet::getSideSetNames () const
Definition at line 298 of file geoMeshBase.C.
References NAME_ARR_NAME, and sides.
Referenced by NEM::MSH::smeshGeoMesh::GMToSMESH().
{
   return sides ? vtkStringArray::SafeDownCast(
                      sides->GetFieldData()->GetAbstractArray(NAME_ARR_NAME))
                : nullptr;
 }
setCellFaceArr()
void NEM::MSH::geoMeshBase::SideSet::setCellFaceArr (vtkIntArray * arr)
Definition at line 287 of file geoMeshBase.C.
References CELL_FACE_NAME, and sides.
Referenced by SideSet().
{
   if (arr) {
     assert(arr->GetNumberOfTuples() == sides->GetNumberOfCells() &&
            arr->GetNumberOfComponents() == 2);
     arr->SetName(CELL_FACE_NAME);
     sides->GetCellData()->AddArray(arr);
   } else {
     sides->GetCellData()->RemoveArray(CELL_FACE_NAME);
   }
 }
setGeoEntArr()
void NEM::MSH::geoMeshBase::SideSet::setGeoEntArr (vtkIntArray * arr)
Definition at line 258 of file geoMeshBase.C.
References GEO_ENT_NAME, and sides.
Referenced by SideSet().
{
   assert(arr);
   arr->SetName(GEO_ENT_NAME);
   sides->GetCellData()->AddArray(arr);
 }
setOrigCellArr()
void NEM::MSH::geoMeshBase::SideSet::setOrigCellArr (vtkIdTypeArray * arr)
Definition at line 270 of file geoMeshBase.C.
References ORIG_CELL_NAME, and sides.
Referenced by SideSet().
{
   if (arr) {
     assert(arr->GetNumberOfTuples() == sides->GetNumberOfCells() &&
            arr->GetNumberOfComponents() == 2);
     arr->SetName(ORIG_CELL_NAME);
     sides->GetCellData()->AddArray(arr);
   } else {
     sides->GetCellData()->RemoveArray(ORIG_CELL_NAME);
   }
 }
setSideSetNamesArr()
void NEM::MSH::geoMeshBase::SideSet::setSideSetNamesArr (vtkStringArray * arr)
Definition at line 304 of file geoMeshBase.C.
References NAME_ARR_NAME, and sides.
Referenced by SideSet().
{
   if (arr) {
     assert(arr->GetNumberOfComponents() == 1);
     arr->SetName(NAME_ARR_NAME);
     sides->GetFieldData()->AddArray(arr);
   } else {
     sides->GetFieldData()->RemoveArray(NAME_ARR_NAME);
   }
 }
Member Data Documentation
CELL_FACE_NAME
constexpr auto NEM::MSH::geoMeshBase::SideSet::CELL_FACE_NAME = "CellFaceIds" static private
Definition at line 414 of file geoMeshBase.H.
Referenced by getCellFaceArr(), and setCellFaceArr().
GEO_ENT_NAME
constexpr auto NEM::MSH::geoMeshBase::SideSet::GEO_ENT_NAME = "GeoEnt" static private
Definition at line 411 of file geoMeshBase.H.
Referenced by getGeoEntArr(), setGeoEntArr(), and SideSet().
NAME_ARR_NAME
constexpr auto NEM::MSH::geoMeshBase::SideSet::NAME_ARR_NAME = "Side Set Names" static private
Definition at line 415 of file geoMeshBase.H.
Referenced by getSideSetNames(), and setSideSetNamesArr().
ORIG_CELL_NAME
constexpr auto NEM::MSH::geoMeshBase::SideSet::ORIG_CELL_NAME = "OrigCellIds" static private
Definition at line 413 of file geoMeshBase.H.
Referenced by getOrigCellArr(), and setOrigCellArr().
sides
vtkSmartPointer<vtkPolyData> NEM::MSH::geoMeshBase::SideSet::sides {nullptr}
Definition at line 399 of file geoMeshBase.H.
Referenced by getCellFaceArr(), getGeoEntArr(), getOrigCellArr(), getSideSetNames(), NEM::MSH::foamGeoMesh::GM2foam(), NEM::MSH::gmshGeoMesh::GM2gmsh(), NEM::MSH::smeshGeoMesh::GMToSMESH(), NEM::MSH::geoMeshBase::reconstructGeo(), NEM::MSH::inpGeoMesh::resetNative(), NEM::MSH::exoGeoMesh::scaleNodes(), setCellFaceArr(), setGeoEntArr(), NEM::MSH::geoMeshBase::setGeoMesh(), setOrigCellArr(), and setSideSetNamesArr().
The documentation for this struct was generated from the following files:
geoMeshBase.H
geoMeshBase.C