FROM ubuntu:16.04

RUN apt-get update --fix-missing

# Compilers and build tools.
RUN apt-get -y install build-essential cmake gfortran libopenmpi-dev

# System TPLs needed by NEMoSys dependencies.
RUN apt-get -y install zlib1g-dev libfreetype6-dev "libfltk1.3-dev" libxmu-dev libxi-dev
RUN apt-get -y install libhdf5-dev liblapack-dev libjpeg-dev

# System TPLs needed by NEMoSys.
RUN apt-get -y install libcgns-dev libmetis-dev libexodusii-dev
RUN apt-get -y install "python3.5-dev" python3-pip "python2.7-dev" python-pip swig

# Install NEMoSys dependencies
RUN apt-get -y install libboost-filesystem-dev libboost-regex-dev

# Run setuptools upgrade twice in case of "distribute" switch
RUN pip2 install --upgrade pip
RUN pip2 install --upgrade setuptools
RUN pip2 install --upgrade setuptools
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install --upgrade setuptools

# OpenFOAM 5
RUN apt-get -y install wget software-properties-common apt-transport-https
RUN sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
RUN add-apt-repository "http://dl.openfoam.org/ubuntu"
RUN apt-get update
RUN apt-get -y install openfoam5

# Copy TPLs
COPY . /Nemosys/TPLs

RUN apt-get install -y /Nemosys/TPLs/gmsh-4.5.1-Linux64.deb
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y /Nemosys/TPLs/netgen-6.2-20012_amd64.deb
RUN apt-get install -y /Nemosys/TPLs/VTK-7.1.0-Linux.deb

RUN echo "source /opt/openfoam5/etc/bashrc" >> /etc/bashrc
ENV BASH_ENV "/etc/bashrc"

RUN useradd -U --shell /bin/bash -m -d /home/user -u 35553 -c "Build Account" build
USER build

WORKDIR /home/user/
ENTRYPOINT /bin/bash
