FROM ubuntu:18.04

RUN apt-get update --fix-missing

RUN apt-get -y install apt-transport-https
RUN apt-get update --fix-missing

# Compilers and build tools.
RUN apt-get -y install build-essential cmake gfortran libopenmpi-dev git

# Install NEMoSys dependencies
RUN apt-get -y install libmetis-dev libexodusii-dev libhdf5-dev
RUN apt-get -y install python3-dev python3-pip swig
RUN apt-get -y install libboost-filesystem-dev libboost-regex-dev

# Install the package in non-interactive mode so that it ignores
# the prompts that the package requests. (opencascade requires tzdata)
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata

# Run setuptools upgrade twice in case of "distribute" switch
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install --upgrade setuptools
# Potentially comment out the above

# OpenFOAM 7
RUN apt-get -y install wget
RUN sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
RUN apt-get update --fix-missing
RUN apt-get -y install software-properties-common
RUN add-apt-repository "http://dl.openfoam.org/ubuntu"
RUN apt-get update
RUN apt-get -y install openfoam7

# Install custom-built dependencies
RUN sh -c "wget -O - http://nemosys-repository.illinois.rocstar/nemosys-repository-pub.gpg | apt-key add -"
RUN add-apt-repository "deb http://nemosys-repository.illinois.rocstar/ bionic main"
RUN apt-get update
# Custom CGNS built with ENABLE_SCOPING
RUN apt-get -y install vtk cgns opencascade netgen gmsh

# Load OpenFOAM7 env variables
RUN echo "source /opt/openfoam7/etc/bashrc" >> /etc/bashrc

ENV BASH_ENV "/etc/bashrc"

RUN useradd -U --shell /bin/bash -m -d /home/user -u 35553 -c "Build Account" build
USER build

WORKDIR /home/user/
ENTRYPOINT /bin/bash
