FROM centos:7

RUN yum update -y
RUN yum upgrade -y

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN yum groupinstall -y "Development Tools"

# Compilers and build tools.
RUN yum install -y cmake3
RUN yum install -y hdf5-devel boost169-devel
RUN yum install -y metis-devel exodusii-devel
RUN yum install -y python3-devel
RUN yum remove -y swig
RUN yum install -y swig3

# Run setuptools upgrade twice in case of "distribute" switch
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install --upgrade setuptools

# Enable gcc-7 compilers
RUN yum install centos-release-scl scl-utils -y
RUN yum install devtoolset-7 -y
RUN echo "source /opt/rh/devtoolset-7/enable" >> /etc/skel/.bashrc

# load OpenMPI module
RUN yum install openmpi-devel -y
RUN echo "source /etc/profile.d/modules.sh" >> /etc/skel/.bashrc
RUN echo "module load mpi/openmpi-x86_64" >> /etc/skel/.bashrc

RUN echo -e "[NEMoSys] \n\
name=NEMoSys \n\
baseurl=http://nemosys-rpm-repository.illinois.rocstar \n\
enabled=1 \n\
gpgcheck=0 \n\
" >> /etc/yum.repos.d/nemosys.repo

# Install previously built packages
RUN yum install gmsh -y
RUN yum install openfoam7 -y
RUN yum install vtk -y
RUN yum install netgen -y
# Custom CGNS build with ENABLE_SCOPING, because package provided by rpm
# results in a namespace collision
RUN yum install cgns -y

RUN echo "source /opt/OpenFOAM-7/etc/bashrc" >> /etc/skel/.bashrc

ENV BASH_ENV "/etc/skel/.bashrc"

RUN useradd -U --shell /bin/bash -m -k /etc/skel -d /home/user -u 35553 -c "Build Account" build
USER build

WORKDIR /home/user/
ENTRYPOINT /bin/bash
